pingcap/tiflash

README.md

Issue Number: ref #4019
Hail TiFlash.
```release-note
Open source
```

Celebrate open-source

---

README.md

Issue Number: close #4554
add apt.llvm.org in README for more detailed instructions.
Tests 
Side effects
Documentation
```release-note
None
```

doc: add apt.llvm.org in README

---

README.md

Issue Number: close #4560
Problem Summary: Fix typo about build in README.
Fix typo about build in README.
Tests 
Side effects
Documentation
```release-note
None
```

Fix typo in README/build

---

dbms/src/Interpreters/Aggregator.cpp
dbms/src/Interpreters/Aggregator.h

Signed-off-by: fuzhe1989 <fuzhe1989@gmail.com>
Issue Number: close #4581 
Tests 
Side effects
Documentation
```release-note
None
```

Agg: replace the usage of `ThreadPool` by `ThreadPoolManager`.

---

dbms/src/Debug/astToExecutor.h

Issue Number: close #4476 
pr #4610 revert the changes in #4477
Save a copy instead of an reference.
Tests 
Side effects
Documentation
```release-note
None
```

*:Fix MppInfo saving reference to temporary object.

---

dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
dbms/src/DataStreams/UnionBlockInputStream.h

ref pingcap/tiflash#4229
Tests 
Side effects
Documentation
```release-note
None
```

cherry pick #4285 to 5.4 hotfix branch

---

dbms/src/Flash/Mpp/MPPTunnel.cpp

close pingcap/tiflash#4238
Tests 
Side effects
Documentation
```release-note
None
```

Fix a bug that MPP tasks may leak threads forever (#4241)

---

dbms/src/Storages/Transaction/DecodingStorageSchemaSnapshot.h
dbms/src/Storages/Transaction/PartitionStreams.cpp
dbms/src/Storages/Transaction/RegionBlockReader.cpp
dbms/src/Storages/Transaction/RowCodec.cpp

Cherry pick of https://github.com/pingcap/tiflash/pull/4140
Issue Number: ref #4072
Tests 
Side effects
Documentation
```release-note
None
```

Fix crash when prehandle snapshot (#4140)

---

dbms/src/Flash/Coprocessor/InterpreterDAG.h

Tests 
Side effects
Documentation
```release-note
None
```

format of release-5.4-20200312

---

dbms/src/Flash/Coprocessor/DAGContext.cpp
dbms/src/Flash/Coprocessor/DAGContext.h
dbms/src/Flash/Coprocessor/InterpreterDAG.h

Tests 
Side effects
Documentation
```release-note
None
```

fix code style of release-5.4-20220312

---

dbms/src/Flash/Mpp/MPPTunnel.cpp

Tests 
Side effects
Documentation
```release-note
None
```

code stlye&format of mpptunnel

---

dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
dbms/src/Interpreters/Join.cpp

Tests 
Side effects
Documentation
```release-note
None
```

fix clang tidy error

---

dbms/src/Flash/Statistics/TableScanImpl.cpp

Issue Number: close #4692 
Tests 
Side effects
Documentation
```release-note
None
```

*: fix tableScan incorrect trace.

---

dbms/src/Flash/Mpp/MPPTunnel.cpp
dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp

Actually, since I can't reproduce it locally or through limited time CI unittests, so I plan to add more detail information to track this issue. And this is what this PR does.
Issue Number: close #4770
Tests 
Side effects
Documentation
```release-note
None
```

Add more debug info for gtest failure

---

README.md

Issue Number: close #4751 
Tests 
Side effects
Documentation
```release-note
None
```

doc: add sanitizer test related docs

---

dbms/src/Columns/ColumnDecimal.cpp
dbms/src/Columns/ColumnDecimal.h
dbms/src/Common/SipHash.h
dbms/src/Common/tests/gtest_siphash.cpp
dbms/src/Core/Types.h
dbms/src/DataTypes/DataTypeDecimal.h
dbms/src/DataTypes/IDataType.h
dbms/src/Flash/Coprocessor/DefaultChunkCodec.cpp
dbms/src/Storages/Transaction/DatumCodec.cpp
dbms/src/Storages/Transaction/DatumCodec.h
dbms/src/Storages/Transaction/RowCodec.cpp
dbms/src/Storages/Transaction/tests/gtest_row_v2.cpp
tests/fullstack-test/expr/decimal_hash.test

Tests 
Side effects
Documentation
```release-note
None
```

fix bug that Decimal256's hash value is not stable (#1574) (#1597)

---

dbms/src/Common/FailPoint.cpp
dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
dbms/src/Flash/Coprocessor/DAGStorageInterpreter.h
dbms/src/Flash/Coprocessor/RemoteRequest.h
dbms/src/Flash/Coprocessor/TablesRegionsInfo.cpp
dbms/src/Interpreters/Context.cpp
dbms/src/Interpreters/Context.h
dbms/src/Server/DTTool/DTTool.h
dbms/src/Server/RaftConfigParser.cpp
dbms/src/Server/RaftConfigParser.h
dbms/src/Server/Server.cpp
dbms/src/Storages/Transaction/StorageEngineType.h
dbms/src/Storages/Transaction/TMTContext.cpp
dbms/src/Storages/Transaction/TMTContext.h
dbms/src/TestUtils/TiFlashTestEnv.cpp

* Base on https://github.com/pingcap/tiflash/pull/4805
* Add a new role "ReadNode" for TiFlash to make TiFlash more elastic and scalable
* Skip the learner read routine for read node
* Use coprocessor to transferring data between read node and write node
Tests 
Side effects
Documentation
```release-note
None
```

Support cop between read node and write node

---

dbms/src/TestUtils/TiFlashTestEnv.cpp

Issue Number: close #5023 
Tests 
Side effects
Documentation
```release-note
None
```

Fix unstable ut in the master branch

---

dbms/src/Storages/FormatVersion.h

Issue Number: ref https://github.com/pingcap/tiflash/issues/5076
Tests 
Side effects
Documentation
```release-note
None
```

use pagestorage V2 by default

---

dbms/src/Common/getNumberOfPhysicalCPUCores.h
dbms/src/Storages/DeltaMerge/workload/Handle.h
libs/libcommon/include/common/getMemoryAmount.h

Issue Number: close #5125 
add some notes.
Tests 
Side effects
Documentation
```release-note
None
```

add some notes about `getMemoryAmount()` and `getNumberOfPhysicalCPUCores()`

---

tests/fullstack-test2/ddl/rename_table_across_databases.test

Issue Number: close #5145
fix the select statement with appropriate operator precedence.
Tests 
Side effects
Documentation
```release-note
None
```

Fix the rename_table_across_databases.test to make it can run successfully multiple times.

---

dbms/src/Common/FailPoint.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/5195
Remove unused parameter
Tests 
Side effects
Documentation
```release-note
None
```

Fix build failed

---

contrib/arm-optimized-routines-cmake/CMakeLists.txt

This is a clang bug.
Issue Number: close #5260 
Tests 
Side effects
Documentation
```release-note
None
```

fix: aarch64-quick-fix

---

dbms/src/Interpreters/Settings.h
dbms/src/Storages/DeltaMerge/DMContext.h
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp

Problem Summary: cherry pick of https://github.com/pingcap/tiflash/pull/1783
Tests 
Side effects
Documentation
```release-note
None
```

Delete range can not remove expected data

---

.github/workflows/license-checker.yml

Signed-off-by: gengliqi <gengliqiii@gmail.com>
Issue Number: close https://github.com/pingcap/tiflash/issues/5317
The same to https://github.com/pingcap/tidb/pull/36038
Tests 
Side effects
Documentation
```release-note
None
```

ci: fix check-license github action

---

CMakeLists.txt

Issue Number: close #5342
Tests 
Side effects
Documentation
```release-note
None
```

*: also enable O3 for aarch64

---

dbms/src/Storages/Transaction/KVStore.cpp

Issue Number: close #5445
As mentioned in https://github.com/pingcap/tidb-engine-ext/pull/130
Tests 
Side effects
Documentation
```release-note
None
```

fix TiFlash wait index timeout due to not replicated filtered commands

---

dbms/src/Common/ThreadManager.cpp
dbms/src/Common/ThreadManager.h
dbms/src/DataStreams/IBlockInputStream.h
dbms/src/Flash/Coprocessor/DAGContext.cpp
dbms/src/Flash/Coprocessor/DAGContext.h
dbms/src/Flash/Coprocessor/DAGDriver.cpp
dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
dbms/src/Flash/Coprocessor/RemoteRequest.h
dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.cpp
dbms/src/Flash/Mpp/ExchangeReceiver.cpp
dbms/src/Flash/Mpp/ExchangeReceiver.h
dbms/src/Flash/Mpp/MPPTask.cpp
dbms/src/Flash/Mpp/MinTSOScheduler.cpp

Issue Number: ref https://github.com/pingcap/tiflash/issues/3994
Now the codes that construct an ExchangeReceiverResult object is hard to understand and write
Add three static method `ExchangeReceiverResult::{newOk,newError,newEOF}` for building the ExchangeReceiverResult instance
Tests 
Side effects
Documentation
```release-note
None
```

*: Refine the ExchangeReceiverResult

---

dbms/src/Flash/DiagnosticsService.cpp
dbms/src/Flash/DiagnosticsService.h
dbms/src/Server/CMakeLists.txt
dbms/src/Server/FlashGrpcServerHolder.cpp
dbms/src/Server/FlashGrpcServerHolder.h
dbms/src/Server/Server.cpp
dbms/src/Server/Server.h

Issue Number: ref #4609 
Tests 
Side effects
Documentation
```release-note
None
```

*: decouple FlashGrpcServerHolder from Server.cpp

---

dbms/src/Storages/Page/V3/BlobStore.cpp
dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp

Issue Number: ref #5532 
Problem Summary: cherry-pick of #5536 
Tests 
Side effects
Documentation
```release-note
None
```

fix potential dead lock when remove blob file

---

dbms/src/Storages/Transaction/LearnerRead.cpp

Issue Number: close #5525
we don't know which index we failed to read when there are region unavailable errors.
So we add more log when error happen
Tests 
Side effects
Documentation
```release-note
None
```

Add more information when read index fail

---

metrics/grafana/tiflash_summary.json

Issue Number: ref #5376
Tests 
Side effects
Documentation
```release-note
None
```

Add desc of read thread and data sharing cache in grafana.

---

dbms/src/Flash/Planner/ExecutorIdGenerator.h

Issue Number: close #5600
Tests 
Side effects
Documentation
```release-note
None
```

fix asan UT fail

---

dbms/src/Flash/Mpp/MPPTaskManager.cpp

Issue Number: ref #5638
refine `MPPTaskCancelFunctor`
Tests 
Side effects
Documentation
```release-note
None
```

refine MPPTaskCancelFunctor

---

dbms/src/DataStreams/TiRemoteBlockInputStream.h
dbms/src/Flash/Mpp/MPPReceiverSet.cpp
dbms/src/Flash/Mpp/MPPReceiverSet.h
dbms/src/Flash/Mpp/MPPTask.cpp

Issue Number: close #5708, ref #5095
Tests 
Side effects
Documentation
```release-note
None
```

fix unstable mpp fail tests

---

dbms/src/WindowFunctions/tests/gtest_lead_lag.cpp

Issue Number: close #5775 
Problem Summary:  
Tests 
Side effects
Documentation
```release-note
None
```

*: fix lead_lag test build fail.

---

docs/design/2022-05-12-window-function.md

Issue Number: close #5781
Tests 
Side effects
Documentation
```release-note
None
```

doc: update window function design doc

---

tests/fullstack-test/mpp/mpp_fail.test

Issue Number: ref #5708, ref #5095
Tests 
Side effects
Documentation
```release-note
None
```

fix unstable tests

---

dbms/src/Storages/DeltaMerge/ReadThread/SegmentReader.cpp

Issue Number: ref #5376
Change an unserious log from error to warning.
Tests 
Side effects
Documentation
```release-note
None
```

Change an unserious log from error to warning

---

dbms/src/Flash/Coprocessor/DAGUtils.cpp

Issue Number: close #5809
Add pb code for regexp functions
Tests 
Side effects
Documentation
```release-note
None
```

Add pb code for regexp functions

---

dbms/src/Flash/Mpp/TrackedMppDataPacket.h

Issue Number: close #5830
Tests 
Side effects
Documentation
```release-note
None
```

add memory_tracker_holder in TrackedMppDataPacket

---

dbms/src/Columns/ColumnAggregateFunction.cpp
dbms/src/Columns/ColumnAggregateFunction.h
dbms/src/Columns/ColumnArray.cpp
dbms/src/Columns/ColumnConst.cpp
dbms/src/Columns/ColumnDecimal.cpp
dbms/src/Columns/ColumnDecimal.h
dbms/src/Columns/ColumnFixedString.cpp
dbms/src/Columns/ColumnNullable.cpp
dbms/src/Columns/ColumnTuple.cpp
dbms/src/Columns/ColumnVector.cpp
dbms/src/Columns/FilterDescription.cpp

Issue Number: ref https://github.com/pingcap/tiflash/issues/4605
Tests 
Side effects
Documentation
```release-note
None
```

*: Fix lint for files under src/Columns

---

dbms/src/Flash/tests/gtest_aggregation_executor.cpp
dbms/src/Flash/tests/gtest_filter_executor.cpp
dbms/src/Flash/tests/gtest_join_executor.cpp
dbms/src/Flash/tests/gtest_limit_executor.cpp
dbms/src/Flash/tests/gtest_projection_executor.cpp
dbms/src/Flash/tests/gtest_topn_executor.cpp
dbms/src/Flash/tests/gtest_window_executor.cpp
dbms/src/TestUtils/ExecutorTestUtils.cpp
dbms/src/TestUtils/ExecutorTestUtils.h
dbms/src/WindowFunctions/tests/gtest_lead_lag.cpp

Issue Number: ref #4609
Tests 
Side effects
Documentation
```release-note
None
```

Test: refine Executor Unit Test

---

dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp

Signed-off-by: Jigao Luo <luojigao@outlook.com>
Issue Number: close #4604 
Tests 
Side effects
Documentation
```release-note
None
```

Fix gtest_dm_minmax_index.cpp clang tidy.

---

dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/ReadThread/CircularScanList.h
dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.h
dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h

Issue Number: close #5960
cherry-pick of #5961 
Tests 
Side effects
Documentation
```release-note
None
```

Performance optimization of SegmentReadTaskScheduler

---

dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
dbms/src/TestUtils/TiFlashTestEnv.cpp

Issue Number: close #6022
Tests 
Side effects
Documentation
```release-note
None
```

.*: fix build fail in  linux amd64

---

dbms/src/Storages/Transaction/tests/gtest_sync_status.cpp

Issue Number: close #6025
Fix `SyncStatusTest` UT detected memory leaks.
Free memory in UT.
Tests 
Side effects
Documentation
```release-note
None
```

Fix SyncStatusTest UT detected memory leaks.

---

dbms/src/Storages/Transaction/ProxyFFIStatusService.cpp

Issue Number: close #6116
Reduce sync-status log.
Tests 
Side effects
Documentation
```release-note
None
```

reduce sync-status log

---

dbms/src/DataStreams/WindowBlockInputStream.cpp
dbms/src/Encryption/RateLimiter.h
dbms/src/Flash/Mpp/ExchangeReceiver.cpp
dbms/src/Flash/Mpp/GRPCSendQueue.h
dbms/src/Flash/Mpp/MPPTunnel.cpp
dbms/src/Functions/FunctionsDateTime.cpp
dbms/src/Functions/FunctionsString.cpp
dbms/src/Interpreters/WindowDescription.cpp
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/workload/DTWorkload.cpp
dbms/src/Storages/DeltaMerge/workload/Options.cpp
dbms/src/Storages/Page/PageStorage.cpp
dbms/src/Storages/Page/V3/BlobStore.cpp
dbms/src/Storages/Page/V3/PageDirectory.cpp
dbms/src/Storages/Page/V3/PageDirectory.h
dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
dbms/src/Storages/Page/V3/WAL/serialize.cpp
dbms/src/WindowFunctions/IWindowFunction.cpp

Issue Number: close #6149
Tests 
Side effects
Documentation
```release-note
None
```

update submodule fmtlib

---

dbms/src/Columns/IColumn.h
dbms/src/Functions/FunctionsMiscellaneous.cpp
dbms/src/Interpreters/ExpressionActions.cpp
dbms/src/Interpreters/ExpressionActions.h
dbms/src/Interpreters/ExpressionAnalyzer.cpp
dbms/src/Interpreters/ExpressionAnalyzer.h
dbms/src/Interpreters/InterpreterSelectQuery.cpp
dbms/src/Parsers/ASTSelectQuery.cpp
dbms/src/Parsers/ASTSelectQuery.h
dbms/src/Parsers/ASTTablesInSelectQuery.cpp
dbms/src/Parsers/ASTTablesInSelectQuery.h
dbms/src/Parsers/ParserTablesInSelectQuery.cpp
dbms/src/Parsers/ParserTablesInSelectQuery.h

Issue Number: close #4860
Tests 
Side effects
Documentation
```release-note
None
```

remove useless arrayJoin

---

dbms/src/Encryption/tests/gtest_rate_limiter.cpp

Issue Number: close #6261 
Tests 
Side effects
Documentation
```release-note
None
```

fix unstable ut.

---

dbms/src/Storages/Page/V3/spacemap/SpaceMap.h
dbms/src/Storages/Page/tools/auto-fio.sh
dbms/src/Storages/Transaction/TiKVRecordFormat.h

Issue Number: close #6287
Remove unreachable google docs
Tests 
Side effects
Documentation
```release-note
None
```

Remove unreachable google docs

---

dbms/src/DataStreams/WindowBlockInputStream.cpp
dbms/src/DataStreams/WindowBlockInputStream.h
dbms/src/WindowFunctions/IWindowFunction.cpp
dbms/src/WindowFunctions/IWindowFunction.h

Issue Number: ref #5900
Tests 
Side effects
Documentation
```release-note
None
```

Move most of `WindowBlockInputStream`'s code to `WindowTransformAction`

---

dbms/src/Common/MyTime.cpp
dbms/src/Common/MyTime.h
dbms/src/Common/tests/gtest_mytime.cpp
dbms/src/Functions/FunctionsTiDBConversion.h
dbms/src/Functions/tests/gtest_tidb_conversion.cpp
tests/fullstack-test/expr/return_warning.test

cherry-pick #5477 
Issue Number: close #5097
Tests 
Side effects
Documentation
```release-note
None
```

fix: error data input for date(CAST(value AS DATETIME)) causing high TiFlash sys CPU

---

dbms/src/Server/Server.cpp

Issue Number: close #6336 
Tests 
Side effects
Documentation
```release-note
None
```

*: fix coredump when stopping tiflash

---

dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
dbms/src/TestUtils/FunctionTestUtils.h

Issue Number: ref #5237
Introduce a new helper macro to assert the ProfileEvent change for a block of code.
Tests 
Side effects
Documentation
```release-note
None
```

test: Introduce ASSERT_PROFILE_EVENT

---

metrics/grafana/tiflash_summary.json

Issue Number: close https://github.com/pingcap/tiflash/issues/6334
If we expand the row "Thread CPU" and "PageStorage" at the same time, then these panels are placed in a wrong position
* Fix the panel id
* Check with the py script
```
>  python3 check_grafana.py metrics/grafana/tiflash_summary.json
2022/11/28 10:52:07 [INFO] Checking panels under row 'Server'
2022/11/28 10:52:07 [INFO] Check done for panels under row 'Server'
2022/11/28 10:52:07 [INFO] Checking panels under row 'Threads CPU'
2022/11/28 10:52:07 [INFO] Check done for panels under row 'Threads CPU'
2022/11/28 10:52:07 [INFO] Checking panels under row 'Coprocessor'
2022/11/28 10:52:07 [INFO] Check done for panels under row 'Coprocessor'
2022/11/28 10:52:07 [INFO] Checking panels under row 'Task Scheduler' …
```

metrics: Fix duplicated id in Grafana panels

---

dbms/src/Common/TiFlashMetrics.h
dbms/src/Flash/EstablishCall.cpp
dbms/src/Flash/Mpp/ExchangeReceiver.cpp
dbms/src/Flash/Mpp/ExchangeReceiver.h
dbms/src/Flash/Mpp/MPPTunnel.cpp
dbms/src/Flash/Mpp/MPPTunnel.h
metrics/grafana/tiflash_summary.json

Issue Number: close #6225
[Grafana Panel](http://172.16.4.99:7005/)
Tests 
Side effects
Documentation
```release-note
None
```

Add metrics about the status of exchange sender/receiver queue

---

dbms/src/Storages/Transaction/ProxyFFI.cpp
dbms/src/Storages/Transaction/ProxyFFI.h

Tests 
Side effects
Documentation
```release-note
None
```

[Cloud] fast add peer: support basic ffi

---

dbms/src/Storages/Transaction/ProxyFFI.cpp

Tests 
Side effects
Documentation
```release-note
None
```

[Cloud] fast add peer: main body

---

etc/config-template.toml

Signed-off-by: guo-shaoge <shaoge1994@163.com>
Issue Number: close #6500
Problem Summary: fix config typo
Tests 
Side effects
Documentation
```release-note
None
```

fix typo in config-template.toml

---

dbms/src/Common/getNumberOfCPUCores.cpp

Issue Number: close #6504
Tests 
Side effects
Documentation
```release-note
None
```

Avoid the occurrence of 0 physical cpu cores

---

dbms/src/Common/TiFlashMetrics.h
dbms/src/Storages/Page/V3/BlobStore.cpp
dbms/src/Storages/Page/V3/PageStorageImpl.cpp
dbms/src/Storages/Page/V3/spacemap/SpaceMapSTDMap.h
dbms/src/Storages/Page/V3/tests/gtest_free_map.cpp
dbms/src/Storages/Page/universal/UniversalPageStorage.cpp

Tests 
Side effects
Documentation
```release-note
None
```

optimize write latency and add metric for UniversalPageStorage

---

docs/design/2022-12-21-auto-reload-tls-certificate.md

Issue Number: close #5503 
Tests 
Side effects
Documentation
```release-note
None
```

doc: add doc for auto-reload-cert

---

dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSchema.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSchema.h
dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
dbms/src/Storages/DeltaMerge/File/dtpb/column_file.proto
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp

Tests 
Side effects
Documentation
```release-note
None
```

Serialize ColumnFileTiny schema to remote snapshot

---

dbms/src/Flash/Coprocessor/GenSchemaAndColumn.cpp
dbms/src/Flash/Coprocessor/GenSchemaAndColumn.h
dbms/src/Server/StorageConfigParser.cpp
dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.cpp
dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.h
dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
dbms/src/Storages/DeltaMerge/DeltaMergeHelpers.h
dbms/src/Storages/DeltaMerge/Remote/RemoteReadTask.cpp
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/StorageDisaggregated.cpp

Set up a tiflash compute node by adding these configs
```
config:
flash.disaggregated_mode: tiflash_compute
storage.remote.dir: /mount/point/to/shared/dir
```
Set up a tiflash storage node by adding these config
```
config:
storage.remote.dir: /mount/point/to/shared/dir
```
Set up a tidb node that sends the disaggregated tasks to the tiflash compute node
```
config:
disaggregated-tiflash: true
```
change the pd's cluster version for joining the cluster
```
tiup ctl:v6.4.0 pd -u 172.16.5.85:6540 config set cluster-version "6.5.0"
```
Load some data in and begin to play with it!
Tests 
Side effects
Documentation
```release-note
None
```

Support disaggregated read all data from remote data source

---

dbms/src/Encryption/RateLimiter.cpp
dbms/src/Flash/Disaggregated/GRPCPageReceiverContext.cpp
dbms/src/Flash/Disaggregated/GRPCPageReceiverContext.h
dbms/src/Flash/Disaggregated/PageReceiver.cpp
dbms/src/Flash/Disaggregated/PageReceiver.h
dbms/src/Flash/Disaggregated/PageTunnel.cpp
dbms/src/Interpreters/Context.cpp
dbms/src/Server/tests/gtest_dttool.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
dbms/src/Storages/DeltaMerge/File/dtpb/column_file.proto
dbms/src/Storages/DeltaMerge/Remote/LocalPageCache.cpp
dbms/src/Storages/DeltaMerge/Remote/RemoteReadTask.cpp
dbms/src/Storages/DeltaMerge/Remote/RemoteReadTask.h
dbms/src/Storages/DeltaMerge/Remote/tests/gtest_remote_read_task.cpp
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_column_file.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_value_space.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment_common_handle.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
dbms/src/Storages/Page/PageUtil.cpp
dbms/src/Storages/Page/PageUtil.h
dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
dbms/src/Storages/StorageDisaggregated.cpp

Tests 
Side effects
Documentation
```release-note
None
```

Fix bug for reading persisted cfs under disaggregated read

---

dbms/src/Core/Block.cpp

Issue Number: close #6564
add structure check when merging blocks.
Tests 
Side effects
Documentation
```release-note
None
```

check structure when merging blocks

---

dbms/src/Storages/Transaction/FastAddPeer.cpp
dbms/src/Storages/Transaction/Region.h
dbms/src/Storages/Transaction/RegionMeta.cpp
dbms/src/Storages/Transaction/RegionMeta.h

Tests 
Side effects
Documentation
```release-note
None
```

[Cloud] Fast add peer: Fix peer

---

dbms/src/IO/ReadBuffer.h
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.h
dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
dbms/src/Storages/DeltaMerge/File/DMFile.cpp
dbms/src/Storages/DeltaMerge/File/DMFile.h
dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
dbms/src/Storages/DeltaMerge/File/DMFileWriterRemote.cpp
dbms/src/Storages/DeltaMerge/File/DMFileWriterRemote.h
dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStore.h
dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreNFS.cpp
dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreNFS.h
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
dbms/src/Storages/DeltaMerge/StableValueSpace.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
dbms/src/Storages/Page/V3/PageDirectory.cpp

Tests 
Side effects
Documentation
```release-note
None
```

avoid download dtfile when ingest checkpoint

---

dbms/src/Storages/Page/V3/PageDirectory.cpp

Tests 
Side effects
Documentation
```release-note
None
```

Fix dump snapshot

---

dbms/src/Interpreters/Context.cpp
dbms/src/Interpreters/Context.h
dbms/src/Storages/Transaction/FastAddPeer.cpp
dbms/src/Storages/Transaction/FastAddPeer.h
dbms/src/Storages/Transaction/LocalPageStorageCache.h
dbms/src/Storages/Transaction/tests/gtest_kvstore_fast_add_peer.cpp

Tests 
Side effects
Documentation
```release-note
None
```

[Cloud] Fast add peer: Add cache for local PS

---

dbms/src/Common/tests/gtest_concurrent_hashmap.cpp
dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreNFS.cpp
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/Segment.h
dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_ingest.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
dbms/src/Storages/Page/V3/Remote/CheckpointPageManager.cpp
dbms/src/Storages/Page/V3/Remote/CheckpointPageManager.h
dbms/src/Storages/Page/V3/Remote/tests/gtest_checkpoint.cpp
dbms/src/Storages/Transaction/FastAddPeer.cpp

Tests 
Side effects
Documentation
```release-note
None
```

Speed up read checkpoint

---

dbms/src/Common/FailPoint.cpp
dbms/src/Interpreters/Context.cpp
dbms/src/Interpreters/Context.h
dbms/src/Storages/Transaction/FastAddPeer.cpp
dbms/src/Storages/Transaction/FastAddPeer.h
dbms/src/Storages/Transaction/FastAddPeerContext.cpp
dbms/src/Storages/Transaction/FastAddPeerContext.h
dbms/src/Storages/Transaction/tests/gtest_kvstore_fast_add_peer.cpp

Tests 
Side effects
Documentation
```release-note
None
```

[Cloud] Fast add peer: support async

---

dbms/src/Common/ThreadPool.cpp
dbms/src/Storages/Transaction/FastAddPeer.h
dbms/src/Storages/Transaction/FastAddPeerContext.cpp
dbms/src/Storages/Transaction/tests/gtest_kvstore_fast_add_peer.cpp

Tests 
Side effects
Documentation
```release-note
None
```

[Cloud] Fast add peer: Fix dangling future

---

dbms/src/Flash/Mpp/ReceiverChannelWriter.cpp

Issue Number: close #6627 
Tests 
Side effects
Documentation
```release-note
None
```

Fix build fail

---

dbms/src/Storages/Transaction/ProxyFFI.cpp
dbms/src/Storages/Transaction/ProxyFFI.h

Tests 
Side effects
Documentation
```release-note
None
```

[Cloud]Fast add peer: refine FFI interfaces

---

dbms/src/Flash/tests/gtest_join_executor.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/6611
build broken
Tests 
Side effects
Documentation
```release-note
None
```

fix(build): fix gtests_dbms build on mac m1

---

dbms/src/Flash/Coprocessor/CHBlockChunkCodecV1.cpp
dbms/src/Flash/Coprocessor/CHBlockChunkCodecV1.h
dbms/src/Flash/Mpp/ExchangeReceiver.cpp
dbms/src/Flash/Mpp/FineGrainedShuffleWriterV1.cpp
dbms/src/Flash/Mpp/FineGrainedShuffleWriterV1.h
dbms/src/Flash/Mpp/HashPartitionWriterV1.cpp
dbms/src/Flash/Mpp/newMPPExchangeWriter.h
dbms/src/Flash/Mpp/tests/gtest_mpp_exchange_writer.cpp

Issue Number: after #6635
Tests 
Side effects
Documentation
```release-note
None
```

6.5 poc: support data compression in FineGrainedShuffle

---

dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.cpp
dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.h
dbms/src/Flash/Mpp/FineGrainedShuffleWriter.cpp
dbms/src/Flash/Mpp/FineGrainedShuffleWriter.h
dbms/src/Flash/Mpp/HashBaseWriterHelper.cpp
dbms/src/Flash/Mpp/HashBaseWriterHelper.h
dbms/src/Flash/Mpp/HashPartitionWriter.cpp
dbms/src/Flash/Mpp/HashPartitionWriter.h
dbms/src/Flash/Mpp/MPPTask.cpp
dbms/src/Flash/Mpp/MPPTunnelSet.cpp
dbms/src/Flash/Mpp/MPPTunnelSet.h
dbms/src/Flash/Mpp/MPPTunnelSetHelper.cpp
dbms/src/Flash/Mpp/MPPTunnelSetHelper.h
dbms/src/Flash/Mpp/tests/gtest_mpp_exchange_writer.cpp

Issue Number: ref #5900
https://github.com/pingcap/tiflash/pull/6596#issuecomment-1379764545
Tests 
Side effects
Documentation
```release-note
None
```

Move the logic of encoding mpp packet from exchange writer to mpp tunnel set

---

dbms/src/Common/setThreadName.cpp

Issue Number: close #6651
fix compile on mac os
Tests 
Side effects
Documentation
```release-note
None
```

fix compile on mac os

---

dbms/src/TiDB/Schema/SchemaGetter.cpp

Issue Number: close #6580
Tests 
Side effects
Documentation
```release-note
None
```

Cover the whole SchemaDiff::deserialize in a try block and print out the error data

---

dbms/src/DataStreams/CreatingSetsBlockInputStream.cpp
dbms/src/DataStreams/HashJoinBuildBlockInputStream.cpp
dbms/src/DataStreams/HashJoinProbeBlockInputStream.cpp
dbms/src/Interpreters/Join.cpp
dbms/src/Interpreters/Join.h
tests/fullstack-test/mpp/mpp_fail.test

Issue Number: close #6739
Fix unstable mpp_fail test
Tests 
Side effects
Documentation
```release-note
None
```

fix unstable mpp_fail tests

---

dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp

Issue Number: close #6775
Tests 
Side effects
Documentation
```release-note
None
```

Fix new segment check in gcTrySegmentMergeDelta/gcTrySegmentMerge

---

dbms/src/Server/Server.cpp

Issue Number: close #6336 
related https://github.com/pingcap/tiflash/pull/6340 https://github.com/pingcap/tiflash/pull/6367
Tests 
Side effects
Documentation
```release-note
None
```

Destroy dynamic thread pool in Server

---

.gitmodules

Issue Number: close #4565
related https://github.com/pingcap/tiflash/pull/4566, https://github.com/pingcap/tiflash/pull/6828
Tests 
Side effects
Documentation
```release-note
None
```

Unify the url of submodule to https url

---

.github/licenserc.yml

Issue Number: close #6903
ref https://github.com/tikv/tikv/pull/14258
Tests 
Side effects
Documentation
```release-note
None
```

release-5.0: update openssl-src of proxy to fix CVE-2023-0286

---

.github/licenserc.yml

Issue Number: close #6903
ref https://github.com/tikv/tikv/pull/14258
Tests 
Side effects
Documentation
```release-note
None
```

release-5.3: update openssl-src of proxy to fix CVE-2023-0286

---

.github/licenserc.yml

Issue Number: close #6903
ref https://github.com/tikv/tikv/pull/14258
Tests 
Side effects
Documentation
```release-note
None
```

release-5.1: update openssl-src of proxy to fix CVE-2023-0286

---

.github/licenserc.yml
tests/run-gtest.sh

Issue Number: close  #6903
Tests 
Side effects
Documentation
```release-note
None
```

release-4.0: update openssl-src of proxy to fix CVE-2023-0286

---

README.md

Tests 
Side effects
Documentation
```release-note
None
```

chore: Add ccache tip in readme.md

---

libs/libcommon/include/boost_wrapper/priority_queue.h

Issue Number: close #6946
Tests 
Side effects
Documentation
```release-note
None
```

Ignored "-Wdeprecated-builtins" in boost priority_queue.

---

dbms/src/DataStreams/MockExchangeReceiverInputStream.cpp
dbms/src/DataStreams/MockExchangeReceiverInputStream.h
dbms/src/Flash/Coprocessor/MockSourceStream.cpp
dbms/src/Flash/tests/gtest_join_executor.cpp

Tests 
Side effects
Documentation
```release-note
None
```

mock exchange receiver with fine grained enable support different max_streams

---

dbms/src/Functions/FunctionsTiDBConversion.h
dbms/src/Functions/tests/gtest_tidb_conversion.cpp

Issue Number: close #6994
Fix bug in round when cast decimal as decimal 
Tests 
Side effects
Documentation
```release-note
None
```

fix decimal cast bug

---

dbms/src/Server/Server.cpp
dbms/src/Storages/S3/FileCache.cpp
dbms/src/Storages/S3/FileCache.h
dbms/src/Storages/S3/tests/gtest_filecache.cpp

Add capacity metrics for FileCache.
Tests 
Side effects
Documentation
```release-note
None
```

Add capacity metrics for FileCache

---

dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/StableValueSpace.cpp

Issue Number: ref #6827 
Problem Summary: Fix the way to get DTFile path.
Tests 
Side effects
Documentation
```release-note
None
```

fix get remote DTFile path

---

dbms/src/Interpreters/ExpressionAnalyzer.cpp

Issue Number: close #7054
Tests 
Side effects
Documentation
```release-note
None
```

disable join from tiflash client

---

dbms/src/Flash/FlashService.cpp

Tests 
Side effects
Documentation
```release-note
None
```

TiDB use session variable to set the memory threshold for TiFlash spill

---

dbms/src/Storages/DeltaMerge/tests/gtest_segment_util.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_skippable_block_input_stream.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/7090
Tests 
Side effects
Documentation
```release-note
None
```

suppress deprecated builtins for boost string

---

tests/fullstack-test2/mpp/null_aware_semi_join.test
tests/tidb-ci/new_collation_fullstack/function_collator.test

Issue Number: close https://github.com/pingcap/tiflash/issues/7079
The bug is fixed in https://github.com/pingcap/tidb/pull/42304.
Add more tests.
Tests 
Side effects
Documentation
```release-note
None
```

add more collator tests for null-aware semi join

---

metrics/grafana/tiflash_summary.json

Tests 
Side effects
Documentation
```release-note
None
```

Add disaggregated read duration breakdown metrics

---

dbms/src/Flash/tests/gtest_execution_summary.cpp

Issue Number: close #7123 
Tests 
Side effects
Documentation
```release-note
None
```

*: fix unstable summary tests

---

dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp

This is just a workaround. It totally skips the remote read logics when there is no need. This avoid the lock contention in LocalPageCache for some reason.
Tests 
Side effects
Documentation
```release-note
None
```

Skip remote read and local rewrite when possible

---

metrics/grafana/tiflash_summary.json

Tests 
Side effects
Documentation
```release-note
None
```

Add S3 metrics to Grafana.

---

dbms/src/Storages/DeltaMerge/Remote/RNRemoteReadTask.cpp
dbms/src/Storages/DeltaMerge/Remote/RNRemoteReadTask.h
dbms/src/Storages/StorageDisaggregated.h
dbms/src/Storages/StorageDisaggregatedRemote.cpp

Make explain analyze work for Disaggregated read.
Tests 
Side effects
Documentation
```release-note
None
```

Support ScanContext for Disaggregated Read

---

dbms/src/Dictionaries/DictionarySourceFactory.cpp
dbms/src/IO/HTTPCommon.cpp
dbms/src/IO/HTTPCommon.h
dbms/src/IO/UseSSL.cpp
dbms/src/IO/UseSSL.h
dbms/src/Server/Server.cpp
dbms/src/Storages/DeltaMerge/workload/MainEntry.cpp
dbms/src/Storages/S3/PocoHTTPClient.cpp
release-centos7-llvm/env/Makefile

Issue Number: close https://github.com/pingcap/tiflash/issues/7176
Depends on
* https://github.com/pingcap/poco/pull/17
Changes:
* introduce a struct `UseSSL` to initlize SSL and finalize SSL
* set remote resolved host on HTTP requests 
* Fix tiflash-env build script when selinux is enabled
Tests 
Side effects
Documentation
```release-note
None
```

Fix poco client resolved host

---

dbms/src/Flash/Executor/PipelineExecutor.cpp
dbms/src/Flash/Executor/PipelineExecutorStatus.cpp
dbms/src/Flash/Executor/PipelineExecutorStatus.h
dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp
dbms/src/Flash/Pipeline/Schedule/Events/Event.h
dbms/src/Flash/Pipeline/Schedule/Events/tests/gtest_event.cpp

Issue Number: close #7229
Tests 
Side effects
Documentation
```release-note
None
```

.*: fix bug introduced by https://github.com/pingcap/tiflash/pull/7175

---

CMakeLists.txt

Issue Number: close #7273
Tests 
Side effects
Documentation
```release-note
None
```

build process_metrics/symbolization/tiflash-proxy sequentially

---

libs/libprocess_metrics/src/lib.rs

Issue Number: close #7279
Tests 
Side effects
Documentation
```release-note
None
```

fix mac build for process_metrics

---

dbms/src/Flash/FlashService.cpp

Issue Number: close #6941 
Tests 
Side effects
Documentation
```release-note
None
```

*: fix read system table without key when tls is enable

---

dbms/src/DataStreams/TiRemoteBlockInputStream.h

Issue Number: ref #7338 #7337 
Tests 
Side effects
Documentation
```release-note
None
```

*: fix check cancel in fetch remote result

---

dbms/src/Flash/Coprocessor/JoinInterpreterHelper.cpp
dbms/src/Flash/Coprocessor/tests/gtest_join_get_kind_and_build_index.cpp

Issue Number: close #7320
Tests 
Side effects
Documentation
```release-note
None
```

Refact getJoinKindAndBuildSideIndex function

---

dbms/src/Storages/StorageDeltaMerge.cpp
dbms/src/Storages/tests/gtest_filter_parser.cpp

Issue Number: ref #7355 
Tests 
Side effects
Documentation
```release-note
None
```

*: fix asan in `StorageDeltaMerge::parsePushDownFilter` and `FilterParserTest`

---

dbms/src/Common/MemoryTracker.cpp
dbms/src/Common/MemoryTracker.h

Issue Number: close #7367
Tests 
Side effects
Documentation
```release-note
None
```

tsan: fix data race in `MemoryTracker::setDescription` and `MemoryTracker::logPeakMemoryUsage`

---

tests/tidb-ci/fullstack-test-dt/issue_1425.test

Issue Number: close #7334
Tests 
Side effects
Documentation
```release-note
None
```

test: add decimal test back

---

tests/fullstack-test/expr/ilike_pushdown.test

Issue Number: close #7373 
Tests 
Side effects
Documentation
```release-note
None
```

Add ft for `ilike` function

---

dbms/src/Common/BackgroundTask.cpp
dbms/src/Common/BackgroundTask.h
dbms/src/Server/FlashGrpcServerHolder.cpp
tests/run-gtest.sh

Issue Number: close #7388 close #6766
ref https://github.com/pingcap/tiflash/pull/6864/files#diff-d34a9dab8c425813ed3663fefb4ece983b9210630f517ad23150d3e593874578R66-R75
Tests 
`./dbms/gtests_dbms --gtest_filter=ComputeServerRunner.*` tsan passed
Side effects
Documentation
```release-note
None
```

Fix unit test `ComputeServerRunner.*` tsan fail

---

dbms/src/Encryption/tests/gtest_rate_limiter.cpp

Issue Number: close #7226 
Tests 
Side effects
Documentation
```release-note
None
```

fix unstable test `WriteLimiterTest.Rate`

---

dbms/src/Operators/SharedAggregateRestorer.cpp
dbms/src/Operators/SpilledBucketInput.cpp

Issue Number: ref #7395
Tests 
Side effects
Documentation
```release-note
None
```

fix crash on `SharedAggregateRestorer::tryLoadBucketData`

---

dbms/src/Core/Spiller.cpp
dbms/src/DataStreams/SpilledFilesInputStream.cpp
dbms/src/Operators/AggregateRestoreSourceOp.cpp
dbms/src/Operators/SharedAggregateRestorer.cpp
dbms/src/Operators/SharedAggregateRestorer.h

Issue Number: close #7395
Tests 
Side effects
Documentation
```release-note
None
```

refine spill failpoint and `SharedSpilledBucketDataLoader`

---

dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp
dbms/src/Flash/Pipeline/Schedule/Events/Event.h
dbms/src/Flash/Pipeline/Schedule/TaskScheduler.cpp
dbms/src/Flash/Pipeline/Schedule/TaskThreadPool.cpp
dbms/src/Flash/Pipeline/Schedule/Tasks/AggregateFinalSpillTask.cpp
dbms/src/Flash/Pipeline/Schedule/Tasks/AggregateFinalSpillTask.h
dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.cpp
dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.h
dbms/src/Flash/Pipeline/Schedule/Tasks/PipelineTask.cpp
dbms/src/Flash/Pipeline/Schedule/Tasks/PipelineTask.h
dbms/src/Flash/Pipeline/Schedule/Tasks/Task.cpp
dbms/src/Flash/Pipeline/Schedule/Tasks/Task.h
dbms/src/Flash/Pipeline/Schedule/WaitReactor.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp

Issue Number: ref #6518 
Tests 
Side effects
Documentation
```release-note
None
```

refine some codes for pipeline

---

dbms/src/Interpreters/CrossJoinProbeHelper.cpp
dbms/src/Interpreters/CrossJoinProbeHelper.h
dbms/src/Interpreters/Join.cpp
dbms/src/Interpreters/Join.h
dbms/src/Interpreters/JoinPartition.cpp
dbms/src/Interpreters/JoinUtils.cpp
dbms/src/Interpreters/JoinUtils.h

Issue Number: ref #7443
This is the first part of #7443: enable ProbeProcessInfo for cross join
Tests 
- already add ut in https://github.com/pingcap/tiflash/pull/7321
Side effects
Documentation
```release-note
None
```

Cross join use probe info

---

dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
dbms/src/Flash/Mpp/AsyncRequestHandler.h
dbms/src/Flash/Mpp/ExchangeReceiver.cpp
dbms/src/Flash/Mpp/GRPCReceiverContext.cpp
dbms/src/Flash/Mpp/GRPCReceiverContext.h
dbms/src/Flash/tests/bench_exchange.h

Issue Number: close #7440
Tests 
Side effects
Documentation
```release-note
None
```

Fix mpp task hang in spill random fail point

---

dbms/src/Common/tests/gtest_cpu_affinity_manager.cpp

Issue Number: close #7472
Tests 
Side effects
Documentation
```release-note
None
```

Check CPU cores in CPUAffinityManagerTest

---

dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
dbms/src/Flash/Planner/PhysicalPlan.cpp

Issue Number: close #7486
Tests 
Side effects
Documentation
```release-note
None
```

Throw exception when disable read thread pool and enable late materialization

---

dbms/src/Interpreters/Settings.h

Issue Number: close #7507
Tests 
Side effects
Documentation
```release-note
None
```

Set reactor as default config for ExchangeReceiver

---

dbms/src/Flash/Executor/PipelineExecutorStatus.cpp
dbms/src/Flash/Executor/PipelineExecutorStatus.h

Issue Number: close #7520
Tests 
Side effects
Documentation
```release-note
None
```

Pipeline: fix crash on `ResultHandler` throwing exception

---

dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp

Issue Number: close #6233 
Tests 
Side effects
Documentation
```release-note
None
```

storage: add an info log of query

---

dbms/src/Functions/FunctionHelpers.cpp
dbms/src/Storages/DeltaMerge/StableValueSpace.cpp

Tests 
Side effects
Documentation
```release-note
None
```

*: use `if (container.contains(value))` instead of `if (container.count(value))`

---

dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
dbms/src/Flash/Pipeline/Exec/PipelineExecBuilder.cpp
dbms/src/Flash/Pipeline/Exec/PipelineExecBuilder.h

Issue Number: close #7565
Tests 
Side effects
Documentation
```release-note
None
```

fix possible issues for `PipelineExecGroupBuilder`

---

dbms/src/Debug/MockRaftStoreProxy.cpp
dbms/src/Debug/dbgFuncMockTiDBTable.cpp
dbms/src/Storages/Transaction/ApplySnapshot.cpp
dbms/src/Storages/Transaction/KVStore.cpp
dbms/src/Storages/Transaction/KVStore.h
dbms/src/Storages/Transaction/Region.cpp
dbms/src/Storages/Transaction/Region.h
dbms/src/Storages/Transaction/RegionData.cpp
dbms/src/Storages/Transaction/RegionData.h
dbms/src/Storages/Transaction/RegionManager.h
dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp

Issue Number: close #7578
Tests 
Side effects
Documentation
```release-note
None
```

Print corresponding region and index when meet PK error

---

dbms/src/Core/SpillHandler.cpp
dbms/src/Core/Spiller.cpp
dbms/src/Core/Spiller.h
dbms/src/Core/tests/gtest_spiller.cpp
dbms/src/DataStreams/MergeSortingBlockInputStream.cpp
dbms/src/DataStreams/MergeSortingBlockInputStream.h
dbms/src/Interpreters/Aggregator.cpp
dbms/src/Interpreters/Aggregator.h
dbms/src/Interpreters/Join.cpp
dbms/src/Operators/MergeSortTransformOp.cpp
dbms/src/Operators/MergeSortTransformOp.h

Issue Number: close #7560
Tests 
Side effects
Documentation
```release-note
None
```

fix false positive error in spiller

---

dbms/src/Storages/StorageDisaggregatedRemote.cpp
dbms/src/Storages/Transaction/FastAddPeer.cpp

Revert "Revert "update client-c to support choosing non pending peer when dis…"

---

dbms/src/Flash/Pipeline/Schedule/Tasks/TaskProfileInfo.h

Issue Number: close #7610
Tests 
Side effects
Documentation
```release-note
None
```

fix build fail in mac introduce by https://github.com/pingcap/tiflash/pull/7584

---

dbms/src/Debug/dbgQueryExecutor.cpp
dbms/src/Debug/dbgQueryExecutor.h
dbms/src/Flash/Mpp/MPPTaskManager.cpp
dbms/src/Flash/Mpp/MPPTaskManager.h
dbms/src/Flash/Mpp/MinTSOScheduler.cpp
dbms/src/Flash/Mpp/tests/gtest_aborted_mpp_gather_cache.cpp
dbms/src/Flash/tests/gtest_compute_server.cpp
dbms/src/Server/FlashGrpcServerHolder.cpp
dbms/src/Server/MockComputeClient.h
dbms/src/TestUtils/MPPTaskTestUtils.cpp
dbms/src/TestUtils/MPPTaskTestUtils.h

Issue Number: ref #7587
- Fix unstable tests introduced by #7589
- Add failpoint tests in mpp_fail.test to ut
Tests 
Side effects
Documentation
```release-note
None
```

Fix unstable tests and add more ut

---

dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
dbms/src/Storages/Transaction/TiKVKeyValue.cpp
dbms/src/Storages/Transaction/TiKVKeyValue.h

Issue Number: close #7647
Add more log when learner read meet error
Tests 
Side effects
Documentation
```release-note
None
```

add more log when learner read meet error

---

dbms/src/Interpreters/Settings.h
dbms/src/Server/Server.cpp

cherry-pick of https://github.com/pingcap/tiflash/pull/7672
* * *
Issue Number: close #7671 
Tests 
Side effects
Documentation
```release-note
None
```

Cut down the wait time for sync schema in restart(release-6.5)

---

dbms/src/Common/tests/gtest_cpu_affinity_manager.cpp
dbms/src/Flash/Mpp/MinTSOScheduler.cpp

cherry pick #7693
close pingcap/tiflash#7692
Tests 
Side effects
Documentation
```release-note
None
```

cherry-pick #7693

---

dbms/src/Flash/Mpp/MPPTask.cpp

Issue Number: ref #7659 
Previously, TiFlash report status to coordinator no matter task failed or not. However, tidb only makes use of reported info in two situations:
1. Root tasks returned error response, thus tidb needs the report info to provide accurate error message.
2. report_execution_summary flag is set, tidb needs to wait all reports to collect execution summaries
Thus, this pr optimize tiflash side to report status when report info is needed.  
Tests 
Side effects
Documentation
```release-note
None
```

ReportStatus to coordinator only when report info is needed

---

dbms/src/IO/BufferWithOwnMemory.h

Issue Number: ref #4605
Tests 
Side effects
Documentation
```release-note
None
```

fix tidy in dbms/src/IO/BufferWithOwnMemory.h

---

dbms/src/IO/CompressedReadBuffer.cpp

Issue Number: ref #4605 
Tests 
Side effects
Documentation
```release-note
None
```

fix tidy in dbms/src/IO/CompressedReadBuffer.cpp

---

dbms/src/Common/tests/gtest_cpu_affinity_manager.cpp

Issue Number: close  pingcap/tiflash#7472
Tests 
Side effects
Documentation
```release-note
None
```

Check CPU cores in CPUAffinityManagerTest (#7473) (#7476)

---

dbms/src/Interpreters/Join.cpp

Issue Number: close #7807 
Tests 
- [] Manual test (add detailed scripts or steps below)
Side effects
Documentation
```release-note
None
```

Add back reservation in join probe

---

dbms/src/Debug/dbgFuncSchemaName.cpp
dbms/src/Debug/dbgTools.cpp

Issue Number: ref #7881
Master branch's ci has some problems since pipeline model is enabled by default, so use this pr to fix the daily fail in release-7.3 branch
Tests 
Side effects
Documentation
```release-note
None
```

fix daily fail for releaes-7.3 branch

---

dbms/src/Storages/DeltaMerge/Remote/RNLocalPageCache.cpp

Issue Number: ref #7883
Tests 
Side effects
Documentation
```release-note
None
```

Refine pagestorage cache wait time.

---

dbms/src/Interpreters/Settings.h

Issue Number: close https://github.com/pingcap/tiflash/issues/7928
In https://github.com/pingcap/tiflash/pull/7895, I mistakenly turn on clang-format for settings.
Tests 
Side effects
Documentation
```release-note
None
```

Turn off clang-format for settings

---

dbms/src/Flash/Mpp/MPPTask.cpp
dbms/src/Flash/Mpp/MPPTaskManager.cpp
tests/fullstack-test2/ddl/alter_exchange_partition.test

Issue Number: close #7933
Remove some redundant error message.
Tests 
Side effects
Documentation
```release-note
None
```

remove redundant error message

---

dbms/src/Storages/Transaction/KVStore.h

Issue Number: close #7936
Tests 
Side effects
Documentation
```release-note
None
```

Fix race condition in PreHandlingTrace

---

dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
dbms/src/Flash/Planner/PhysicalPlanNode.cpp
dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
dbms/src/Interpreters/Join.cpp
dbms/src/Interpreters/Join.h

Add tidb_executor_id in Join's log
Tests 
Side effects
Documentation
```release-note
None
```

Add tidb executor id in Join's log

---

.github/licenserc.yml

Issue Number: close https://github.com/pingcap/tiflash/issues/7968
Tests 
Side effects
Documentation
```release-note
None
```

Update licenserc.yml (release-7.1)

---

.devcontainer/Makefile

Tests 
Side effects
Documentation
```release-note
None
```

Fix license (release-7.2)

---

.devcontainer/Makefile

Tests 
Side effects
Documentation
```release-note
None
```

Fix license (release-7.0)

---

.devcontainer/Makefile

Tests 
Side effects
Documentation
```release-note
None
```

Fix license (release-7.3)

---

.devcontainer/Makefile

Issue Number: close https://github.com/pingcap/tiflash/issues/7968
Tests 
Side effects
Documentation
```release-note
None
```

Fix license (release-7.1)

---

.devcontainer/Makefile

Issue Number: close https://github.com/pingcap/tiflash/issues/7968
Tests 
Side effects
Documentation
```release-note
None
```

Fix license

---

dbms/src/Server/Server.cpp

Issue Number: ref #7595
Tests 
Side effects
Documentation
```release-note
None
```

Fix error message.

---

dbms/src/Flash/CoprocessorHandler.cpp
dbms/src/Storages/DeltaMerge/SSTFilesToBlockInputStream.cpp
dbms/src/Storages/DeltaMerge/SSTFilesToBlockInputStream.h
dbms/src/Storages/Transaction/ApplySnapshot.cpp
dbms/src/Storages/Transaction/LearnerRead.cpp
dbms/src/Storages/Transaction/Region.cpp
dbms/src/Storages/Transaction/RegionException.h
dbms/src/Storages/Transaction/RegionMeta.h

Issue Number: ref #7777
1. Clean some nesting lambda in learner read
2. Add some more region error case
Tests 
Side effects
Documentation
```release-note
None
```

Add more info when learner read fails

---

dbms/src/Common/FailPoint.cpp
dbms/src/Flash/Coprocessor/DAGContext.cpp
dbms/src/Flash/Coprocessor/DAGContext.h
dbms/src/Flash/tests/gtest_auto_spill_aggregation.cpp
dbms/src/Flash/tests/gtest_auto_spill_join.cpp
dbms/src/Flash/tests/gtest_auto_spill_sort.cpp
dbms/src/Flash/tests/gtest_spill_aggregation.cpp
dbms/src/Flash/tests/gtest_spill_join.cpp
dbms/src/Flash/tests/gtest_spill_sort.cpp
dbms/src/Interpreters/AggSpillContext.cpp
dbms/src/Interpreters/AggSpillContext.h
dbms/src/Interpreters/Aggregator.cpp
dbms/src/Interpreters/HashJoinSpillContext.cpp
dbms/src/Interpreters/HashJoinSpillContext.h
dbms/src/Interpreters/JoinPartition.cpp
dbms/src/Interpreters/SortSpillContext.cpp
dbms/src/Interpreters/SortSpillContext.h
dbms/src/TestUtils/ExecutorTestUtils.cpp
dbms/src/TestUtils/ExecutorTestUtils.h

Add ut for auto spill
Tests 
Side effects
Documentation
```release-note
None
```

Add auto spill ut

---

dbms/src/Storages/KVStore/FFI/ProxyFFI.cpp
dbms/src/Storages/KVStore/FFI/ProxyFFI.h
dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp

Issue Number: ref #7777
Tests 
Side effects
Documentation
```release-note
None
```

Fix empty rethrow in apply snapshot

---

dbms/src/Common/MemoryTracker.cpp

Issue Number: ref #8128
Tests 
Side effects
Documentation
```release-note
None
```

Only add shared column data size to root_of_query_mem_trackers.

---

dbms/src/Flash/Pipeline/Schedule/TaskQueues/ResourceControlQueue.cpp

Issue Number: close #8141
Tests 
Side effects
Documentation
```release-note
None
```

fix RCQ::cancel miss calling notify_all

---

dbms/src/Flash/Mpp/MinTSOScheduler.cpp

Issue Number: close #8157
Tests 
Side effects
Documentation
```release-note
None
```

Adjust the soft limit of mintso scheduler to logical cores

---

dbms/src/Flash/Mpp/MinTSOScheduler.cpp

Issue Number: close #8157
Tests 
Side effects
Documentation
```release-note
None
```

Adjust the soft limit of mintso scheduler to 2 * logical cores

---

dbms/src/Flash/Executor/PipelineExecutorContext.cpp
dbms/src/Flash/Executor/tests/gtest_pipeline_executor_context.cpp

Issue Number: close #8165
Tests 
Side effects
Documentation
```release-note
None
```

Fix possible stuck due to cop response writing occur error

---

dbms/src/Flash/Mpp/MPPTaskId.h
metrics/grafana/tiflash_summary.json

Issue Number: close #8162
Tests 
Side effects
Documentation
```release-note
None
```

refine resource group metric name

---

release-centos7-llvm/Makefile
release-centos7-llvm/scripts/build-asan.sh
release-centos7-llvm/scripts/build-tiflash-release.sh
release-centos7-llvm/scripts/build-tsan.sh

Issue Number: close #8190 
Tests 
Manually test tsan build script.
Side effects
Documentation
```release-note
None
```

Add asan/tsan docker build script

---

dbms/src/Common/FailPoint.cpp
dbms/src/Common/tests/mpmc_queue_perftest.cpp
dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
dbms/src/Flash/FlashService.cpp
dbms/src/Flash/tests/bench_exchange.cpp
dbms/src/Storages/DeltaMerge/PKSquashingBlockInputStream.h
dbms/src/Storages/KVStore/Read/LearnerRead.cpp
dbms/src/Storages/KVStore/Read/ReadIndex.cpp
dbms/src/Storages/StorageDisaggregatedRemote.cpp
libs/libcommon/src/tests/gtest_crc64.cpp
libs/libcommon/src/tests/gtest_mem_utils.cpp

* Refine error message when establish disagg task timeout
* Refine error logging when wn handling expired EstablishDisaggTask request
* Refine error logging when query fails with the keyspace id of table
* Simplify some logic in learner read
Before this PR
```sql
-- EstablishDisaggTask timeout
> select count(*) from sbtest1;
(1105, 'other error for mpp stream: Code: 0, e.displayText() = DB::Exception: EstablishDisaggTask Failed4: Deadline Exceeded, e.what() = DB::Exception,')
-- Wait index timeout
> select count(*) from sbtest1;
(1105, 'other error for mpp stream: Code: 0, e.displayText() = DB::Exception: EstablishDisaggregatedTask failed: Region unavailable, region_id=199035950 wait_index=1528819 …
```

*: Refine error message when deadline exceeded

---

dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp
dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.h

Tests 
Side effects
Documentation
```release-note
None
```

Refine filter parser

---

dbms/src/Storages/DeltaMerge/SegmentReadTask.h

Issue Number: close https://github.com/pingcap/tiflash/issues/6233
Problem Summary: Fix build on mac
Tests 
Side effects
Documentation
```release-note
None
```

*: Fix build on mac

---

dbms/src/Interpreters/Join.cpp

Issue Number: close #8257
Tests 
Side effects
Documentation
```release-note
None
```

Add some logs about join build

---

dbms/src/Storages/KVStore/Read/LearnerRead.h
dbms/src/Storages/KVStore/Read/LearnerReadWorker.cpp
dbms/src/Storages/KVStore/Read/LearnerReadWorker.h
dbms/src/Storages/KVStore/tests/gtest_learner_read.cpp

Issue Number: close #8249
This may not be the root cause, but it can panic.
Tests 
Side effects
Documentation
```release-note
None
```

Fix a potential null pointer issue

---

.devcontainer/README.md

Issue Number: close https://github.com/pingcap/tiflash/issues/6233
Tests 
Side effects
Documentation
```release-note
None
```

Update README.md of devcontainer

---

dbms/src/Common/ThreadedWorker.h

Issue Number: ref #8316
Tests 
Side effects
Documentation
```release-note
None
```

Storage: Add stacktrace in log when ThreadedWorker meets an exception.

---

dbms/src/Common/tests/gtest_cpu_affinity_manager.cpp

Issue Number: close #8327
Tests 
Side effects
Documentation
```release-note
None
```

fix unstable unit test `CPUAffinityManagerTest.CPUAffinityManager`

---

dbms/src/Common/TiFlashMetrics.h
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.cpp
dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
dbms/src/Storages/DeltaMerge/Segment.h
dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h
dbms/src/Storages/StorageDisaggregatedRemote.cpp

Issue Number: close #8362 
master: https://github.com/pingcap/tiflash/pull/8369
Tests 
Side effects
Documentation
```release-note
None
```

Check RU in read thread of Storage.

---

dbms/src/Interpreters/Settings.cpp
dbms/src/Interpreters/Settings.h
dbms/src/Server/Server.cpp

Issue Number: close #8367
Tests 
Side effects
Documentation
```release-note
None
```

Print changed config during starting to better check whether configs take affect

---

dbms/src/Flash/Executor/PipelineExecutor.cpp
dbms/src/Flash/Mpp/MPPTask.cpp

Tests 
Side effects
Documentation
```release-note
None
```

refine log

---

dbms/src/Encryption/KeyManager.h
dbms/src/Storages/Page/V2/PageFile.cpp
dbms/src/Storages/Page/V2/PageFile.h
dbms/src/Storages/Page/V2/PageStorage.cpp
dbms/src/Storages/Page/V2/PageStorage.h
dbms/src/Storages/Page/V2/VersionSet/PageEntriesBuilder.h
dbms/src/Storages/Page/V2/VersionSet/PageEntriesVersionSetWithDelta.cpp
dbms/src/Storages/Page/V2/VersionSet/PageEntriesVersionSetWithDelta.h
dbms/src/Storages/Page/V2/gc/DataCompactor.h
dbms/src/Storages/Page/V2/gc/LegacyCompactor.cpp
dbms/src/Storages/Page/V2/gc/LegacyCompactor.h
dbms/src/Storages/Page/V2/gc/restoreFromCheckpoints.h
dbms/src/Storages/Page/V2/tests/gtest_legacy_compactor.cpp
dbms/src/Storages/Page/V2/tests/gtest_page_file.cpp
dbms/src/Storages/Page/V2/tests/gtest_page_map_version_set.cpp
dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV2.cpp
dbms/src/Storages/Page/workload/PSStressEnv.h

use `DB::Logger` instead of `Poco::Logger *`
Tests 
Side effects
Documentation
```release-note
None
```

PageStorage: fix some tidy

---

dbms/src/Flash/ResourceControl/LocalAdmissionController.h

Issue Number: close #8459
Tests 
Side effects
Documentation
```release-note
None
```

Add try/catch protection for ~LocalAdmissionController

---

dbms/src/Flash/Coprocessor/DAGExpressionAnalyzerHelper.cpp
dbms/src/Flash/Coprocessor/DAGUtils.cpp
dbms/src/Flash/Coprocessor/DAGUtils.h
tests/fullstack-test/expr/issue_8482.test

Issue Number: close #8482
Tests 
Side effects
Documentation
```release-note
None
```

Fix the issue that functions that rely on `tipb::FieldType` may produce incorrect results

---

dbms/src/Storages/DeltaMerge/tests/gtest_dm_ingest.cpp
dbms/src/Storages/KVStore/Utils.h
dbms/src/Storages/Page/V3/Blob/BlobStat.cpp
dbms/src/Storages/Page/V3/PageDirectory.h
release-centos7-llvm/env/prepare-sysroot.sh

Issue Number: ref https://github.com/pingcap/tiflash/issues/7193
* Fix some compile errors under clang 17
* Refine the style of `release-centos7-llvm/env/prepare-sysroot.sh`
Tests 
Side effects
Documentation
```release-note
None
```

*: Fix compile error under clang 17

---

dbms/src/Functions/FunctionsMiscellaneous.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/8508
Tests 
Side effects
Documentation
```release-note
None
```

Fix compile error on mac

---

dbms/src/Common/FailPoint.cpp
dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp
dbms/src/Storages/KVStore/MultiRaft/RegionSerde.h
dbms/src/Storages/KVStore/Region.cpp
dbms/src/Storages/KVStore/Region.h
dbms/src/Storages/KVStore/Utils/SerializationHelper.h
dbms/src/Storages/KVStore/tests/gtest_raftstore_v2.cpp
dbms/src/Storages/KVStore/tests/gtest_region_persister.cpp

Issue Number: close #8647
Pick https://github.com/pingcap/tiflash/pull/8614 for issue https://github.com/pingcap/tiflash/issues/8590
Tests 
See below
Side effects
Documentation
```release-note
None
```

KVStore: pick flexible region format to release-7.5

---

dbms/src/Common/TiFlashMetrics.h
dbms/src/Storages/Page/workload/CMakeLists.txt
dbms/src/Storages/Page/workload/PSBackground.cpp
dbms/src/Storages/Page/workload/PSWorkload.cpp
dbms/src/Storages/Page/workload/TiFlashMetricsHelper.cpp
dbms/src/Storages/Page/workload/TiFlashMetricsHelper.h

Issue Number: ref https://github.com/pingcap/tiflash/issues/8650
Following testing after https://github.com/pingcap/tiflash/pull/8651. Run `./tiflash pageworkload --color false` for 3 times
-- | read_speed (GB/s) | write_speed(GB/s)
-- | -- | --
without optimization | 28.83633333 | 0.9126666667
with optimization | 33.02466667 | 0.9873333333
--  | blob_write-p999 | blob_write-p99 | blob_write-avg | total-p999 | total-avg
-- | -- | -- | -- | -- | --
without optimization | 99.78 | 45.47233333 | 8.125333333 | 118.4893333 | 9.66
with optimization | 28.968 | 16.99433333 | 7.356 | 37.537 | 8.836666667
We can see that the read_speed increase about 14%, write_speed increase about 8%. And p999 write latency down from 118.49ms to 37.53ms, avg write latency down from 9.66ms to 8.83ms …

 testing: Add the p99 quantile of write latency to `pageworkload`

---

dbms/src/TiDB/Schema/SchemaBuilder.cpp
dbms/src/TiDB/Schema/SchemaBuilder.h

Tests 
Side effects
Documentation
```release-note
None
```

ddl: Add the reason why an IStorage instance is recovered

---

dbms/src/Storages/DeltaMerge/File/DMFile.h

Tests 
Side effects
Documentation
```release-note
None
```

DTTool: ouput columns order by column id

---

dbms/src/Encryption/KeyspacesKeyManager.cpp
dbms/src/Encryption/KeyspacesKeyManager.h

Issue Number: close #8351
```
file_provider -> key_manager
key_manager -> page_storage
page_storage -> file_provider
```
own `std::weak_ptr<UniversalPageStorage>` in `KeyspacesKeyManager`
Tests 
Side effects
Documentation
```release-note
None
```

Encryption: fix circular reference in KeyspacesKeyManager

---

contrib/abseil-cpp-cmake/CMakeLists.txt

Issue Number: close https://github.com/pingcap/tiflash/issues/8715, close https://github.com/pingcap/tiflash/issues/8685
Includes fixes of https://github.com/pingcap/tiflash/pull/8693 https://github.com/pingcap/tiflash/pull/8714
Tests 
Side effects
Documentation
```release-note
None
```

update client-c for release-6.1

---

dbms/src/Storages/DeltaMerge/ReadThread/CPU.cpp

Fix build error in intel mac.
Tests 
Side effects
Documentation
```release-note
None
```

fix mac build error

---

dbms/src/Interpreters/Aggregator.cpp
dbms/src/Interpreters/Aggregator.h
dbms/src/Operators/AggregateContext.cpp
dbms/src/Operators/AggregateContext.h
tests/fullstack-test/issues/issue_8799.test

Issue Number: close #8799
Tests 
Side effects
Documentation
```release-note
None
```

fix agg bug in some corner cases

---

CMakePresets.json

Issue Number: close #8826
Add CMakePresets.json and some common pre-defined cmake presets.
Tests 
Side effects
Documentation
```release-note
None
```

Add CMakePresets.json and some common pre-defined cmake presets

---

dbms/src/Storages/KVStore/FFI/ProxyFFI.h

Issue Number: close #8835
Tests 
Side effects
Documentation
```release-note
None
```

KVStore: Fix FFI in disagg mode

---

dbms/src/Flash/Mpp/MinTSOScheduler.cpp

Issue Number: ref #8876
Tests 
Side effects
Documentation
```release-note
None
```

adjust the up bound of task_scheduler_active_set_soft_limit

---

dbms/src/Flash/Mpp/MinTSOScheduler.cpp

Issue Number: close #8876
Tests 
Side effects
Documentation
```release-note
None
```

remove implicit up bound of active query soft limit

---

dbms/src/Interpreters/SemiJoinHelper.cpp
tests/fullstack-test/issues/issue_8811.test

Issue Number: close #8811
Tests 
Side effects
Documentation
```release-note
Fix the unexpected exception "The equal condition from in column should be nullable, otherwise it should be used as join key"
```

Fix the unexpected exception "The equal condition from in column should be nullable, otherwise it should be used as join key"

---

dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilter.cpp
dbms/src/Storages/DeltaMerge/File/ColumnCache.cpp
dbms/src/Storages/DeltaMerge/File/ColumnCache.h
dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
dbms/src/Storages/DeltaMerge/File/DMFileReader.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp

Reverts pingcap/tiflash#8854
Highly suspected to be related to https://github.com/pingcap/tiflash/issues/8904
```release-note
None
```

Revert "Storage: Refactor DMFileReader"

---

dbms/src/Storages/DeltaMerge/SegmentReadTask.h
dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task.cpp

Tests 
Side effects
Documentation
```release-note
None
```

tests: Remove `DBMS_PUBLIC_GTEST` hack in SegmentReadTask

---

README.md
dbms/src/Storages/KVStore/Decode/PartitionStreams.cpp
docs/tiflash_http_api.md
release-centos7-llvm/gen_coverage.sh

Add http API doc on TiFlash server
Preview:
https://github.com/pingcap/tiflash/blob/78e9bb55f848e8087ece334e12a14052ee224c37/docs/tiflash_http_api.md
Tests 
Side effects
Documentation
```release-note
None
```

*: Add http docs for TiFlash

---

dbms/src/IO/Compression/tests/gtest_codec_compression.cpp

Reduce the number of unit test cases.
Before: 1132
Now: 204
Tests 
Side effects
Documentation
```release-note
None
```

Compression: refine unit tests

---

.github/pull_request_template.md

Issue Number: close #9074
Add marker, so that bot can recognize it and put it into commit message when merging.
Tests 
Side effects
Documentation
```release-note
None
```

GitHub: Add marker in PR template to be recognized by bot to put into commit message

---

README.md

This reverts commit e6f88ef7c5cf9c8dd396a74e65bfb710a059ae65.
Issue Number: close #9074
```commit-message
Revert previous boring change.
```
Tests 
Side effects
Documentation
```release-note
None
```

chore: Revert "chore: Test commit message (#9076)"

---

dbms/src/Storages/DeltaMerge/StableValueSpace.cpp

Issue Number: ref #6233, ref https://github.com/pingcap/tiflash/issues/9036
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

*: fix Exception

---

dbms/src/IO/Compression/tests/bench_codec_delta_for.cpp

```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

*: fix bench_dbms build

---

dbms/src/Common/TiFlashMetrics.h
dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
metrics/grafana/tiflash_summary.json

Issue Number: close #8081
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

KVStore: More metrics for Prehandling

---

dbms/src/Common/TiFlashSecurity.h
dbms/src/Common/tests/gtest_tiflash_security.cpp

Simplify nesting if..else code in `TiFlashSecurity.h`
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

*: Simplify nesting if..else code

---

.clang-tidy
dbms/src/Common/TiFlashMetrics.h
dbms/src/Flash/Disaggregated/S3LockClient.cpp
dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeer.cpp
dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp

Issue Number: ref https://github.com/pingcap/tiflash/issues/9098
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

KVStore: Add metrics for AddLock failure

---

dbms/src/Flash/tests/gtest_compute_server.cpp

Issue Number: ref #8285 
https://github.com/pingcap/tiflash/issues/8285#issuecomment-2212916541
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Change sleep time for sanitizer build type of gtest_compute_server

---

dbms/src/IO/Compression/CompressionSettings.h
dbms/src/IO/Compression/tests/CodecTestSequence.h
dbms/src/IO/Compression/tests/bench_codec.cpp
dbms/src/IO/Compression/tests/gtest_codec_compression.cpp

Issue Number: close #8982
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Compression: add microbenchmark

---

dbms/src/Common/TiFlashMetrics.h
dbms/src/Storages/DeltaMerge/File/DMFileWithVectorIndexBlockInputStream.cpp
dbms/src/Storages/DeltaMerge/Index/VectorIndexHNSW/Index.cpp
dbms/src/Storages/DeltaMerge/Index/VectorIndexHNSW/Index.h

Pick https://github.com/tidbcloud/tiflash-cse/pull/190
```commit-message
storage: Add vector search metrics
```
Tests 
Side effects
Documentation
```release-note
None
```

storage: Add vector search metrics

---

dbms/src/TestUtils/gtests_dbms_main.cpp

```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

tests: update the number of read threads in unittest

---

dbms/src/Common/TiFlashMetrics.h
dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h

Issue Number: ref #6834
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Storages: add metrics of read thread

---

release-centos7-llvm/dockerfiles/Dockerfile-tiflash-ci
release-centos7-llvm/dockerfiles/Dockerfile-tiflash-ci-base
tests/docker/mock-test-dt.yaml
tests/docker/tiflash-dt-disable-local-tunnel.yaml
tests/docker/tiflash-dt-force-enable-lm.yaml
tests/docker/tiflash-dt-lightweight-compression.yaml
tests/docker/tiflash-dt-sync-grpc.yaml
tests/docker/tiflash-dt.yaml
tests/run-test.py

Problem Summary: python2 has been archived since 2020. https://www.python.org/doc/sunset-python-2/
```commit-message
ci: upgrade tiflash-ci-base image to Python3
```
Tests 
Side effects
Documentation
```release-note
None
```

ci: upgrade tiflash-ci-base image to Python3

---

dbms/src/Storages/DeltaMerge/File/DMFileWriter.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/9032
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Fix build under release mode

---

release-centos7-llvm/env/.gitignore
tests/docker/config/tics_dt.toml
tests/docker/config/tiflash_dt.toml
tests/docker/config/tiflash_dt_disable_local_tunnel.toml
tests/docker/config/tiflash_dt_force_enable_lm.toml
tests/docker/config/tiflash_dt_lightweight_compression.toml
tests/docker/config/tiflash_dt_sync_grpc.toml
tests/docker/run.sh
tests/docker/tiflash-dt-disable-local-tunnel.yaml
tests/docker/tiflash-dt-force-enable-lm.yaml
tests/docker/tiflash-dt-lightweight-compression.yaml
tests/docker/tiflash-dt-sync-grpc.yaml
tests/docker/tiflash-dt.yaml
tests/docker/tiflash-tagged-image.yaml
tests/docker/util.sh

cleanup useless params in the integration test config files
```commit-message
tests: Refine integration tests
```
Tests 
Side effects
Documentation
```release-note
None
```

tests: Refine integration tests

---

dbms/src/DataStreams/FormatFactory.cpp

```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

*: add TabSeparated format back

---

dbms/src/Functions/FunctionsLogical.h

Issue Number: ref #9146
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

fix issue introduced by #9523

---

dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyVectorIndexWriter.cpp

```commit-message
*: fix darwin build
```
Tests 
Side effects
Documentation
```release-note
None
```

*: fix darwin build

---

dbms/src/Storages/DeltaMerge/File/DMFileWithVectorIndexBlockInputStream.cpp

```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

build: fix drawin build

---

dbms/src/Functions/tests/gtest_strings_replace.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile.h
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp
dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.cpp
dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.h
dbms/src/Storages/DeltaMerge/Decode/BoundedSSTFilesToBlockInputStream.cpp
dbms/src/Storages/DeltaMerge/Decode/SSTFilesToBlockInputStream.h
dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.h
dbms/src/Storages/DeltaMerge/Delta/MemTableSet.cpp
dbms/src/Storages/DeltaMerge/DeltaMerge.h
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/Segment.h
dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_version_filter.cpp

```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Storages: some minor refine

---

.devcontainer/Dockerfile
.devcontainer/Makefile
.devcontainer/misc/codespaces.zsh-theme
.devcontainer/misc/docker-entrypoint.sh

```commit-message
Update TiFlash devcontainer to use latest build infrastructure.
```
Currently it may be not friendly for users that cannot access hub.pingcap.net. I hope some alternative way could be provided later.
Tests 
Side effects
Documentation
```release-note
None
```

misc: Update devcontainer

---

dbms/src/IO/FileProvider/CompressedReadBufferFromFileBuilder.cpp
dbms/src/IO/FileProvider/CompressedReadBufferFromFileBuilder.h
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileDeleteRange.h
dbms/src/Storages/DeltaMerge/File/DMFile.cpp
dbms/src/Storages/DeltaMerge/File/DMFile.h
dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.cpp
dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.h

```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

*: Add const in some function parameters and member functions

---

dbms/src/DataTypes/DataTypeString.cpp

Issue Number: ref #9673
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Small refinement of DataTypeString

---

dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
tests/fullstack-test2/ddl/partitions/rename_column.test

Issue Number: close #9787
```commit-message
Sync schema for all partitions if the schema of one of physical tables is different from the logical table.
```
Tests 
Side effects
Documentation
```release-note
fix query partition table failed after rename column
```

ddl: fix query partition table failed after rename column

---

dbms/src/Storages/KVStore/MultiRaft/Disagg/RaftLogManager.h
dbms/src/Storages/KVStore/MultiRaft/RegionCFDataBase.h
dbms/src/Storages/KVStore/MultiRaft/RegionData.cpp
dbms/src/Storages/KVStore/MultiRaft/RegionData.h
libs/libcommon/include/common/demangle.h

Issue Number: close #9833
See https://github.com/pingcap/tiflash/issues/9833#issuecomment-2614259328
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Fix compile issue of RegionDataMemDiff in macOS

---

dbms/src/Interpreters/Settings.cpp
dbms/src/Interpreters/Settings.h
dbms/src/Server/Server.cpp

Issue Number: close #9745 ref #4982
```commit-message
```
Tests 
Side effects
Documentation
```release-note
Fix an issue that TiFlash may unexpectedly reject raft message when memory usage is not high
```

Set proxy's memory limit by TiFlash (#9753) and update tiflash proxy

---

dbms/src/Debug/dbgKVStore/dbgFuncRegion.cpp
dbms/src/Debug/dbgTools.cpp
dbms/src/Server/Server.cpp
dbms/src/Server/Setup.cpp
dbms/src/Server/Setup.h
dbms/src/Storages/KVStore/Decode/RegionTable.cpp
dbms/src/Storages/KVStore/Decode/RegionTable.h
dbms/src/Storages/KVStore/FFI/ProxyFFI.cpp
dbms/src/Storages/KVStore/KVStore.cpp
dbms/src/Storages/KVStore/KVStore.h
dbms/src/Storages/KVStore/MultiRaft/RegionMeta.cpp
dbms/src/Storages/KVStore/MultiRaft/RegionMeta.h
dbms/src/Storages/KVStore/MultiRaft/RegionRangeKeys.cpp
dbms/src/Storages/KVStore/MultiRaft/RegionRangeKeys.h
dbms/src/Storages/KVStore/MultiRaft/RegionSerde.h
dbms/src/Storages/KVStore/Read/ReadIndex.cpp
dbms/src/Storages/KVStore/TMTContext.cpp
dbms/src/Storages/KVStore/TMTContext.h
dbms/src/Storages/KVStore/tests/gtest_kvstore.cpp
dbms/src/Storages/KVStore/tests/gtest_spill.cpp

```commit-message
* Move config `flash.wait_region_ready_tick` to `TMTContext::TMTContext`
* Move `setOpenFileLimit` to `Setup.h` and skip setting open file limit if not set
* Refine some codes in `RegionMeta` `RegionRangeKeys`
```
Tests 
Side effects
Documentation
```release-note
None
```

*: Refine codes on Raft

---

dbms/src/Interpreters/JoinV2/HashJoinProbe.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/9937
```commit-message
Fix operator new[] and delete mismatch for join probe prefetch states
```
Tests 
Side effects
Documentation
```release-note
None
```

Fix operator new[] and delete mismatch for join probe prefetch states

---

dbms/src/Flash/tests/gtest_aggregation_executor.cpp

Issue Number: close #9940 
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Fix the out of bound array access issue for gtest

---

dbms/src/AggregateFunctions/AggregateFunctionMinMaxAny.h
dbms/src/AggregateFunctions/AggregateFunctionMinMaxWindow.h
dbms/src/DataStreams/WindowTransformAction.cpp
dbms/src/DataStreams/WindowTransformAction.h
tests/fullstack-test/mpp/window_agg.test

Issue Number: close #9964
```commit-message
```
Tests 
Side effects
Documentation
```release-note
Fix the issue that arena is nullptr in aggregation window function
```

Fix nullptr arena in aggregation window function

---

dbms/src/Columns/ColumnString.cpp
dbms/src/Columns/IColumn.h

Issue Number: close #https://github.com/pingcap/tiflash/issues/10001
Problem Summary: manually cherry pick https://github.com/pingcap/tiflash/pull/10000
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

[cherrypick 9.0-beta.1] fix access invalid memory for Aggregation

---

dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index_utils.h

Polish annQueryInfo again. This should be the better way:
1. Use named parameters for more readability
2. This function only builds TopK. If other kind is needed (like EnableDistanceProj), a new function could be introduced.
Tests 
Side effects
Documentation
```release-note
None
```

Storage: Polish ANNQueryInfo in tests

---

tests/fullstack-test/expr/duration_pushdown.test

Issue Number: close https://github.com/pingcap/tiflash/issues/10020
```commit-message
fix integration tests failed due to lack of alias of the derived table
```
Tests 
Side effects
Documentation
```release-note
None
```

fix integration tests failed due to lack of alias of the derived table

---

dbms/src/Flash/Coprocessor/TiDBTableScan.cpp

Issue Number: ref #9843
```commit-message
https://github.com/pingcap/tipb/pull/355
update tipb to prepare for supporting inverted index
```
Tests 
Side effects
Documentation
```release-note
None
```

*: update tipb to support columnar index

---

tests/fullstack-test/expr/duration_pushdown.test

Issue Number: close https://github.com/pingcap/tiflash/issues/10032
Related tiflash-proxy PR: https://github.com/pingcap/tidb-engine-ext/pull/431, cherry-pick https://github.com/tikv/tikv/pull/18330 from upstream to fix that BR restore may hang tiflash-proxy
And cherry-pick https://github.com/pingcap/tiflash/pull/10021 to fix integration test
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

proxy: Update proxy to fix br hangs (release-9.0-beta.1)

---

dbms/src/Flash/Statistics/ExchangeReceiverImpl.cpp
dbms/src/Flash/Statistics/ExchangeSenderImpl.cpp
dbms/src/Flash/Statistics/TableScanImpl.cpp

Issue Number: ref https://github.com/pingcap/tiflash/issues/9748
Introduced by https://github.com/pingcap/tiflash/pull/9747
After this PR
```
[2025/03/26 17:19:51.120 +08:00] [INFO] [MPPTaskStatistics.cpp:139] ["{\"query_tso\":456911956465680386,\"task_id\":2,\"is_root\":true,\"sender_executor_id\":\"ExchangeSender_28\",\"executors\":[{\"id\":\"ExchangeSender_28\",\"type\":\"ExchangeSender\",\"children\":[\"HashAgg_10\"],\"outbound_rows\":1,\"outbound_blocks\":1,\"outbound_bytes\":9,\"outbound_allocated_bytes\":208,\"concurrency\":1,\"execution_time_ns\":102999905,\"partition_num\":1,\"sender_target_task_ids\":[-1],\"exchange_type\":\"PassThrough\",\"connection_details\":[{\"tunnel_id\":\"tunnel2+-1\",\"sender_target_task_id\":-1,\"sender_target_host\":\"10.2.12.81:54800\" …
```

*: Fix invalid json in ExchangeReceiveDetail

---

dbms/src/Storages/KVStore/ProxyStateMachine.h

Issue Number: ref https://github.com/pingcap/tiflash/issues/9857
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

*: Fix param typo in ProxyStateMachine

---

dbms/src/Flash/FlashService.cpp
dbms/src/Interpreters/JoinV2/HashJoin.cpp

Issue Number: ref https://github.com/pingcap/tiflash/issues/9060
```commit-message
Support enabling Hash Join V2 by TiDB
```
Tests 
Side effects
Documentation
```release-note
None
```

Support enabling hash join v2 by TiDB

---

dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
dbms/src/Storages/DeltaMerge/Filter/PushDownExecutor.cpp
dbms/src/Storages/DeltaMerge/Index/VectorIndex/Reader.cpp
dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/Ctx.cpp
dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/ReaderFromDMFile.cpp
dbms/src/Storages/DeltaMerge/Index/VectorIndex/tests/gtest_dm_vector_index.cpp
dbms/src/Storages/DeltaMerge/Index/VectorIndex/tests/gtest_dm_vector_index_utils.h
dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp

Issue Number: ref #9032 
https://github.com/pingcap/tipb/pull/358
Tests 
Side effects
Documentation
```release-note
None
```

*: update tipb to deprecate column_id field

---

dbms/src/Interpreters/JoinV2/HashJoin.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/10062
```commit-message
Add some failpoints in hash join v2 to fix integration tests failure
```
Tests 
Side effects
Documentation
```release-note
None
```

Add some failpoints in hash join v2 to fix integration tests failure

---

dbms/src/Storages/DeltaMerge/Index/InvertedIndex/Reader/ReaderFromDMFile.cpp
dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/ReaderFromDMFile.cpp
dbms/src/Storages/S3/FileCache.cpp
dbms/src/Storages/S3/FileCache.h

Issue Number: ref #9843 
```commit-message
Add `downloadFileForLocalReadWithRetry` in `FileCache`
```
Tests 
Side effects
Documentation
```release-note
None
```

Storages: refine download index file

---

dbms/src/Common/TiFlashMetrics.h
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/VersionChain/MVCCBitmapFilter.cpp
metrics/grafana/tiflash_summary.json

Issue Number: ref #9963
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Storages: Add metrics for VersionChain

---

libs/libclara-cmake/CMakeLists.txt

Issue Number: ref #10080 
```commit-message
Fix ASAN build failures
```
Tests 
Side effects
Documentation
```release-note
None
```

clara: Fix ASAN

---

dbms/src/TiDB/Schema/TiDB.cpp

Issue Number: ref #9032 
This PR is not required. We just align the code name in accordance with the name change in https://github.com/pingcap/tidb/pull/60719
Tests 
Side effects
Documentation
```release-note
None
```

tidb: Rename HNSW -> Vector

---

dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp

```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Storages: fix TSAN error

---

dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
dbms/src/Storages/DeltaMerge/File/DMFileReader.h
dbms/src/Storages/DeltaMerge/File/ReadBlockInfo.cpp
dbms/src/Storages/DeltaMerge/File/ReadBlockInfo.h
dbms/src/Storages/DeltaMerge/Index/FullTextIndex/Stream/DMFileInputStream.cpp
dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/DMFileInputStream.cpp

```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Storages: separate ReadBlockInfo

---

dbms/src/Storages/DeltaMerge/ConcatSkippableBlockInputStream.cpp
dbms/src/Storages/DeltaMerge/ConcatSkippableBlockInputStream.h
dbms/src/Storages/DeltaMerge/DMDecoratorStreams.h
dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
dbms/src/Storages/DeltaMerge/DeltaMergeHelpers.h
dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.cpp
dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/Segment.h
dbms/src/Storages/DeltaMerge/SegmentRowID.h
dbms/src/Storages/DeltaMerge/tests/gtest_segment_bitmap.cpp

Issue Number: ref #5252
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Storages: implement fast scan using bitmap

---

dbms/src/Flash/Pipeline/Schedule/TaskQueues/tests/gtest_resource_control_queue.cpp

Issue Number: close #10139
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

fix mock LAC unit test data race

---

dbms/src/Common/TiFlashMetrics.h
dbms/src/Flash/Pipeline/Schedule/TaskQueues/ResourceControlQueue.cpp
dbms/src/Flash/Pipeline/Schedule/TaskQueues/tests/gtest_resource_control_queue.cpp
dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp
dbms/src/Flash/ResourceControl/LocalAdmissionController.h
dbms/src/Flash/ResourceControl/MockLocalAdmissionController.cpp
dbms/src/Flash/ResourceControl/TokenBucket.cpp
dbms/src/Flash/ResourceControl/TokenBucket.h

Issue Number: close #10137
before
1. low token notify doesn't work becuase `wait_for` ignore low token signal
2. 5s for computing avg speed is too long, which may not reflect the latest ru speed.
3. acquire token from GAC every 5s
after:
1. `mainLoop` thread will compute ru speed every 1s
2. `requestGACLoop` thread is dedicated to sending gac thread
4. only acquire token from GAC when got low token signal
5. change `min_wait_dura_ms ` from 100ms to 10ms.
```commit-message
```
Tests 
1. create tidb cluster with 2 tiflash(16c)
6. load tpch50g workload
7. run the following scripts: https://github.com/guo-shaoge/tiflash_resource_control_test_tool, detailed test report is internal
1. [high.change.sh](https://github.com/guo-shaoge/tiflash_resource_control_test_tool/blob/master/h …

fix tiflash resource control low token signal miss

---

dbms/src/Flash/Mpp/MPPTask.cpp
dbms/src/Flash/Mpp/MPPTask.h

Add mpp task execution time in info log
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

add mpp task execution time in info log

---

dbms/src/Server/Server.cpp
dbms/src/Storages/Tantivy/TantivyInputStream.h

1. update kvproto and tici to origin master
2. insert Null to missing field, because searchlib can only return pk now, but the columns requested by tidb are not necessarily only pk
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

chore: update kvproto,tici submodule and insert Null to missing field 

---

release-darwin/build/build-release.sh

Issue Number: Close #10237, ref #6233 
```commit-message
build: fix unbound variable error for darwin build script
```
Tests 
Side effects
Documentation
```release-note
None
```

build: fix unbound variable error for darwin build script

---

contrib/tici-search-lib/CMakeLists.txt
dbms/src/Flash/Coprocessor/ShardInfo.h
dbms/src/Storages/Tantivy/TantivyInputStream.h
rust-toolchain.toml

```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

tici: Using u8 slice instead of String for KeyRanges

---

dbms/src/Operators/TantivyReaderSourceOp.cpp
dbms/src/Operators/TantivyReaderSourceOp.h
dbms/src/Storages/StorageTantivy.cpp
dbms/src/Storages/Tantivy/TantivyInputStream.h

```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

tici: Pass the read_ts parameter to searchlib.

---

docs/tiflash_http_api.md

```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

docs: Add http api docs

---

dbms/src/Server/Server.cpp

```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

contrib: update tici

---

dbms/src/Storages/KVStore/TMTContext.cpp

```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

tici: using etcd client to get tici meta service address

---

dbms/src/Server/CMakeLists.txt

```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

*: fix MacOS build

---

dbms/src/Server/DTTool/DTTool.h
dbms/src/Server/DTTool/DTToolBench.cpp
dbms/src/Server/DTTool/DTToolInspect.cpp
dbms/src/Server/tests/gtest_dttool.cpp
dbms/src/Storages/DeltaMerge/File/DMFile.h
dbms/src/Storages/DeltaMerge/VersionChain/MVCCBitmapFilter.cpp

Issue Number: ref https://github.com/pingcap/tiflash/issues/7595
```commit-message
```
```
cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
./dbms/src/Server/tiflash dttool bench --columns 1000 --rows 131000 --sparse-ratio 0.999 --field 12 --write-repeat 1 --repeat 20 --workdir ./tmp_v2 --version 2
[2025/08/21 23:11:07.747 +08:00] [INFO] [DTToolBench.cpp:547] ["average read time: 781.95 ms"] [thread_id=1]
[2025/08/21 23:11:07.747 +08:00] [INFO] [DTToolBench.cpp:555] ["throughput by deserialized bytes (MB/s): 1442.393 throughput by compressed bytes (MB/s): 646.683"] [thread_id=1]
./dbms/src/Server/tiflash dttool bench --columns 1000 --rows 131000 --sparse-ratio 0.999 --field 12 --write-repeat 1 --repeat 20 --workdir ./tmp_v3 --version 3
[2025/08/21 23:12:48.928 +08:00] …
```

dttool: Add dttool bench for sparse column

---

dbms/src/Flash/FlashService.cpp
dbms/src/Flash/Mpp/MPPTaskManager.cpp
dbms/src/Flash/Mpp/MPPTaskManager.h
dbms/src/Server/FlashGrpcServerHolder.cpp
dbms/src/Server/Server.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/10266
Cherry-pick https://github.com/pingcap/tiflash/pull/10299 and https://github.com/pingcap/tiflash/pull/10313 and https://github.com/pingcap/tiflash/pull/10317 to release-8.5
```commit-message
Support graceful shutdown in TiFlash
```
Tests 
Side effects
Documentation
```release-note
Support graceful shutdown in TiFlash
```

Support graceful shutdown in TiFlash (release-8.5)

---

metrics/grafana/tiflash_summary.json

Issue Number: ref https://github.com/pingcap/tiflash/issues/10443
* https://github.com/pingcap/tidb-engine-ext/pull/439
* https://github.com/tidbcloud/cloud-storage-engine/pull/3422
```commit-message
proxy: Add metrics on status-server
```
Tests 
Side effects
Documentation
```release-note
Add metrics about status server
```

proxy: Add metrics on status-server
