pingcap/tiflash

.gitmodules

Issue Number: close #4565
change url of submodule to https url
Tests 
Side effects
Documentation
```release-note
None
```

Unify the url of submodule to https url

---

dbms/src/Storages/Page/V3/tests/gtest_wal_log.cpp

Issue Number: close #4571 
Remove useless TODO in `dbms/src/Storages/Page/V3/tests/gtest_wal_log.cpp`

Remove useless TODO in `dbms/src/Storages/Page/V3/tests/gtest_wal_log.cpp`

---

README.md

Issue Number: close #4574 
Tests 
Side effects
Documentation
```release-note
None
```

doc: add instructions for runing unit tests

---

dbms/src/Common/DynamicThreadPool.cpp

Signed-off-by: fuzhe1989 <fuzhe1989@gmail.com>
Issue Number: close #4595 
`DynamicThreadPool` relies on a counter to detect if all dynamic threads end, until when it can safely destruct.
Previously the last instruction of `DynamicThreadPool::dynamicWork` is exactly the counter's decrement. This is an implicit contract.
However after #4169 for recording thread-related metrics, `UPDATE_CUR_AND_MAX_METRIC` was added. It contains a `SCOPE_EXIT` which will run after the counter's decrement and break the implicit contract.
This introduces a risk that the main thread may find the counter is 0 and exit (and destruct all static variables like `TiFlashMetric`), however the dynamic threads do not really exit and try to visit `TiFlashMetric`.
Wrap the body of …

Fix potential data race in DynamicThreadPool

---

dbms/src/Debug/astToExecutor.cpp
dbms/src/TestUtils/InterpreterTestUtils.cpp
dbms/src/TestUtils/InterpreterTestUtils.h
dbms/src/TestUtils/mockExecutor.cpp
dbms/src/TestUtils/mockExecutor.h
dbms/src/TestUtils/tests/gtest_mock_executors.cpp

Issue Number:  ref #4609 
Tests 
Side effects
Documentation
```release-note
None
```

Interpreter: Hand write tipb::Executor.

---

dbms/CMakeLists.txt
dbms/src/Encryption/RateLimiter.cpp
dbms/src/Interpreters/Context.cpp
dbms/src/Interpreters/Context.h
dbms/src/Server/Server.cpp
dbms/src/Storages/BackgroundProcessingPool.cpp
dbms/src/Storages/BackgroundProcessingPool.h
libs/libcommon/include/common/logger_useful.h

Issue Number: close #4684 #4685
1. `Context::setDefaultProfiles` should be called before  `Context::initializeRateLimiter`. Because `Context::initializeRateLimiter` calls `Context::getBackgroundPool` and `Context::getBlockableBackgroundPool` inside to get background thread ids.
2. `BackgroundProcessingPool::getThreadIds` and `BackgroundProcessingPool::addThreadId` are executing concurrently. `BackgroundProcessingPool::getThreadIds` may be called before all background threads executing  ``BackgroundProcessingPool::addThreadId` completely.
1. Adjust the initialization sequence of `Context`.
2. Add `absl::BlockingCounter` to count all background threads executing `BackgroundProcessingPool::addThreadId` completely.
Tests 
1. Set configuration …

Fix background_pool_size not take effect and BackgroundProcessingPool::getThreadIds may misses some thread_ids.

---

dbms/src/Common/CPUAffinityManager.h
libs/libcommon/include/common/defines.h

Issue Number: close https://github.com/pingcap/tiflash/issues/4701
```release-note
None
```

fix: fix build issue `‘maybe_unused’ attribute ignored` on centos server 

---

dbms/src/Storages/Transaction/ApplySnapshot.cpp

Issue Number: close #4414
Tests 
1. load data into tidb cluster with multiple tiflash nodes by import csv file and set tiflash replica to 1;
2. set tiflash replica to 0 and see whether the data can be reclaimed;
Side effects
Documentation
```release-note
Avoid left data on tiflash node after set tiflash replica to 0
```

clear old range before apply snapshot

---

dbms/src/Storages/DeltaMerge/File/DMFileWriter.cpp
dbms/src/Storages/DeltaMerge/File/DMFileWriter.h

Issue Number: close #4708
In this pr #4500, we avoid write data into minmax index file for emtpy dmfile. But this kind of dmfile cannot be recogonized by older version. So after degrading, tiflash fails.
Reuse old index file format and just ignore the size written into minmax index file in this case.
Tests 
1. Test that `stable_siz_on_disk` is 0 for empty segments;
2. Test that after this fix the master branch can be degraded to ver6.0.0;
Side effects
Documentation
```release-note
None
```

reuse old index file format for empty dmfile and just ignore it's size in statistical data

---

dbms/src/Debug/dbgFuncCoprocessor.cpp
dbms/src/Debug/dbgNaturalDag.cpp
dbms/src/Debug/dbgNaturalDag.h

Issue Number: close #4304 
Tests 
Side effects
Documentation
```release-note
None
```

Add some debug friendly utilities for dag request based test framework

---

dbms/src/Debug/astToExecutor.cpp
dbms/src/Debug/astToExecutor.h
dbms/src/TestUtils/InterpreterTestUtils.cpp
dbms/src/TestUtils/InterpreterTestUtils.h
dbms/src/TestUtils/mockExecutor.cpp
dbms/src/TestUtils/mockExecutor.h
dbms/src/TestUtils/tests/gtest_mock_executors.cpp

Issue Number: ref #4609 
I didn't support mock exchange executors function, in order to fully supprt mock dagrequest, need to implement all of them.
Mock exchangeSender&Receivers.
Little refactor of Interpreter test utils in order to mock exchange executors easily.
Tests 
Side effects
Documentation
```release-note
None
```

Interpreter: Mock exchange executors.

---

dbms/src/Server/StorageConfigParser.cpp
dbms/src/Storages/Page/PageDefines.h
dbms/src/Storages/Page/V3/BlobStore.cpp
dbms/src/Storages/Page/V3/LogFile/LogWriter.cpp
dbms/src/Storages/Page/V3/PageDirectory.cpp
dbms/src/Storages/Page/V3/PageEntriesEdit.h
dbms/src/Storages/Page/V3/PageEntry.h
dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
dbms/src/Storages/Page/WriteBatch.h

Signed-off-by: jiaqizho <zhoujiaqi@pingcap.com>
Issue Number: ref #3594 
- Run `ddl test`  with enable_ps_v3 will get random `nullptr` error. 
- Also we still have some uninit errors when I run valgrind.
```
==24236== Syscall param pwrite64(buf) points to uninitialised byte(s)
==24236==    at 0xE0D8FC3: ??? (syscall-template.S:81)
==24236==    by 0x47D2EEE: DB::PosixWritableFile::pwrite(char*, unsigned long, long) const (PosixWritableFile.cpp:91)
==24236==    by 0x4B4107F: void DB::PageUtil::writeFile<std::shared_ptr<DB::WritableFile> >(std::shared_ptr<DB::WritableFile>&, unsigned long, char*, unsigned long, std::shared_ptr<DB::WriteLimiter> const&, bool) (PageUtil.h:178)
==24236==    by 0x4BB3A04: DB::PS::V3::LogWriter::flush(std::shared_ptr<DB::WriteLimiter> const&) …
```

Fix pagestorage v3 ddl problem.

---

dbms/src/DataStreams/AggregatingBlockInputStream.h
dbms/src/DataStreams/ConcatBlockInputStream.h
dbms/src/DataStreams/ExpressionBlockInputStream.cpp
dbms/src/DataStreams/ExpressionBlockInputStream.h
dbms/src/DataStreams/FilterBlockInputStream.cpp
dbms/src/DataStreams/FilterBlockInputStream.h
dbms/src/DataStreams/HashJoinBuildBlockInputStream.h
dbms/src/DataStreams/LimitBlockInputStream.cpp
dbms/src/DataStreams/LimitBlockInputStream.h
dbms/src/DataStreams/MergeSortingBlockInputStream.cpp
dbms/src/DataStreams/MergeSortingBlockInputStream.h
dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
dbms/src/DataStreams/ParallelAggregatingBlockInputStream.h
dbms/src/DataStreams/PartialSortingBlockInputStream.h
dbms/src/DataStreams/SharedQueryBlockInputStream.h
dbms/src/DataStreams/SquashingBlockInputStream.cpp
dbms/src/DataStreams/SquashingBlockInputStream.h
dbms/src/DataStreams/TiRemoteBlockInputStream.h
dbms/src/DataStreams/UnionBlockInputStream.h
dbms/src/Storages/DeltaMerge/DMSegmentThreadInputStream.h

cherry-pick of https://github.com/pingcap/tics/pull/4022 to release-5.4
* * *
Signed-off-by: JaySon-Huang <jayson.hjs@gmail.com>
Issue Number: close https://github.com/pingcap/tics/issues/4030
```
[2022-02-14T08:41:46.709Z] /build/tics/dbms/src/Storages/DeltaMerge/DMSegmentThreadInputStream.h:47:35: error: Call to virtual method 'DMSegmentThreadInputStream::getName' during construction bypasses virtual dispatch [clang-analyzer-optin.cplusplus.VirtualCall,-warnings-as-errors]
[2022-02-14T08:41:46.709Z]         , log(getMPPTaskLog(log_, getName()))
[2022-02-14T08:41:46.709Z]                                   ^
```
Tests 
Side effects
Documentation
```release-note
None
```

Fix calling virtual function in ctor (#4022)

---

dbms/src/Storages/Page/V3/PageDirectory.cpp
dbms/src/Storages/Page/V3/spacemap/SpaceMapSTDMap.h

Fxied some compile errors on mac in PS V3

---

dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h

Issue Number: close #4752 
This was not previously triggered because index files should be very small.
Tests 
Side effects
Documentation
```release-note
None
```

fix: frame total size include header for indices

---

dbms/src/Storages/DeltaMerge/WriteBatches.h

Issue Number: ref #3594 
The ns_id is uninited. When ingest happened, `PageStorage` won't del the `ext_page_id` because ns_id is wrong.
```
[2022/04/27 07:21:14.499 +08:00] [TRACE] [WriteBatches.h:147] ["WriteBatches:Rollback remove from data_wb : X140630288340448.2241"] [thread_id=58]
[2022/04/27 07:21:27.138 +08:00] [TRACE] [WriteBatches.h:147] ["WriteBatches:Rollback remove from data_wb : X140630288340448.2065"] [thread_id=58]
[2022/04/27 07:21:52.968 +08:00] [TRACE] [WriteBatches.h:147] ["WriteBatches:Rollback remove from data_wb : X140630288340448.2247"] [thread_id=58]
[2022/04/27 07:22:18.728 +08:00] [TRACE] [WriteBatches.h:147] ["WriteBatches:Rollback remove from data_wb : X140630288340448.2249"] [thread_id=58]
[2022/04/27 07:22:31.249 +08:00] [TRACE] …
```

Fix ingest dmfile won't rollback

---

dbms/src/Server/DTTool/DTToolMigrate.cpp
dbms/src/Server/tests/gtest_dttool.cpp
dbms/src/Storages/DeltaMerge/File/DMFile.cpp

Signed-off-by: SchrodingerZhu <i@zhuyi.fan>
Issue Number: close #4778
This PR fixes the problem mentioned in  #4778 and add variant frame lengths to cover the cases.
Tests 
Side effects
Documentation
```release-note
fix potential data corruption for large indices
```

fix: ut and more idx error

---

dbms/src/Interpreters/Context.cpp
dbms/src/Interpreters/Context.h

These methods in Context are duplicated and no effect on other code,
so remove them.
Signed-off-by: Jun Zhang <jun@junz.org>
Issue Number: close #4740
Tests 
Side effects
Documentation
```release-note
None
```

refactor: Remove some non-const member methods in Context.

---

dbms/src/Functions/FunctionsGeo.cpp
dbms/src/Functions/GeoUtils.h

Signed-off-by: Jun Zhang <jun@junz.org>
Issue Number: close #4771 
Tests 
Side effects
Documentation
```release-note
None
```

fix: Suppress the warning from boost to fix build failure.

---

dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp

Issue Number: close #4749 
In previous gtest, we use MPPTunnel's thread_manager field to create the local reader thread. However since local_reader and mpp tunnel are shared_pointer, and main_thread might finish before local read thread(low possiblity but could happen, this explains the low reproduce possibility of this issue.) Then local read thread will take responsiblity for destructing MPPTunnel object, and will lead to thread joining itself. This must be a problem. 
Although I still can't figure out how the index out of bound error in CI happened, I believe adding thread_manager->wait() in main_thread will fix the unstable issue.
Tests 
Side effects
Documentation
```release-note
None
```

Fix gtest mpp tunnel local write unstable issue

---

dbms/src/Storages/Page/V3/PageDirectory.cpp
dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp

Issue Number: ref #3594 
- When we del the page id
- In getMaxId won't now current page_id have been deleted
Tests 
Side effects
Documentation
```release-note
None
```

Fix getMaxId won't get the right max id before GC

---

dbms/src/Storages/Page/V3/LogFile/LogReader.cpp
dbms/src/Storages/Page/V3/WAL/WALReader.h
dbms/src/Storages/Page/V3/WALStore.cpp
dbms/src/Storages/Page/V3/tests/gtest_wal_store.cpp

Issue Number: close #4841 
- after `fullpath` changed, we need link encryption info.
Tests 
Side effects
Documentation
```release-note
None
```

Fix dump snapshot encryption info not right after rename.

---

dbms/src/Storages/Page/V3/PageDirectory.cpp
dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp

Issue Number: ref #3594 
Problem Summary: If `getMaxId` ignore the deleted entry, we will reuse the PageId after a restart, which break the assumption that we will never reuse a PageID after deleted.
Reverts pingcap/tiflash#4838
Tests 
Side effects
Documentation
```release-note
None
```

Revert "Fix getMaxId won't get the right max id before GC"

---

dbms/src/Storages/Page/V3/PageDirectory.cpp
dbms/src/Storages/Page/V3/WAL/serialize.cpp
dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
dbms/src/Storages/Page/V3/tests/gtest_wal_store.cpp

Issue Number: close #4851 
```
[2022/05/10 15:18:28.483 +08:00] [TRACE] [PageDirectoryFactory.cpp:131] ["PageDirectoryFactory:restoring record [type=1] [page_id=192.352] [ver=<3405,0>] [entry=PageEntry{file: 0, offset: 0x0, size: 0, checksum: 0x0}]"] [thread_id=1]
[2022/05/10 15:18:28.483 +08:00] [TRACE] [PageDirectoryFactory.cpp:131] ["PageDirectoryFactory:restoring record [type=8] [page_id=192.352] [ver=<3407,0>] [entry=PageEntry{file: 0, offset: 0x0, size: 0, checksum: 0x0}]"] [thread_id=1]
[2022/05/10 15:18:28.483 +08:00] [TRACE] [PageDirectoryFactory.cpp:131] ["PageDirectoryFactory:restoring record [type=6] [page_id=192.357] [ver=<3421,0>] [entry=PageEntry{file: 0, offset: 0x0, size: 0, checksum: 0x0}]"] [thread_id=1]
```
- The `page_id=192.352` type is …

Fix bug for deseri type error that cause data error

---

dbms/src/Storages/Transaction/RegionPersister.cpp
dbms/src/Storages/Transaction/RegionPersister.h

Issue Number: ref #3594
- After user running in mix mode and `kvstore` transform is very slow.
- Force transform the `kvstore` from V2 to V3 when it restored.
Tests 
Side effects
Documentation
```release-note
None
```

Add a force transfrom kvstore from v2 to v3

---

dbms/src/Storages/DeltaMerge/StoragePool.cpp
dbms/src/Storages/Transaction/RegionPersister.cpp

Issue Number: close #4893 
- When we changed `MIX_MODE` to `ONLY_V3`, we will change the `run_mode` at last. 
- Then we will used `PageReaderImplMixed`/`PageWriterImplMixed` to read/write page. But in that ps_v2 will be nullptr.
- make writer and reader not used `Mixed`, if we do change `MIX_MODE` to `ONLY_V3`.
Tests 
Side effects
Documentation
```release-note
None
```

Fix nullptr when mix mode change to only v3.

---

dbms/src/DataTypes/IDataType.h
dbms/src/Storages/DeltaMerge/File/DMFileWriter.cpp
dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.cpp
dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp

Reverts pingcap/tiflash#4792 to avoid the risk of TiFlash 6.1 LTS version.
Issue Number: ref #4787
Reverts pingcap/tiflash#4792 to avoid the risk of TiFlash 6.1 LTS version.
Tests 
Side effects
Documentation
```release-note
None
```

Revert "MinMax Index Supports Nullable DataType"

---

dbms/src/Common/ErrorCodes.cpp
dbms/src/Interpreters/Context.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/StoragePool.cpp
dbms/src/Storages/DeltaMerge/StoragePool.h
dbms/src/Storages/Page/PageStorage.h
dbms/src/Storages/Page/V2/PageStorage.cpp
dbms/src/Storages/Page/V2/PageStorage.h
dbms/src/Storages/Page/V2/tests/gtest_page_storage.cpp
dbms/src/Storages/Page/V3/BlobStore.h
dbms/src/Storages/Page/V3/PageDirectory.cpp
dbms/src/Storages/Page/V3/PageDirectory.h
dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
dbms/src/Storages/Page/V3/PageDirectoryFactory.h
dbms/src/Storages/Page/V3/PageEntriesEdit.h
dbms/src/Storages/Page/V3/PageStorageImpl.cpp
dbms/src/Storages/Page/V3/PageStorageImpl.h
dbms/src/Storages/Page/V3/WAL/serialize.cpp
dbms/src/Storages/Page/V3/WALStore.cpp
dbms/src/Storages/Page/V3/WALStore.h
dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
dbms/src/Storages/Page/V3/tests/gtest_page_storage_mix_mode.cpp
dbms/src/Storages/Page/V3/tests/gtest_wal_store.cpp
dbms/src/Storages/Page/V3/tests/page_storage_ctl.cpp
dbms/src/TestUtils/TiFlashTestEnv.cpp
tests/delta-merge-test/ddl/alter.test
tests/delta-merge-test/raft/schema/partition_table_restart.test
tests/delta-merge-test/raft/txn_mock/partition_table.test

Issue Number: ref https://github.com/pingcap/tiflash/issues/3594
https://github.com/pingcap/tiflash/issues/4872
https://github.com/pingcap/tiflash/issues/4849
We fix those two bugs with previous PRs, but those changes introduce new misbehavior for TiFlash. Find a better way to fix those bugs.
Fix reusing same page_id for different kind by:
* Throw exception with error code == PS_DIR_APPLY_INVALID_STATUS when `VersionedPageEntries:: createNewEntry/createNewExternal/createNewRef/createNewExternal/createNewRef` run into invali state
* When restoring edit run into exception with error code == PS_DIR_APPLY_INVALID_STATUS, then call GC on mvcc_directory  entries and run apply edit again
Other changes:
* When restoring the storage pool for DeltaTree, get the max id for this …

Fix the bug for restoring data with duplicated page id

---

README.md

Issue Number: ref https://github.com/pingcap/tiflash/issues/4019
Polish the README to fetch submodule concurrently.
Tests 
Side effects
Documentation
```release-note
None
```

docs: git clone concurrently

---

dbms/src/Flash/Management/tests/gtest_manual_compact.cpp

Issue Number: close #4949
- rm `std::ref`
Tests 
Side effects
Documentation
```release-note
None
```

Fix StorageDeltaMerge constructor not match in gtest_manual_compact

---

README.md

Issue Number: close #4953 
Tests 
Side effects
Documentation
```release-note
None
```

Add note about how to handle build oom or hang

---

dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/Segment.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp

Issue Number: close #4956 
When do segment split, we try to copy the tail column files in the delta layer of the original segment to the new result
segments. So the new segments may contain data that doesn't belong to its segment range.
And this is ok for most cases, because the redundant data will be filtered out by the segment range when serve the read requests to the segment. So the redundant is invisible in almost all cases.
But when do segment merge later, if the previous redundant data is still not flushed to disk, it will be directly copied to the new merged segment again.
So the redundant data in each segment become visible again after segment merge which may cause potential data incorrectness.
Flush cache before every merge operation. So the potential unsaved …

flush cache before segment merge

---

dbms/src/Storages/DeltaMerge/File/DMFileWriter.cpp
dbms/src/Storages/DeltaMerge/tests/dm_basic_include.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
tests/docker/run.sh
tests/docker/util.sh

Issue Number: ref #4747
If rows in a stable pack is all mark deleted, then it's minmax index for pk column is both 0.
And when dt_enable_skippable_place is enabled and try to place delta index on this segment, it will filter out all pack which is not in the pk range [start_key, +infinite). So the previous stable pack is ignored.
But for the place delta index algorithm, it's expected that all the rows in the pk range [start_key, +infinite) is placed no matter whether it's deleted. So when we try to read this segment using the placed delta index, it reports error like "DeltaMerge return wrong result"
Ignore delmark when add minmax for pk column.
Tests 
Side effects
Documentation
```release-note
Fix potential query error when select on a table with many delete operations
```

ignore delmark when add minmax for pk column (#4746)

---

dbms/src/Storages/Page/V3/PageDirectory.cpp
dbms/src/Storages/Page/V3/tests/gtest_page_storage_mix_mode.cpp

Issue Number: close #5000
This is caused by concurrent reading and merge delta under mix mode
* Assume that page 1000 stored in V2
* Thread A create snapshot `s0` (contains one V2 and one V3 snapshot) under mix mode for reading, containing page 1000
* Thread B applies merge delta and delete page 1000 to V3 (and also V2, doesn't matter for this case)
* Thread A continues to read page 1000 by snapshot `s0`, when it try to get 1000 from V3, it throws exception because v3 will find a deleted entry and throw an exception.
- Allow not throw, if find a deleted page in V3.
- Then if we do find a deleted page in V3, PageWriter will find the page in V2 with a V2 snapshot.
Tests 
Side effects
Documentation
```release-note
None
```

Fix v3 can not find entry in mix mode.

---

dbms/src/Storages/Page/V3/BlobStore.cpp
dbms/src/Storages/Page/V3/BlobStore.h

Issue Number: close #5016
- After `restore`,  the size of `snapshot` will be 0, Then some of the total size from blobstat will get 0.
- But the blob file size in disk may not be 0.
- Truncate the blob file size.
- Also update valid rate to 0 is total size is 0.
Tests 
Side effects
Documentation
```release-note
None
```

Optimize blobstore gc when current stat total size is 0

---

dbms/src/Interpreters/AsynchronousMetrics.cpp
dbms/src/Interpreters/AsynchronousMetrics.h
dbms/src/Server/Server.cpp
dbms/src/Storages/DeltaMerge/StoragePool.h
dbms/src/Storages/Page/FileUsage.h
dbms/src/Storages/Page/PageStorage.cpp
dbms/src/Storages/Page/PageStorage.h
dbms/src/Storages/Page/Snapshot.h
dbms/src/Storages/Page/V3/BlobStore.cpp
dbms/src/Storages/Page/V3/BlobStore.h
dbms/src/Storages/Page/V3/PageStorageImpl.cpp
dbms/src/Storages/Page/V3/PageStorageImpl.h
dbms/src/Storages/Transaction/KVStore.h
dbms/src/Storages/Transaction/RegionPersister.cpp
dbms/src/Storages/Transaction/RegionPersister.h
metrics/grafana/tiflash_summary.json

Issue Number: close https://github.com/pingcap/tiflash/issues/4922
Problem Summary: Report the file size, valid data size, file num of all PageStorage instances in a TiFlash node
- Report the file size, valid data size, file num of all PageStorage instances in `AsynchronousMetrics::update`
- Show the file size, valid data size and file num in Grafana
- Move "PageStorage Blob Status" into "StoragePool"
Tests 
- Deploy and run sysbench oltp_update_index workload
- http://172.16.5.81:21510/d/5xovuGr7k/verify-tiflash-summary?orgId=1&from=1653629400000&to=1653632700000
- ![image](https://user-images.githubusercontent.com/4865550/170656897-22f530c7-6f34-4c3b-abd5-c4034cd86612.png)
Side effects
Documentation
```release-note
None
```

PageStorage: Report the file usage of BlobStore

---

dbms/src/Common/Decimal.h
dbms/src/Core/Field.h
dbms/src/DataTypes/DataTypeDecimal.h
dbms/src/DataTypes/FieldToDataType.h
dbms/src/DataTypes/tests/gtest_decimal_literal_datatype.cpp

Issue Number: close #5007
As the issue described.
1. DecimalField::getPrec() ensures that the returned precision is not less than decimal's scale
2. `FieldToDataType` will return a more precise type for DecimalField
Tests 
Side effects
Documentation
```release-note
None
```

refine get type from decimal literal

---

dbms/src/Storages/DeltaMerge/tests/gtest_dm_storage_delta_merge.cpp
dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
tests/docker/config/tics_dt.toml
tests/docker/config/tiflash_dt_async_grpc.toml
tests/docker/config/tiflash_dt_disable_local_tunnel.toml

Issue Number: close https://github.com/pingcap/tiflash/issues/4904
`RegionKVStoreTest` will try to decode data for `table id == 1`. But the schema of tests in `RegionKVStoreTest` does not match that we created in `StorageDeltaMergeTest.ReadExtraPhysicalTableID`. 
`./gtests_dbms --gtest_filter='*StorageDeltaMergeTest*:*RegionKVStoreTest*'`
```
Note: Google Test filter = *StorageDeltaMergeTest*:*RegionKVStoreTest*
[==========] Running 6 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 5 tests from StorageDeltaMergeTest
[ RUN      ] StorageDeltaMergeTest.ReadWriteCase1
...
[       OK ] StorageDeltaMergeTest.RestoreAfterClearData (624 ms)
[----------] 5 tests from StorageDeltaMergeTest (835 ms total)
[----------] 1 test from RegionKVStoreTest …
```

Fix broken unit test for `--gtest_filter='*StorageDeltaMergeTest*:*RegionKVStoreTest*'`

---

dbms/src/Common/FailPoint.cpp
dbms/src/Debug/dbgFuncSchema.cpp
dbms/src/Storages/IManageableStorage.h
dbms/src/Storages/StorageDeltaMerge.cpp
dbms/src/Storages/StorageDeltaMerge.h
dbms/src/Storages/Transaction/DecodingStorageSchemaSnapshot.h
dbms/src/Storages/Transaction/PartitionStreams.cpp
dbms/src/Storages/Transaction/SchemaBuilder.cpp
dbms/src/Storages/Transaction/TiDBSchemaSyncer.h
dbms/src/Storages/Transaction/tests/RowCodecTestUtils.h
tests/fullstack-test2/ddl/alter_column_when_pk_is_handle.test

Issue Number: ref #5032
Problem Summary: Currently we cache decoding schema for decoding raft data if a table schema doesn't change. And we judge whether a table schema has changed based on the table schema version.
But the schema version is not strictly consistent with the actual table schema which can be seen at https://github.com/pingcap/tiflash/blob/master/dbms/src/TiDB/Schema/SchemaBuilder.cpp#L362. That is when applying different schema changes in a diff, the table schema version will be set to the latest schema version after the first schema change is applied.
More concretely, when a lossy ddl change occurs, it will trigger `drop column` and `add column` schema changes and also rewrite some data at the same time.  The schema changes will be applied one by one, and because tiflash …

Fix potential data inconsistency under heavy ddl operation

---

dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/Page/PageUtil.h
dbms/src/Storages/Page/V2/tests/gtest_page_util.cpp
dbms/src/Storages/Page/V3/BlobStore.cpp
dbms/src/Storages/Page/V3/BlobStore.h
dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/5093, ref https://github.com/pingcap/tiflash/issues/5076
Problem Summary: The entry.tag is incorrect after full gc, this will lead to more IO caused by `RegionPersister::doPersist`
https://github.com/pingcap/tiflash/blob/5b61ae70550624d3bf0b5ca6bac89013ed5a6a4b/dbms/src/Storages/Transaction/RegionPersister.cpp#L111-L115
* Copy the old entry and upodate the fields of new entry
* Add some error message when exception is thrown while reading (for #5076 )
Tests 
Side effects
Documentation
```release-note
None
```

PageStorage: Fix entry.tag after full gc && add more debug message

---

dbms/src/Flash/Mpp/MPPTask.cpp
dbms/src/Flash/Mpp/MPPTask.h
dbms/src/Flash/Mpp/MPPTunnelSet.cpp
dbms/src/Flash/Mpp/MPPTunnelSet.h

Currently, there 2 tunnel related components in `MPPTask`
- [tunnel_set](https://github.com/pingcap/tiflash/blob/1e3207d3794d8870fc8afad895017191851e4cca/dbms/src/Flash/Mpp/MPPTask.h#L124)
- [tunnel_map](https://github.com/pingcap/tiflash/blob/1e3207d3794d8870fc8afad895017191851e4cca/dbms/src/Flash/Mpp/MPPTask.h#L127)
This pr move `tunnel_map` to MPPTunnelSet, and all the tunnel releated operate are handled in `MPPTunnelSet`
Tests 
Side effects
Documentation
```release-note
None
```

move `tunnel_map` to MPPTunnelSet

---

dbms/src/Debug/dbgFuncMockRaftSnapshot.cpp
dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
dbms/src/Storages/Transaction/DecodingStorageSchemaSnapshot.h
dbms/src/Storages/Transaction/PartitionStreams.cpp
dbms/src/Storages/Transaction/RegionBlockReader.cpp
dbms/src/Storages/Transaction/RegionBlockReader.h
dbms/src/Storages/Transaction/RowCodec.cpp
dbms/src/Storages/Transaction/TiKVRecordFormat.h
dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
dbms/src/Storages/Transaction/tests/region_helper.h
tests/fullstack-test/mpp/mpp_fail.test

Signed-off-by: JaySon-Huang <jayson.hjs@gmail.com>
Issue Number: ref https://github.com/pingcap/tiflash/issues/4862
* Add some comments about decoding row data
Tests 
Side effects
Documentation
```release-note
None
```

*: Add some comments about decoding

---

dbms/src/Storages/Page/workload/CMakeLists.txt
dbms/src/Storages/Page/workload/HeavyMemoryCostInGC.h
dbms/src/Storages/Page/workload/HeavyRead.h
dbms/src/Storages/Page/workload/HeavySkewWriteRead.h
dbms/src/Storages/Page/workload/HeavyWrite.h
dbms/src/Storages/Page/workload/HighValidBigFileGC.h
dbms/src/Storages/Page/workload/HoldSnapshotsLongTime.h
dbms/src/Storages/Page/workload/MainEntry.cpp
dbms/src/Storages/Page/workload/Normal.h
dbms/src/Storages/Page/workload/PSWorkload.h
dbms/src/Storages/Page/workload/PageStorageInMemoryCapacity.h
dbms/src/Storages/Page/workload/ThousandsOfOffset.h

Issue Number: close #5164
Register workload in `mainEntry` explicitly.
Tests 
./tiflash pageworkload --help
Side effects
Documentation
```release-note
None
```

fix pageworklaod

---

README.md

Issue Number: close #5172 #5178 
Add how to run integration tests and microbenchmark tests in README
Tests 
Side effects
Documentation
```release-note
None
```

Enhancement: Add how to run integration tests and microbenchmark tests in README

---

dbms/src/Storages/DeltaMerge/DeltaTree.h
dbms/src/Storages/DeltaMerge/DeltaTree.ipp

Issue Number: close #5200
Tests 
Side effects
Documentation
```release-note
None
```

feat: delta tree dispatching

---

dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
dbms/src/DataStreams/UnionBlockInputStream.h
dbms/src/Flash/Mpp/ExchangeReceiver.cpp
dbms/src/Flash/Mpp/MPPHandler.cpp
dbms/src/Flash/Mpp/MPPTask.cpp
dbms/src/Flash/Mpp/MPPTask.h
dbms/src/Flash/Mpp/MPPTaskManager.cpp
dbms/src/Flash/Mpp/MPPTaskManager.h
dbms/src/Flash/Mpp/TaskStatus.cpp
dbms/src/Flash/Mpp/TaskStatus.h
tests/fullstack-test/mpp/issue_2471.test
tests/fullstack-test/mpp/mpp_fail.test
tests/run-test.py

1. Add `MPPTask::abort()` function to abort task in case of being cancelled or encounter an error.
2. Both `MPPTask::cancel()` and `MPPTask::handleError()` will call `MPPTask::abort()` using different abort type.
3. In case of error handling, cancel the `DataStreams` silently to avoid useless error message.
Tests 
Side effects
Documentation
```release-note
None
```

add `MPPTask::handleError()`

---

dbms/src/Server/Server.cpp

Issue Number: close #5255
Currently, TiFlash does not check the result of `ServerBuilder::BuildAndStart` and it will cause Segment Fault if `flash.service_addr` is invalid.
Tests 
Side effects
Documentation
```release-note
Fix the panic issue that occurs when `flash.service_addr` is invalid
```

Check result of starting grpc server

---

contrib/prometheus-cpp-cmake/core/CMakeLists.txt
contrib/prometheus-cpp-cmake/pull/CMakeLists.txt
contrib/prometheus-cpp-cmake/push/CMakeLists.txt

Signed-off-by: YangKeao <yangkeao@chunibyo.icu>
Issue Number: close #5278 #2103
The prometheus-cpp in tiflash is out of date, and will cause compile-error in new version of libstdc++
Upgrade the prometheus-cpp to v1.0.1. Modify the cmake files according to the repo.
Tests 
```release-note
none
```

upgrade prometheus-cpp to v1.0.1

---

dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp

Issue Number: close #5179
This PR flushes the cache when doing the manual compaction.
Tests 
Side effects
Documentation
```release-note
None
```

Flush segment cache when doing the compaction

---

dbms/src/DataStreams/TiRemoteBlockInputStream.h
dbms/src/Debug/astToExecutor.cpp
dbms/src/Flash/Coprocessor/DAGContext.cpp
dbms/src/Flash/Coprocessor/DAGContext.h
dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.h
dbms/src/Flash/Coprocessor/GenSchemaAndColumn.cpp
dbms/src/Flash/Coprocessor/GenSchemaAndColumn.h
dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
dbms/src/Flash/Coprocessor/InterpreterUtils.h
dbms/src/Flash/tests/gtest_interpreter.cpp
dbms/src/Interpreters/Settings.h
dbms/src/TestUtils/mockExecutor.h

Issue Number: close #4739 
port from https://github.com/pingcap/tiflash/pull/5143
Tests 
Side effects
Documentation
```release-note
None
```

*: mini refactor

---

dbms/src/Common/MPMCQueue.h

Signed-off-by: guo-shaoge <shaoge1994@163.com>
Issue Number: close #5329
Problem Summary: MPMCQueue maybe used by different threads, copy and move it is dangerous.
Tests 
Side effects
Documentation
```release-note
None
```

delete copy/move ctor of MPMCQueue explicitly

---

dbms/src/Columns/ColumnConst.h
dbms/src/Functions/CollationOperatorOptimized.h
dbms/src/Functions/FunctionsComparison.h
dbms/src/Storages/Transaction/Collator.cpp
tests/tidb-ci/new_collation_fullstack/expr.test

Issue Number: ref #5294 
cherry-pick #5299
```release-note
None
```

Optimize comparision for collation `UTF8_BIN` and `UTF8MB4_BIN` (#5299)

---

dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/GCManager.cpp

Issue Number: close #5073 
Problem Summary: when the table num in the cluster is big, the gc process print too many logs which is of little use.
Lower the log level of some logs and print some log when gc really happens.
Tests 
Side effects
Documentation
```release-note
None
```

decrease the frequency of background gc log

---

dbms/src/Flash/Mpp/MPPTunnel.cpp
dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp

Issue Number: close #5378 
When MPPTunnel finished before connected, the tunnelSender won't be initialized. And in such situation, write/writeDone will to this tunnel will raise exception. However, the exception try to access tunnelSender which will lead to segment fault.
So the fix is direct, check if tunnelSender is nullptr to protect.
Tests 
Side effects
Documentation
```release-note
None
```

Fix write after unconnect finish bug

---

dbms/src/Storages/DeltaMerge/workload/DTWorkload.cpp
dbms/src/Storages/DeltaMerge/workload/MainEntry.cpp
dbms/src/TestUtils/TiFlashTestEnv.cpp
dbms/src/TestUtils/TiFlashTestEnv.h

Issue Number: ref #5348 
- PageStorage V3 will be initialized before DeltaMerge created.
- PageStorage V3 will use default configuration to initialize background thread pools that results in background thread count is different with PageStorage V2 enabled.
Initialize background thread pools in the beginning.
Tests 
Side effects
Documentation
```release-note
None
```

Fix background thread count in dtworkload.

---

dbms/src/Storages/Page/V2/PageStorage.cpp
dbms/src/Storages/Page/V2/PageStorage.h
dbms/src/Storages/Page/V2/tests/gtest_page_storage.cpp
dbms/src/Storages/Transaction/RegionPersister.cpp

Issue Number: close #5385 
Problem Summary: When restart, ps v2 will try to reuse old page file for writing. But if no file can be used for writing, it will create new page file. But the file id of the new page file is determined by the max file id in writing page file set which is empty now. And it will create `PageFile_1_0` in this case for writing which may override previous data.
Make sure new page file id is larger than all current page files at restart.
Tests 
Side effects
Documentation
```release-note
None
```

fix pagestorage v2 restore

---

dbms/src/Storages/DeltaMerge/StoragePool.cpp
dbms/src/Storages/DeltaMerge/StoragePool.h
dbms/src/Storages/Page/PageStorage.cpp
dbms/src/Storages/Page/PageStorage.h
dbms/src/Storages/Page/V2/PageStorage.cpp
dbms/src/Storages/Page/V2/PageStorage.h
dbms/src/Storages/PathPool.cpp
dbms/src/Storages/PathPool.h
dbms/src/Storages/Transaction/RegionPersister.cpp

Issue Number: close #5336 
Problem Summary: After transform from all data from ps v2 to ps v3, there are still some v2 data left which may consume unnecessary disk space.
When the valid pages in ps v2 is 0, we write a mark file to indicate that ps v2 is deleted. And try to drop v2 data.
And at later restart, if we find that there is are ps v2 delete mark file, we will not restore ps v2 and may try to clear obsolete v2 data if previous drop process was interrupted.
Tests 
1. load data in ps v2 format;
2. edit config to use ps v3 format;
3. run sql `alter table ... compact tiflash replica;` to transform all data from ps v2 to ps v3;
4. restart again to check whether the ps v2 data in the table data path is deleted.
Before restart:
After restart and run compact:
Side effects
Documentation …

clear obsolete v2 data for tables that totally transform to ps v3

---

dbms/src/DataStreams/CreatingSetsBlockInputStream.cpp
dbms/src/Interpreters/Join.cpp
dbms/src/Interpreters/Join.h

Issue Number: close #5403
1. `Join` will save the total build input rows
2. For join, `CreatingSetsBlockInputStream` get the `head_rows` from `subquery.join` directly.
Tests 
Side effects
Documentation
```release-note
None
```

refine log in creating set for join build

---

dbms/src/Flash/EstablishCall.cpp
dbms/src/Flash/EstablishCall.h
dbms/src/Flash/Mpp/MPPTunnel.cpp

Issue Number: close #5405 
In MPPTunnel refact PR, consumerFinished won't set tunnel's state to finished. So for async tunnel mode, when AsyncSender call consumerFinish and then call writer's writeDone method, writer will be deleted anytime. However, tunnel might not notice this, and call AsyncSender's tryFlushOne still, then segment fault happened.
So fix the issue by check if AsyncSender has already consumerFinished before do actually work for TryFlushOne/SendOne.
Tests 
Side effects
Documentation
```release-note
None
```

Fix async sender nullptr bug

---

dbms/src/Flash/Coprocessor/DAGContext.h

Signed-off-by: fuzhe1989 <fuzhe1989@gmail.com>
Issue Number: ref #5416
Tests 
Side effects
Documentation
```release-note
None
```

DAGContext: remove useless explicitly call to tunnel_set's default ctor

---

tests/fullstack-test/expr/extract_datetime.test

Issue Number: close #5421
After TiDB PR https://github.com/pingcap/tidb/pull/36297, `extract(day_microsecond/second/minute/hour)` behavior changed to evaluate the second argument to time, thus the day portion wouldn't be showing up in the result.
Update test reference.
Tests 
Side effects
Documentation
```release-note
None
```

Fix extract fullstack test

---

contrib/CMakeLists.txt

Issue Number: ref https://github.com/pingcap/tiflash/issues/5368
`cpu_features` is not added as a subdirectory under intel mac
Due to cmake condition
```
>  cat CMakeLists.txt
project(test)
set(ARCH_AARCH64 0)
set(ARCH_AMD64 1)
set(APPLE 1)
if ((NOT APPLE))
message(STATUS "    not apple -- APPLE:${APPLE} ARCH_AARCH64:${ARCH_AARCH64}")
else()
message(STATUS "        apple -- APPLE:${APPLE} ARCH_AARCH64:${ARCH_AARCH64}")
endif()
if ((NOT ARCH_AARCH64))
message(STATUS "    not arm64 -- APPLE:${APPLE} ARCH_AARCH64:${ARCH_AARCH64}")
else()
message(STATUS "        arm64 -- APPLE:${APPLE} ARCH_AARCH64:${ARCH_AARCH64}")
endif()
if (APPLE AND ARCH_AARCH64)
message(STATUS "     apple and arm64  -- APPLE:${APPLE} ARCH_AARCH64:${ARCH_AARCH64}")
else()
message(STATUS "not (apple and …
```

build: Fix build under intel mac machine

---

dbms/src/Storages/DeltaMerge/ReadThread/SegmentReader.cpp

Issue Number: close #5457
Tests 
Side effects
Documentation
```release-note
None
```

fix sched_setaffinity failed.

---

dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
dbms/src/Flash/Coprocessor/InterpreterDAG.cpp
dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
dbms/src/Flash/Coprocessor/InterpreterUtils.h

Issue Number: ref #4739
move some codes from InterpreterDAG to InterpreterUtils
Tests 
Side effects
Documentation
```release-note
None
```

refine `InterpreterDAG`

---

dbms/src/Common/TiFlashMetrics.h

Issue Number: close #5473
Tests 
Side effects
Documentation
```release-note
None
```

Fix typo of Metrics

---

dbms/src/Storages/Transaction/KVStore.cpp
dbms/src/Storages/Transaction/KVStore.h
dbms/src/Storages/Transaction/ProxyFFI.cpp
dbms/src/Storages/Transaction/ProxyFFI.h
dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp

Issue Number: close #5458
We need to update apply index in pre_exec when handing CompactLog
Tests 
Side effects
Documentation
```release-note
None
```

Fix RegionEpoch Error and CheckWaitIndex takes too long

---

dbms/src/Storages/Page/V3/BlobStore.cpp
dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp

Issue Number: close #5532
Problem Summary: There is a potential dead lock when remove blob file.
Tests 
Side effects
Documentation
```release-note
None
```

fix potential dead lock when remove blob file

---

dbms/src/Flash/Mpp/MPPTask.cpp
dbms/src/Flash/Mpp/MPPTask.h
dbms/src/Flash/Mpp/MinTSOScheduler.cpp

Issue Number: close #5556
Fix some bugs that active tasks count/ estimated thread usage may be repeat added, and `type_waiting_tasks_count` may lost update when schedule meet error.
Tests 
Side effects
Documentation
```release-note
None
```

fix bug in `MinTSOScheduler` that `estimated_thread_usage`/`waiting_tasks_count`/`active_tasks_count` are not 0 even if there is no queries running

---

dbms/src/Storages/Page/V3/BlobStore.cpp
dbms/src/Storages/Page/V3/BlobStore.h

Issue Number: close #5552 
Problem Summary: When interacting with `BlobStat/BlobStats`, there are two locks. One is on `BlobStat` and the other is on `BlobStats`. We must always get lock on BlobStats before lock on BlobStat.
But after we lock `BlobStats` in `getBlobFileParentPath`, we may lock on `BlobStat` before lock on `BlobStats` which may cause deadlock.
Avoid lock in `getBlobFileParentPath`.
Tests 
Side effects
Documentation
```release-note
None
```

fix dead lock when do truncate gc on blob file

---

dbms/src/Functions/FunctionsString.cpp

Issue Number: close #5592 
Incorrectly using `arg0` as argument offsets instead of `arguments[arg0]`. 
use `arguments[arg0]` as argument column offset
Tests 
Side effects
Documentation
```release-note
None
```

fix: use arguments[arg0] as argument column offset

---

dbms/src/Flash/Planner/PhysicalPlanVisitor.h

Issue Number: close https://github.com/pingcap/tiflash/issues/5590
Compile error under MacOS after https://github.com/pingcap/tiflash/pull/5321 merged, see the issue for details.
Seems that the clang under MacOS brings `std::visit` by accident.
explicitly call full name with namespace `DB::PhysicalPlanVisitor::visit` instead of `visit`
Tests 
Side effects
Documentation
```release-note
None
```

Fix compile error under MacOS

---

dbms/src/TestUtils/FunctionTestUtils.cpp
dbms/src/TestUtils/FunctionTestUtils.h

Issue Number: close #5596 
Shuffle input columns before execution in function unit tests.
Tests 
Side effects
Documentation
```release-note
None
```

refine: shuffle column order before execute function ut

---

dbms/src/Common/ThreadMetricUtil.cpp

Issue Number: close #5595
Tests 
Side effects
Documentation
```release-note
None
```

fix: time unit not match in ThreadMetricUtil.cpp

---

dbms/src/Storages/Transaction/KVStore.cpp
dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp

This is a cherry-pick of https://github.com/pingcap/tiflash/pull/5603
Issue Number: close #5602
This problem can be caused by:
1. Region is removed on TiFlash's side, however not on Proxy's side before a restart
1. Proxy replay log, and ask a flush for a region not exist in TiFlash
1. Thus TiFlash keeps panicking
> 1. TiFlash implementation`AdminCmd::ChangePeer::RemoveNode`, the persistence is successful after deleting the region.
> 2. However, when the proxy persisted meta information to kvdb, the node encountered unexpected downtime.
Tests 
Side effects
Documentation
```release-note
None
```

Fix panic when region is not found on TiFlash's side in tryFlushData to release-6.2

---

dbms/src/DataStreams/CreatingSetsBlockInputStream.cpp
dbms/src/Flash/Mpp/MPPTaskManager.cpp

Issue Number: ref #5095, close #5638
After #5361, in `MPPTaskManager::cancelMPPQuery`, we try to move mpp task to the cancel thread so each mpp task can be destructed parallelly instead of be destructed one by one in `cancelMPPQuery` thread.
However, due to SOO in llvm(https://github.com/llvm/llvm-project/issues/32472), this move actaully failed, and there is a chance that mpp task is destructed inside the follow cancel loop:
https://github.com/pingcap/tiflash/blob/8404e6565e3ff2e47e50497550d838ea76e6e776/dbms/src/Flash/Mpp/MPPTaskManager.cpp#L102-L108
Destruct MPP inside the cancel loop means the task will be destructed before all mpp tasks are cancelled, this may cause some dead lock issues since there are some dependency between mpp tasks(especially in the case of …

Fix bug that mpp_task is not move to cancel thread due to llvm SOO

---

dbms/src/Flash/FlashService.cpp
dbms/src/Flash/Mpp/GRPCReceiverContext.cpp
dbms/src/Flash/Mpp/MPPTask.cpp
dbms/src/Flash/Mpp/MPPTaskManager.cpp
dbms/src/Flash/Mpp/MPPTaskManager.h

1. remove `MPPTaskManager::findTaskWithTimeout`
2. add `MPPTaskManager::findTunnleWithTImeout`
3. remove some unused code
Tests 
Side effects
Documentation
```release-note
None
```

Remove `MPPTaskManager::findTaskWithTimeout`

---

dbms/src/Flash/Coprocessor/DAGContext.cpp
dbms/src/Flash/Coprocessor/DAGContext.h
dbms/src/Flash/EstablishCall.cpp
dbms/src/Flash/Mpp/MPPTask.cpp
dbms/src/Flash/Mpp/MPPTask.h
dbms/src/Flash/Mpp/MPPTunnel.cpp

Issue Number: ref #5095, close #5651
- Data race in tunnel_set/receiver_set:
In #5132, it try to use the atomic variable `status` to protect tunnel_set/receiver_set in multiple thread read/write(MPPTask::runImpl thread to write and MPPTask::abort thread to read):
https://github.com/pingcap/tiflash/blob/b6536f6af56cc061eec1d65ff82ff79a1c6f81f0/dbms/src/Flash/Mpp/MPPTask.cpp#L145-L147
Unfortunately, it turns out not working becase the value of `status` can be changed after L145 and before L147
- Data race in establish call data:
https://github.com/pingcap/tiflash/blob/b6536f6af56cc061eec1d65ff82ff79a1c6f81f0/dbms/src/Flash/EstablishCall.cpp#L106-L113
After `write(packet)` in L109, the call data is put back to completion queue, and it can be deleted anytime, so there is a …

Fix data race in tunnel_set/receiver_set and establish call data

---

dbms/src/Flash/FlashService.cpp
dbms/src/Flash/Mpp/ExchangeReceiver.cpp
dbms/src/Flash/Mpp/MPPTunnel.cpp

Issue Number: ref #5142
Tests 
Side effects
Documentation
```release-note
None
```

Avoid too many log in `ExchangeReceiver`/`MPPTunnel`

---

dbms/src/Storages/Page/V3/BlobStore.cpp
dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp

Issue Number: ref #5558 
Problem Summary: The alloc size for BlobFile when do heavy gc may be wrong which is introduced by https://github.com/pingcap/tiflash/pull/5544
Tests 
Side effects
Documentation
```release-note
None
```

fix wrong alloc size when do heavy gc for blob file

---

dbms/src/Storages/DeltaMerge/File/DMFileWriter.cpp
dbms/src/Storages/DeltaMerge/tests/dm_basic_include.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp

cherry pick of https://github.com/pingcap/tiflash/pull/4757
Tests 
Side effects
Documentation
```release-note
None
```

ignore delmark when add minmax for pk column (#4746) (#4757)

---

dbms/src/Common/Exception.h
dbms/src/DataStreams/WindowBlockInputStream.cpp

Issue Number: close #5774
There is [a common mistake](https://github.com/pingcap/tiflash/pull/5762#discussion_r961355060) that we may specify a string literal to `RUNTIME_CHECK` hoping it will format things. Actually it will not work.
For example,
```c++
RUNTIME_CHECK(false, "some description");
```
will just become:
```
Check false failed, "some description" = some description
```
I don't have ideas how we can reliably handle this case and make it just work™. So this PR simply throw compile errors when it **seems** to be this case. 
If we have good ways to print it out nicely later then we can relax the check at that time.
Tests 
```
/Users/breezewish/Work/tiflash-workspace2/dbms/src/Common/tests/gtest_exception.cpp:26:5: …
```

misc: protect from calling RUNTIME_CHECK with string literals

---

dbms/src/Common/MemoryTracker.cpp

Issue Number: close #5776
Bugfix: memtracker accuracy test
When memory usage drops, it can be very inaccurate because the process itself caches memory. For example, if memory usage suddenly drops from 30G to 1G, then the ```amount``` will be 1G, but the ```real _rss``` will still be 30G.
Tests 
Side effects
Documentation
```release-note
None
```

Bugfix of memtracker accuracy test

---

dbms/src/Debug/dbgFuncMisc.cpp
dbms/src/Storages/StorageDeltaMerge.cpp
tests/delta-merge-test/query/misc/timestamp_rough_set_filter.test

Issue Number: ref https://github.com/pingcap/tiflash/issues/5718
After https://github.com/pingcap/tiflash/pull/5715, the logging become too verbose for mpp task, the tso appear many times
```
[2022/09/06 17:05:28.830 +08:00] [DEBUG] [Segment.cpp:1470] ["Segment:<segment_id=146 epoch=17> MPP<query:435802637197639681,task:1> Table<129> read_tso=435802637197639681 Begin segment getReadInfo"] [thread_id=89]
[2022/09/06 17:05:28.831 +08:00] [DEBUG] [Segment.cpp:1470] ["Segment:<segment_id=1 epoch=32> MPP<query:435802637197639681,task:1> Table<129> read_tso=435802637197639681 Begin segment getReadInfo"] [thread_id=90]
[2022/09/06 17:05:28.831 +08:00] [DEBUG] [Segment.cpp:1470] ["Segment:<segment_id=146 epoch=17> MPP<query:435802637197639681,task:1> Table<129> …
```

*: Fix verbose logging in the DeltaTree engine

---

dbms/src/DataStreams/WindowBlockInputStream.cpp
dbms/src/DataStreams/WindowBlockInputStream.h

Issue Number: close #5814
Tests 
Side effects
Documentation
```release-note
Fix the bug that window function may cause tiflash crash when canceled.
```

Fix incorrect window function cancellation handling

---

dbms/src/Flash/Mpp/ExchangeReceiver.cpp
dbms/src/Flash/Mpp/ExchangeReceiver.h
dbms/src/Flash/Mpp/GRPCReceiverContext.cpp
dbms/src/Flash/Mpp/GRPCReceiverContext.h

When in local tunnel mode, if `ExchangeReceiver` meet some error, local tunnel will call `consumerFinish` with error message, but currently, the error message is just `Receiver Finish/Receiver closed`, it does not contain any useful information.
This pr add a new interface `cancel` to `ExchangePacketReader`, and if exchange receiver meet error, it will call `cancel` to pass the error message to local tunnel explicitly.
Tests 
Side effects
Documentation
```release-note
None
```

Refine error propagation in local tunnel

---

dbms/src/Common/MemoryTracker.cpp
dbms/src/Common/MemoryTracker.h
dbms/src/Flash/Mpp/MPPTunnel.cpp

Issue Number: close #5853
Tests 
Side effects
Documentation
```release-note
None
```

eliminate tsan warnings of accuracy_diff_for_test

---

dbms/src/Flash/Mpp/MPPTaskManager.cpp
dbms/src/Flash/Mpp/MPPTaskManager.h
dbms/src/Flash/Mpp/MinTSOScheduler.cpp
dbms/src/Flash/Mpp/MinTSOScheduler.h

Issue Number: ref #5864
1. Replace `Poco::Logger` by `DB::Logger` in `MPPTaskManager` and `MinTSOScheduler`
2. Use `RUNTIME_ASSERT` to simplify code in https://github.com/pingcap/tiflash/blob/a6bc771f2b3cb1d08c628b649ff9ca796e026932/dbms/src/Flash/Mpp/MinTSOScheduler.cpp#L131-L135
Tests 
Side effects
Documentation
```release-note
None
```

Replace Poco::Logger by DB::Logger in MPPTaskManager and MinTSOScheduler

---

dbms/src/Interpreters/Context.cpp
dbms/src/Storages/BackgroundProcessingPool.cpp
dbms/src/Storages/BackgroundProcessingPool.h
metrics/grafana/tiflash_summary.json

Issue Number: ref #5807
In https://github.com/pingcap/tiflash/pull/5808 we added metric graph for background tasks. However, due to bg pool and blockable bg pool are sharing the same name, the red-limit-line would be misleading. For example, user cannot learn the case when one of the bg pool is full and another one is idle.
This PR use different names for the two bg pool, so that we can learn whether it hits the maximum thread limit:
Tests 
Side effects
Documentation
```release-note
None
```

storage: Use different names for block bg pool

---

dbms/src/Storages/Transaction/ProxyFFI.cpp
dbms/src/Storages/Transaction/ProxyFFI.h
dbms/src/Storages/Transaction/ProxyFFIStatusService.cpp
dbms/src/Storages/Transaction/RegionTable.cpp
dbms/src/Storages/Transaction/RegionTable.h

Issue Number: ref #4902
Store leader and self safe_ts in `RegionTable`, use the safe_ts diff to determine whether the peer's data synchronization progress is far behind the leader.
Tests 
BR restore tables with TiFlash replica, check the log and `progress` in `information_schema.tiflash_replica`.
Side effects
Documentation
```release-note
None
```

Use safe_ts to determine whether the peer's data synchronization progress is far behind the leader.

---

dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/Segment.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp

Issue Number: ref #5237
Add (unused) lock in the function signature to avoid forgetting.
Tests 
Side effects
Documentation
```release-note
None
```

storage: require lock for segment operations

---

dbms/src/Storages/Transaction/ApplySnapshot.cpp

Issue Number: ref #5237
Consider that we received a 2GB-sized snapshot (which may happen when dynamic region is enabled).
- Improved: In ApplySnapshot, we use ingestBySplit. In this case, 2GB sized snapshot becomes a 2GB sized segment immediately, which causes segment split again. If we pre-split the DTFile, then the segment will be stable and don't need further operations.
- No change: In IngestSST, we use ingestByColumnFile. In this case, 2GB sized snapshots are all written to the segment delta layer. Even if we split into multiple DTFiles, they are still all written to the segment delta layer (for now). So there will be no changes.
Tests 
Side effects
Documentation
```release-note
None
```

storage: Always split the pre-ingested DTFile

---

dbms/src/Common/TiFlashMetrics.h
dbms/src/Flash/Mpp/MPPTaskManager.cpp
metrics/grafana/tiflash_summary.json

Add mpp query count metrics
Tests 
Side effects
Documentation
```release-note
None
```

add mpp query count metrics

---

README.md

Signed-off-by: Jigao Luo <luojigao@outlook.com>
Issue Number: close #5968
I have a pure Arch environment and start to install the dependencies in README.
But the build is failed as in #5968. 
The reason is easily in LLVM linker `lld` , which in not installed and **not mentioned in the Arch dependencies in README**.
`lld` is included in the MacOS brew and is mentioned in the Debian Ubuntu dependencies in README.
I guess we just forget to mention `lld` in our Arch part.
Tests 
Side effects
Documentation
```release-note
None
```

Add lld to Arch dependencies of README.

---

dbms/src/Common/MemoryTracker.h
dbms/src/Flash/Coprocessor/DAGContext.cpp
dbms/src/Flash/Coprocessor/DAGContext.h
dbms/src/Flash/Coprocessor/DAGQuerySource.cpp
dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
dbms/src/Flash/EstablishCall.cpp
dbms/src/Flash/Mpp/ExchangeReceiver.cpp
dbms/src/Flash/Mpp/ExchangeReceiver.h
dbms/src/Flash/Mpp/MPPHandler.cpp
dbms/src/Flash/Mpp/MPPReceiverSet.cpp
dbms/src/Flash/Mpp/MPPReceiverSet.h
dbms/src/Flash/Mpp/MPPTask.cpp
dbms/src/Flash/Mpp/MPPTask.h
dbms/src/Flash/Mpp/MPPTunnel.cpp
dbms/src/Flash/Mpp/MPPTunnel.h
dbms/src/Flash/Mpp/MPPTunnelSet.cpp
dbms/src/Flash/Mpp/MPPTunnelSet.h
dbms/src/Flash/Mpp/TrackedMppDataPacket.h
dbms/src/Flash/Planner/PlanQuerySource.cpp
dbms/src/Interpreters/Context.cpp
dbms/src/Interpreters/Context.h
dbms/src/Interpreters/ProcessList.h
dbms/src/Interpreters/executeQuery.cpp

Issue Number: ref #5609
This is a refine pr for #5610
1. create `processlist/memory_tracker` in `MPPTask::prepare`, so when creating `MPPTunnel/ExchangeReceiver`, there is already a memory_tracker to use.
3. save memory tracker in `TunnelSender`, so each `TrackedMPPPacket` does not need to hold the shared ptr of memory tracker
4. remove some workaround code
Tests 
- run random failpoint tests for more than 12 hours
- run mpp fail tests for more than 12 hours
Side effects
Documentation
```release-note
None
```

Refine the lifecycle of memory_tracker for MPP query

---

contrib/grpc-cmake/CMakeLists.txt
dbms/src/Storages/Page/V3/PageEntriesEdit.h
dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
dbms/src/Storages/Page/V3/tests/gtest_wal_store.cpp

Issue Number: ref https://github.com/pingcap/tiflash/issues/4562
Problem Summary: Remove embed test funcs from PageEntriesEdit
Replace those tests functions by regex matching
Tests 
Side effects
Documentation
```release-note
None
```

tests: Remove embed test funcs from PageEntriesEdit

---

dbms/src/Storages/Page/ExternalPageCallbacks.h
dbms/src/Storages/Page/PageStorage.h
dbms/src/Storages/Page/V3/PageDirectory.cpp
dbms/src/Storages/Page/V3/PageDirectory.h
dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
dbms/src/Storages/Page/V3/WAL/WALReader.cpp
dbms/src/Storages/Page/V3/WAL/WALReader.h
dbms/src/Storages/Page/V3/tests/gtest_wal_store.cpp

Issue Number: ref https://github.com/pingcap/tiflash/issues/6071
We plan to support both string and u128 type for page id, making serialize/deserialize out of WALReader is more convenient
* Move deserialize out of WALReader
* Move ExternalPageCallbacks `Storages/Page/ExternalPageCallbacks.h` as it will be shared by universal pagestorage class
* Move enum class ResolveResult out of class VersionedPageEntries
Tests 
Side effects
Documentation
```release-note
None
```

PageStorage: Make deserialize out of WALReader

---

dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp

Issue Number: close #6072
TestMPPTunnel_WriteAfterFinished is unstable.
The root cause is 
https://github.com/pingcap/tiflash/blob/72a21d102f4ab54800562fb07edcc7d5d5b4a05e/dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp#L425-L444
In L433, the tunnel is closed but the sender thread is not. In L436 tunnel write throw exception, then `writer_ptr` is destructed before `mpp_tunnel_ptr` is destructed, so the sender thread use a invalid pointer.
Tests 
Side effects
Documentation
```release-note
None
```

fix unstable tests

---

CMakeLists.txt

Issue Number: close #6093 
```shell
$ cmake .. -GNinja -DCMAKE_BUILD_TYPE=DEBUG
CMake Warning (dev) at CMakeLists.txt:15 (project):
Policy CMP0048 is not set: project() command manages VERSION variables.
Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
The following variable(s) would be set to empty:
CMAKE_PROJECT_VERSION
CMAKE_PROJECT_VERSION_MAJOR
CMAKE_PROJECT_VERSION_MINOR
CMAKE_PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.
-- Using CXX=/data1/qiuyang/projects/tiflash-env/sysroot/bin/clang++, ver=13.0.0;CC=/data1/qiuyang/projects/tiflash-env/sysroot/bin/clang, ver=13.0.0
-- Using ccache: …
```

suppress cmake warning 

---

contrib/abseil-cpp-cmake/CMakeLists.txt
contrib/grpc-cmake/CMakeLists.txt
dbms/src/Common/tests/gtest_cpu_affinity_manager.cpp
dbms/src/Functions/tests/gtest_strings_simd_consistency.cpp
dbms/src/IO/tests/gtest_dm_checksum_buffer.cpp

Issue Number: ref https://github.com/pingcap/tiflash/issues/5265
Problem Summary: https://github.com/pingcap/tiflash/issues/5265#issuecomment-1275698115
```
In file included from /workspace/tiflash/dbms/src/Common/tests/gtest_cpu_affinity_manager.cpp:31:
In file included from /workspace/tiflash/contrib/boost/boost/algorithm/string.hpp:23:
In file included from /workspace/tiflash/contrib/boost/boost/algorithm/string/split.hpp:16:
In file included from /workspace/tiflash/contrib/boost/boost/algorithm/string/iter_find.hpp:27:
In file included from /workspace/tiflash/contrib/boost/boost/algorithm/string/find_iterator.hpp:24:
In file included from /workspace/tiflash/contrib/boost/boost/algorithm/string/detail/find_iterator.hpp:18:
In file included from …
```

Fix unit test under clang-15

---

dbms/src/Storages/System/StorageSystemDTSegments.cpp
dbms/src/Storages/System/StorageSystemDTTables.cpp

Issue Number: ref #5665 
Problem Summary: When process query for system tables, tiflash will initialize useless store under `mysql` database. And the data of these stores cannot be cleared manually which make test for data leak problem hard to write.
Tests 
Side effects
Documentation
```release-note
None
```

avoid init store when process query for tiflash system tables

---

dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task_pool.cpp

Issue Number: ref #6092 
`SegmentReadTaskPool::getTask(UInt64 segment_id)` need to scan a `std::list` to get a task with certain segment_id.
- Use `std::unordered_map` to index tasks by segment ID if read thread enabled.
- Still support in-order dequeue if read thread disabled (keep-order is required).
Tests 
Side effects
Documentation
```release-note
None
```

Optimization of SegmentReadTaskPool::getTask

---

dbms/src/Functions/FunctionsLogical.h
dbms/src/Functions/tests/gtest_logical.cpp

Issue Number: close #6127
Tests 
Side effects
Documentation
```release-note
None
```

fix inconsistent result before deleting some rows

---

dbms/src/Common/FailPoint.cpp
dbms/src/Common/FailPoint.h
dbms/src/Debug/DBGInvoker.cpp
dbms/src/Debug/dbgFuncFailPoint.cpp
dbms/src/Debug/dbgFuncFailPoint.h
dbms/src/Flash/EstablishCall.cpp
dbms/src/Flash/EstablishCall.h
dbms/src/Flash/FlashService.cpp
dbms/src/Flash/FlashService.h
dbms/src/Flash/Mpp/MPPTaskManager.cpp
dbms/src/Flash/Mpp/MPPTaskManager.h
dbms/src/Server/tests/gtest_grpc_alarm.cpp
tests/fullstack-test/mpp/async_server_alarm.test

Issue Number: close #6047, ref #5653
- seperate `establishMPPConnectionAsync` and `EstablishMPPConnection` since now async establish is much different from the sync version
- use `grpc::Alarm` to make `establishMPPConnectionAsync` non block
- enhance pause failpoint so the failpoint can now be paused for a specified duration
Tests 
Side effects
Documentation
```release-note
None
```

make `establishMPPConnectionAsync` non block

---

CMakeLists.txt
cmake/arch.cmake

Signed-off-by: Lloyd-Pottiger <yan1579196623@gamil.com>
Issue Number: ref #6129
set linker name equal to `ld` when using AppleClang.
Tests 
Side effects
Documentation
```release-note
None
```

Set linker name when using AppleClang

---

dbms/src/IO/CompressedReadBufferBase.cpp

Issue Number: close #6172
1. update submodule lz4 to the latest stable version to get better performance
2. use `LZ4_decompress_safe` instead of `LZ4_decompress_fast` which is deprecated and [slower](https://github.com/lz4/lz4/blob/dev/lib/lz4.h#L815-L840)
Tests 
Side effects
Documentation
```release-note
None
```

update submodule lz4 to v1.9.4 and use LZ4_decompress_safe

---

dbms/src/Storages/DeltaMerge/Delta/DeltaPack_V3.cpp

Issue Number: close #6159 
When do serialization for ColumnFileTiny, we can avoid serialize the schema info if it share the same schema with previous ColumnFileTiny. But actually we fail to do that, so after restart all ColumnFileTiny has its own schema object and cannot be compacted together.
1. Avoid serializing the schema of ColumnFileTiny if it is already saved by previous column files.
Tests 
Side effects
Documentation
```release-note
None
```

Fix minor compaction after restart

---

dbms/src/Storages/Transaction/RegionCFDataBase.cpp
dbms/src/Storages/Transaction/TiKVRecordFormat.h
dbms/src/Storages/Transaction/tests/gtest_tikv_keyvalue.cpp

Signed-off-by: Calvin Neo <calvinneo1995@gmail.com>
Issue Number: close #6238
Introduced by https://github.com/tikv/tikv/pull/13698
The new type is to boost TiKV's MVCC Read. Ignore it in TiFlash.
Tests 
Side effects
Documentation
```release-note
None
```

KVStore: Support new lock type 'l'

---

dbms/src/Encryption/tests/gtest_encryption_test.cpp

Issue Number: ref https://github.com/pingcap/tiflash/issues/6218
introduced by https://github.com/pingcap/tiflash/pull/6237
```
dbms/CMakeFiles/gtests_dbms.dir/src/Encryption/tests/gtest_encryption_test.cpp.o -MF dbms/CMakeFiles/gtests_dbms.dir/src/Encryption/tests/gtest_encryption_test.cpp.o.d -o dbms/CMakeFiles/gtests_dbms.dir/src/Encryption/tests/gtest_encryption_test.cpp.o -c /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Encryption/tests/gtest_encryption_test.cpp
[2022-11-03T18:51:02.553Z] /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Encryption/tests/gtest_encryption_test.cpp:236:13: error: expected expression
[2022-11-03T18:51:02.553Z]             )));
[2022-11-03T18:51:02.553Z]             ^ …
```

asan: Fix compile error

---

dbms/src/TiDB/Schema/SchemaBuilder.cpp

Issue Number: close #6257 
Tests 
- create, rename and drop table repeatedly in a short period of time and no alert is generated.
Side effects
Documentation
```release-note
None
```

Fix exception type and error code.

---

CMakeLists.txt
README.md
cmake/test_compiler.cmake
cmake/tools.cmake

Issue Number: ref #6233, ref #6201
Since we do not support gcc any more, this PR will clean up gcc legacy scripts.
- set (CLANG_MINIMUM_VERSION 12)
- remove gcc condition in cmake scripts.
Tests 
Side effects
Documentation
```release-note
None
```

Remove gcc legacy scripts

---

dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.cpp
dbms/src/Flash/Mpp/FineGrainedShuffleWriter.cpp
dbms/src/Flash/Mpp/FineGrainedShuffleWriter.h
dbms/src/Flash/Mpp/HashPartitionWriter.cpp
dbms/src/Flash/Mpp/HashPartitionWriter.h
dbms/src/Flash/Mpp/MPPTunnel.cpp
dbms/src/Flash/Mpp/MPPTunnel.h
dbms/src/Flash/Mpp/MPPTunnelSet.cpp
dbms/src/Flash/Mpp/MPPTunnelSet.h
dbms/src/Flash/Mpp/tests/gtest_mpp_exchange_writer.cpp
dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp

Issue Number: close #6302
-  Use right-valued reference passing for `TrackedMppDataPacketPtr`
- Copy `TrackedMppDataPacketPtr` for broadcast because `TrackedMppDataPacket::switchMemTracker` will be called by multiple threads
The reason for the crash is
- `HashPartitionWriter` pass `TrackedMppDataPacketPtr`  to local tunnel  by left-valued reference. And now the `TrackedMppDataPacketPtr` hold the memory tracker of mpp task a.
- `LocalTunnel::readForLocal` call `TrackedMppDataPacket::switchMemoryTracker` and now the `TrackedMppDataPacketPtr` hold the memory tracker of mpp task b.
- And then the memory tacker throw exception like `RSS(Resident Set Size) much larger than limit`.
- mpp task b finished, and mpp task b is destroyed, as well as mpp task b's memory tracker.
- And …

Use right-valued reference passing for `TrackedMppDataPacketPtr`

---

dbms/src/DataStreams/ExchangeSenderBlockInputStream.h
dbms/src/Flash/Coprocessor/DAGBlockOutputStream.cpp
dbms/src/Flash/Coprocessor/DAGDriver.cpp
dbms/src/Flash/Coprocessor/DAGResponseWriter.h
dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.cpp
dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.h
dbms/src/Flash/Coprocessor/UnaryDAGResponseWriter.cpp
dbms/src/Flash/Coprocessor/UnaryDAGResponseWriter.h
dbms/src/Flash/Coprocessor/tests/gtest_streaming_writer.cpp
dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.cpp
dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.h
dbms/src/Flash/Mpp/FineGrainedShuffleWriter.cpp
dbms/src/Flash/Mpp/FineGrainedShuffleWriter.h
dbms/src/Flash/Mpp/HashPartitionWriter.cpp
dbms/src/Flash/Mpp/HashPartitionWriter.h
dbms/src/Flash/Mpp/tests/gtest_mpp_exchange_writer.cpp

Issue Number: close #6355
- remove uesless check `assert(rows_in_blocks == 0)` in ExchangeWriter and StreamingWriter
- move the almost of code in `UnaryDAGResponseWriter::finishWrite` to `UnaryDAGResponseWriter::flush`
- move filling execution summary from `UnaryDAGResponseWriter::finishWrite` to `DAGDriver::execute`
The reason for the crash is
1. One of the MPPTask occur exception and call `manager->abortMPPQuery(id.start_ts, updated_msg, AbortType::ONERROR)`
2. Other mpp task is called `MPPTask::abortDataStreams(AbortType::ONERROR)`
3. And then the final UnionBlockInputStream return an empty block in advance and finish `Stream->read`, and `StreamingWriter::flush` is not called, so `rows_in_blocks != 0`
4. the stream->readPrefix is called, and the tiflash node crash in …

Remove `DAGResponseWriter::finishWrite`

---

dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile_V3.cpp
dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp

Issue Number: close #6361 
1. The minor compaction process may always select level 0 and there are two many small column files in other levels which cannot be compacted.
2. The minor compaction trigger condition is bad which will and it harder and harder to trigger it.
1. Increase next compaction level before return compaction level;
2. Reset minor compaction trigger statistics if the compaction succeed;
Tests 
Side effects
Documentation
```release-note
Fix too many column files under heavy write pressure.
```

avoid always compacting level0 under heavy write pressure

---

dbms/src/Server/Server.cpp

Issue Number: close #6365 
The DynamicThreadPool::global_instance->reset() is called before all query tasks done, then when task request threads from DynamicThreadPool, the global_instance points to nullptr.
Tests 
Side effects
Documentation
```release-note
None
```

revert #6340

---

dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_randomized.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_sst_files_stream.cpp

Issue Number: ref #5237
Always produce a single sorted block, instead of a list of blocks, when we need to fill rows in tests. In this way, we can produce a correct DMFile from these rows.
Tests 
Side effects
Documentation
```release-note
None
```

test: merge blocks when prepare

---

dbms/src/Encryption/tests/gtest_rate_limiter.cpp

Issue Number: close #6261
https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/tiflash-ghpr-unit-tests/runs/7135/nodes/75/steps/80/log/?start=0
thread may be interrupted between line 208 and line 209 which cause t1-t0 is larger than 40ms, then limiter can directly refill once without waiting.
Tests 
Side effects
Documentation
```release-note
None
```

fix unstable test

---

dbms/src/Flash/Coprocessor/DAGQueryBlock.cpp
dbms/src/Flash/Planner/PhysicalPlan.cpp

Issue Number: close #6381 
Tests 
Side effects
Documentation
```release-note
None
```

Raise error for streamAgg when plan contains group by key

---

dbms/src/Common/TiFlashMetrics.h
dbms/src/Storages/Page/V3/Blob/BlobStat.cpp
dbms/src/Storages/Page/V3/Blob/BlobStat.h
dbms/src/Storages/Page/V3/BlobStore.cpp
dbms/src/Storages/Page/V3/PageStorageImpl.cpp
dbms/src/Storages/Page/V3/spacemap/SpaceMapSTDMap.h
dbms/src/Storages/Page/V3/tests/gtest_blob_stat.cpp
dbms/src/Storages/Page/V3/tests/gtest_free_map.cpp
dbms/src/Storages/Transaction/KVStore.cpp

Issue Number: close #6404 
Problem Summary: The process to search an available space in BlobFile is an O(n) operation and introduce too much latency for the whole write process.
1. Introduce a `free_map_invert_index` to eliminate the O(n) operation;
2. Skip BlobFiles which are already locked when search for an available space for write;
Tests 
Side effects
Documentation
```release-note
None
```

Optimize search write position in BlobFile

---

dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp

Issue Number: close #6409 
Reverts pingcap/tiflash#6344
Tests 
Side effects
Documentation
```release-note
None
```

Revert "Use `num_streams` as parallelism when read thread is enabled."

---

dbms/src/Flash/Mpp/MPPTask.cpp
dbms/src/Flash/Mpp/MPPTask.h

Issue Number: ref #6418 
Tests 
Side effects
Documentation
```release-note
Avoiding tiflash global locks with small probability of long term blocking.
```

Use `BlockIO.in->cancel` directly to avoid possible blocking of ProcessList::mutex

---

dbms/src/Storages/DeltaMerge/Delta/ColumnFileFlushTask.cpp
dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.h
dbms/src/Storages/DeltaMerge/Delta/MinorCompaction.cpp
dbms/src/Storages/DeltaMerge/Delta/MinorCompaction.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_value_space.cpp

Issue Number: close #6431 
cherry pick of https://github.com/pingcap/tiflash/pull/6432
Problem Summary: When under heavy write pressure in some scenario, there are many small column files in `DeltaValueSpace`, and the current minor compaction algorithm cannot compact these small column files effectively which may cause large memory consumption and has the risk of out of memory.
Avoid dividing different levels in `ColumnFilePersistedSet` and just keep one level in it. For every minor compaction, we will always check all column files whether they can be compacted and do the compaction at once.
Note that this may cause some write amplification, but the price should be acceptable compare to high memory usage.
Tests 
1. Compare this fix with previous binary in a cluster with heavy write …

reduce column files num under heavy write pressure

---

dbms/src/Flash/Coprocessor/DAGContext.h
dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
dbms/src/Flash/Coprocessor/DAGStorageInterpreter.h
dbms/src/Interpreters/InterpreterSelectQuery.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_storage_delta_merge.cpp
dbms/src/Storages/Page/V2/PageStorage.h
dbms/src/Storages/RegionQueryInfo.h
dbms/src/Storages/StorageDeltaMerge.cpp
dbms/src/Storages/StorageDeltaMerge.h
dbms/src/Storages/StorageDisaggregated.cpp
dbms/src/Storages/Transaction/LearnerRead.cpp
dbms/src/Storages/Transaction/LearnerRead.h

* Put ScanContextPtr into MvccQueryInfo
* Remove the reduant DeltaMergeStore::read with explicit ScanContextPtr interface
* Remove useless `MvccQueryInfo::concurrent`
* Fix a compile error (unused var) under release mode
Tests 
Side effects
Documentation
```release-note
None
```

Refine the storage->read in DAGStorageInterpreter

---

dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
dbms/src/Storages/DeltaMerge/Delta/MinorCompaction.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_value_space.cpp
dbms/src/Storages/Page/V2/PageFile.cpp
dbms/src/Storages/Page/V2/tests/gtest_page_storage.cpp
dbms/src/Storages/Page/V3/BlobStore.cpp
dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp

Issue Number: close #6460 
1. Use `PageReader::read(PageId page_id)` instead of `PageReader::read(const std::vector<PageStorage::PageReadFields> & page_fields)` in `ColumnFileTiny::readBlockForMinorCompaction`. So that we only need to do 1 read for each cftiny, instead of the number of columns.
2. Use a better compact strategy: do delta compact only if the *increased* number of cftiny is larger than the limit, instead of the *total* number.
Tested on the worst update workload of TiFlash: large volume data, each transaction only update 1 rows, and the update pk is very distributed. Results:
1. Read iops reduces from 80K to 4K
2. Write amplification reduces from 75x to 25x
Before:
After:
Tests 
Side effects
Documentation
```release-note
Reduce the IOPS and write …
```

Optimize delta compact strategy to reduce iops and write amplification

---

dbms/src/Common/getNumberOfCPUCores.cpp
dbms/src/Common/getNumberOfCPUCores.h
dbms/src/Flash/FlashService.cpp
dbms/src/Flash/Mpp/MinTSOScheduler.cpp
dbms/src/Interpreters/SettingsCommon.h
dbms/src/Server/Server.cpp

Issue Number: close #6480
Tests 
Side effects
Documentation
```release-note
None
```

Set max_threads according to the number of physical cpu cores

---

dbms/src/Flash/Coprocessor/DAGContext.h
dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
dbms/src/Flash/Executor/DataStreamExecutor.cpp
dbms/src/Flash/Executor/DataStreamExecutor.h
dbms/src/Flash/Executor/QueryExecutor.h
dbms/src/Flash/Mpp/MPPTask.cpp
dbms/src/Flash/Mpp/MPPTask.h

Issue Number: 
ref #5095 
ref #5900
- Move the table locks from `BlockInputStream` to `DAGContext`
- Always use non-kill to cancel `BlockInputStream`
Tests 
Side effects
Documentation
```release-note
None
```

Minor refine of `TableLock` and `MPPTask::cancel`

---

dbms/src/DataStreams/NonJoinedBlockInputStream.cpp
dbms/src/DataStreams/NonJoinedBlockInputStream.h
dbms/src/Interpreters/Join.cpp
dbms/src/Interpreters/Join.h

Signed-off-by: windtalker <xufeixw@ustc.edu.cn>
Issue Number: ref #5900
move `NonJoinedBlockInputStream` out of Join.cpp
Tests 
Side effects
Documentation
```release-note
None
```

move NonJoinedBlockInputStream out of Join.cpp

---

dbms/src/DataStreams/FilterBlockInputStream.cpp
dbms/src/DataStreams/FilterTransformAction.cpp
dbms/src/DataStreams/FilterTransformAction.h

In #6250 , replace `child->read(child_filter, true)` by `child->read()` in `FilterBlockInputStream`. When the child of `FilterBlockInputStream` is tablescan, we support `Block read(FilterPtr & res_filter, bool return_filter)`. By calling `Block read(FilterPtr & res_filter, bool return_filter)`, we can merge the column filter together, reducing the cost, since column filter is a heavy-cost operator.
Tests 
Side effects
Documentation
```release-note
None
```

.*: Refine `FilterBlockInputStream` and `FilterTransformAction`

---

dbms/src/Storages/Transaction/LearnerRead.cpp

Issue Number: close #6525
https://ci.pingcap.net/blue/organizations/jenkins/tiflash_scripts_ghpr_test/detail/tiflash_scripts_ghpr_test/314/pipeline
test case failed because [the read_tso is std::numeric_limits<uint64_t>::max() and became 0](https://github.com/pingcap/tiflash/blob/b99541f240c2d56c4aaadfb80de0d51f1a64c389/dbms/src/Storages/Transaction/LearnerRead.cpp#L215) so that stale read was triggered.
`read_tso is 0` means that it is in testing scenario, should not trigger stale read.
Tests 
Side effects
Documentation
```release-note
None
```

Fix stale read in testing scenario

---

dbms/src/DataTypes/DataTypeNullable.cpp
dbms/src/DataTypes/DataTypeNullable.h
dbms/src/DataTypes/DataTypeNumberBase.cpp
dbms/src/DataTypes/DataTypeNumberBase.h
dbms/src/DataTypes/DataTypesNumber.h
dbms/src/DataTypes/IDataType.h
dbms/src/Storages/MutableSupport.h
dbms/src/Storages/Transaction/Datum.cpp
dbms/src/Storages/Transaction/TiDB.cpp
dbms/src/Storages/Transaction/TiDB.h
dbms/src/Storages/Transaction/TypeMapping.cpp
dbms/src/Storages/Transaction/tests/gtest_type_mapping.cpp

Previously, we added "widen" property to make DDL works on TransactionMergeTree without rewriting the data on disk. https://github.com/pingcap/tiflash/pull/110
As TMT is no longer supported and DeltaTree engine support DDL by adding cast on reading, we don't need the "widen" anymore.
Remove the "widen" related codes
Tests 
Side effects
Documentation
```release-note
None
```

*: Remove useless DataType widen property

---

dbms/src/Common/OptimizedRegularExpression.inl.h

Issue Number: close #6559 
```
FAILED: dbms/src/Functions/CMakeFiles/clickhouse_functions.dir/FunctionsRegexp.cpp.o 
/Library/Developer/CommandLineTools/usr/bin/c++ -DBOOST_BIND_GLOBAL_PLACEHOLDERS -DBOOST_CONTEXT_EXPORT="" -DBOOST_CONTEXT_NO_LIB -DBOOST_CONTEXT_STATIC_LINK -DBOOST_FIBER_NO_LIB -DBOOST_FIBER_STATIC_LINK -DBOOST_NO_CXX98_FUNCTION_BASE -DBOOST_SYSTEM_NO_DEPRECATED -DCARES_STATICLIB -DFIU_ENABLE -DLZ4_DISABLE_DEPRECATE_WARNINGS=1 -DMULTIPLE_CONTEXT_GTEST -DPOCO_STATIC -DPOCO_UNBUNDLED_ZLIB -DTIFLASH_COMPILER_VPCLMULQDQ_SUPPORT=0 -DTIFLASH_ENABLE_ASIMD_SUPPORT=1 -DTIFLASH_SOURCE_PREFIX=\"/Users/qizhi/p/tiflash\" -I/Users/qizhi/p/tiflash/contrib/libdivide -I/Users/qizhi/p/tiflash/contrib/libmetrohash/src -I/Users/qizhi/p/tiflash/contrib/libfarmhash …
```

chore: fix build on mac m1

---

dbms/src/Common/TiFlashMetrics.h
metrics/grafana/tiflash_summary.json

Problem Summary: old metrics aggregated the type information.
1. remove `type_dispatch_mpp_task`, `type_mpp_establish_conn`, `type_cancel_mpp_task`, `type_run_mpp_task` of tiflash_coprocessor_request_handle_seconds, because they won't be set.
2. show query type of `Request Duration` and `Request Handle Duration`
3. default hide `Request Duration` 's p99, p95, p80, only show p999 by default, because there are too much items.
Tests 
before
after
Side effects
Documentation
```release-note
None
```

metrics: refine metrics of `Request Duration` and `Request Handle Duration`

---

dbms/src/Debug/MockComputeServerManager.cpp
dbms/src/Debug/MockComputeServerManager.h
dbms/src/Debug/MockStorage.cpp
dbms/src/Debug/MockStorage.h
dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
dbms/src/Flash/Coprocessor/MockSourceStream.cpp
dbms/src/Flash/Coprocessor/MockSourceStream.h
dbms/src/Flash/FlashService.cpp
dbms/src/Flash/FlashService.h
dbms/src/Flash/Planner/PhysicalPlan.cpp
dbms/src/Flash/Planner/plans/PhysicalMockExchangeReceiver.cpp
dbms/src/Flash/Planner/plans/PhysicalMockExchangeReceiver.h
dbms/src/Flash/Planner/plans/PhysicalMockTableScan.cpp
dbms/src/Flash/tests/gtest_aggregation_executor.cpp
dbms/src/Flash/tests/gtest_executors_with_dm.cpp
dbms/src/Flash/tests/gtest_filter_executor.cpp
dbms/src/Flash/tests/gtest_limit_executor.cpp
dbms/src/Flash/tests/gtest_mock_storage.cpp
dbms/src/Flash/tests/gtest_projection_executor.cpp
dbms/src/Flash/tests/gtest_squashing_hash_join_transform.cpp
dbms/src/Flash/tests/gtest_topn_executor.cpp
dbms/src/Interpreters/Context.cpp
dbms/src/Interpreters/Context.h
dbms/src/Server/FlashGrpcServerHolder.cpp
dbms/src/Server/FlashGrpcServerHolder.h
dbms/src/TestUtils/ExecutorTestUtils.cpp
dbms/src/TestUtils/ExecutorTestUtils.h
dbms/src/TestUtils/mockExecutor.cpp
dbms/src/TestUtils/mockExecutor.h

Issue Number: ref #4609
We want to use `DeltaMergeStorage` to run the query in `ut framework`.
Then we can test the whole query process in single node(not including mpp with multiple nodes, we assume that data are stored in one node).
It will be helpful for features that change both `storage code` and `compute code`. Eg: late materialization and pipeline model.
Maybe RSFilter can use `ut framework` too.
Here is one simple case:
```c++
context.addMockDeltaMerge({"test_db", "t0"},
{{"col0", TiDB::TP::TypeLongLong}},
{{toVec<Int64>("col0", {0, 1, 2, 3, 4, 5, 6, 7})}});
auto request = context
.scan("test_db", "t0")
.build(context);
executeAndAssertColumnsEqual(
request,
{{toNullableVec<Int64>("col0", {0, 1, 2, 3, 4, 5, 6, 7})}});
```
1. We use `MockStorage` to hold …

Test: Bind delta merge storage with executor ut

---

dbms/src/Common/Config/ConfigReloader.h
dbms/src/Common/tests/gtest_config_reloader.cpp

Issue Number: close #6569
Tests 
Side effects
Documentation
```release-note
None
```

fix tsan fail in unit test `ConfigReloaderTest.WithConfigObject`

---

dbms/src/Debug/MockStorage.cpp
dbms/src/Debug/MockStorage.h
dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
dbms/src/Flash/Planner/PhysicalPlan.cpp
dbms/src/Flash/Planner/plans/PhysicalMockTableScan.cpp
dbms/src/Flash/Planner/plans/PhysicalMockTableScan.h
dbms/src/Flash/Planner/tests/gtest_physical_plan.cpp
dbms/src/Flash/tests/gtest_collation.cpp
dbms/src/Flash/tests/gtest_filter_executor.cpp
dbms/src/Flash/tests/gtest_join_executor.cpp
dbms/src/Flash/tests/gtest_query_expr.cpp
dbms/src/TestUtils/ExecutorTestUtils.cpp
dbms/src/TestUtils/ExecutorTestUtils.h
dbms/src/TestUtils/mockExecutor.cpp
dbms/src/TestUtils/mockExecutor.h

Issue Number: ref #4609 
We don't push down filter to storage layer in current ut framework.
In `getStreamFromDeltaMerge`, mock `DAGQueryInfo` with `PushDownFilter` from `tipb:Selection`
Tests 
Side effects
Documentation
```release-note
None
```

Test: support push down filter in ut

---

dbms/src/Debug/MockStorage.cpp
dbms/src/Debug/MockStorage.h
dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
dbms/src/Flash/Coprocessor/GenSchemaAndColumn.cpp
dbms/src/Flash/Coprocessor/GenSchemaAndColumn.h
dbms/src/Flash/Coprocessor/MockSourceStream.cpp
dbms/src/Flash/Coprocessor/MockSourceStream.h
dbms/src/Flash/Planner/plans/PhysicalMockTableScan.cpp
dbms/src/Flash/tests/gtest_scan_concurrency_hint.cpp
dbms/src/TestUtils/ExecutorTestUtils.cpp
dbms/src/TestUtils/mockExecutor.cpp
dbms/src/TestUtils/mockExecutor.h

Signed-off-by: xufei <xufei@pingcap.com>
Add scan concurrency hint for mock table, so the concurrency of mock table scan is decided by `dag_context.initialize_concurrency` and the scan concurrency hint.
Tests 
Side effects
Documentation
```release-note
None
```

support scan concurrency hint for mock table

---

dbms/src/Common/Spiller.cpp
dbms/src/Common/Spiller.h
dbms/src/Common/tests/gtest_spiller.cpp
dbms/src/DataStreams/SpilledFilesInputStream.cpp
dbms/src/DataStreams/SpilledFilesInputStream.h
dbms/src/TestUtils/ColumnGenerator.cpp
dbms/src/TestUtils/ColumnGenerator.h

Signed-off-by: xufei <xufei@pingcap.com>
1. add `Spiller` to handle spill/restore blocks.
Tests 
Side effects
Documentation
```release-note
None
```

add spiller

---

dbms/src/Flash/Mpp/MPPTaskStatistics.cpp

Issue Number: close #6587 
The log is used by tracing tool, which expects the messge satisfy json format. It's ok to remove query id here, because the logger itself contains query id info already.
Tests 
Check the changed log.
Side effects
Documentation
```release-note
None
```

Removed redundant query id from tracingJson

---

dbms/src/Interpreters/Context.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
dbms/src/Storages/DeltaMerge/StoragePool.cpp
dbms/src/Storages/DeltaMerge/StoragePool.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
dbms/src/Storages/Page/V2/PageStorage.cpp
dbms/src/Storages/Page/V3/PageDirectory.h
dbms/src/Storages/Page/V3/PageDirectory/ExternalIdsByNamespace.cpp
dbms/src/Storages/Page/V3/PageDirectory/ExternalIdsByNamespace.h
dbms/src/Storages/Page/V3/PageStorageImpl.cpp
dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
dbms/src/Storages/PathPool.cpp
dbms/src/Storages/PathPool.h
dbms/src/Storages/StorageDeltaMerge.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/6486
From the log file, we can see that (almost all) dmfile are removed after "Release DeltaMerge Store end". This should not happen because we will check the `path_pool_weak_ref` is valid or not in the remover callback (introduced in https://github.com/pingcap/tiflash/pull/5699).
https://github.com/pingcap/tiflash/blob/5bd0e891eef0dcaecf35198b3051f71c20939c0a/dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp#L70-L77
However, it do happen :(
Maybe there are some background tasks that is being handled and keep a shared_ptr of `path_pool` or `delta-merge-store` so the detect is false positive passed.
I can reproduce the similar problem by a unit test …

PageStorage: Fix unexpected dmfile removed after shutdown

---

dbms/src/Storages/Transaction/LearnerRead.cpp
dbms/src/Storages/Transaction/RegionTable.cpp
dbms/src/Storages/Transaction/tests/gtest_sync_status.cpp

Issue Number: close #6605
After https://github.com/tikv/tikv/pull/13897 merged, full safe_ts timestamp will be passed to observer, so need to modify related code in TiFlash.
Tests 
Side effects
Documentation
```release-note
None
```

save full safe_ts timestamp

---

dbms/src/DataStreams/WindowBlockInputStream.cpp

Issue Number: ref #5900 
1. reduce some useless copy in `isDifferentFromPrevPartition`
2. compare several times first to speed up the case that the partition end is very close.
Tests 
Test step
```sql
create table win(s varchar(20));
insert into 50000000 lines where `s` are all different.
explain analyze select row_number() over (partition by s) rn from win;
```
v6.5.0
```sql
mysql> explain analyze select row_number() over (partition by s) rn from win;
+------------------------------------+-------------+----------+--------------+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```

Optimize `getPartitionEndRow` for window function

---

dbms/src/Core/BlockInfo.h
dbms/src/DataStreams/MergingAggregatedMemoryEfficientBlockInputStream.cpp
dbms/src/DataStreams/MergingAggregatedMemoryEfficientBlockInputStream.h
dbms/src/DataStreams/MergingAndConvertingBlockInputStream.h
dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
dbms/src/DataStreams/ParallelAggregatingBlockInputStream.h
dbms/src/DataStreams/SizeLimits.h
dbms/src/DataStreams/TotalsHavingBlockInputStream.cpp
dbms/src/DataStreams/TotalsHavingBlockInputStream.h
dbms/src/Flash/Coprocessor/AggregationInterpreterHelper.cpp
dbms/src/Flash/tests/gtest_spill_sort.cpp
dbms/src/Interpreters/Aggregator.cpp
dbms/src/Interpreters/Aggregator.h
dbms/src/Interpreters/InterpreterSelectQuery.cpp
dbms/src/Interpreters/InterpreterSelectQuery.h
dbms/src/Interpreters/SettingsCommon.h

Signed-off-by: xufei <xufei@pingcap.com>
remove `over_flow_row` related logical in Aggregation, since we should never use it.
Tests 
Side effects
Documentation
```release-note
None
```

remove over_flow_row in aggregation

---

dbms/src/Common/TiFlashMetrics.h
dbms/src/Flash/Disaggregated/PageDownloader.cpp
dbms/src/Storages/DeltaMerge/Remote/RemoteReadTask.cpp
dbms/src/Storages/DeltaMerge/Remote/RemoteSegmentThreadInputStream.cpp
dbms/src/Storages/DeltaMerge/Remote/RemoteSegmentThreadInputStream.h
dbms/src/Storages/DeltaMerge/Remote/tests/gtest_remote_read_task.cpp
dbms/src/Storages/StorageDisaggregated.cpp

https://github.com/pingcap/tiflash/blob/c6b2eb5d2b9adf782cb3a84537546bc164a7700b/dbms/src/Flash/Disaggregated/PageDownloader.cpp#L98-L114
* PageDownloader do preparation (place delta index) after data downloaded
* Fix the bug that build delta index in background threads may block
* Investigate the performance issue
* `profiles.default.dis_prepare: 0` by default because it does not improve the performance now
Because we add union-stream on top of RemoteSegmentThreadInputStream to improve the io concurrency. The union stream are blocked by background tasks to build delta index. So no performance gain even if we support build delta index in background threads.
If we remove the union-stream, then we can get about 10% performance gain. However, it is …

Read node support build delta index in background threads

---

dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
dbms/src/Storages/DeltaMerge/ScanContext.h
dbms/src/Storages/DeltaMerge/Segment.cpp

Issue Number: ref #5926
Change the time unit of measurement in ScanContext.
Choose ns instead of ms as the time unit can improve the accuracy of statistics.
Tests 
Side effects
Documentation
```release-note
None
```

change the time unit of measurement in ScanContext

---

dbms/src/DataStreams/NonJoinedBlockInputStream.cpp
dbms/src/DataStreams/NonJoinedBlockInputStream.h
dbms/src/Flash/tests/gtest_join_executor.cpp

Issue Number: ref #3436
1. make the size of block returned by `NonJoinedBlockInputStream` under `max_block_size`
2. refine test for non-joined-data, use left join's result as the reference.
Tests 
Side effects
Documentation
```release-note
None
```

`max_block_size` take effect on `NonJoinedBlockInputStream`

---

dbms/src/Core/TiFlashDisaggregatedMode.cpp
dbms/src/Core/TiFlashDisaggregatedMode.h
dbms/src/Flash/DiagnosticsService.cpp
dbms/src/Interpreters/AsynchronousMetrics.cpp
dbms/src/Interpreters/Context.h
dbms/src/Server/Server.cpp
dbms/src/Storages/Transaction/LearnerRead.cpp
dbms/src/Storages/Transaction/TMTContext.cpp
etc/config-template.toml

Signed-off-by: guo-shaoge <shaoge1994@163.com>
Issue Number: close #6701
1. https://github.com/pingcap/tiflash/pull/6588 removed proxy when node is in tiflash_compute mode, so all tilfash_compute nodes will be managed by *AutoScaler* instead of PD.
2. AutoScaler is not stable for now, we want to add switcher to help roll back.
1. Check if use_autoscaler corresponding to each change in https://github.com/pingcap/tiflash/pull/6588
Tests 
Side effects
Documentation
```release-note
None
```

add use_autoscaler config for AutoSaler prod rollback

---

tests/docker/cluster.yaml
tests/docker/cluster_disable_new_collation.yaml
tests/docker/cluster_new_collation.yaml
tests/docker/cluster_tidb_fail_point.yaml
tests/docker/tiflash-dt.yaml

Signed-off-by: lijie <lijie@pingcap.com>
Fix integration test in CI because docker is too old
Tests 
Side effects
Documentation
```release-note
None
```

fix: mitigate old docker for full stack test

---

dbms/src/DataStreams/HashJoinProbeBlockInputStream.cpp
dbms/src/DataStreams/HashJoinProbeBlockInputStream.h
dbms/src/Flash/tests/gtest_join_executor.cpp

Issue Number: ref #6713
revert `squashing_transform` in HashJoinProbeBlockInputStream ---- merge output blocks if need in hash join #6529 816b8d5d5dff61b7fa452311c0b666947c34deb8
Tests 
Side effects
Documentation
```release-note
None
```

Remove usage about `SquashingHashJoinBlockTransform` in `HashJoinProbeBlockInputStream`

---

dbms/src/DataStreams/HashJoinProbeBlockInputStream.cpp
dbms/src/DataStreams/HashJoinProbeBlockInputStream.h

Issue Number: close #6692 
When one HashJoinProbStream canceled before another HashJoinProbStream entered readImpl function, the join instance's finishOneProb function wouldn't be invoked and cause HashJoinProbStream hang.
Since we can't distinguish normal finish and abort in HashJoinProbStream's cancel function now, so use atomic field to ensure join instance's finishOneProb is invoked exactly once.
Tests 
Manually run the failed randomPoint test, and check no thread leak now.
Side effects
Documentation
```release-note
None
```

Fix hashJoinProb thread leak issue

---

dbms/src/Storages/DeltaMerge/RowKeyRange.h
dbms/src/Storages/DeltaMerge/tests/gtest_key_range.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/6699
Consider an Int Handle in variable `foo` which is 0xCCAB. It is encoded as `{ 80 00 00 00 00 00 CC AB }` in bytes.
In #6538:
```
foo.toNext:       int_value = 0xCCAC, bytes_value = { 80 00 00 00 00 00 CC AB 00 }
foo.toPrefixNext: int_value = 0xCCAC, bytes_value = { 80 00 00 00 00 00 CC AC }
```
The implementation of `toNext()` is incorrect because it violates the rule that the int_value and bytes_value should be matching. 
Let's see what will happen when this rule is not respected:
- Consider we construct a new Int Handle in variable `bar` from int 0xCCAC. It will be built as `int_value = 0xCCAC, bytes_value = { 80 00 00 00 00 00 CC AC }`. Now `bar` and …

Fix incorrect string value when doing int_handle.toNext

---

dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetSnapshot.h
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/WriteBatches.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_column_file.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
dbms/src/Storages/Page/V3/BlobStore.cpp
dbms/src/Storages/Page/V3/PageEntry.h
dbms/src/TestUtils/FunctionTestUtils.h

Issue Number: close https://github.com/pingcap/tiflash/issues/6726
1. Run TPCC workload
2. Add a column
3. Only read the newly added column
This might lead to an exception with error message `Reading with fields but entry size is 0`
Because only the newly added column is read, `fields.length() == 0`. It violates an assumption in BlobStore::read and an exception is thrown
https://github.com/pingcap/tiflash/blob/4206a522521d19d918ae0483a482874f727da30e/dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp#L62-L80
https://github.com/pingcap/tiflash/blob/4206a522521d19d918ae0483a482874f727da30e/dbms/src/Storages/Page/V3/BlobStore.cpp#L582-L586
* In `ColumnFileTiny::readFromDisk`, skip reading from disk if all are filled by default column
* In `BlobStore::read` return an …

Fix an exception thrown while reading from ColumnFileTiny after add column

---

dbms/src/DataStreams/HashJoinProbeBlockInputStream.cpp
dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.cpp
dbms/src/Flash/Mpp/FineGrainedShuffleWriter.cpp
dbms/src/Flash/Mpp/HashPartitionWriter.cpp
dbms/src/Flash/Mpp/MPPTunnelSetHelper.cpp
dbms/src/TestUtils/FunctionTestUtils.h

Issue Number: close #6733 
The gtest's failure is caused by the internal reorder of blocks in ExchangeSender. Fix it by writing them sequentially.
Tests 
Side effects
Documentation
```release-note
None
```

Fix gtest false negative case

---

dbms/src/Functions/tests/gtest_from_unixtime.cpp
dbms/src/Functions/tests/gtest_unix_timestamp.cpp

Issue Number: close #6756
The root cause is Daylight Saving Time in Santiago in 2022 is changed from `2022-09-04 01:00:00` to `2022-09-11 01:00:00`,
this pr use the Daylight Saving Time in 2021 instead.
Tests 
Side effects
Documentation
```release-note
None
```

fix timezone test

---

dbms/src/Core/SpillHandler.cpp
dbms/src/Core/Spiller.cpp
dbms/src/Core/Spiller.h
dbms/src/Core/tests/gtest_spiller.cpp
dbms/src/DataStreams/SpilledFilesInputStream.cpp
dbms/src/DataStreams/SpilledFilesInputStream.h

1. refine some logs in spiller
2. support `release_spilled_file_on_restore` in Spiller, which will release the spill file once all the data in that file has been restored.
Tests 
Side effects
Documentation
```release-note
None
```

Refine spiller

---

dbms/src/Common/FailPoint.cpp
dbms/src/Interpreters/Context.cpp
dbms/src/Interpreters/Context.h
dbms/src/Server/DTTool/DTTool.h
dbms/src/Server/RaftConfigParser.cpp
dbms/src/Server/RaftConfigParser.h
dbms/src/Server/Server.cpp
dbms/src/Storages/Page/V3/tests/gtest_page_storage_mix_mode.cpp
dbms/src/Storages/PathPool.cpp
dbms/src/Storages/PathPool.h
dbms/src/Storages/Transaction/RegionPersister.cpp
dbms/src/Storages/Transaction/RegionPersister.h
dbms/src/Storages/Transaction/tests/gtest_region_persister.cpp
dbms/src/TestUtils/TiFlashTestEnv.cpp

Issue Number: ref #6728 
Problem Summary: `stable_page_storage` is useless which stands for V1 format page data. This format is really too old and should be able to read by V2 format related code.
Remove `stable_page_storage` from RegionPersister.
Tests 
Side effects
Documentation
```release-note
None
```

remove legacy code in RegionPersister

---

dbms/src/Debug/MockRaftStoreProxy.cpp
dbms/src/Debug/MockStorage.cpp
dbms/src/Debug/MockStorage.h
dbms/src/Flash/tests/gtest_mock_storage.cpp
dbms/src/Storages/Transaction/tests/gtest_new_kvstore.cpp
dbms/src/Storages/Transaction/tests/kvstore_helper.h
dbms/src/TestUtils/FunctionTestUtils.cpp
dbms/src/TestUtils/TiFlashTestEnv.cpp
dbms/src/TestUtils/TiFlashTestEnv.h

Issue Number: close #6767
Tests 
Side effects
Documentation
```release-note
None
```

fix RegionKVStoreTest

---

dbms/src/Flash/Mpp/ExchangeReceiver.cpp
dbms/src/Flash/Mpp/MPPTunnel.cpp
dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp

1. Add more information to the error message in MPPTunnel
2. Use warning log when ExchangeReceiver::connectionDone is called with meet_error = true
Tests 
Side effects
Documentation
```release-note
None
```

Add more information to the error message in MPPTunnel

---

README.md

After I install arch linux and prepare according to the prompt of README.MD. When I excute the commands follows , error occurs.
```
mkdir cmake-build-debug  # The directory name can be customized
cd cmake-build-debug
cmake .. -GNinja -DCMAKE_BUILD_TYPE=DEBUG
ninja tiflash
```
error(cmake/tools.cmake:87):
```
Cannot find ar.
```
After excute
```
sudo pacman -S llvm
```
No error occurs again.
Issue Number: close #6800 
Problem Summary:  Prepare Prerequisites on Arch Linux is not enough. We should add ' llvm ' .
Just append ' llvm ' in prepare commands on Arch Linux in ` README.md `
Side effects
Documentation
```release-note
None
```

fix(README) : Prepare Prerequisites on Arch Linux

---

dbms/src/Core/Spiller.cpp

1. refine restore log
2. add lock when restore
Tests 
Side effects
Documentation
```release-note
None
```

refine spill log

---

dbms/src/Common/MPMCQueue.h
dbms/src/Common/tests/gtest_mpmc_queue.cpp

In TiFlash runtime, some executors(like ExchangeReceiver, MPPTunnelSender, UnionBlockInputStream) use a MPMC queue to buffer the data, but the queues are only limited by the number of elements. If the element occupies a large amount of memory, the buffer queue may occupy too much memory, this pr add `auxiliary_memory_bound` to mpmc queue, so the memory usage by the queue can be limited.
Tests 
Side effects
Documentation
```release-note
None
```

add support for auxiliary memory bound in mpmc_queue

---

dbms/src/Interpreters/Context.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_storage_delta_merge.cpp
dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.cpp
dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.h
dbms/src/Storages/Page/V3/Universal/tests/gtest_universal_page_storage_storage_pool.cpp

Issue Number: close #6841 
Problem Summary: There are some asan failure after running unit tests which was introduced by https://github.com/pingcap/tiflash/pull/6717. This is caused by unsuccessfully cleaning some objects after running unit tests.
Do some clean work after running unit test.
Tests 
Side effects
Documentation
```release-note
None
```

Fix asan test failed

---

release-centos7-llvm/dockerfiles/misc/bake_llvm_base_aarch64.sh
release-centos7-llvm/dockerfiles/misc/bake_llvm_base_amd64.sh

Problem Summary: The OpenSSL version in tiflash build image has some security problem recently. Although it takes no effect in tiflash release binary now because we link to BoringSSL in our release binary, just upgrade it to avoid future confusion.
Update OpenSSL version in tiflash build image from `1.1.1l` to `1.1.1t`.
Tests 
Side effects
Documentation
```release-note
None
```

bump openssl version to 1.1.1t in build image

---

dbms/src/Interpreters/Context.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
dbms/src/Storages/DeltaMerge/StoragePool.cpp
dbms/src/Storages/DeltaMerge/StoragePool.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
dbms/src/Storages/Page/V2/PageStorage.cpp
dbms/src/Storages/Page/V2/PageStorage.h
dbms/src/Storages/Page/V3/PageDirectory.h
dbms/src/Storages/Page/V3/PageDirectory/ExternalIdsByNamespace.cpp
dbms/src/Storages/Page/V3/PageDirectory/ExternalIdsByNamespace.h
dbms/src/Storages/Page/V3/PageStorageImpl.cpp
dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
dbms/src/Storages/PathPool.cpp
dbms/src/Storages/PathPool.h
dbms/src/Storages/StorageDeltaMerge.cpp

Issue Number: close #6486
From the log file, we can see that (almost all) dmfile are removed after "Release DeltaMerge Store end". This should not happen because we will check the `path_pool_weak_ref` is valid or not in the remover callback
https://github.com/pingcap/tiflash/blob/5bd0e891eef0dcaecf35198b3051f71c20939c0a/dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp#L70-L77
However, it do happen :(
Maybe there are some background tasks that is being handled and keep a shared_ptr of `path_pool` or `delta-merge-store` so the detect is false positive passed.
I can reproduce the similar problem by a unit test
https://github.com/pingcap/tiflash/blob/eac71b95263790f758f9bdf7120b692f4ad13af4/dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp#L136-L149 …

PageStorage: Fix unexpected dmfile removed after shutdown (cherry-pick #6558) 

---

dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
dbms/src/Flash/Coprocessor/DAGQueryInfo.h
dbms/src/Flash/Coprocessor/FilterConditions.cpp
dbms/src/Flash/Coprocessor/FilterConditions.h
dbms/src/Flash/Coprocessor/JoinInterpreterHelper.cpp
dbms/src/Flash/Planner/Plans/PhysicalFilter.cpp
dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp
dbms/src/Storages/tests/gtest_filter_parser.cpp

Use `RepeatedPtrField<tipb::Expr>` instead of `vector<tipb::Expr *>` to reduce useless copy and make code clear.
Tests 
Side effects
Documentation
```release-note
None
```

use RepeatedPtrField<tipb::Expr> instead of vector<tipb::Expr *>

---

dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
dbms/src/Storages/DeltaMerge/File/dtpb/column_file.proto
dbms/src/Storages/DeltaMerge/Remote/DeltaIndexCache.h
dbms/src/Storages/DeltaMerge/Segment.cpp

When there are flush, the delta index is changed. This PR adds a delta index epoch for it, so that read node can know delta index cache is invalidated.

Fix delta index cache

---

dbms/src/Common/FailPoint.cpp
dbms/src/Flash/Executor/PipelineExecutorStatus.cpp
dbms/src/Flash/Executor/PipelineExecutorStatus.h
dbms/src/Flash/Mpp/MPPTunnel.cpp
dbms/src/Flash/Mpp/MPPTunnel.h
dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp
dbms/src/Flash/Pipeline/Schedule/Events/Event.h
dbms/src/Flash/Pipeline/Schedule/Events/PlainPipelineEvent.cpp
dbms/src/Flash/Pipeline/Schedule/Events/PlainPipelineEvent.h
dbms/src/Flash/Pipeline/Schedule/Events/tests/gtest_event.cpp
dbms/src/Flash/Pipeline/Schedule/TaskQueues/FiFOTaskQueue.cpp
dbms/src/Flash/Pipeline/Schedule/TaskQueues/FiFOTaskQueue.h
dbms/src/Flash/Pipeline/Schedule/TaskQueues/TaskQueue.h
dbms/src/Flash/Pipeline/Schedule/TaskQueues/tests/gtest_fifo.cpp
dbms/src/Flash/Pipeline/Schedule/TaskScheduler.cpp
dbms/src/Flash/Pipeline/Schedule/TaskScheduler.h
dbms/src/Flash/Pipeline/Schedule/TaskThreadPool.cpp
dbms/src/Flash/Pipeline/Schedule/TaskThreadPool.h
dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.cpp
dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.h
dbms/src/Flash/Pipeline/Schedule/Tasks/Task.h
dbms/src/Flash/Pipeline/Schedule/WaitReactor.cpp
dbms/src/Flash/Pipeline/Schedule/WaitReactor.h
dbms/src/Flash/Pipeline/Schedule/WaitingTaskList.cpp
dbms/src/Flash/Pipeline/Schedule/WaitingTaskList.h
dbms/src/Flash/Pipeline/Schedule/tests/gtest_task_scheduler.cpp
dbms/src/Operators/Operator.cpp

Issue Number: ref #6518 
- Refactor `Event::scheduleImpl` to avoid potential problems.
- Add `noexcept` for some function of `Task`, `Event` and etc.
- Add random fail points:
```
M(random_tunnel_write_failpoint)                    \
M(random_pipeline_model_task_run_failpoint)         \
M(random_pipeline_model_task_construct_failpoint)   \
M(random_pipeline_model_event_schedule_failpoint)   \
M(random_pipeline_model_event_finish_failpoint)     \
M(random_pipeline_model_operator_run_failpoint)     \
M(random_pipeline_model_cancel_failpoint)
```
Tests 
Side effects
Documentation
```release-note
None
```

Pipeline: add random fail points

---

dbms/src/Common/ProfileEvents.cpp
dbms/src/Common/TiFlashMetrics.h
dbms/src/Encryption/FileProvider.cpp
dbms/src/Flash/Disaggregated/tests/gtest_s3_lock_service.cpp
dbms/src/Server/Server.cpp
dbms/src/Storages/DeltaMerge/File/DMFile.cpp
dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
dbms/src/Storages/S3/MockS3Client.cpp
dbms/src/Storages/S3/MockS3Client.h
dbms/src/Storages/S3/S3Common.cpp
dbms/src/Storages/S3/S3Common.h
dbms/src/Storages/S3/S3Filename.cpp
dbms/src/Storages/S3/S3Filename.h
dbms/src/Storages/S3/S3RandomAccessFile.cpp
dbms/src/Storages/S3/S3RandomAccessFile.h
dbms/src/Storages/S3/S3WritableFile.cpp
dbms/src/Storages/S3/S3WritableFile.h
dbms/src/Storages/S3/tests/gtest_s3file.cpp
dbms/src/Storages/S3/tests/gtest_s3filename.cpp
dbms/src/TestUtils/gtests_dbms_main.cpp

1. This PR adds support for DMFiles reading and writing S3.
2. `S3RandomAccessFile` is similar to `PosixRandomAccessFile`. If you pass a S3 filename to `DMFile::restore` it will automatically read from S3.
3. `S3WritableFile` is similar to `PosixWritableFile`. Theoretically, like `DMFile::restore`, if you pass a S3 filename in `DMFile::create` it will automatically write to S3. 
4. However, in order to ensure atomic visibility of DMFile, currently code DMFile is written to local disk and then uploaded to S3. It still need some adaptation to support writing to S3 directly.
TODO:
Note: **Not support S3 when encryption enabled.**
Tests 
Side effects
Documentation
```release-note
None
```

Storage: DMFile supports read/write from S3.

---

dbms/src/Server/StorageConfigParser.cpp
dbms/src/Server/tests/gtest_storage_config.cpp

Issue Number: close #6827
1. Currently, TiFlash reads access_key_id and secret_access_key from envionment variables.
2. This PR supports reading access_key_id and secret_access_key from configuration, too.
3. In conclusion, after this PR, TiFlash will first read from the environment variables. If access_key_id or secret_access_key is empty, it will read from configuration.
4. Change envionment variables' name:
1. `AWS_ACCESS_KEY_ID` to `ACCESS_KEY_ID`
2. `AWS_SECRET_ACCESS_KEY` to `SECRET_ACCESS_KEY`
Add new configuration:
1. `storage.s3.access_key_id`
3. `storage.s3.secret_access_key`
Tests 
Side effects
Documentation
```release-note
None
```

Support read S3 authentication information from configuration.

---

dbms/src/Core/BlockInfo.cpp
dbms/src/Core/BlockInfo.h

This reverts commit 379eba5f6ae1e9ab587c94539b8ba209e705339a.
Since next TiFlash version is 7.0, it is ok to add some im-compatible changes, so this pr revert #6702
Tests 
Side effects
Documentation
```release-note
None
```

Revert "make tiflash compatible with old version client (#6702)"

---

dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.cpp
dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.h
dbms/src/Storages/Page/V3/CheckpointFile/tests/gtest_file_read_write.cpp
dbms/src/Storages/Page/V3/PageDirectory.cpp
dbms/src/Storages/Page/V3/PageDirectory.h
dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.h
dbms/src/Storages/Page/V3/Universal/tests/gtest_checkpoint.cpp
dbms/src/Storages/StorageDisaggregated.cpp

Add `UniversalPageStorage::dumpIncrementalCheckpoint`.
Tests 
Side effects
Documentation
```release-note
None
```

Add dumpIncrementalCheckpoint utility

---

dbms/src/Server/StorageConfigParser.cpp
dbms/src/Server/StorageConfigParser.h
dbms/src/Server/tests/gtest_storage_config.cpp

1. Envionment variables' name `ACCESS_KEY_ID` and `SECRET_ACCESS_KEY` that are intruduced by  #6933, **looks very general. It can easily conflict with others**.
2. So, rename both `ACCESS_KEY_ID` and `SECRET_ACCESS_KEY` to `S3_ACCESS_KEY_ID` and `S3_SECRET_ACCESS_KEY`. 
Tests 
Side effects
Documentation
```release-note
None
```

Rename env variables of S3 authentication.

---

dbms/src/Flash/Mpp/MPPTunnelSetWriter.cpp

Issue Number: close #6951, caused by #6880
- `TrackedMppDataPacket` in `TrackedMppDataPacketPtr` is mutable. If `local_tracked_packet` and `remote_tracked_packet` share same object, there is also another optional way to copy `remote_tracked_packet` early.
- Use fast path to reduce maximum memory usage
Tests 
Side effects
Documentation
```release-note
None
```

*: fix crash issue 

---

dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.h
dbms/src/Storages/Page/Page.h
dbms/src/Storages/Page/PageDefinesBase.h
dbms/src/Storages/Page/V1/Page.h
dbms/src/Storages/Page/V1/PageFile.cpp
dbms/src/Storages/Page/V2/PageFile.cpp
dbms/src/Storages/Page/V2/tests/gtest_page_file.cpp
dbms/src/Storages/Page/V2/tests/gtest_page_storage_multi_writers.cpp
dbms/src/Storages/Page/V3/BlobStore.cpp
dbms/src/Storages/Page/V3/CheckpointFile/CPWriteDataSource.cpp
dbms/src/Storages/Page/V3/Universal/S3PageReader.cpp

ByteBuffer is:
- Not immutable, where actually it should be immutable
- The name is misleading, does not indicate it has no ownership
- Does not implement standard compare operators, hard to use
- Is not printable by default in google test
- Hard to construct easily
`ByteBuffer` is replaced by `std::string_view`, which is an immutable view to a buffer and does not own the memory of the buffer.
Note: In some places we need a mutable `char *` in order to free the memory later. For such cases, `std::span<char>` is used instead.
Tests 
Side effects
Documentation
```release-note
None
```

Remove ByteBuffer

---

dbms/src/Server/DTTool/DTToolBench.cpp
dbms/src/Server/tests/gtest_dttool.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
dbms/src/Storages/DeltaMerge/DMContext.h
dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_column_file.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_value_space.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment_common_handle.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_replace_data.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h

The PathPool, StoragePool in DMContext may not need when reading from S3.
Meanwhile, when uploading files to S3, physical table id is needed.
Make PathPool, StoragePool an optional pointer in DMContext
Add physical_table_id in DMContext
Remove useless `not_compress`
Tests 
Side effects
Documentation
```release-note
None
```

Make DMContext adapt to remote data provider

---

dbms/src/Core/SpillHandler.cpp
dbms/src/Core/SpillHandler.h
dbms/src/Core/Spiller.cpp
dbms/src/Core/Spiller.h
dbms/src/Core/tests/gtest_spiller.cpp
dbms/src/Interpreters/Aggregator.cpp

release block once it is written to file in SpillHandler
Tests 
Side effects
Documentation
```release-note
None
```

release block earlier in SpillHandler

---

dbms/src/Core/TiFlashDisaggregatedMode.cpp
dbms/src/Core/TiFlashDisaggregatedMode.h
dbms/src/Server/Server.cpp

Issue Number: ref #6882
Rename "tiflash_storage" to "tiflash_write" in configuration, to make sure naming is consistent to documents.
Tests 
Side effects
Documentation
```release-note
None
```

Rename tiflash_storage to tiflash_write

---

dbms/src/Storages/S3/FileCache.cpp

When a segment is initialized, it will create an empty DMFile that contains some empty files.
Tests 
Side effects
Documentation
```release-note
None
```

Storage: File size of DMFile's subfiles can be zero.

---

dbms/src/Columns/ColumnString.h
dbms/src/Columns/IColumn.h
dbms/src/Flash/tests/gtest_spill_aggregation.cpp
dbms/src/Flash/tests/gtest_spill_sort.cpp
dbms/src/Interpreters/Aggregator.cpp
dbms/src/Interpreters/Aggregator.h
dbms/src/TestUtils/mockExecutor.h

1. For aggregation key of a string with not null collator, still fill the string column in `insertKeyIntoColumns`, since it will be used during the restore stage
2. For merge aggregation stage, clear the collator info because the input column is already the `sort_key` of the original column, so don't need to get the sort_key again
3. Add more spill tests on spill agg and spill sort
Tests 
Side effects
Documentation
```release-note
None
```

Add more spill tests and fix bug

---

dbms/src/Interpreters/Settings.h
dbms/src/Server/StorageConfigParser.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetSnapshot.h
dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStore.h
dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.cpp
dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.h
dbms/src/Storages/DeltaMerge/Remote/Proto/remote.proto
dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
dbms/src/Storages/DeltaMerge/Remote/Serializer.h
dbms/src/Storages/StorageDisaggregatedRemote.cpp
dbms/src/TiDB/Etcd/Client.cpp
dbms/src/TiDB/OwnerManager.cpp

Problem Summary: After FastAddPeer (https://github.com/pingcap/tiflash/pull/6987), the data of one TiFlash write node could ingest some data (ColumnFileTiny/DMFile) that is generated by another TiFlash write node. This break the previous consumption. WNs should return the real remote location to the RN so that RN can fetch the data from remote store (e.g. S3) directly.
* Change the checkpoint interval from 60 seconds to 30 seconds
* Serialize the remote key (S3 path) for DMFile to `RemotePb::ColumnFileBig` so that RN can get the correct S3 key for reading
* Note that if a ColumnFileTiny is ingested by FAP and later read by RN,
* Now it is still read by WN at the first time, then written back to WN's UniPS
* When RN receives …

Support disagg read after data ingest by FAP

---

dbms/src/Storages/StorageDisaggregatedRemote.cpp
tests/tidb-ci/new_collation_fullstack/function_collator.test

Currently prepare (delta index) does not have benefits, because we always use a high concurrency to read (in order to migrate the latency of reading from S3), and during the reading the delta index will be built. Thus, our placing delta index step, which is a time consuming step, is already done in parallel.
We may plan to do something more complicated in prepare, for example, trying to prioritise placing delta index for segments that have cached data, so that such segments can start reading as soon as possible. However this optimization may be too complicated and its benefit may be small, considering that actually placing delta index will not cost much time when we have a delta index cache.
I'm a fan of …

Disable prepare stage

---

dbms/src/Storages/DeltaMerge/File/DMFile.cpp
dbms/src/Storages/DeltaMerge/File/DMFile.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp

Issue Number: ref #6825
**Note: this PR will broken the checksum verification of old cluster which has enabled metav2, mainly for cloud native version.**
There are mainly two problems:
First, the default checksums algorithm for DMFile is XX3H. However, tests found that the XX3H algorithm could not support arbitrary incremental checksums like the CRC algorithm. The specific problems are as follows:
```cpp
{
auto digest =  std::make_unique<DB::UnifiedDigest<DB::Digest::CRC32>>();
digest->update("hello", 5);
std::cout << digest->base64() << std::endl;   // Output: hqYQNg==
}
{
auto digest =  std::make_unique<DB::UnifiedDigest<DB::Digest::CRC32>>();
digest->update("h", 1);
digest->update("ello", 4);
std::cout << digest->base64() << std::endl;  // Output: hqYQNg==
}
{
auto …
```

Fix checksums of metav2.

---

dbms/src/Interpreters/Settings.h
dbms/src/Server/Server.cpp
dbms/src/Storages/DeltaMerge/Remote/DisaggSnapshot.cpp
dbms/src/Storages/DeltaMerge/Remote/RNRemoteSegmentThreadInputStream.cpp
dbms/src/Storages/StorageDisaggregatedRemote.cpp

Tests 
Side effects
Documentation
```release-note
None
```

Default enable Delta Index cache for disaggregated read

---

dbms/src/Common/TiFlashMetrics.h
dbms/src/Interpreters/Context.cpp
dbms/src/Interpreters/Context.h
dbms/src/Server/Bootstrap.cpp
dbms/src/Server/Bootstrap.h
dbms/src/Server/CMakeLists.txt
dbms/src/Server/Server.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
dbms/src/Storages/DeltaMerge/File/DMFile.cpp
dbms/src/Storages/DeltaMerge/File/DMFile.h
dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStore.h
dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.cpp
dbms/src/Storages/DeltaMerge/SSTFilesToBlockInputStream.h
dbms/src/Storages/DeltaMerge/SSTFilesToDTFilesOutputStream.cpp
dbms/src/Storages/DeltaMerge/SSTFilesToDTFilesOutputStream.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_fast_add_peer.cpp
dbms/src/Storages/GCManager.cpp
dbms/src/Storages/Page/V3/CheckpointFile/CPDataFileStat.cpp
dbms/src/Storages/Page/V3/Universal/UniversalPageIdFormatImpl.h
dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.cpp
dbms/src/Storages/S3/S3RandomAccessFile.h
dbms/src/Storages/Transaction/ApplySnapshot.cpp

* In the previous PR, when handling ingesting SST/apply snapshot, we put the DMFile to S3 in the `DeltaMergeStore::ingestFiles`, which could be slow because the apply threads is quite limited compared to the predecode threads. This greatly slow down the speed of ingesting snapshot from TiKV/restoring from BR
* Some background services that cause Segment creation could be failed when `store_id` is not inited
* GCManager - background delta-merge and segment-merge
* SchemaSyncService - create a new DeltaMergeStore and its very first segment
* If these services create segment before `store_id` is inited, they will try put some data to S3 with `store_id==0`, which will be deleted by S3GCManager
* Move upload to …

Speedup ingest when S3 is enabled && fix bug caused by store_id not inited

---

dbms/src/Storages/S3/MockS3Client.cpp

clang-15 has deprecated some built-in functions that used by boost string split.
Ignored these warnning in `boost/algorithm/string/split.hpp`.
Tests 
Side effects
Documentation
```release-note
None
```

Fix deprecated warnings of clang-15

---

dbms/src/Flash/Disaggregated/WNEstablishDisaggTaskHandler.cpp
dbms/src/Storages/DeltaMerge/Remote/DisaggSnapshot.cpp
dbms/src/Storages/DeltaMerge/Remote/DisaggSnapshot.h
dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp

Meet following fault in test environment:
```
0x72f0621	faultSignalHandler(int, siginfo_t*, void*) [tiflash+120522273]
libs/libdaemon/src/BaseDaemon.cpp:220
0x7fb576f13420	<unknown symbol> [libpthread.so.0+82976]
0x72ca124	DB::DM::Remote::DisaggReadSnapshot::empty() const [tiflash+120365348]
dbms/src/Storages/DeltaMerge/Remote/DisaggSnapshot.cpp:58
0x7b9fdc5	DB::DM::Remote::WNDisaggSnapshotManager::unregisterSnapshotIfEmpty(DB::DM::DisaggTaskId const&) [tiflash+129629637]
dbms/src/Storages/DeltaMerge/Remote/WNDisaggSnapshotManager.cpp:45
0x7f3f036	DB::FlashService::FetchDisaggPages(grpc::ServerContext*, disaggregated::FetchDisaggPagesRequest const*, grpc::ServerWriter<disaggregated::PagesPacket>*) …
```

Fix race condition for DisaggSnapshot

---

dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
dbms/src/Storages/S3/MockS3Client.cpp
dbms/src/Storages/S3/S3GCManager.cpp
dbms/src/Storages/S3/tests/gtest_s3gcmanager.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/7128
When S3GCManager remove a DMFile stored in S3, it try to scan all sub files of that dmfile and mark them as "tiflash_deleted=true". But we must append a "/" after the key or it will remove unexpect S3 objects of other dmfile.
Removing dmfile with key "s108/data/t_104/dmf_2/meta", "s108/data/t_104/dmf_2/1.mrk", ... should never remove "s108/data/t_104/dmf_27/meta" etc...
```
[2023/03/20 21:34:57.126 +08:00] [DEBUG] [S3LockClient.cpp:114] ["request, address=127.0.0.1:3930 req=data_file_key: \"s108/data/t_104/dmf_2\""] [source="<key=s108/data/t_104/dmf_2,type=MarkDelete>"] [thread_id=15]
[2023/03/20 21:34:57.171 +08:00] [DEBUG] [S3Common.cpp:524] ["listPrefix prefix=lock/s108/t_104/dmf_2.lock_, total_keys=0, …
```

Fix bug for dmfile is remove unexpectly

---

dbms/src/Common/FailPoint.cpp
dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
dbms/src/Flash/Disaggregated/WNEstablishDisaggTaskHandler.cpp
dbms/src/Flash/Mpp/MPPTunnelSetHelper.cpp
dbms/src/Server/Server.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
dbms/src/Storages/DeltaMerge/Remote/DisaggSnapshot.cpp
dbms/src/Storages/DeltaMerge/Remote/DisaggSnapshot.h
dbms/src/Storages/DeltaMerge/Remote/Proto/remote.proto
dbms/src/Storages/DeltaMerge/Remote/RNRemoteSegmentThreadInputStream.cpp
dbms/src/Storages/DeltaMerge/Remote/RNRemoteSegmentThreadInputStream.h
dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_fast_add_peer.cpp
dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.cpp
dbms/src/Storages/S3/MockS3Client.cpp
dbms/src/Storages/S3/S3Common.cpp
dbms/src/Storages/S3/S3Common.h
dbms/src/Storages/S3/S3GCManager.cpp
dbms/src/Storages/S3/tests/gtest_s3gcmanager.cpp

cherry-pick of https://github.com/pingcap/tiflash/pull/7129
New commit since release-7.0: https://github.com/pingcap/tiflash/compare/release-7.0...master. pick some essential crash fixes and correctness fixes
* * *
Issue Number: close https://github.com/pingcap/tiflash/issues/7128
When S3GCManager remove a DMFile stored in S3, it try to scan all sub files of that dmfile and mark them as "tiflash_deleted=true". But we must append a "/" after the key or it will remove unexpect S3 objects of other dmfile.
Removing dmfile with key "s108/data/t_104/dmf_2/meta", "s108/data/t_104/dmf_2/1.mrk", ... should never remove "s108/data/t_104/dmf_27/meta" etc...
```
[2023/03/20 21:34:57.126 +08:00] [DEBUG] [S3LockClient.cpp:114] ["request, address=127.0.0.1:3930 req=data_file_key: …
```

Fix bug for dmfile is remove unexpectly (release-7.0)

---

dbms/src/DataStreams/NonJoinedBlockInputStream.cpp
dbms/src/Interpreters/Join.cpp
dbms/src/Interpreters/Join.h
dbms/src/Interpreters/JoinPartition.cpp
dbms/src/Interpreters/JoinPartition.h

Issue Number: ref #6233, close #7140
The ultimate goal is to move `HashMap/RowsNotInsertToMap` to `JoinPartition`, and this is pr is to move `JoinPartition` to a seperated file.
Tests 
Side effects
Documentation
```release-note
None
```

Move JoinPartition to a seperated file

---

dbms/src/DataStreams/AggregatingBlockInputStream.cpp
dbms/src/DataStreams/MergeSortingBlockInputStream.cpp
dbms/src/Interpreters/Join.cpp

Add an unified restore log for spill to make it easier to detect if spill is triggered in test.
Tests 
Side effects
Documentation
```release-note
None
```

add unified restore log for spill

---

dbms/src/Flash/Coprocessor/TiDBTableScan.cpp
dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
dbms/src/Storages/DeltaMerge/File/DMFileReader.h
dbms/src/Storages/DeltaMerge/LateMaterializationBlockInputStream.cpp

Issue Number: close https://github.com/pingcap/tidb/issues/42555
1. set `partition_table_scan.pushed_down_filter_conditions`
2. seek before read when skip last time
3. `&` with bitmap when filter condition is always true
Tests 
Side effects
Documentation
```release-note
None
```

Storage: should seek before read

---

contrib/aws-cmake/CMakeLists.txt
dbms/src/Storages/S3/S3Common.cpp
dbms/src/Storages/S3/S3Common.h

Issue Number: ref https://github.com/pingcap/tiflash/issues/7157, ref https://github.com/pingcap/tiflash/issues/6827
S3 disagg CN failed to access to S3. But the aws client can access to S3.
Use STSClient to show the `CallerIdentity` when connecting to AWS. It will show some logging as below.
```
[2023/03/25 11:31:35.774 +00:00] [INFO] [S3Common.cpp:381] ["CallerIdentity{UserId:xxx:i-xxx, Account:xxx, Arn:arn:aws:sts::xxx:assumed-role/xxx/i-xxx}"] [thread_id=1]
```
Tests 
Side effects
Documentation
```release-note
None
```

Show CallerIdentity when connect to S3 client

---

dbms/src/Server/Server.cpp
dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.cpp
dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.h
dbms/src/Storages/Page/V3/CheckpointFile/CPManifestFileWriter.cpp
dbms/src/Storages/Page/V3/CheckpointFile/CPManifestFileWriter.h
dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.h
dbms/src/Storages/Page/V3/Universal/tests/gtest_checkpoint.cpp
metrics/grafana/tiflash_summary.json

```
[2023/03/24 08:49:10.532 +00:00] [INFO] [S3GCManager.cpp:149] ["latest manifest, gc_store_id=172 upload_seq=486 key=s172/manifest/mf_486"] [thread_id=14]
[2023/03/24 08:49:10.532 +00:00] [INFO] [S3GCManager.cpp:512] ["Reading manifest, key=s172/manifest/mf_486"] [thread_id=14]
[2023/03/24 08:49:16.765 +00:00] [ERROR] [Exception.cpp:90] ["Code: 49, e.displayText() = DB::Exception: Check prefix_size < MAX_SIZE failed: Expect total message to be < 1GiB, size=1401166563, e.what() = DB::Exception......
```
- Split edits record of checkpoint manifest into multi-parts, 100000 records per part by default.
- By the way, only enable FileCache in compute nodes.
- Also add metrics in of checkpoint durations.
Tests 
Side effects
Documentation …

Split edits record of checkpoint manifest into multi-parts.

---

dbms/src/Common/TiFlashMetrics.h
dbms/src/Interpreters/Settings.h
dbms/src/Server/StorageConfigParser.h
dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStore.h
dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.cpp
dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.h
dbms/src/Storages/S3/S3Common.cpp
dbms/src/Storages/S3/S3Common.h
dbms/src/Storages/S3/S3GCManager.cpp
dbms/src/Storages/S3/S3GCManager.h
dbms/src/Storages/S3/tests/gtest_s3gcmanager.cpp
dbms/src/Storages/Transaction/TMTContext.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/7158
Problem Summary: As issue described. And find `CopyObject` request time out after fixing that problem.
* Add `MetadataDirective::REPLACE` to `CopyObject`
* Delete subkeys of DMFile in parallel to shorten the GC time
* Changed `storage.s3.request_timeout_ms` default to 7 seconds, `storage.s3.max_connections` default to 4096
* S3 GC rewriting CheckpointDataFile cause about 3~4 seconds
* Add some metrics and loggings about S3 GC time comsume
* Add a settings `remote_gc_method` to allow using scan instead of lifecycle for running GC on S3
Tests 
Side effects
Documentation
```release-note
None
```

Fix S3GC is broken on AWS

---

dbms/src/Common/FailPoint.cpp
dbms/src/Server/StorageConfigParser.cpp
dbms/src/Storages/DeltaMerge/Remote/RNRemoteReadTask.cpp
dbms/src/Storages/DeltaMerge/Remote/RNRemoteReadTask.h
dbms/src/Storages/DeltaMerge/Remote/RNRemoteReadTask_fwd.h
dbms/src/Storages/DeltaMerge/Remote/tests/gtest_rn_remote_read_task.cpp
dbms/src/Storages/S3/S3Common.cpp
dbms/src/Storages/S3/S3Common.h
dbms/src/Storages/S3/S3WritableFile.cpp
dbms/src/Storages/StorageDisaggregated.h
dbms/src/Storages/StorageDisaggregatedRemote.cpp
dbms/src/TiDB/Etcd/Client.cpp
dbms/src/TiDB/OwnerManager.cpp
dbms/src/TiDB/tests/gtest_owner_manager.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/7187, ref https://github.com/pingcap/tiflash/issues/6827
<details>
<summary> build a partition table and analyze it </summary>
```
SET @@sql_mode = '';
CREATE TABLE employees  (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
fname VARCHAR(25) NOT NULL,
lname VARCHAR(25) NOT NULL,
store_id INT NOT NULL,
department_id INT NOT NULL
)
PARTITION BY RANGE(id)  (
PARTITION p0 VALUES LESS THAN (5),
PARTITION p1 VALUES LESS THAN (10),
PARTITION p2 VALUES LESS THAN (15),
PARTITION p3 VALUES LESS THAN MAXVALUE
);
INSERT INTO employees VALUES
('', 'Bob', 'Taylor', 3, 2), ('', 'Frank', 'Williams', 1, 2),
('', 'Ellen', 'Johnson', 3, 4), ('', 'Jim', 'Smith', 2, 4),
('', 'Mary', 'Jones', 1, 1), ('', 'Linda', 'Black', 2, 3),
('', …
```

Fix exception thrown when reading from multiple partitions under S3 disagg

---

dbms/src/Storages/Transaction/RegionCFDataBase.cpp
dbms/src/Storages/Transaction/TiKVRecordFormat.h

Issue Number: close #7212
Compatible new field(TXN_SOURCE_PREFIX,LAST_CHANGE_PREFIX)  in write/lock cf with TiKV.
Tests 
Side effects
Documentation
```release-note
None
```

Compatible new field in write/lock cf with TiKV

---

dbms/src/DataStreams/CreatingSetsBlockInputStream.cpp
dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
dbms/src/Flash/Executor/PipelineExecutor.cpp

Issue Number: close #7221
Cancel current running when one of the hash build meet error
Tests 
Add random failpoint tests
Side effects
Documentation
```release-note
None
```

fix potential deadlock in `CreatingSetBlockInputStream`

---

dbms/src/Common/ProfileEvents.cpp
dbms/src/Storages/DeltaMerge/File/DMFileWriter.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
dbms/src/Storages/DeltaMerge/workload/MainEntry.cpp
dbms/src/Storages/S3/MockS3Client.cpp
dbms/src/Storages/S3/PocoHTTPClient.cpp
dbms/src/Storages/S3/S3Common.cpp
dbms/src/Storages/S3/S3Common.h
dbms/src/Storages/S3/S3RandomAccessFile.cpp
dbms/src/Storages/S3/S3RandomAccessFile.h

After using `PocoHTTPClient`:
1. `S3RandomAccessFile::seek` is failed.
2. Occasionally a connection reset by peer occurs.
1. Use `ignore` to replace `seek`.
2. Retry when connection reset by peer occurs.
Tests 
- Run chbenchmark in AWS EC2 and S3.
Side effects
Documentation
```release-note
None
```

Fix S3 file's seek operation and retry when connection reset by peer

---

.gitmodules
dbms/src/Server/StorageConfigParser.h
dbms/src/Storages/DeltaMerge/File/DMFileWriter.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
dbms/src/Storages/Page/V3/Universal/tests/gtest_lock_local_mgr.cpp
dbms/src/Storages/S3/MockS3Client.cpp
dbms/src/Storages/S3/PocoHTTPClient.cpp
dbms/src/Storages/S3/PocoHTTPClient.h
dbms/src/Storages/S3/PocoHTTPClientFactory.cpp
dbms/src/Storages/S3/PocoHTTPClientFactory.h
dbms/src/Storages/S3/S3Common.cpp
dbms/src/Storages/S3/S3Common.h
dbms/src/Storages/S3/S3RandomAccessFile.cpp
dbms/src/Storages/S3/S3RandomAccessFile.h
dbms/src/Storages/S3/tests/gtest_s3file.cpp
dbms/src/Storages/S3/tests/gtest_s3gcmanager.cpp
dbms/src/Storages/Transaction/TMTContext.cpp
dbms/src/TestUtils/TiFlashTestEnv.cpp
dbms/src/TestUtils/TiFlashTestEnv.h
dbms/src/TestUtils/gtests_dbms_main.cpp

Issue Number: ref https://github.com/pingcap/tiflash/issues/7176
The S3::listObjects always return an empty result after https://github.com/pingcap/tiflash/pull/7209. So does some other S3 APIs
* pick https://github.com/ClickHouse/aws-sdk-cpp/commit/41a52d906db0401de841b5985825282f7ad621dc for poco HTTP client stream ends
* pick a part of https://github.com/pingcap/tiflash/pull/7247 to fix the seek operation on S3 file
* fix some issue when testing with local deployed MinIO
* increase the default storage.s3.request_timeout_ms to 30 seconds
* fix a crash cause by `RemoteHostFilter`
* fix a crash cause by cert update when deployed without disagg
```
[2023/04/06 11:32:09.521 +00:00] [ERROR] [BaseDaemon.cpp:376] [########################################] [source=BaseDaemon] …
```

Make poco client can detect stream end correctly

---

dbms/src/DataStreams/CreatingSetsBlockInputStream.cpp
dbms/src/DataStreams/HashJoinProbeBlockInputStream.cpp
dbms/src/DataStreams/HashJoinProbeBlockInputStream.h
dbms/src/DataStreams/NonJoinedBlockInputStream.cpp
dbms/src/Interpreters/Join.cpp
dbms/src/Interpreters/Join.h

There are two kinds of data race
- When `Join::cancel()` is called when some threads are wait on `Join::waitUntilAllBuildFinished`, the waiting threads will be waken up, and begin reading from hash table while some build threads are still inserting data into the same hash table
- When a right outer join spill is triggered, and `Join::cancel()` is called when some threads are wait on `Join::waitUntilAllBuildFinished`, the waiting threads will be waken up, and call `Join::finishOneNonJoin` at the end, and inside `Join::finishOneNonJoin`, it will clear the hash map, at the same time, it is possible that other threads are still accessing that hash map.
1. Only clear hash map if there is no active build/probe threads
2. For Join Probe, return empty …

Fix data race in join when `Join::cancel()` is called

---

dbms/src/Storages/S3/FileCache.cpp

Add file size to metrics when tiflash restart.
Tests 
- Restart TiFlash and check the metrics.
Side effects
Documentation
```release-note
None
```

Fix metrics of FileCache used size.

---

dbms/src/DataStreams/NonJoinedBlockInputStream.cpp
dbms/src/DataStreams/NonJoinedBlockInputStream.h
dbms/src/Interpreters/Join.cpp
dbms/src/Interpreters/Join.h
dbms/src/Interpreters/JoinHashTable.h
dbms/src/Interpreters/JoinPartition.cpp
dbms/src/Interpreters/JoinPartition.h
dbms/src/Interpreters/JoinUtils.cpp
dbms/src/Interpreters/JoinUtils.h
dbms/src/Interpreters/NullAwareSemiJoinHelper.cpp
dbms/src/Interpreters/NullAwareSemiJoinHelper.h

1. move hash map to `JoinPartition`
2. move all the insert/probe hash table code to `JoinPartition`
3. refine `NonJoinedBlockInputStream` so it now read non joined data based on `JoinPartition`
blocked by #7127
Tests 
Side effects
Documentation
```release-note
None
```

Move maps to join partition

---

dbms/src/Storages/StorageDisaggregatedRemote.cpp

Drop regions when retry for partitioned table scan.
Tests 
```sql
create table t1(id int, age int, key(id)) partition by range(id) (
partition p0 values less than (100),
partition p1 values less than (200),
partition p2 values less than (300),
partition p3 values less than (400));
insert into t1 values (1, 10);
insert into t1 values (10, 10);
alter table t1 set tiflash replica 1;
set @@session.tidb_isolation_read_engines='tiflash';
set @@session.tidb_partition_prune_mode = 'dynamic';
analyze table t1;
select * from information_schema.tiflash_replica;
select count(*) from t1 where id < 150;
-- Trigger a region ver change manually
split table t1 by (4), (7);
select count(*) from t1 where id < 150;
```
Side …

Region retry for partitioned table in disaggrgated read

---

dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
dbms/src/Flash/Coprocessor/DAGUtils.cpp
dbms/src/Flash/Coprocessor/DAGUtils.h
dbms/src/Storages/StorageDeltaMerge.cpp

Issue Number: ref #5829 
Tests 
Side effects
Documentation
```release-note
None
```

fix `columns_to_read` contains `_tidb_rowid`

---

dbms/src/Interpreters/Join.cpp
dbms/src/Interpreters/JoinUtils.cpp
dbms/src/Interpreters/JoinUtils.h

Currently, for each `Join::doJoinBlockHash`, it will do some preparations before call `JoinPartition::probeBlock`, if split happens, these preparations are redundant if the input block is unchanged.
Refine code to avoid redundant calculation when join probe split happens
Tests 
Side effects
Documentation
```release-note
None
```

refine code to avoid redundant calculation when join probe split happens

---

dbms/src/Flash/EstablishCall.cpp
dbms/src/Flash/EstablishCall.h
dbms/src/Flash/FlashService.cpp
dbms/src/Flash/FlashService.h
dbms/src/Flash/Mpp/MPPTaskManager.cpp

When try to find the root cause of #7294, I found if `EstablishCallData::writeDone` is called, it will be more convenient to log it's query/connection info even if the current connection is not connected.
- Try to log information in `EstablishCallData::writeDone` even if the EstablishCallData is not connected.
- Log tunnel info when `FindTunnel` failed.
Tests 
Side effects
Documentation
```release-note
None
```

Refine establish log

---

release-centos7-llvm/Makefile
release-centos7-llvm/env/Makefile

`podman` is a default placement for `docker` under rocky linux 9.
Define the docker binary by `DOCKER ?= docker` in some Makefiles, so that we can run by `DOCKER=podman make build_tiflash_release_amd64`
Tests 
Side effects
Documentation
```release-note
None
```

Support using podman to replace docker in some build scripts

---

dbms/src/Debug/MockExecutor/JoinBinder.h
dbms/src/Flash/tests/gtest_join_executor.cpp
dbms/src/Interpreters/Join.cpp

1. add more tests for cross join
2. refine `CrossJoinAdder`, so only `Cross_Anti` join will use `is_row_matched` and only `strictness == All` will use `expanded_row_size_after_join`
Tests 
Side effects
Documentation
```release-note
None
```

Add more cross join tests, refine `CrossJoinAdder`

---

dbms/src/Storages/S3/S3RandomAccessFile.cpp

Issue Number: ref #7312 
Check read content length of S3 file.
Tests 
- Run chbenchmark.
- TP workload: `tiup bench ch --warehouses 1500 -T 20 -t 0 --time 100h --ignore-error -H 127.0.0.1 -P 4000 -D chbenchmark run`
- AP workload: `tiup bench ch --warehouses 1500 -T 0 -t 2 --time 100h  -H 127.0.0.1 -P 4000 -D chbenchmark --ignore-error  run`
Side effects
Documentation
```release-note
None
```

Check read content length of S3 file.

---

dbms/src/Functions/FunctionsGrouping.h

Issue Number: close https://github.com/pingcap/tiflash/issues/7134
Problem Summary: release build is broken caused by https://github.com/pingcap/tiflash/pull/7135
```
[2023-04-21T14:30:11.625Z] In file included from /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Functions/FunctionsGrouping.cpp:16:
[2023-04-21T14:30:11.625Z] /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Functions/FunctionsGrouping.h:39:13: error: unused function 'isPowerOf2' [-Werror,-Wunused-function]
[2023-04-21T14:30:11.625Z] static bool isPowerOf2(uint64_t num)
[2023-04-21T14:30:11.625Z]             ^
[2023-04-21T14:30:11.625Z] 1 error generated.
```
Add `[[maybe_unused]]`
Tests 
Side effects
Documentation
```release-note
None
```

Fix build under release mode

---

dbms/src/Common/FailPoint.cpp
dbms/src/IO/MemoryReadWriteBuffer.cpp
dbms/src/Storages/Page/V3/Blob/BlobStat.h
dbms/src/Storages/Page/V3/BlobStore.cpp
dbms/src/Storages/Page/V3/BlobStore.h
dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
dbms/src/Storages/Transaction/RegionPersister.cpp
dbms/src/Storages/Transaction/tests/gtest_region_persister.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/7316
The root cause is `BlobStore<Trait>::handleLargeWrite` get a buffer from `MemoryWriteBuffer` and access the memory by `write.size`, which exceed the memory bound. `MemoryWriteBuffer` actually is composed by a list of `chunk`s
https://github.com/pingcap/tiflash/blob/b2b976edbe33b4bb130d9abff44948877d86cda5/dbms/src/Storages/Page/V3/BlobStore.cpp#L190-L216
The write batch data size is large, we do NOT copy the data into a temporary buffer in order to make the memory usage of tiflash more smooth. Instead, we process the data in ReadBuffer in a streaming manner.
Tests 
Side effects
Documentation
```release-note
Fix a crash issue when tiflash persists the data of a large Region
```

Fix large write cause tiflash crash

---

dbms/src/Functions/FunctionsTiDBConversion.h
dbms/src/Functions/tests/gtest_tidb_conversion.cpp

Issue Number: close #7348
Accoring to TiDB's implementation, truncate in cast decimal as decimal should be always treated as a warning instead of error.
https://github.com/pingcap/tidb/blob/96fa4692b09b43ae587ea449e5891a9d9fd6e5c8/types/datum.go#L1512-L1519
Tests 
Side effects
Documentation
```release-note
None
```

truncate should always be treated as warning in cast decimal as decimal

---

dbms/src/Functions/FunctionsGrouping.h
dbms/src/Storages/Page/V3/PageDirectory.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/7290
`iter`, `iter->first`, `iter->second` will be all invalidated when iter is erased:
```c++
int main() {
std::map<int, int> a;
a.emplace(1, 2);
auto it = a.find(1);
a.erase(1);
std::cout << it->second << std::endl;
return 0;
}
==36182==ERROR: AddressSanitizer: heap-use-after-free on address 0x000105600cb0 at pc 0x0001025d5dac bp 0x00016d82b2b0 sp 0x00016d82b2a8
READ of size 4 at 0x000105600cb0 thread T0
#0 0x1025d5da8 in main main.cpp:22
#1 0x102971084 in start+0x200 (dyld:arm64+0x5084) (BuildId: fbb89662e6f23434b542f75185ac5e7432000000200000000100000000030c00)
#2 0xb308fffffffffffc  (<unknown module>)
```
Thus we must only access iter inside a lock.
Tests 
Side effects
Documentation
```release-note
None
```

storage: Fix UAFs in PageStorage

---

dbms/src/Common/FailPoint.cpp
dbms/src/Common/FailPoint.h
dbms/src/Common/TiFlashMetrics.h
dbms/src/IO/MemoryReadWriteBuffer.cpp
dbms/src/Storages/Page/V3/Blob/BlobStat.h
dbms/src/Storages/Page/V3/BlobStore.cpp
dbms/src/Storages/Page/V3/BlobStore.h
dbms/src/Storages/Page/V3/PageDirectory.cpp
dbms/src/Storages/Page/V3/PageStorageImpl.cpp
dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
dbms/src/Storages/Transaction/RegionPersister.cpp
dbms/src/Storages/Transaction/tests/gtest_region_persister.cpp
dbms/src/TestUtils/TiFlashTestEnv.cpp
dbms/src/TestUtils/TiFlashTestEnv.h

Manual cherry-pick of https://github.com/pingcap/tiflash/pull/7335
* * *
Issue Number: close https://github.com/pingcap/tiflash/issues/7316
The root cause is `BlobStore<Trait>::handleLargeWrite` get a buffer from `MemoryWriteBuffer` and access the memory by `write.size`, which exceed the memory bound. `MemoryWriteBuffer` actually is composed by a list of `chunk`s
https://github.com/pingcap/tiflash/blob/b2b976edbe33b4bb130d9abff44948877d86cda5/dbms/src/Storages/Page/V3/BlobStore.cpp#L190-L216
The write batch data size is large, we do NOT copy the data into a temporary buffer in order to make the memory usage of tiflash more smooth. Instead, we process the data in ReadBuffer in a streaming manner.
Tests 
Side effects
Documentation
```release-note
Fix a crash issue when …
```

Fix large write cause tiflash crash (release-6.5)

---

dbms/src/Flash/Executor/DataStreamExecutor.cpp
dbms/src/Flash/Executor/PipelineExecutor.cpp
dbms/src/Flash/Executor/PipelineExecutor.h
dbms/src/Flash/Executor/PipelineExecutorStatus.cpp
dbms/src/Flash/Executor/PipelineExecutorStatus.h
dbms/src/Flash/Executor/ResultHandler.h
dbms/src/Flash/Executor/tests/gtest_pipeline_executor_status.cpp
dbms/src/Flash/Pipeline/Exec/tests/gtest_simple_operator.cpp
dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp
dbms/src/Flash/Pipeline/Schedule/Events/Event.h
dbms/src/Flash/Pipeline/Schedule/Events/FineGrainedPipelineEvent.cpp
dbms/src/Flash/Pipeline/Schedule/Events/FineGrainedPipelineEvent.h
dbms/src/Flash/Pipeline/Schedule/Events/PlainPipelineEvent.cpp
dbms/src/Flash/Pipeline/Schedule/Events/PlainPipelineEvent.h
dbms/src/Flash/Pipeline/Schedule/Events/tests/gtest_event.cpp

Issue Number: ref #6518  close #7361
- If task creation fails and one task has already been successfully created, the task that has been created will be destructed in `scheduleImpl`. This will trigger `onTaskFinish`, leading to unexpected problems.
- refine the code of `scheduleImpl` and use `Event::tasks` to hold the tasks that ready to be scheduled.
Tests 
Side effects
Documentation
```release-note
None
```

Pipeline: Fix crash for `random_pipeline_model_task_construct_failpoint`

---

dbms/src/Flash/Disaggregated/RNPageReceiver.cpp
dbms/src/Functions/FunctionsGrouping.h
dbms/src/Storages/DeltaMerge/Remote/RNRemoteReadTask.h

Issue Number: close https://github.com/pingcap/tiflash/issues/7303
We increase the total task counter **before** (instead of **after**) pushing to the queue, because the task may be consumed immediately after we pushing to the queue.
Tests 
Side effects
Documentation
```release-note
None
```

storage: Fix counter race in disaggregated mode

---

dbms/src/Common/TiFlashMetrics.h
dbms/src/Storages/S3/S3RandomAccessFile.cpp

Issue Number: ref #7354
```
[2023/04/23 20:14:45.180 +08:00] [DEBUG] [PocoHTTPClient.cpp:200] ["Make request"] [source="URI=http://minio-peer:9000/cse-keyspace/cluster1_data/s8/data/t_2686/dmf_1480/8.dat pool=true"] [thread_id=471]
[2023/04/23 20:14:45.180 +08:00] [DEBUG] [PocoHTTPClient.cpp:331] ["connect cost 0ms"] [source="URI=http://minio-peer:9000/cse-keyspace/cluster1_data/s8/data/t_2686/dmf_1480/8.dat pool=true"] [thread_id=471]
[2023/04/23 20:14:45.180 +08:00] [DEBUG] [PocoHTTPClient.cpp:350] ["Receiving response..."] [source="URI=http://minio-peer:9000/cse-keyspace/cluster1_data/s8/data/t_2686/dmf_1480/8.dat pool=true"] [thread_id=471]
[2023/04/23 20:14:45.191 +08:00] [DEBUG] [PocoHTTPClient.cpp:361] ["Response status: 206, Partial Content"] …
```

Retry when 'Resource temporarily unavailable'

---

dbms/src/Storages/StorageDeltaMerge.cpp
tests/fullstack-test/mpp/late_materialization_generate_column.test

ref #6518Signed-off-by: Lloyd-Pottiger <yan1579196623@gmail.com>### What problem does this PR solve?
Issue Number: close #7383 #7385
when there are generated columns, the size of `columns_to_read` is less than `table_column_infos`, due to `table_column_infos` contains generated columns. So the order of columns changes, causing build filter incorrectly.
Add generated columns to analyzer.
Tests 
Side effects
Documentation
```release-note
None
```

[cherry-pick 7386] fix lm query fail when there are generated columns

---

dbms/src/DataStreams/ScanHashMapAfterProbeBlockInputStream.cpp
dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
dbms/src/Flash/Coprocessor/JoinInterpreterHelper.cpp
dbms/src/Flash/Coprocessor/JoinInterpreterHelper.h
dbms/src/Flash/tests/gtest_join_executor.cpp
dbms/src/Interpreters/Join.cpp
dbms/src/Interpreters/JoinPartition.cpp
dbms/src/Interpreters/JoinPartition.h
dbms/src/Interpreters/JoinUtils.h
tests/fullstack-test/mpp/right_join.test

Issue Number: ref #7280 
Add support for RightOuter kind join with other conditions, and do a little refact:
1. Add a new "RowFlaggedHashMapAdder" for RightSemi/RightAnti/RightOuter joins with other conditions
2. Add 'row_flagged_map' template parameter to simplify some logics
Tests 
Side effects
Documentation
```release-note
None
```

Support right outer join with other conditions

---

dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
dbms/src/Storages/StorageDeltaMerge.cpp
tests/fullstack-test/mpp/late_materialization_generate_column.test

Signed-off-by: Lloyd-Pottiger <yan1579196623@gmail.com>### What problem does this PR solve?
Issue Number: close #7383 close #7385
when there are generated columns, the size of `columns_to_read` is less than `table_column_infos`, due to `table_column_infos` contains generated columns. So the order of columns changes, causing build filter incorrectly.
Add generated columns to analyzer.
Tests 
Side effects
Documentation
```release-note
None
```

fix lm query fail when there are generated columns

---

dbms/src/Flash/EstablishCall.cpp
dbms/src/Flash/FlashService.cpp
dbms/src/Flash/Mpp/ExchangeReceiver.cpp
dbms/src/Flash/Mpp/GRPCReceiverContext.cpp
dbms/src/Flash/Mpp/LocalRequestHandler.h
dbms/src/Flash/Mpp/MPPTask.cpp
dbms/src/Flash/Mpp/MPPTunnel.h

For both sync tunnel and async tunnel, when a tunnel is finished, there is a info log to record the tunnel cost time, but for local tunnel, there is no such logs, this pr add this log for local tunnel.
Tests 
Side effects
Documentation
```release-note
None
```

add info log to log tunnel time for local tunnel

---

dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp
dbms/src/Flash/Pipeline/Schedule/Events/Event.h
dbms/src/Flash/Pipeline/Schedule/Events/tests/gtest_event.cpp
dbms/src/Flash/Pipeline/Schedule/TaskScheduler.h

Issue Number: close #7409
In the original implementation, `output->addInput` may be called by multiple threads, leading to data race issues.
Here we change 
```
/// eventA───────►eventB ===> eventA─────────────►eventB
///                             │                    ▲
///                             └────►insert_event───┘
```
to
```
/// eventA───────►eventB ===> eventA───►insert_event───►eventB
```
, so that it will not cause data race issues.
Tests 
Side effects
Documentation
```release-note
None
```

Tsan: fix data race on `Event::insertEvent`

---

dbms/src/Common/ProfileEvents.cpp
dbms/src/Common/TiFlashMetrics.h
dbms/src/Storages/S3/S3Common.cpp
metrics/grafana/tiflash_summary.json

- Currently, both uploading checkpoints and dmfiles are using `S3 PutObject`.
- But the difference between checkpoints and dmfiles is quite significant, separating metics is helpful when we need to locate  problems.
- Add metrics: 
- `S3WriteDMFileBytes`
- `S3PutDMFile` ops
- `S3PutDMFileRetry` ops
- `put_dmfile` duration
Tests 
Side effects
Documentation
```release-note
None
```

Refine metrics of uploading DMFile.

---

dbms/src/Flash/Coprocessor/CHBlockChunkCodecV1.cpp

Issue Number: close #7416 
Tests 
Side effects
Documentation
```release-note
Fix the issue that the query might use much larger memories than actual needed when Join build side data is very large and contains many small-size string type columns. 
```

Donot reserve memory for non-fixed type columns in decodeAndSquash

---

dbms/src/Columns/ColumnAggregateFunction.cpp
dbms/src/Columns/IColumn.h
dbms/src/Core/tests/gtest_block.cpp
dbms/src/DataStreams/MergeSortingBlockInputStream.cpp
dbms/src/Interpreters/JoinPartition.cpp
dbms/src/Operators/LocalSortTransformOp.cpp

Issue Number: close #7417
use `Block::estimateByteSizeForSpill` to estimate block memory usage in spill
Tests 
Side effects
Documentation
```release-note
None
```

use `Block::estimateByteSizeForSpill` to estimate block memory in spill

---

tests/fullstack-test/mpp/having.test
tests/fullstack-test/mpp/late_materialization_generate_column.test
tests/fullstack-test/mpp/left_semi_family_joins.test
tests/fullstack-test/mpp/mpp_fail.test

Issue Number: close #7428
The root cause is here is some random internal mpp query generated by auto analyze, and the fix is drop useless table to so not to trigger auto analyze job.
Tests 
Side effects
Documentation
```release-note
None
```

make mpp_fail test stable

---

dbms/src/Flash/Mpp/MPPTask.cpp
dbms/src/Flash/Mpp/MPPTask.h

Issue Number: close #7432
Tests 
Side effects
Documentation
```release-note
None
```

Tsan: fix data race on `ComputeServerRunner.cancelJoinTasks`

---

dbms/src/Flash/Coprocessor/GenSchemaAndColumn.cpp
dbms/src/Storages/StorageDisaggregated.cpp
dbms/src/Storages/StorageDisaggregated.h
dbms/src/Storages/StorageDisaggregatedRemote.cpp
dbms/src/Storages/Transaction/TypeMapping.cpp
dbms/src/Storages/Transaction/TypeMapping.h

Issue Number: close #7414
View duration type as int64 to read, and add an extra cast after read.
Tests 
```
./bin/tiup-playground nightly --mode=tidb-disagg --disagg.s3_endpoint=xxxx:xxx --tiflash.binpath ../tiflash/tiflash/tiflash
```
```
create table if not exists test.t(a time(4));
insert into test.t values('700:10:10.123456');
insert into test.t values('-700:10:10.123456');
alter table test.t set tiflash replica 1;
set tidb_isolation_read_engines='tiflash'; select a from t;
set tidb_isolation_read_engines='tiflash'; select hour(a) from t;
create table t1(t varchar(100));
insert into test.t1 values('700:10:10.123456');
set tidb_isolation_read_engines='tiflash'; select t from t1;
set tidb_isolation_read_engines='tiflash'; select hour(t) from t1;
```
Side effects …

Fix read duration type column failed in disaggregated mode

---

dbms/src/Flash/Mpp/AsyncRequestHandler.h
dbms/src/Flash/Mpp/ExchangeReceiver.cpp
dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp
dbms/src/Flash/Pipeline/Schedule/Tasks/Task.cpp

Issue Number: close #7498
Tests 
Side effects
Documentation
```release-note
None
```

Add info for ExchangeReceiver logs

---

dbms/src/Columns/ColumnNullable.cpp
dbms/src/Columns/ColumnNullable.h
dbms/src/Columns/ColumnString.cpp
dbms/src/Columns/ColumnString.h
dbms/src/Columns/IColumn.h
dbms/src/Core/Block.cpp
dbms/src/Core/Block.h
dbms/src/Core/tests/gtest_block.cpp

Issue Number: ref #7495
As the issue described.
- Add a new function `reserveWithTotalMemoryHint` to IColumn
- Use `reserveWithTotalMemoryHint` to reserve memory in `vstackBlocks` for non-fixed-size column
Tests 
Side effects
Documentation
```release-note
None
```

Add `reserveWithTotalMemoryHint` to IColumn

---

dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
dbms/src/Flash/Coprocessor/DAGStorageInterpreter.h
dbms/src/Storages/StorageDeltaMerge.cpp
dbms/src/Storages/StorageDisaggregated.cpp

The logic of appendExtraCastsAfterTS is kind of mess now, which means it is hard to understand.
1. remove `ExtraCastAfterTSMode`
2. use a `std::vector<bool>` to record the columns may need to add a cast.
3. judge which really need to add cast in `DAGExpressionAnalyzer::buildExtraCastsAfterTS` uniformly
Tests 
Side effects
Documentation
```release-note
None
```

*: refine appendExtraCastsAfterTS

---

dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
dbms/src/Storages/S3/S3RandomAccessFile.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/7513
The segment delta index on wn is useless now. But it introduces high CPU and high S3 read-write flow after restart. And now wn could serve much more data than the coupled arch.
We should disable the segment place index under disagg arch.
Only generate place index tasks after restart when deployed with coupled arch
Tests 
Side effects
Documentation
```release-note
None
```

Reduce unnecessary S3 read flow after restart

---

dbms/src/Flash/Coprocessor/DAGContext.cpp
dbms/src/Flash/Coprocessor/DAGContext.h
dbms/src/Flash/Coprocessor/DAGDriver.cpp
dbms/src/Flash/Mpp/MPPTask.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.h
dbms/src/Storages/DeltaMerge/ScanContext.h
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h
dbms/src/Storages/DeltaMerge/StableValueSpace.cpp

Issue Number: ref #7491
In order to calculate the number of 'RU' used by a query, TiFlash need to return `read bytes` to TiDB.
- Add `total_user_read_bytes` in `ScanContext`.
- Calculate 'read bytes' after compression.
- Calculate `total_user_read_bytes` in `ConcatSkippableBlockInputStream` for `StableValueSpace`.
- Calculate `total_user_read_bytes` in `ColumnFileSetReader` for `DeltaValueSpace`.
- Since the flow control method of TiDB is not suitable for large queries like TiFlash, the RU of TiFlash is not considered for transmission to TiDB to participate in flow control. And just report to Prometheus directly.
Tests 
Side effects
Documentation
```release-note
None
```

Add total_user_read_bytes in ScanContext and report read RU

---

dbms/src/Storages/DeltaMerge/workload/DTWorkload.cpp

Issue Number: close #7548
Previously, PSv3 maintained a maximum ID internally during runtime, but maintaining this maximum ID during uniPS runtime was costly, so it was changed to calculating the maximum ID during restart.
Initialize global storage pool every time before creating DeltaMergeStore.
Tests 
- Run `./tiflash dtworkload --testing_type=daily_perf`
- Output:
```
Date,Table Schema,Workload,Init Seconds,Write Speed(rows count),Read Speed(rows count)
20230530,constant,uniform,0.01,438180,5796247
20230530,constant,normal,0.01,455697,2331561
20230530,constant,incremental,0.01,215553,4877337
```
Side effects
Documentation
```release-note
None
```

DTWorkload: initialize global storage pool every time before creating DeltaMergeStore.

---

dbms/src/Storages/Transaction/TiKVRecordFormat.cpp
dbms/src/Storages/Transaction/TiKVRecordFormat.h

Issue Number: close #7563
Due to https://github.com/pingcap/tidb/issues/43540, tikv propose a fix that introduce a new flag F that shall be filtered by TiFlash.
The new flag is to persist a special state that guides tikv how to resolve locks.
Tests 
Side effects
Documentation
```release-note
None
```

Filter lock flag 'F'

---

dbms/src/Storages/StorageDisaggregatedRemote.cpp
dbms/src/Storages/Transaction/FastAddPeer.cpp

Issue Number: close #7301
Mainly changes are in https://github.com/tikv/client-c/pull/144 
* Try to use non-pending peer for TiFlash queries
* If any pending peer exists, each time build mpp task will invalid the region cache and retry to get the latest RegionInfo next time access to that Region
* If all peers are pending, fallback to send request to all stores
Tests 
Side effects
Documentation
```release-note
None
```

update client-c to support choosing non pending peer when dispatch task

---

metrics/grafana/tiflash_summary.json

Issue Number: ref #7491
Modifications of tiflash_summary.json is forgotten in PR https://github.com/pingcap/tiflash/pull/7571.
Tests 
Side effects
Documentation
```release-note
None
```

Add metrics of RU to grafana.

---

dbms/src/Flash/Mpp/MPPTaskId.cpp
dbms/src/Flash/Mpp/MPPTaskId.h
dbms/src/Flash/Mpp/MPPTaskManager.cpp
dbms/src/Flash/Mpp/MPPTaskManager.h
dbms/src/Flash/Mpp/MinTSOScheduler.cpp
dbms/src/Flash/Mpp/tests/gtest_aborted_mpp_gather_cache.cpp
dbms/src/Flash/Mpp/tests/gtest_cancelled_mpp_gather_cache.cpp
dbms/src/Flash/tests/gtest_compute_server.cpp
dbms/src/TestUtils/MPPTaskTestUtils.cpp
dbms/src/TestUtils/MPPTaskTestUtils.h

Issue Number: ref #7587, close #6727
When TiDB cancel a mpp query, there is a chance that the `cancel` is lost:
| time | TiDB | TiFlash |
|-----|------|---------|
| t1 | Send Disptach MPPTask to TiFlash| Dispatch request is not received yet |
| t2 | Send CancelMPPTask request to TiFlash| Received CancelMPPTask, and found nothing to cancel |
| t3 |   | Receive Dispatch request of t1, then the cancel is lost | 
This pr add a `AbortedMPPGatherCache` to avoid this cancel lost
Tests 
Side effects
Documentation
```release-note
None
```

Fix "lost cancel" for mpp query

---

dbms/src/Flash/Disaggregated/WNEstablishDisaggTaskHandler.cpp
dbms/src/Server/StorageConfigParser.h
dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.h
dbms/src/Storages/DeltaMerge/Remote/RNReadTask.cpp
dbms/src/Storages/DeltaMerge/Remote/RNReadTask.h
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
dbms/src/Storages/StorageDisaggregatedRemote.cpp

Issue Number:  ref https://github.com/pingcap/tiflash/issues/7576, ref https://github.com/pingcap/tiflash/issues/7605
* Add some logging to locate the bug of #7576
* Disable `storage.s3.enable_http_pool` by default to workaround #7605
Tests 
Side effects
Documentation
```release-note
None
```

Add some logging for locating bug

---

dbms/src/Flash/FlashService.cpp
dbms/src/Flash/executeQuery.cpp
dbms/src/Operators/SharedQueue.h
dbms/src/Server/Server.cpp

Issue Number: ref #6518 
- Initialize the pipeline task scheduler by default, and then `enable_pipeline` and `enforce_enable_pipeline` can take effect immediately without restarting the tiflash process.
- The three groups of threads in pipeline task scheduler(WaitReactor, CPU/IO Task Thread Pool) are blocked when no tasks are submitted, the cpu utilization rates are 0, and the default total number of threads is `1 + 2 * cpu core num`, so the impact of the default Initializing is small.
from https://github.com/pingcap/tiflash/pull/7584
- support set `enable_pipeline` from tidb, related to https://github.com/pingcap/tidb/pull/44467
Tests 
Side effects
Documentation
```release-note
None
```

Initialize the pipeline task scheduler by default

---

dbms/src/Columns/ColumnFixedString.cpp
dbms/src/Columns/ColumnNullable.h
dbms/src/Columns/ColumnVector.h
dbms/src/DataStreams/NativeBlockInputStream.cpp
dbms/src/DataTypes/DataTypeNumberBase.cpp
dbms/src/Functions/FunctionsGrouping.h
dbms/src/Functions/FunctionsString.cpp
dbms/src/Interpreters/Aggregator.h
dbms/src/Storages/DeltaMerge/convertColumnTypeHelpers.cpp

resize_fill() with initializer uses std::fill() which is a loop over all
elements, while resize_fill() without argument uses memset().
Tests 
Side effects
Documentation
```release-note
None
```

*: call PODArray::resize_fill(size_t n) instead of resize_fill(size_t n, 0)

---

dbms/src/Common/FailPoint.cpp
dbms/src/Common/FailPoint.h
dbms/src/DataStreams/ExchangeSenderBlockInputStream.cpp
dbms/src/DataStreams/IProfilingBlockInputStream.cpp
dbms/src/Flash/Coprocessor/DAGResponseWriter.h
dbms/src/Flash/Executor/DataStreamExecutor.cpp
dbms/src/Flash/Executor/QueryExecutor.cpp
dbms/src/Flash/Mpp/MPPHandler.cpp
dbms/src/Flash/Mpp/MPPTask.cpp
dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.cpp
dbms/src/Flash/tests/gtest_compute_server.cpp
dbms/src/Operators/ExchangeSenderSinkOp.cpp
tests/fullstack-test/mpp/mpp_fail.test
tests/sanitize/tsan.suppression

Issue Number: close #7626
- ignore data race of `Failpoint` and `BlockStreamProfileInfo`
- https://github.com/pingcap/tiflash/issues/7631
- add todo to fix the data race on `BlockStreamProfileInfo`
- move failpoint `exception_during_mpp_non_root_task_run`, `exception_during_mpp_root_task_run` and `hang_in_execution` to more suitable positions.
- add failpoint `exception_during_query_run`
Tests 
Side effects
Documentation
```release-note
None
```

Tsan: fix data race on `ComputeServerRunner`

---

dbms/src/Common/tests/gtest_threaded_worker.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/7653
Problem Summary: `ThreadedWorker.ErrorInWorkerWithNonEmptyQueue` is not stable
Because the test workers concurrency is 2, there could be a chance that some new result is pushed into the result_queue before exception cancel all the wokers.
As long as the queue is cancelled before all elements are handled, consider this test passed. 
Tests 
Side effects
Documentation
```release-note
None
```

Fix unstable unittest `ThreadedWorker.ErrorInWorkerWithNonEmptyQueue`

---

dbms/src/Common/TiFlashMetrics.h
dbms/src/Debug/dbgQueryExecutor.cpp
dbms/src/Flash/Mpp/ExchangeReceiver.cpp
dbms/src/Flash/Mpp/LocalRequestHandler.h
dbms/src/Flash/Mpp/MPPTask.cpp
dbms/src/Flash/Mpp/MPPTask.h
dbms/src/Flash/Mpp/MPPTaskManager.cpp
dbms/src/Flash/Mpp/MPPTaskManager.h
dbms/src/Flash/Mpp/MPPTunnel.cpp
dbms/src/Flash/Mpp/MPPTunnel.h
dbms/src/Flash/Mpp/TrackedMppDataPacket.h
dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
dbms/src/Flash/executeQuery.cpp
dbms/src/Interpreters/ProcessList.cpp
dbms/src/Interpreters/ProcessList.h
dbms/src/Interpreters/executeQuery.cpp
dbms/src/Interpreters/executeQuery.h

Issue Number: close #7643
- Introduce query level processListEntry for mpp query, so all the mpp tasks belong to the same mpp query will share the same processListEntry(and the same memory_tracker)
- Remove `switchMemTracker` for local tunnel since the memory tracker is now the same in source mpp task and target mpp task. 
- Disable local tunnel in ut if sender task is the root task
Tests 
Side effects
Documentation
```release-note
None
```

Introduce mpp query level processListEntry

---

dbms/src/Common/TiFlashMetrics.h
dbms/src/Debug/dbgQueryExecutor.cpp
dbms/src/Flash/Mpp/ExchangeReceiver.cpp
dbms/src/Flash/Mpp/LocalRequestHandler.h
dbms/src/Flash/Mpp/MPPTask.cpp
dbms/src/Flash/Mpp/MPPTask.h
dbms/src/Flash/Mpp/MPPTaskManager.cpp
dbms/src/Flash/Mpp/MPPTaskManager.h
dbms/src/Flash/Mpp/MPPTunnel.cpp
dbms/src/Flash/Mpp/MPPTunnel.h
dbms/src/Flash/Mpp/TrackedMppDataPacket.h
dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
dbms/src/Flash/executeQuery.cpp
dbms/src/Interpreters/ProcessList.cpp
dbms/src/Interpreters/ProcessList.h
dbms/src/Interpreters/executeQuery.cpp
dbms/src/Interpreters/executeQuery.h

This reverts commit b9899e9e302b4ad9b6aa4828f166fb9ec111530f.
Issue Number: ref #7687
revert #7644 in release-7.2 since #7644 is actually not needed in v7.2.0
Tests 
Side effects
Documentation
```release-note
None
```

Revert "Introduce mpp query level processListEntry (#7644)"

---

dbms/CMakeLists.txt
dbms/src/Common/TiFlashMetrics.h
dbms/src/Flash/Disaggregated/WNEstablishDisaggTaskHandler.cpp
dbms/src/Flash/FlashService.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/Transaction/PDTiKVClient.h
dbms/src/TiDB/Schema/TiDBSchemaSyncer.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/7713
When there are many DeltaMergeStore in one tiflash instance, each `DeltaMergeStore::getStoreStats` will try to get the snapshot stats from PSV3/UniPS. But the PSV3/UniPS is a global instance that brings much CPU waste and locks contention. So it causes slow queries.
* Only get snapshot stats under `PageStorageRunMode::ONLY_V2`, because PSV2 have different PS instances for different table
* Reduce the lock scope of `read_write_mutex` in `DeltaMergeStore::getStoreStats`
* Add metrics about disagg RPC requests
* Refine some loggings
Tests 
Side effects
Documentation
```release-note
None
```

Reduce UniPS snapshot stat overhead

---

dbms/src/Flash/Coprocessor/DAGExpressionAnalyzerHelper.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/7717
Tests 
use tiflash pr: https://github.com/pingcap/tiflash/pull/7169
```
create table t(a int, b int, c int);
alter table t set tiflash replica 1;
insert into t values(1,1),(1,2);
select count(1), grouping(a), grouping(b) from t group by a,b with rollup;
select count(1), grouping(b), grouping(a) from t group by a,b with rollup;
```
Side effects
Documentation
```release-note
function: fix grouping function result name
```

function: fix grouping function result name

---

dbms/src/Common/CurrentMetrics.cpp
dbms/src/Common/TiFlashMetrics.h
dbms/src/Storages/Page/V3/BlobStore.cpp
dbms/src/Storages/Page/V3/LogFile/LogReader.h
dbms/src/Storages/Page/V3/LogFile/LogWriter.cpp
dbms/src/Storages/Page/V3/LogFile/LogWriter.h
dbms/src/Storages/Page/V3/PageDirectory.cpp
dbms/src/Storages/Page/V3/PageDirectory.h
dbms/src/Storages/Page/V3/PageEntriesEdit.h
dbms/src/Storages/Page/V3/PageStorageImpl.cpp
dbms/src/Storages/Page/V3/WALStore.cpp
dbms/src/Storages/Page/V3/WALStore.h
dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
dbms/src/Storages/Page/V3/tests/gtest_wal_log.cpp
metrics/grafana/tiflash_summary.json

Issue Number: close #7735 close #7736
Problem Summary: cherry pick of https://github.com/pingcap/tiflash/pull/7154 and https://github.com/pingcap/tiflash/pull/7616
Tests 
Side effects
Documentation
```release-note
None
```

Decrease write latency in PageStorage

---

dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/7766
Previously there are two checks, so we should use `&&`.
Tests 
Side effects
Documentation
```release-note
None
```

Fix a typo in ingest range check

---

dbms/src/Debug/DAGProperties.h
dbms/src/Debug/MockComputeServerManager.cpp
dbms/src/Debug/MockComputeServerManager.h
dbms/src/Debug/MockExecutor/AstToPB.cpp
dbms/src/Debug/MockExecutor/AstToPB.h
dbms/src/Debug/MockExecutor/ExchangeReceiverBinder.cpp
dbms/src/Debug/MockExecutor/ExchangeSenderBinder.cpp
dbms/src/Debug/dbgQueryCompiler.h
dbms/src/Debug/dbgQueryExecutor.cpp
dbms/src/Flash/EstablishCall.cpp
dbms/src/Flash/FlashService.cpp
dbms/src/Flash/Mpp/MPPTask.cpp
dbms/src/Flash/Mpp/MPPTask.h
dbms/src/Flash/Mpp/MPPTaskId.cpp
dbms/src/Flash/Mpp/MPPTaskId.h
dbms/src/Flash/Mpp/MPPTaskManager.cpp
dbms/src/Flash/Mpp/MPPTaskManager.h
dbms/src/Flash/Mpp/MPPTaskStatistics.cpp
dbms/src/Flash/Mpp/MinTSOScheduler.cpp
dbms/src/Flash/Mpp/MinTSOScheduler.h
dbms/src/Flash/tests/gtest_compute_server.cpp
dbms/src/Storages/DeltaMerge/Remote/DisaggTaskId.cpp
dbms/src/Storages/StorageDisaggregated.cpp
dbms/src/Storages/StorageDisaggregatedRemote.cpp
dbms/src/TestUtils/MPPTaskTestUtils.cpp
dbms/src/TestUtils/MPPTaskTestUtils.h
dbms/src/TestUtils/mockExecutor.cpp
tests/fullstack-test/mpp/apply.test

Issue Number: close #7746, close #7744
- Change the organization of MPPTasks in MPPTaskManager from two-level to three-level:
- Before this pr: `MPPTask`s => `MPPQueryTaskSet`, `MPPQueryTaskSet`s => `MPPTaskMananger` 
- After this pr: `MPPTask`s => `MPPGatherTaskSet`, `MPPGatherTaskSet`s => `MPPQuery`, `MPPQuery`s => `MPPTaskManager`
- `Cancel/Abort` mpp task works on `MPPGather` level, cancel a mpp gather does not affect other mpp gathers that belongs to the same mpp query
- `Schedule` mpp task still works on `MPPQuery` level, which means if a mpp query is the min-tso query, all the gathers belongs to the same mpp query will be scheduled
- Refine test to support mpp gather
Tests 
- test tpch queries
Side effects
Documentation
```release-note
None
```

Cancel MPP task works on Mpp gather level

---

dbms/src/Flash/tests/gtest_runtime_filter_executor.cpp
dbms/src/Storages/DeltaMerge/Filter/In.h

Fixed #7798
This PR change the IN RS operator when values is empty. Using return RSResult::None instead of thrown exception when values is empty.
The In RS Operator is only used for runtime filter. When filter is empty (the build side is empty infact), the IN values will be empty. So this is not a exception and it should skip all of scan of packs.
Issue Number: close #7798
Tests 
Side effects
Documentation
```release-note
None
```

[Bug] Fix the empty values when runtime filter is LOCAL mode

---

tests/fullstack-test/mpp/apply.test

Issue Number: ref #7746
Enable parallel apply tests since https://github.com/pingcap/tidb/issues/45299 is fixed.
Tests 
Side effects
Documentation
```release-note
None
```

enable parallel apply tests

---

dbms/src/Storages/Page/V3/PageDirectory.cpp
dbms/src/Storages/Page/V3/PageEntriesEdit.cpp
dbms/src/Storages/Page/V3/PageEntryCheckpointInfo.h

Issue Number: close #7799 
Problem Summary: After disable uploading page data when do checkpoint, the data file id in manifest will be empty. And after restart, tiflash may try to recover from the latest manifest file and set a empty checkpoint location which is unexpected and will make tiflash crash in the next round of uploading checkpoint.
When restoring from manifest file at restart, check whether the data file id is empty before copy the checkpoint info to memory.
Tests 
1. deploy a cluster and load some data;
2. restart and write more data, and then check whether tiflash will crash;
Side effects
Documentation
```release-note
None
```

Fix wrong checkpoint info after restart

---

dbms/src/Debug/MockStorage.cpp
dbms/src/Flash/Executor/PipelineExecutor.cpp
dbms/src/Flash/Pipeline/Pipeline.cpp
dbms/src/Flash/Pipeline/Pipeline.h
dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp
dbms/src/Flash/Planner/PhysicalPlan.cpp
dbms/src/TestUtils/ExecutorTestUtils.cpp

Issue Number: close #7768
- fix `stack-use-after-scope` in `MockStorage`.
- fix unstable ut `ExecutionSummaryTestRunner.*`
- refine `Pipeline::toTreeString` and cache the result of `toTreeString`.
Tests 
Side effects
Documentation
```release-note
None
```

Some refines

---

dbms/src/Storages/Transaction/Region.cpp
dbms/src/Storages/Transaction/Region.h

Issue Number: close #7836
Allow duplicate key-value in raftstore v2 mode
Tests 
Side effects
Documentation
```release-note
None
```

Handle orphan default keys

---

dbms/src/Debug/dbgFuncRegion.cpp
dbms/src/Storages/Transaction/ApplySnapshot.cpp
dbms/src/Storages/Transaction/KVStore.cpp
dbms/src/Storages/Transaction/KVStore.h
dbms/src/Storages/Transaction/RegionTable.cpp
dbms/src/Storages/Transaction/RegionTable.h
dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
dbms/src/Storages/Transaction/tests/gtest_new_kvstore.cpp
dbms/src/Storages/Transaction/tests/kvstore_helper.h

Remove more dead codes after https://github.com/pingcap/tiflash/pull/7853. Make the codebase more clear
* Remove the param `try_persist` from `RegionTable::tryWriteBlockByRegionAndFlush` because all are called with `try_persist=false`
* Remove `RegionTable::writeBlockByRegionAndFlush` because `try_persist` is always false and the function is the same as `writeBlockByRegion`
* Move `tryPersistRegion` to `RegionKVStoreTest` to reduce the code complexity in `KVStore `
Tests 
Side effects
Documentation
```release-note
None
```

Remove more dead codes

---

dbms/src/DataStreams/RuntimeFilter.cpp

Issue Number: close #7865 
Tests 
Side effects
Documentation
```release-note
None
```

Avoid meanless runtime filter wait when filter failed

---

dbms/CMakeLists.txt
dbms/src/Flash/Pipeline/Schedule/TaskQueues/IOPriorityQueue.cpp
dbms/src/Flash/Pipeline/Schedule/TaskQueues/IOPriorityQueue.h
dbms/src/Flash/Pipeline/Schedule/TaskQueues/MultiLevelFeedbackQueue.cpp
dbms/src/Flash/Pipeline/Schedule/TaskQueues/MultiLevelFeedbackQueue.h
dbms/src/Flash/Pipeline/Schedule/TaskQueues/TaskQueue.h
dbms/src/Flash/Pipeline/Schedule/TaskQueues/tests/bench_task_queue.cpp
dbms/src/Flash/Pipeline/Schedule/TaskQueues/tests/gtest_io_priority.cpp
dbms/src/Flash/Pipeline/Schedule/TaskQueues/tests/gtest_mlfq.cpp

Issue Number: close #7904
This pr has no affcets on performance, check:
before this pr:
```
[2023/08/7 12:47:41 Day-219] guojiangtao-arch :: tiflash/build/master_rel ‹f2bb4c4ee*› » ./dbms/bench_dbms --benchmark_filter='MLFQBench*'
2023-08-07T12:47:41+08:00
Running ./dbms/bench_dbms
Run on (20 X 4800 MHz CPU s)
CPU Caches:
L1 Data 48 KiB (x10)
L1 Instruction 32 KiB (x10)
L2 Unified 1280 KiB (x10)
L3 Unified 25600 KiB (x1)
Load Average: 0.76, 0.43, 0.53
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
----------------------------------------------------------------------------
Benchmark                                  Time             CPU   Iterations …
```

refine TaskQueue::take semantics to drain all tasks when finished

---

dbms/src/DataStreams/HashJoinProbeExec.cpp
dbms/src/Interpreters/Join.cpp

Issue Number: close #7905
Introduced by #7741. The root cause is in #7741, for restore join that can not support spill again(restore_round == 4), it disable join spill, so `join->isEnableSpill()` will return false, but in `HashJoinProbeExec`, it assumes that all the child joins should  return true for `join->isEnableSpill()` if parent join spill is triggered.
- `HashJoinProbeExec::onScanHashMapAfterProbeFinish` and `HashJoinProbeExec::onProbeFinish` returns right value if spill is triggered
- Update `Join.cpp` so UT can conver this issue
Tests 
Side effects
Documentation
```release-note
None
```

Fix bug in join spill

---

release-centos7-llvm/dockerfiles/misc/prepare_basic.sh

Tests 
Side effects
Documentation
```release-note
None
```

Remove excess backslashes

---

dbms/src/Flash/Mpp/ReceivedMessageQueue.cpp
dbms/src/Flash/Mpp/ReceivedMessageQueue.h

Issue Number: close #7951
The root cause is object stored in `PODArray` must be POD object, and clearly `LooseBoundedMessageQueue` is not a POD object
Tests 
Side effects
Documentation
```release-note
None
```

Fix memory leak in `ReceivedMessageQueue`

---

dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp

Issue Number: close #7915 
Problem Summary: In some cases, some ref if may be lost when restart. For example, like the following steps
1. do some operations like put, delete or ref;
2. put 100 at seq 1000;
3. delete 100 at seq 1001;
4. dump snapshot with snap_seq to 1001;(now the checkpoint file name will be log_xxx_xxx_1001)
5. restart and because the operations put 100 and delete 100 is not in checkpoint file, the max sequence will be less or equal than 1000(let's say it's 1000);
6. put 200 at seq 1000;
7. ref 201 -> 200 at seq 1001;
8. restart again, and because the snap seq of checkpoint file is 1001, so all ref operations with sequence less or equal than seq 1001 will be ignored, so page id 201 will lost after restart;
Make sure the restored max sequence is larger or equal than the …

fix the potential problem that some ref id may be lost after restart

---

dbms/src/Flash/Mpp/MinTSOScheduler.cpp

Issue Number: close #8034 
Problem Summary: Schedule all waiting tasks with same query_id and gather_id to "Exceed" when hard limit reached. Don't rely tidb's cancel request to do this.
Tests 
Test randomFailpoint related tests.
Side effects
Documentation
```release-note
None
```

Fix MinTSOScheduler incorrectly erased waiting_set issue

---

dbms/src/Core/tests/gtest_spiller.cpp
dbms/src/DataStreams/AggHashTableToBlocksBlockInputStream.h
dbms/src/Interpreters/Aggregator.cpp
dbms/src/Interpreters/Aggregator.h

spill aggregation data using `Spiller::spillBlocksUsingBlockInputStream` because it is more memory friendly.
Tests 
Side effects
Documentation
```release-note
None
```

spill agg blocks using BlockInputStream

---

dbms/src/Storages/DeltaMerge/Remote/RNDeltaIndexCache.h
dbms/src/Storages/DeltaMerge/Remote/RNReadTask.cpp
dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
dbms/src/Storages/DeltaMerge/Remote/Serializer.h

Issue Number: ref #7359
Keyspace ID is not in RNDeltaIndexCache::CacheKey, it could mixuse delta index of different keyspace ID.
Add keyspace ID to RNDeltaIndexCache::CacheKey.
Tests 
Side effects
Documentation
```release-note
None
```

Add keyspace_id to RNDeltaIndexCache.

---

dbms/src/Core/FineGrainedOperatorSpillContext.cpp
dbms/src/Core/FineGrainedOperatorSpillContext.h
dbms/src/Core/OperatorSpillContext.cpp
dbms/src/Core/OperatorSpillContext.h
dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
dbms/src/Flash/Coprocessor/InterpreterUtils.h
dbms/src/Flash/Planner/Plans/PhysicalAggregation.cpp
dbms/src/Flash/Planner/Plans/PhysicalTopN.cpp
dbms/src/Flash/Planner/Plans/PhysicalWindowSort.cpp
dbms/src/Interpreters/tests/gtest_operator_spill_context.cpp
dbms/src/Operators/LocalAggregateTransform.cpp
dbms/src/Operators/LocalAggregateTransform.h
dbms/src/Operators/MergeSortTransformOp.h

When fine grained shuffle is enabled, due to implicit depentency of all the operator belongs to the same TiDB executor, auto spill will meet a big performance regression if auto spill treated all the operator spill contexts from the same TiDB executor independently. This pr add `FineGrainedOperatorSpillContext` and try to align the spill behavior for fine grained executor.
- Add `FineGrainedOperatorSpillContext`
- For operator that comes from the same TiDB executor, auto spill will be triggered at TiDB executor level, instead of triggering each operator independently
Test on TPCH-100 dataset, with 2 TiFlash node
For fine grained agg, test sql is
```
select /*+ mpp_1phase_agg() */ l_orderkey, max(L_COMMENT), max(L_SHIPMODE), max(L_SHIPINSTRUCT), …
```

Refine auto spill for fine grained executor

---

dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
dbms/src/Storages/DeltaMerge/SSTFilesToDTFilesOutputStream.cpp
dbms/src/Storages/PathPool.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/8054
introduced by https://github.com/pingcap/tiflash/pull/7876 .
Under disagg mode, we don't record the dt file parent path by `StableDiskDelegator::addDTFile`. It causes exception when cancelling snapshot.
As the comments describe, we just ignore the local files under disagg arch.
Tests 
Side effects
Documentation
```release-note
None
```

Fix crash for cancel apply snapshot

---

dbms/src/AggregateFunctions/AggregateFunctionCount.h
dbms/src/AggregateFunctions/AggregateFunctionIf.h
dbms/src/AggregateFunctions/AggregateFunctionNull.h
dbms/src/AggregateFunctions/AggregateFunctionSum.h
dbms/src/AggregateFunctions/IAggregateFunction.h
dbms/src/Columns/ColumnsCommon.cpp
dbms/src/Columns/ColumnsCommon.h
dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
dbms/src/DataStreams/ParallelAggregatingBlockInputStream.h
dbms/src/Interpreters/Aggregator.cpp
dbms/src/Interpreters/Aggregator.h
dbms/src/Operators/AggregateContext.cpp
dbms/src/Operators/AggregateContext.h

Before this pr, `Aggregator::executeOnBlock` only support aggregate the whole input block once a time, after this pr, `Aggregator::executeOnBlock` support aggregate only part of the data from the input block.
Note this pr only supports aggregation on part of the input block in terms of form, the code logic is not changed, the real support will be on the next pr.
Tests 
Side effects
Documentation
```release-note
None
```

Refine API in IAggregateFunction/Aggregator to support aggregate on part of the input `block` formally

---

dbms/src/Storages/Transaction/RaftLogManager.cpp
dbms/src/Storages/Transaction/RaftLogManager.h
dbms/src/Storages/Transaction/tests/gtest_raft_log_manager.cpp
dbms/src/TiDB/Etcd/Client.cpp
dbms/src/TiDB/Etcd/Client.h
dbms/src/TiDB/OwnerManager.cpp
dbms/src/TiDB/OwnerManager.h
dbms/src/TiDB/tests/gtest_owner_manager.cpp
metrics/grafana/tiflash_summary.json

Issue Number: close https://github.com/pingcap/tiflash/issues/8069
When deployed under disagg arch, the non S3 gc owner TiFlash wn may hang forever. It is because when `EtcdOwnerManager::cancelImpl` is called, `client->campaign` is still stuck on the RPC call, and `th_camaign.join()` may never get returned. 
* Cancel the grpc context of `client->campaign` when `EtcdOwnerManager::cancelImpl` is called
* Add some unit test for RaftLogManager
* Fix the position of some grafana panels
Before this PR
After this PR
Tests 
Side effects
Documentation
```release-note
None
```

Disagg: Fix hang when canceling non-owner

---

dbms/src/Common/FailPoint.cpp
dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
dbms/src/Flash/tests/gtest_aggregation_executor.cpp
dbms/src/Flash/tests/gtest_spill_aggregation.cpp
dbms/src/Interpreters/Aggregator.cpp
dbms/src/Interpreters/Aggregator.h
dbms/src/Operators/AggregateBuildSinkOp.cpp
dbms/src/Operators/AggregateBuildSinkOp.h
dbms/src/Operators/AggregateContext.cpp
dbms/src/Operators/AggregateContext.h
dbms/src/Operators/LocalAggregateTransform.cpp
dbms/src/Operators/Operator.cpp

This pr is after #8056, and in the pr, aggregate part of the input block in `Aggregator` fully supported. However, although supported, this feature can only be triggered by failpoint.
Tests 
Side effects
Documentation
```release-note
None
```

Fully support aggregate on part of a input block

---

dbms/src/Common/CurrentMetrics.cpp
dbms/src/Debug/dbgFuncMockRaftSnapshot.cpp
dbms/src/Storages/DeltaMerge/StoragePool.cpp
dbms/src/Storages/DeltaMerge/StoragePool.h
dbms/src/Storages/Page/V3/PageStorageImpl.cpp
dbms/src/Storages/Page/V3/Universal/tests/gtest_checkpoint.cpp
dbms/src/Storages/Transaction/ApplySnapshot.cpp
metrics/grafana/tiflash_summary.json

Issue Number: ref https://github.com/pingcap/tiflash/issues/6882
Problem Summary: The number of DeltaMergeStore running on disagg-arch is not reported
Tests 
Side effects
Documentation
```release-note
None
```

Disagg: show the num of tables on Grafana

---

dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
dbms/src/Flash/Disaggregated/WNFetchPagesStreamWriter.cpp
dbms/src/Flash/Disaggregated/WNFetchPagesStreamWriter.h
dbms/src/Storages/DeltaMerge/Remote/DisaggSnapshot.cpp
dbms/src/Storages/DeltaMerge/Remote/DisaggSnapshot.h

Issue Number: close https://github.com/pingcap/tiflash/issues/8090
Problem Summary: Deployed on a disagg arch cluster, when we execute queries on a table with generate column(s), the query will fail
Because `DisaggPhysicalTableReadSnapshot:: output_field_types` is not used by any codes now. We just remove it and its checks.
Tests 
- Deploy a disagg cluster
```sql
CREATE TABLE `cached` (
`cache_key` varchar(512) NOT NULL,
`created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`expires` int(11) DEFAULT '-1' COMMENT 'cache will expire after n seconds',
`expired_at` datetime GENERATED ALWAYS AS (if(`expires` > 0, date_add(`updated_at`, interval `expires` second), date_add(`updated_at`, interval 99 year))) …
```

Disagg: Fix exception when query table with generated column(s)

---

dbms/src/Common/HashTable/TwoLevelHashTable.h
dbms/src/Common/HashTable/TwoLevelStringHashTable.h
dbms/src/Core/CachedSpillHandler.cpp
dbms/src/Interpreters/Aggregator.cpp
dbms/src/Interpreters/Aggregator.h
dbms/src/Interpreters/JoinPartition.cpp

This pr set ResizeCallback for aggregation hash table, so when the hash table need resize in aggregation, it has the chance to check if current hash table is already maked to spill, if yes, it can simply give up resize and release the memory in time.
Tests 
will add integration test in endless
Side effects
Documentation
```release-note
None
```

support agg resize callback

---

dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
dbms/src/DataStreams/ParallelAggregatingBlockInputStream.h
dbms/src/Interpreters/Aggregator.cpp
dbms/src/Interpreters/Aggregator.h
dbms/src/Operators/AggregateContext.cpp
dbms/src/Operators/AggregateContext.h
tests/fullstack-test2/ddl/alter_partition_by.test

In #8064, it use a `while` loop to handle aggregate input block, like 
https://github.com/pingcap/tiflash/blob/f6e8ffa5b76768c307368e45f7e668f78c1a1e71/dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp#L150-L155
while, unfortunately, both the while loop and `allBlockDataHandled()` does not aware that the agg is cancelled, so it may cause hang.
This pr makes `AggProcessInfo` aware the cancellation of current aggregator. 
Tests 
Side effects
Documentation
```release-note
None
```

Fix MPPTask hang introduced by #8064

---

dbms/src/Interpreters/AsynchronousMetrics.cpp
dbms/src/Storages/KVStore/TMTContext.cpp
tests/fullstack-test2/ddl/alter_partition_by.test

Issue Number: close https://github.com/pingcap/tiflash/issues/7713
After https://github.com/pingcap/tiflash/pull/7706, when PS V3 or UniPS is enabled, the metrics of max snapshot lifetime is always reported to prometheus as 0.
When PS V3 or UniPS is enabled, get and report the metrics in `AsynchronousMetrics::update`
Tests 
* Block the queries by using `DBGInvoke disable_fail_point(hang_in_execution)` through `tiflash client`
* We can see that the max snapshot lifetime is reported normally on Grafana
Side effects
Documentation
```release-note
None
```

*: Fix max snapshot lifetime is now shown on Grafana

---

dbms/src/Common/TiFlashMetrics.h
dbms/src/Debug/MockRaftStoreProxy.cpp
dbms/src/Debug/dbgFuncMockRaftSnapshot.cpp
dbms/src/Debug/dbgTools.cpp
dbms/src/Storages/DeltaMerge/SSTFilesToBlockInputStream.cpp
dbms/src/Storages/DeltaMerge/SSTFilesToBlockInputStream.h
dbms/src/Storages/DeltaMerge/SSTFilesToDTFilesOutputStream.h
dbms/src/Storages/KVStore/Decode/RegionDataRead.h
dbms/src/Storages/KVStore/FFI/ProxyFFI.cpp
dbms/src/Storages/KVStore/KVStore.h
dbms/src/Storages/KVStore/MultiRaft/ApplySnapshot.cpp
dbms/src/Storages/KVStore/tests/gtest_kvstore.cpp
metrics/grafana/tiflash_summary.json

Issue Number: ref #7777
1. change type_apply_snapshot_predecode and type_apply_snapshot_predecode_sst2dt from order 10 to order 15.
2. add a metric to observe all ongoing snapshot size on disk.
Tests 
Side effects
Documentation
```release-note
None
```

Add metrics to monitor size of ongoing raft snapshots

---

dbms/src/Storages/DeltaMerge/SSTFilesToBlockInputStream.h
dbms/src/Storages/KVStore/MultiRaft/ApplySnapshot.cpp
dbms/src/Storages/KVStore/MultiRaft/IngestSST.cpp
dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
dbms/src/Storages/KVStore/Region.cpp

Issue Number: ref #7777 ref #4646
The pr is:
1. as part of kvstore refactor
2. as part of parallel pre-handling single snapshot
3. remove some needless utils
4. move some raft-related utils into these modules
We've done the following in this pr:
1. an PrehandleSnapshot.cpp which is about how to generate column format files(DTFiles) from SST format(including a whole rocksdb instance) file
2. an IngestSST.cpp which is about how to ingest an sst file as part of data of a region.
5. an ApplySnapshot.cpp is about how to replace data in a certain key range. 
Tests 
Side effects
Documentation
```release-note
None
```

Sort raft snapshot related utils into different modules

---

dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h

Issue Number: close #7359 https://github.com/tidbcloud/tiflash-cse/issues/88
- `delta_index_epoch` is not persisted. It will fallback to zero if TiFlash (WN) restarts.
- This will result in inconsistent `delta_index_epoch` between WN and CN and lead to inconsistent delta index eventually.
- `delta_index_epoch` is used in disaggregated mode by compute-nodes to identify if the delta_index has changed.
- To avoid persisting it, we use `std::chrono::steady_clock` to make it monotonic increase.
- Accuracy of `std::chrono::steady_clock` in Linux is nanosecond. This is much smaller than the interval between two flushes.
Tests 
Side effects
Documentation
```release-note
None
```

Make delta_index_epoch monotonic increase.

---

docs/design/2023-09-22-tiflash-query-level-auto-spill.md

Add design doc for TiFlash query level auto spill
Tests 
Side effects
Documentation
```release-note
None
```

add design doc for query level spill

---

dbms/src/Common/CurrentMetrics.cpp
dbms/src/Common/MemoryTracker.cpp
dbms/src/Common/MemoryTracker.h
dbms/src/Common/PODArray.h
dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
dbms/src/Storages/DeltaMerge/ReadThread/ColumnSharingCache.cpp
dbms/src/Storages/DeltaMerge/ReadThread/ColumnSharingCache.h
dbms/src/TestUtils/TiFlashTestEnv.cpp
dbms/src/TestUtils/gtests_dbms_main.cpp

Issue Number: close #8128 
- In `DMFileReader::readCoumn`, if there are some concurrent `DMFileReader` of the same file existing, this column data is likely to be shared, so disable memory tracing by setting `current_memory_tracker` to `nullptr`.
- Mark `PODArray` the underlying memory of column data to be `is_shared_memory` and use `shared_column_data_mem_tracker` to trace its memory.
Before this PR(from issue #8128)
```
[2023/09/21 09:08:37.087 +08:00] [DEBUG] [MemoryTracker.cpp:101] ["Peak memory usage (for query): 10.48 GiB."] [source=MemoryTracker] [thread_id=269]
[2023/09/21 09:08:37.090 +08:00] [DEBUG] [MemoryTracker.cpp:101] ["Peak memory usage (for query): 288.86 MiB."] [source=MemoryTracker] [thread_id=270]
[2023/09/21 09:08:37.090 +08:00] [DEBUG] [MemoryTracker.cpp:101] ["Peak …
```

No tracing memory usage of shared column data in MPPTask's memory tracker

---

dbms/src/Flash/Pipeline/Schedule/TaskQueues/ResourceControlQueue.h
dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp
dbms/src/Flash/ResourceControl/LocalAdmissionController.h

Issue Number: close #8074
two problems:
1. Grpc needs new a client context for each new reader/writer, otherwise may crash.
2. Network between GAC and LAC may got network error(like timeout). Need to handle it more gracefully, otherwise tiflash will crash.
two enhancements:
1. Delete `handleBackgroundError()`, because it's just a dummy wrap of `LOG_ERROR`
2. Add lock when call `refill_token_callback` to avoid RCQ been destroied when calling `refill_token_callback`
Tests 
1. start cluster with tiflash
3. continuously kill pd and check tiflash should not crash
Side effects
Documentation
```release-note
None
```

fix network error handling of LocalAdmissionController

---

dbms/src/DataStreams/HashJoinProbeExec.cpp
dbms/src/Interpreters/HashJoinSpillContext.cpp
dbms/src/Interpreters/HashJoinSpillContext.h
dbms/src/Interpreters/Join.cpp
dbms/src/Interpreters/Join.h
dbms/src/Operators/HashProbeTransformExec.cpp

Issue Number: close #8144
Fix data race in join auto spill.
The root cause is join spill will call `spilled_partition_indexes.push_back(i);` concurrently in auto spill mode.
This pr fix it by
* Rename `spilled_partition_indexes` to `remaining_partition_indexes_to_restore`, and only use this during restore stage
* Init `remaining_partition_indexes_to_restore` in `workAfterBuildFinish`, which is thread safe.
Tests 
Side effects
Documentation
```release-note
None
```

fix data race in join auto spill

---

dbms/src/Flash/EstablishCall.cpp
dbms/src/Flash/EstablishCall.h
dbms/src/Flash/Mpp/MPPTask.cpp
dbms/src/Flash/Mpp/MPPTask.h
dbms/src/Flash/Mpp/MPPTaskManager.cpp
dbms/src/Flash/Mpp/MPPTaskManager.h
dbms/src/Flash/Mpp/MinTSOScheduler.cpp
dbms/src/Flash/Mpp/MinTSOScheduler.h
dbms/src/Flash/Mpp/tests/gtest_mpp_task_manager.cpp
dbms/src/Interpreters/Aggregator.cpp
dbms/src/Interpreters/Join.cpp

In `MPPTaskManager::unregisterTask`
https://github.com/pingcap/tiflash/blob/9d4485f152f8fd11225018aec128a760141f6edb/dbms/src/Flash/Mpp/MPPTaskManager.cpp#L404-L407
it only remove `MPPGatherTaskSet` if current gather_set does not has mpp task && current gather_set does not have pending alarms. If there is any pending alarms, the gather_set will be kept in `MPPTaskManager`, thus also kept in `MinTSOScheduler`, if all the task are unregistered, the only way to remove gather_set from `MPPTaskManager` and `MinTSOScheduler` is from TiDB's cancel request, if the request is lost, the `MinTSOScheduler` may be work as expected since `min_tso` will not be updated.
In this pr, it tries to only keep "valid" alarms in gather_set by
* `MPPGatherTaskSet` keep a …

Fix potential hang if tidb cancel is lost

---

dbms/src/Flash/FlashService.cpp

Issue Number: close #8173
1. In `WNEstablishDisaggTaskHandler::execute`, a `ProcessListElement` object will be created and sets `current_memory_tracker` to its `memory_tracker` member in constructor. And `current_memory_tracker`  will be reset in the destructor of  `ProcessListElement`.
2. However, objects of `ProcessListElement` are created in threads of  `WNEstablishDisaggTaskPool`, but destructed in threads of GRPC because it will be destructed with object of  `WNEstablishDisaggTaskHandler` (`handler` -> `dag_context` -> `process_list_entry`).
3. This result in `current_memory_tracker` of threads of `WNEstablishDisaggTaskPool` is not reset after task finished and other tasks may continue to use this memory tracker, although it may have already been destructed.
- Reset …

Reset current_memory_tracker when WNEstablishDisaggTaskHandler finished.

---

dbms/src/Interpreters/Settings.h

Issue Number: ref https://github.com/pingcap/tiflash/issues/8177
See https://github.com/pingcap/tiflash/issues/8177
Currently, disable cop stream for remote read by default in order to pass several tests. 
I will fix https://github.com/pingcap/tiflash/issues/8177 and then enable cop stream for remote read by default.
Tests 
Side effects
Documentation
```release-note
None
```

Disable cop stream for remote read by default

---

dbms/src/Storages/DeltaMerge/Decode/SSTFilesToDTFilesOutputStream.cpp
dbms/src/Storages/DeltaMerge/Decode/SSTFilesToDTFilesOutputStream.h
dbms/src/Storages/DeltaMerge/tests/gtest_sst_files_stream.cpp
dbms/src/Storages/KVStore/KVStore.h
dbms/src/Storages/KVStore/MultiRaft/PreHandlingTrace.h
dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
dbms/src/Storages/KVStore/MultiRaft/RegionCFDataBase.cpp
dbms/src/Storages/KVStore/Region.cpp

Issue Number: close #8081
it is reported that in some case, there are duplicated keys when merge uncommitted region data.
Add some debug info to peek exactly which key is duplicated.
Tests 
Side effects
Documentation
```release-note
None
```

Add some debug info when meet duplicate key in parallel prehandling

---

dbms/src/Flash/BatchCoprocessorHandler.cpp
dbms/src/Flash/BatchCoprocessorHandler.h
dbms/src/Flash/Coprocessor/CoprocessorReader.h
dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
dbms/src/Flash/CoprocessorHandler.cpp
dbms/src/Flash/CoprocessorHandler.h
dbms/src/Flash/FlashService.cpp

Issue Number: close #8181
1. refine the log of cop/batch cop
2. refine the log inside client-c for remote read
3. update client-c to fix some minor bugs
Before this pr, the log for cop/batch cop is
```
[DEBUG] [PhysicalPlan.cpp:84] ["tidb table scan has runtime filter size:0"] [source=CoprocessorHandler(stream)] [thread_id=240]
```
The log for client-c remote read is
```
[INFO] [<unknown>] ["thread start."] [source=pingcap/coprocessor] [thread_id=250]
```
After this pr, these log will be 
```
[DEBUG] [PhysicalPlan.cpp:84] ["tidb table scan has runtime filter size:0"] [source="Coprocessor, is_remote_read: true, start_ts: 444859118261370884, region_info: {1125035, 2, 1088}, resource_group: default"] [thread_id=283]
[INFO] [<unknown>] ["thread start."] …
```

refine log for cop/batch cop

---

dbms/src/Flash/Mpp/MPPTask.cpp
dbms/src/Flash/Mpp/MPPTask.h
dbms/src/Flash/Mpp/MPPTaskManager.cpp
dbms/src/Flash/Mpp/MPPTaskManager.h
dbms/src/Flash/Mpp/tests/gtest_mpp_task_manager.cpp

Issue Number: close #8192
Only unregister and remove from mpp task monitor if the task is registered successfully.
Tests 
Side effects
Documentation
```release-note
None
```

Fix potential hang when duplicated task registered.

---

dbms/src/Storages/Page/workload/HeavyMemoryCostInGC.h
dbms/src/Storages/Page/workload/HighValidBigFileGC.h
dbms/src/Storages/Page/workload/MainEntry.cpp
dbms/src/Storages/Page/workload/Normal.h
dbms/src/Storages/Page/workload/PSBackground.cpp
dbms/src/Storages/Page/workload/PSBackground.h
dbms/src/Storages/Page/workload/PSRunnable.cpp
dbms/src/Storages/Page/workload/PSRunnable.h
dbms/src/Storages/Page/workload/PSStressEnv.cpp
dbms/src/Storages/Page/workload/PSStressEnv.h
dbms/src/Storages/Page/workload/PSWorkload.cpp
dbms/src/Storages/Page/workload/PSWorkload.h
dbms/src/Storages/Page/workload/PageStorageInMemoryCapacity.h
dbms/src/Storages/Page/workload/ThousandsOfOffset.h

The previous output of `pageworkload` is hard to parse and run performance result comparsion
* Add `--color false` for pageworkload to disable color fields in the output
* The performance summary is print into stdout and the running logging is print into stderr
* Use `JSON` as the performance output format
```
> ./dbms/src/Server/tiflash pageworkload -T 10 --color false > a.log 2> a.err.log
>  tail a.log
Workload summary: {"memory":{"avg":111674800,"latest":127928458,"top":127928458},"read":{"bytes_read":33,"pages":27123,"read_speed":"3.283"},"snapshots":{"avg":2017,"latest":3432,"top":3432},"write":{"bytes_written":4,"pages":2539,"write_speed":"0.493"}}
```
Tests 
Side effects
Documentation
```release-note …
```

*: Refine pageworkload output

---

dbms/src/DataStreams/RuntimeFilter.cpp
dbms/src/DataStreams/RuntimeFilter.h
dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp
dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.h
tests/fullstack-test/mpp/runtime_filter.test

This pr fix #8222.
The rs operator which is parsed by filter should change the timezone to UTF when the column type is timestamp.
The tiflash storage layer store the timestamp type value using UTF. So all of literal include runtime filter values should be changed to UTF timezone.
Issue Number: close #8222
Tests 
```
tiup playground --tiflash 1
use test;
create table t1(k1 int , k2 timestamp);
create table t2(k1 int, k2 timestamp);
alter table t1 set tiflash replica 1;
alter table t2 set tiflash replica 1;
set tidb_isolation_read_engines = "tiflash";
insert into t1 values (1, "2023-10-20 00:00:00");
insert into t2 values (1, "2023-10-20 00:00:00");
set tidb_runtime_filter_mode="LOCAL";
explain select * from t1, t2 where t1.k2=t2.k2; -- with runtime filter
mysql> select * …
```

runtime filter: fix timezone error in runtime filter

---

dbms/src/Interpreters/Join.cpp
dbms/src/Interpreters/Join.h
dbms/src/Interpreters/JoinPartition.cpp
dbms/src/Interpreters/ProbeProcessInfo.cpp
dbms/src/Interpreters/ProbeProcessInfo.h

Issue Number: close #8294
Tests 
```
mysql> desc t;
+---------+---------+------+------+---------+-------+
| Field   | Type    | Null | Key  | Default | Extra |
+---------+---------+------+------+---------+-------+
| from_id | int(11) | YES  |      | NULL    |       |
| to_id   | int(11) | YES  |      | NULL    |       |
| value   | int(11) | YES  |      | NULL    |       |
+---------+---------+------+------+---------+-------+
mysql> select count(*) from t;
+----------+
| count(*) |
+----------+
|   393216 |
+----------+
mysql> select count(*), from_id, to_id, value from t group by from_id, to_id, value;
+----------+---------+-------+-------+
| count(*) | from_id | to_id | value |
+----------+---------+-------+-------+
|   131072 |       2 |     3 |     2 |
|   131072 | …
```

Reduce redundant calculation in join probe, optimize `mergeNullAndFilterResult`

---

release-centos7-llvm/dockerfiles/misc/bake_llvm_base_aarch64.sh
release-centos7-llvm/dockerfiles/misc/bake_llvm_base_amd64.sh
release-centos7-llvm/dockerfiles/misc/install_ccache.sh
release-centos7-llvm/dockerfiles/misc/install_git.sh

Issue Number: close #8324
- git version is too old for recent tiflash repo
- easier ccache enabling dir
- update git version for the tiflash building container 
Tests 
Side effects
Documentation
```release-note
None
```

fix: update git version for submodules

---

CMakeLists.txt
dbms/src/Debug/MockKVStore/MockProxyRegion.cpp
dbms/src/Debug/MockKVStore/MockRaftStoreProxy.cpp
dbms/src/Debug/MockKVStore/MockRaftStoreProxy.h
dbms/src/Debug/MockKVStore/MockReadIndex.cpp
dbms/src/Flash/Disaggregated/S3LockService.cpp
dbms/src/Flash/Disaggregated/S3LockService.h
dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.h
dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.h
dbms/src/Storages/KVStore/KVStore.cpp
dbms/src/Storages/KVStore/MultiRaft/PreHandlingTrace.h
dbms/src/Storages/KVStore/Read/ReadIndexWorker.cpp
dbms/src/Storages/KVStore/Read/ReadIndexWorker.h
dbms/src/Storages/KVStore/tests/gtest_read_index_worker.cpp
dbms/src/Storages/Page/V3/Blob/BlobStat.cpp
dbms/src/Storages/Page/V3/Blob/BlobStat.h
dbms/src/Storages/Page/V3/BlobStore.cpp
dbms/src/Storages/Page/V3/PageDirectory.cpp
dbms/src/Storages/Page/V3/PageDirectory.h
dbms/src/Storages/Page/V3/tests/gtest_blob_stat.cpp
dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
dbms/src/Storages/Page/V3/tests/gtest_versioned_entries.cpp

Issue Number: ref #6834, ref https://github.com/pingcap/tiflash/issues/6350
- Clang Thread Safety Analysis is a C++ language extension which warns about potential race conditions in code. The analysis is completely static (i.e. compile-time); there is no run-time overhead. For more information, please check [https://clang.llvm.org/docs/ThreadSafetyAnalysis.html](https://clang.llvm.org/docs/ThreadSafetyAnalysis.html).
- Support Clang Thread Safety Analysis in TiFlash (`-DENABLE_TSA=ON`).
- Usage: 
```
cmake .. \
-DCMAKE_CXX_COMPILER=clang++ \
-DCMAKE_C_COMPILER=clang \
-DCMAKE_BUILD_TYPE=RELWITHDEBINFO \
-DENABLE_TSA=ON \
-GNinja
```
- Annotated `SegmentReadTaskScheduler` and `MergedTaskPool` with thread-safety-analysis attributes.
- The main problem of TiFlash's existing code is that the …

Support Clang Thread Safety Analysis

---

dbms/src/Common/Stopwatch.h

Issue Number: close https://github.com/pingcap/tiflash/issues/8336
Use `nanosecondsWithBound` to ensure the return value is not less than `last_ns` in `elapsedFromLastTime`
Tests 
Side effects
Documentation
```release-note
None
```

*: Fix time step backward for `Stopwatch::elapsedFromLastTime`

---

dbms/src/TestUtils/FunctionTestUtils.cpp

Unittests TestDateTimeDayMonthYear.dayMonthYearTest is unstable, due to "std::exception. Code: 1001, type: std::__1::system_error, e.what() = random_device failed to open /dev/urandom: Operation not permitted".
- Replace `std::random_device` with `std::chrono::system_clock` here to avoid exceptions like 'random_device failed to open /dev/urandom: Operation not permitted'.
- The reason of exceptions is unknown, but the probability of its occurrence in unittests TestDateTimeDayMonthYear.dayMonthYearTest is not low.
- Since this function is just used for testing, using current timestamp as a random seed is not a problem.
Tests 
Side effects
Documentation
```release-note
None
```

Try to fix unstable unittests.

---

dbms/src/TiDB/Schema/SchemaBuilder.cpp
dbms/src/TiDB/Schema/SchemaBuilder.h
dbms/src/TiDB/Schema/SchemaGetter.cpp
dbms/src/TiDB/Schema/TiDB.cpp
tests/fullstack-test2/ddl/alter_partition_by.test
tests/fullstack-test2/ddl/remove_partitioning.test
tests/fullstack-test2/ddl/reorganize_partition.test

cherry-pick of https://github.com/pingcap/tiflash/pull/8337
Issue Number: close https://github.com/pingcap/tiflash/issues/8206
Introduced by https://github.com/pingcap/tiflash/pull/7822
When executing `alter table xxx partition by ...` to turn a non-partition table into partition table, there could be a chance that tiflash see a non-partition table turn into a partition table (using the same table_id). But it would be skipped by the previous implementation
https://github.com/pingcap/tiflash/blob/b092db0b8f0bede1867b3cebfececad619adfdb7/dbms/src/TiDB/Schema/SchemaBuilder.cpp#L407-L423
And then tiflash mistaken drop the old table along with all its partitions, but actually those partition are now attached to a new logical table. This leads to data lost after `alter table …

ddl: Fix potential data lost of `alter_partition_by` (release-7.5)

---

dbms/src/TiDB/Schema/SchemaBuilder.cpp
dbms/src/TiDB/Schema/SchemaBuilder.h
dbms/src/TiDB/Schema/SchemaGetter.cpp
dbms/src/TiDB/Schema/TiDB.cpp
dbms/src/TiDB/Schema/TiDB.h
tests/fullstack-test2/ddl/alter_partition_by.test
tests/fullstack-test2/ddl/remove_partitioning.test
tests/fullstack-test2/ddl/reorganize_partition.test

Issue Number: close https://github.com/pingcap/tiflash/issues/8206
Introduced by https://github.com/pingcap/tiflash/pull/7822
When executing `alter table xxx partition by ...` to turn a non-partition table into partition table, there could be a chance that tiflash see a non-partition table turn into a partition table (using the same table_id). But it would be skipped by the previous implementation
https://github.com/pingcap/tiflash/blob/b092db0b8f0bede1867b3cebfececad619adfdb7/dbms/src/TiDB/Schema/SchemaBuilder.cpp#L407-L423
And then tiflash mistaken drop the old table along with all its partitions, but actually those partition are now attached to a new logical table. This leads to data lost after `alter table xxx partition ...
* Use tidb_isolation_read_engines instead …

ddl: Fix potential data lost of `alter_partition_by`

---

dbms/src/Storages/StorageDisaggregatedRemote.cpp

Issue Number: close #8358
storage read bytes ru has added for coupled tiflash, should also add it for disagg mode.
Tests 
check the following image, after add read bytes ru for disagg mode , we can see ru usage is very different.
Side effects
Documentation
```release-note
None
```

add read bytes ru in disagg mode for resource control

---

dbms/src/TiDB/Schema/SchemaSyncService.cpp
dbms/src/TiDB/Schema/SchemaSyncService.h
dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/8356
After a new tidb cluster deployed, there is an interval that PD will return gc safepoint with 0
```
>  tiup ctl:nightly pd -u [10.2.12.81:6540](http://10.2.12.81:6540/) -i
Starting component `ctl`: /DATA/disk1/ra_common/.tiup/components/ctl/v7.6.0-alpha-nightly-20231112/ctl pd -u [10.2.12.81:6540](http://10.2.12.81:6540/) -i
» service-gc-safepoint
{
"service_gc_safe_points": [
{
"service_id": "gc_worker",
"expired_at": 9223372036854775807,
"safe_point": 445603590956646400
}
],
"gc_safe_point": 0 <-- tiflash use this value
}
```
This will lead to `SchemaSyncService::gc` running repeatedly. This results in lots of useless logging and getting gc safepoint from pd frequently.
* If tiflash receives a gc …

ddl: Fix zero safepoint make schema gc run repeatly

---

dbms/src/Encryption/RateLimiter.cpp
dbms/src/TiDB/Schema/SchemaBuilder.cpp
dbms/src/TiDB/Schema/SchemaBuilder.h
tests/fullstack-test2/ddl/alter_exchange_partition.test

Issue Number: close https://github.com/pingcap/tiflash/issues/8372
For example:
1. Create a partition table, logical_table_id=100, partition p0 physical_table_id=101
2. The partition table schema is synced to TiFlash
3. A non-partition table (table_id=222) is created
4. Execute exchange partition immediately, exchange non-partition table_id=222 with physical_table_id=101
5. TiFlash starts its schema sync, try to get the TableInfo of table_id=222 from TiKV
6. TiKV return nothing because table_id=222 is a partition table of logical_table_id=100 now. TiFlash treat the table as dropped and failed to create IStorage for table_id=222.
7. TiFlash tries to execute the `EXCHANGE PARTITION` DDL, but failed to find the IStorage instance of table_id=222. However, the new partition …

ddl: Fix failure on executing exchange partition(release-6.5)

---

dbms/src/TiDB/Schema/SchemaBuilder.cpp
dbms/src/TiDB/Schema/SchemaBuilder.h
tests/fullstack-test2/ddl/alter_exchange_partition.test

Issue Number: close https://github.com/pingcap/tiflash/issues/8372
For example:
1. Create a partition table, logical_table_id=100, partition p0 physical_table_id=101
2. The partition table schema is synced to TiFlash
3. A non-partition table (table_id=222) is created
4. Execute exchange partition immediately, exchange non-partition table_id=222 with physical_table_id=101
5. TiFlash starts its schema sync, try to get the TableInfo of table_id=222 from TiKV
6. TiKV return nothing because table_id=222 is a partition table of logical_table_id=100 now. TiFlash treat the table as dropped and failed to create IStorage for table_id=222.
7. TiFlash tries to execute the `EXCHANGE PARTITION` DDL, but failed to find the IStorage instance of table_id=222. However, the new partition …

ddl: Fix failure on executing exchange partition(release-7.1)

---

dbms/src/Encryption/RateLimiter.cpp
dbms/src/Storages/Transaction/SchemaBuilder.cpp
dbms/src/Storages/Transaction/SchemaBuilder.h
tests/fullstack-test2/ddl/alter_exchange_partition.test

Issue Number: close https://github.com/pingcap/tiflash/issues/8372
For example:
1. Create a partition table, logical_table_id=100, partition p0 physical_table_id=101
2. The partition table schema is synced to TiFlash
3. A non-partition table (table_id=222) is created
4. Execute exchange partition immediately, exchange non-partition table_id=222 with physical_table_id=101
5. TiFlash starts its schema sync, try to get the TableInfo of table_id=222 from TiKV
6. TiKV return nothing because table_id=222 is a partition table of logical_table_id=100 now. TiFlash treat the table as dropped and failed to create IStorage for table_id=222.
7. TiFlash tries to execute the `EXCHANGE PARTITION` DDL, but failed to find the IStorage instance of table_id=222. However, the new partition …

ddl: Fix failure on executing exchange partition(release-6.1)

---

dbms/src/Common/Exception.cpp
dbms/src/Common/Exception.h
dbms/src/Storages/KVStore/FFI/ProxyFFI.cpp

Issue Number: ref #8365
Tests 
Side effects
Documentation
```release-note
None
```

Set log level to FATAL on FFI boundary on exception

---

dbms/src/Common/TiFlashMetrics.h
dbms/src/Server/Server.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.cpp
dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
dbms/src/Storages/DeltaMerge/Segment.h
dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h
dbms/src/Storages/StorageDisaggregatedRemote.cpp

Issue Number: close #8362
1. Check whether RU is exhausted in `MergedTask`. If RU is exhausted, yield this task.
2. Check whether RU is exhausted is `SegmentReadTaskScheduler`. If RU is exhausted, don't schedule this `SegmentReadTaskPool`.
Tests 
Side effects
Documentation
```release-note
None
```

Check RU in read thread of Storage.

---

dbms/src/Debug/MockSchemaGetter.h
dbms/src/Encryption/tests/gtest_rate_limiter.cpp
dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
dbms/src/TiDB/Schema/SchemaBuilder.cpp
dbms/src/TiDB/Schema/SchemaBuilder.h
dbms/src/TiDB/Schema/SchemaGetter.cpp
dbms/src/TiDB/Schema/SchemaGetter.h
dbms/src/TiDB/Schema/TiDB.cpp
dbms/src/TiDB/Schema/TiDBSchemaSyncer.cpp
dbms/src/TiDB/Schema/TiDBSchemaSyncer.h
dbms/src/TiDB/Schema/tests/gtest_table_id_map.cpp
tests/fullstack-test2/ddl/alter_exchange_partition.test
tests/fullstack-test2/ddl/rename_table_across_databases.test

manual cherry-pick of https://github.com/pingcap/tiflash/pull/8402
Issue Number: close https://github.com/pingcap/tiflash/issues/8398
The main problem is when we want to create a Storage instance
* `TiDBSchemaSyncer::syncTableSchema` first check whether we can find the TableID mapping in memory
* If we can find the TableID mapping, then `SchemaBuilder::applyTable` will fetch the table info from TiKV and try to create the table
https://github.com/pingcap/tiflash/blob/5ba01c04abc057f376eb71c8598cab65bc711460/dbms/src/TiDB/Schema/TiDBSchemaSyncer.cpp#L174-L215
https://github.com/pingcap/tiflash/blob/5ba01c04abc057f376eb71c8598cab65bc711460/dbms/src/TiDB/Schema/SchemaBuilder.cpp#L1203-L1213
However, even if we can find the TableID from the TableID mapping, we can not ensure …

ddl: Fix broken TableIDMapping lead to data loss or crashes (release-7.5)

---

dbms/src/Flash/Disaggregated/WNEstablishDisaggTaskHandler.cpp
dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
dbms/src/Storages/DeltaMerge/Remote/Serializer.h
dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task.cpp

Issue Number: ref #6834
- The name `serializeTo` is too generalization and there are too many overload functions with this name.
- Change `serializeTo` to `serializeXXX`, XXX is the object type to be serialized.
Tests 
Side effects
Documentation
```release-note
None
```

Rename some names of DB::DM::Remote::Serializer.

---

dbms/src/Debug/MockSchemaGetter.h
dbms/src/Encryption/tests/gtest_rate_limiter.cpp
dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
dbms/src/TiDB/Schema/SchemaBuilder.cpp
dbms/src/TiDB/Schema/SchemaBuilder.h
dbms/src/TiDB/Schema/SchemaGetter.cpp
dbms/src/TiDB/Schema/SchemaGetter.h
dbms/src/TiDB/Schema/TiDB.cpp
dbms/src/TiDB/Schema/TiDBSchemaSyncer.cpp
dbms/src/TiDB/Schema/TiDBSchemaSyncer.h
dbms/src/TiDB/Schema/tests/gtest_table_id_map.cpp
tests/fullstack-test2/ddl/alter_exchange_partition.test
tests/fullstack-test2/ddl/rename_table_across_databases.test

Issue Number: close https://github.com/pingcap/tiflash/issues/8398
The main problem is when we want to create a Storage instance
* `TiDBSchemaSyncer::syncTableSchema` first check whether we can find the TableID mapping in memory
* If we can find the TableID mapping, then `SchemaBuilder::applyTable` will fetch the table info from TiKV and try to create the table
https://github.com/pingcap/tiflash/blob/5ba01c04abc057f376eb71c8598cab65bc711460/dbms/src/TiDB/Schema/TiDBSchemaSyncer.cpp#L174-L215
https://github.com/pingcap/tiflash/blob/5ba01c04abc057f376eb71c8598cab65bc711460/dbms/src/TiDB/Schema/SchemaBuilder.cpp#L1203-L1213
However, even if we can find the TableID from the TableID mapping, we can not ensure its freshness. There could be some DDLs has changed the TableID …

ddl: Fix broken TableIDMapping lead to data loss or crashes

---

dbms/src/Common/MemoryTracker.cpp
dbms/src/Common/MemoryTracker.h
dbms/src/Common/tests/gtest_memtracker.cpp
dbms/src/Interpreters/ProcessList.cpp
dbms/src/Server/Server.cpp
dbms/src/Storages/BackgroundProcessingPool.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/8408
There is an invalid memory access. This is because the logging system is already closed
When `sub_root_of_query_storage_task_mem_trackers` and its children are destructoring, it means the process is shutting down and the logging system is stopped.
Suppress the logging of these memory trackers.
Tests 
- Add a line after store_idnet is got to mock an exception thrown and tiflash stopped `throw Exception("Mock exception thrown");`
https://github.com/pingcap/tiflash/blob/3d3a5f14d51a55c636223e1ac9c9038e082ebb62/dbms/src/Server/Server.cpp#L1707-L1716
Side effects
Documentation
```release-note
None
```

*: Fix invalid memory access when shutting down

---

dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
dbms/src/Flash/FlashService.cpp
dbms/src/Flash/Mpp/MPPTaskId.cpp
dbms/src/Flash/Mpp/MPPTaskId.h
dbms/src/Flash/Mpp/MPPTaskManager.cpp
dbms/src/Flash/Planner/PhysicalPlanNode.cpp
dbms/src/Flash/Planner/PhysicalPlanNode.h
dbms/src/Flash/Planner/Plans/PhysicalAggregation.cpp
dbms/src/Flash/Planner/Plans/PhysicalAggregationBuild.cpp
dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp

Issue Number: close #8399
1. for `resource_group/conn_id/conn_alias`, only log it once at the begining of each request
2. remove some redundant information in each executor's log identifier
Before this pr, the spill file name in `AggregationBuild` is
```
tmp_MPP_gather_id__gather_id_1__query_ts_1700522319105637023__local_query_id_13__server_id_1453__start_ts_445781716263239681__resource_group__default__conn_id__3047162128__conn_alias____task_id_5__Aggregation_HashAgg_80_AggregationBuild_HashAgg_80_aggregation_partition_0_1749
``` 
After this pr, the spill file name will be
```
tmp_MPP_gather_id_1__query_ts_1700522319105637023__local_query_id_13__server_id_1453__start_ts_445781716263239681_task_id_5__AggregationBuild_HashAgg_80_partition_0_1749
```
Tests 
Side effects …

Don't log too many useless information in log

---

dbms/src/Flash/Pipeline/Schedule/TaskQueues/ResourceControlQueue.cpp
dbms/src/Flash/Pipeline/Schedule/TaskQueues/ResourceControlQueue.h

Issue Number: close #8415
Tests 
Side effects
Documentation
```release-note
Fixed the issue that updateStatistics was not called for mlfq in resource group queue.
```

Fixed the issue that `updateStatistics` was not called for `mlfq` in `resource group queue`

---

dbms/src/Functions/FunctionsJson.h
dbms/src/Functions/tests/gtest_cast_as_json.cpp

Issue Number: close #8427
Tests 
Side effects
Documentation
```release-note
None
```

fix asan fail for `cast_decimal_as_json` and `cast_time_as_json`

---

dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task.cpp

Issue Number: close #8436
1. Extract page id from MemTableSet.
2. Initialize data provider of MemTableSet.
Tests 
Side effects
Documentation
```release-note
None
```

Disagg: Fix the problem of missing remote page id in MemTableSet.

---

dbms/src/DataStreams/MergingSortedBlockInputStream.cpp

Issue Number: close #8438 
Tests 
Side effects
Documentation
```release-note
None
```

Avoid out of bound InsertRangeFrom exception in MergingSortedBlockInputStream

---

dbms/src/Common/TiFlashMetrics.h
dbms/src/Storages/DeltaMerge/Delta/ColumnFileFlushTask.h
dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
dbms/src/Storages/DeltaMerge/Delta/MinorCompaction.cpp
dbms/src/Storages/DeltaMerge/Delta/MinorCompaction.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/KVStore/MultiRaft/RegionMeta.cpp
dbms/src/Storages/KVStore/MultiRaft/RegionMeta.h
dbms/src/Storages/KVStore/Read/LearnerReadWorker.cpp
dbms/src/Storages/KVStore/Read/ReadIndex.cpp
dbms/src/Storages/KVStore/Region.h
dbms/src/Storages/KVStore/tests/gtest_kvstore.cpp
metrics/grafana/tiflash_summary.json

Issue Number: close https://github.com/pingcap/tiflash/issues/8448, close https://github.com/pingcap/tiflash/issues/8076
logging after this PR will print the "source=request_identifier" into logging, along with the index info and time elapsed
```
[2023/11/30 21:51:23.688 +08:00] [DEBUG] [LearnerReadWorker.cpp:317] ["[Learner Read] Batch read index, num_regions=1 num_requests=1 num_stale_read=0 num_cached_index=0 num_unavailable=0 cost=2ms"] [source="MPP<gather_id:1, query_ts:1701352283678367892, local_query_id:11, server_id:956, start_ts:445999293050388482,task_id:1>"] [thread_id=271]
[2023/11/30 21:51:30.827 +08:00] [INFO] [ReadIndex.cpp:100] ["[region_id=188005] wait learner index done, prev_index=8 curr_index=9 to_wait=9 elapsed_s=7.139 timeout_s=300.000"] …
```

Raft: Add identifier to logger when wait index happens

---

dbms/src/Common/TiFlashMetrics.h
dbms/src/Storages/DeltaMerge/Delta/ColumnFileFlushTask.h
dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
dbms/src/Storages/DeltaMerge/Delta/MinorCompaction.cpp
dbms/src/Storages/DeltaMerge/Delta/MinorCompaction.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/Transaction/LearnerRead.cpp
dbms/src/Storages/Transaction/Region.cpp
dbms/src/Storages/Transaction/Region.h
dbms/src/Storages/Transaction/RegionMeta.cpp
dbms/src/Storages/Transaction/RegionMeta.h
dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
metrics/grafana/tiflash_summary.json

manual cherry-pick of https://github.com/pingcap/tiflash/pull/8446
Issue Number: close https://github.com/pingcap/tiflash/issues/8448, close https://github.com/pingcap/tiflash/issues/8076
logging after this PR will print the "source=request_identifier" into logging, along with the index info and time elapsed
```
[2023/11/30 21:51:23.688 +08:00] [DEBUG] [LearnerReadWorker.cpp:317] ["[Learner Read] Batch read index, num_regions=1 num_requests=1 num_stale_read=0 num_cached_index=0 num_unavailable=0 cost=2ms"] [source="MPP<gather_id:1, query_ts:1701352283678367892, local_query_id:11, server_id:956, start_ts:445999293050388482,task_id:1>"] [thread_id=271]
[2023/11/30 21:51:30.827 +08:00] [INFO] [ReadIndex.cpp:100] ["[region_id=188005] wait learner index done, prev_index=8 …
```

Raft: Add identifier to logger when wait index happens(release-7.1)

---

tests/fullstack-test2/ddl/flashback_database.test

Issue Number: close https://github.com/pingcap/tiflash/issues/8450
```
mysql> alter table d1.t3 add column b int;
mysql> insert into d1.t3 values(2,2);
mysql> alter table d1.t4 add column b int;
-- drop immediately after adding new columns
mysql> drop database d1;
mysql> flashback database d1 to d1_new
```
If database is dropped before tiflash apply the `add column` DDLs, then tiflash can not know the latest table info because it has been "dropped"
Add a schema sync on tiflash before executing `drop database`
Tests 
Side effects
Documentation
```release-note
None
```

ddl: Fix unstable FLASHBACK DATABASE test (release-6.5)

---

dbms/src/Functions/FunctionsJson.h
dbms/src/Functions/tests/gtest_json_extract.cpp
tests/fullstack-test/expr/json_extract.test

Issue Number: close #8486
Tests 
Side effects
Documentation
```release-note
None
```

Support only null type for json_extract

---

dbms/src/Flash/Pipeline/Schedule/Tasks/RFWaitTask.h
dbms/src/Operators/UnorderedSourceOp.cpp
dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.cpp
dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.h
dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.h
dbms/src/Storages/DeltaMerge/ReadThread/SegmentReader.cpp
dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.h

Issue Number: ref #6834
Tests 
Side effects
Documentation
```release-note
None
```

Storages: small refine of MergedTask.

---

dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
dbms/src/Storages/DeltaMerge/SegmentReadTask.h

Issue Number: close #8515
When network partitioned, CN fetches pages and memtableset from WN will fail. However, we forgot to check the status of grpc after response stream returns false, and the function `FetchPages()` may think that the pages fetching was successful (but actually not).
Before [PR8430](https://github.com/pingcap/tiflash/pull/8430), [some](https://github.com/pingcap/tiflash/blob/master/dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp#L674-L678)[ condition checks](https://github.com/pingcap/tiflash/blob/master/dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp#L674-L678) will discover these anomalies, and throw exceptions. In the case that all pages are cached, this condition check takes no effect. 
In [PR8430](https://github.com/pingcap/tiflash/pull/8430), …

Storages: fix segmentfault when `fetchPages` failed.

---

tests/sanitize/tsan.suppression

Issue Number: ref #8285
In PR #8499, try add AssignDescriptors to tsan suppression to ignore false positive warnings. However, the tool fails to recognize and ignore some cases(write code is protected by call_once):
Ignore high level functions: DebugString and ShortDebugString
Tests 
Side effects
Documentation
```release-note
None
```

Update tsan suppressions to ignore protobuf DebugString and ShortDebugString

---

dbms/src/Common/FailPoint.cpp
dbms/src/TiDB/Etcd/Client.cpp
dbms/src/TiDB/OwnerManager.cpp
dbms/src/TiDB/tests/gtest_owner_manager.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/8519
When the campaign loop is break by watch key deleted, and etcd session expired. The campaign loop still keep trying with the old session.
```
[2023/12/01 05:07:43.325 +00:00] [INFO] [OwnerManager.cpp:368] ["watch failed, owner key is deleted"] [source="owner_id=0.0.0.0:3930"] [thread_id=1233]Show context
[2023/12/01 05:08:08.199 +00:00] [WARN] [OwnerManager.cpp:304] ["is not the owner"] [source="owner_id=0.0.0.0:3930"] [thread_id=1203]
[2023/12/01 05:08:08.201 +00:00] [INFO] [OwnerManager.cpp:270] ["failed to campaign, id=0.0.0.0:3930 lease=73928bb2367fd5e9 code=2 msg=etcdserver: requested lease not found"] [source="owner_id=0.0.0.0:3930"] [thread_id=1203]
[2023/12/01 05:08:08.403 +00:00] [INFO] …
```

Disagg: Fix infinite retries on owner election

---

dbms/src/Common/FailPoint.cpp
dbms/src/Debug/MockSchemaGetter.h
dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
dbms/src/TiDB/Schema/SchemaBuilder.cpp
dbms/src/TiDB/Schema/SchemaBuilder.h
dbms/src/TiDB/Schema/SchemaGetter.cpp
dbms/src/TiDB/Schema/SchemaGetter.h
dbms/src/TiDB/tests/gtest_table_info.cpp
tests/fullstack-test2/ddl/flashback/flashback_database.test

Issue Number: close https://github.com/pingcap/tiflash/issues/8506
If the Region snapshot arrived TiFlash after the database has been dropped, then we can not successfully create the Storage instance because we can not fetch it from TiKV. And also `DatabaseInfo` can not be fetch by "mvcc get".
https://github.com/pingcap/tiflash/blob/a46271dd7db654ec0ab59f77915706863bf91e0b/dbms/src/TiDB/Schema/SchemaBuilder.cpp#L1454-L1465
To successfully create a Storage instance (`applyCreateStorageInstance`), we don't need the `DatabaseInfo`, a `DatabaseID` is sufficient. We are rewriting methods in `SchemaBuilder` to replace the methods with `DatabaseInfo` by `DatabaseID`. So that we can create those Storage instances and decode the Raft logs or snapshots after a database is dropped …

ddl: Fix corner case of `FLASHBACK DATABASE`

---

dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.h

This reverts commit adf85696270f864c0317526919b37fbdfe5a6417.
Issue Number: close https://github.com/pingcap/tiflash/issues/8539
See https://github.com/pingcap/tiflash/issues/8539
#8511 introduced an issue that `WorkQueue<Block>` in `SegmentReadTaskPool` may not finish forever. Revert this PR to fix this issue for safety and simplicity.
Tests 
Side effects
Documentation
```release-note
None
```

Revert "Refine cancel for read thread stream (#8511)"

---

dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.h

Issue Number: close #8551
See commnets in code.
Tests 
Side effects
Documentation
```release-note
None
```

Storages: fix MemoryTracker may release before MemoryTrackerSetter destructed

---

dbms/src/Common/FailPoint.cpp
dbms/src/Storages/KVStore/Region.cpp
dbms/src/TiDB/Etcd/Client.cpp
dbms/src/TiDB/OwnerManager.cpp
dbms/src/TiDB/tests/gtest_owner_manager.cpp

manual cherry-pick of https://github.com/pingcap/tiflash/pull/8534
* * *
Issue Number: close https://github.com/pingcap/tiflash/issues/8519
When the campaign loop is break by watch key deleted, and etcd session expired. The campaign loop still keep trying with the old session.
```
[2023/12/01 05:07:43.325 +00:00] [INFO] [OwnerManager.cpp:368] ["watch failed, owner key is deleted"] [source="owner_id=0.0.0.0:3930"] [thread_id=1233]Show context
[2023/12/01 05:08:08.199 +00:00] [WARN] [OwnerManager.cpp:304] ["is not the owner"] [source="owner_id=0.0.0.0:3930"] [thread_id=1203]
[2023/12/01 05:08:08.201 +00:00] [INFO] [OwnerManager.cpp:270] ["failed to campaign, id=0.0.0.0:3930 lease=73928bb2367fd5e9 code=2 msg=etcdserver: requested lease not found"] …
```

Disagg: Fix infinite retries on owner election (#8534)

---

dbms/src/TiDB/Schema/SchemaBuilder.cpp
dbms/src/TiDB/Schema/SchemaGetter.cpp
dbms/src/TiDB/Schema/SchemaSyncService.cpp
dbms/src/TiDB/Schema/TiDB.cpp
dbms/src/TiDB/Schema/TiDB.h
tests/fullstack-test2/ddl/flashback/flashback_database.test

Issue Number: close #8506
Introduced by https://github.com/pingcap/tiflash/pull/8536. In that PR, we don't check whether the `DatabaseInfo` exist when creating a Storage instance.
However, if the DDL "create database" and decoding raftlog or snapshot comes after TiDB executed "drop database". Then `applyCreateStorageInstance` can not handle it because the `IDatabase` instance is not created in TiFlash.
In order to resolve the `DatabaseInfo`  can not be fetched from TiKV, we will construct a "fake" `DatabaseInfo` and create the `IDatabase` instance in TiFlash. Because
* If the database is not `FLASHBACK`, then we don't care its display name in TiFlash, we just need it for storing the raft log / snapshot data
* If the database is `FLASHBACK` later, then the `DatabaseInfo` …

ddl: Fix snap after dropping database

---

dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.h
dbms/src/Storages/Page/V3/BlobStore.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/8563
* Log down the pool_id and num_stream once for one TableScan
* Avoid calling `BlobFile::truncate` repeatly when its data size is zero
Tests 
Side effects
Documentation
```release-note
None
```

*: Reduce logging from `UnorderedInputStream`

---

dbms/src/Interpreters/JoinUtils.cpp
tests/fullstack-test/issues/issue_8562.test

Issue Number: close #8562 
TiDB changes the return type of IfString from String to Null(Strange that not constant folding completely), thus introduced ColumnNothing in filter result column. It is not handled before.
Tests 
Side effects
Documentation
```release-note
None
```

Handle ColumnNothing column in recordFilteredRows of Join

---

dbms/src/Common/FailPoint.cpp
dbms/src/Server/tests/gtest_server_config.cpp
dbms/src/Storages/KVStore/Decode/RegionTable.h
dbms/src/Storages/KVStore/KVStore.cpp
dbms/src/Storages/KVStore/KVStore.h
dbms/src/Storages/KVStore/MultiRaft/ApplySnapshot.cpp
dbms/src/Storages/KVStore/MultiRaft/IngestSST.cpp
dbms/src/Storages/KVStore/MultiRaft/RaftCommandsKVS.cpp
dbms/src/Storages/KVStore/MultiRaft/RegionPersister.cpp
dbms/src/Storages/KVStore/MultiRaft/RegionPersister.h
dbms/src/Storages/KVStore/TMTContext.h
dbms/src/Storages/KVStore/tests/gtest_region_persister.cpp
dbms/src/Storages/KVStore/tests/kvstore_helper.h

Issue Number: close https://github.com/pingcap/tiflash/issues/8583
https://github.com/pingcap/tiflash/blob/5980908e68629f40c2191ae2d100f41d554dce44/dbms/src/Storages/KVStore/MultiRaft/RegionPersister.cpp#L99-L125
`RegionPersister::doPersist` acquires a lock and calls `PageStorage::write` with the lock. This means when we're persisting Region meta, all other threads can not do the persistence for other Region meta. Which is not reasonable.
There is a `region_task_lock` to ensure that only one thread could call `RegionPersister::doPersist` at the same time. And `PageStorage` support multi-thread reading and writing for different page_id. There is no need to acquire another lock in `RegionPersister::doPersist` that could slowdown the raft apply process
And also remove …

KVStore: Reduce lock contention in `RegionPersister::doPersist`

---

dbms/src/Common/FailPoint.cpp
dbms/src/Storages/Transaction/RegionPersister.cpp
dbms/src/Storages/Transaction/RegionPersister.h
dbms/src/Storages/Transaction/tests/gtest_region_persister.cpp

cherry-pick of https://github.com/pingcap/tiflash/pull/8584
Issue Number: close https://github.com/pingcap/tiflash/issues/8583
https://github.com/pingcap/tiflash/blob/5980908e68629f40c2191ae2d100f41d554dce44/dbms/src/Storages/KVStore/MultiRaft/RegionPersister.cpp#L99-L125
`RegionPersister::doPersist` acquires a lock and calls `PageStorage::write` with the lock. This means when we're persisting Region meta, all other threads can not do the persistence for other Region meta. Which is not reasonable.
There is a `region_task_lock` to ensure that only one thread could call `RegionPersister::doPersist` at the same time. And `PageStorage` support multi-thread reading and writing for different page_id. There is no need to acquire another lock in `RegionPersister::doPersist` that …

KVStore: Reduce lock contention in `RegionPersister::doPersist` (release-6.5)

---

dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.cpp
dbms/src/Storages/DeltaMerge/ScanContext.cpp
dbms/src/Storages/DeltaMerge/ScanContext.h

Issue Number: close https://github.com/pingcap/tiflash/issues/8563
Add mvcc input bytes and num columns about TableScan to `MPPTaskStatistics::logTracingJson`
Run the following queries on ch-benchmark 1500, the mvcc input rows is the same. But the query time elapsed, mvcc input bytes, are quite different.
```
time_elapsed num_columns_scan mvcc_input_rows outbound_rows mvcc_input_bytes outbound_bytes
2.081s      4               464139510       334475782       18565580400     10233415852
2.307s      4               464139510       334475782       18565580400     10233415852
4.252s      5               464139510       334475782       34346323740     25361074068
4.978s      9               464139510       334475782       41772555900     32479972052
```
```
select   ol_number, …
```

*: Add mvcc input bytes and num columns read to logging

---

dbms/src/Storages/Page/V3/PageDirectory.cpp

Usually one TableScan read task can easily involve hundreds of Segments, each of the segment read task acquire a snapshot of PageStorage.
So when there are leaking or long-time running tasks, the logging of "Meet a stale snapshot" will print lots of redundant logging.
Only print one logging for the same tracing_id
Tests 
Side effects
Documentation
```release-note
None
```

PageStorage: avoid redundantly print stale snapshot log

---

dbms/src/Storages/DeltaMerge/tests/gtest_dm_storage_delta_merge.cpp
dbms/src/Storages/S3/MockS3Client.cpp

```
==395555==ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new vs free) on 0x6120006196c0
#0 0x4cebc92 in free /llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:111:3
#1 0x213fefda in std::__1::enable_if<std::is_polymorphic<std::__1::basic_iostream<char, std::__1::char_traits<char> > >::value, void>::type Aws::Delete<std::__1::basic_iostream<char, std::__1::char_traits<char> > >(std::__1::basic_iostream<char, std::__1::char_traits<char> >*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/aws/src/aws-cpp-sdk-core/include/aws/core/utils/memory/AWSMemory.h:120:9
#2 0x213fefda in Aws::Utils::Stream::ResponseStream::ReleaseStream() …
```

tests: Fix some issue found by ASAN

---

dbms/src/Debug/DBGInvoker.cpp
dbms/src/Debug/MockTiDB.cpp
dbms/src/Debug/MockTiDB.h
dbms/src/Debug/dbgFuncSchema.cpp
dbms/src/Debug/dbgFuncSchema.h
dbms/src/TiDB/Schema/TiDBSchemaSyncer.cpp
dbms/src/TiDB/Schema/TiDBSchemaSyncer.h
tests/README.md
tests/_env.sh
tests/delta-merge-test/raft/schema/concurrent_ddl_conflict.test
tests/docker/config/tics_dt.toml

Issue Number: close https://github.com/pingcap/tiflash/issues/8578
Problem Summary: When there is conflict in concurrency DDL, it will skip some schema version, which generate an empty SchemaDiff.
Skip when meets an empty SchemaDiff in the non-latest schema version
As that in the relese-7.1 branch https://github.com/pingcap/tiflash/issues/8578#issuecomment-1869402064
https://github.com/pingcap/tiflash/blob/9f7e054ab3401c68c291acdd88879631d8d294ba/dbms/src/TiDB/Schema/TiDBSchemaSyncer.h#L233-L262
Refine the readme of running integration tests in local
Tests 
Side effects
Documentation
```release-note
Fix the crash issue after TiDB's concurrent DDL meets a conflict
```

ddl: Fix sync empty schema diff

---

dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp
tests/fullstack-test/expr/in_expression.test

Issue Number: close #8631
reject all children which are not `ColumnRef` or `Literal`.
Tests 
Side effects
Documentation
```release-note
Fix the wrong result when executing queries with a filter like `ColumnRef in (Literal, Func...)`
```

fix In ScalarFunc in RoughSetFilter

---

dbms/src/Flash/tests/gtest_join_executor.cpp
dbms/src/Interpreters/Join.cpp

Issue Number: close #8633
The root cause is in `Join::finalize`, it may add some `REMOVE_COLUMN` action in `other_cond_expr` if it is not semi or nullaware join:
https://github.com/pingcap/tiflash/blob/ce42814e493e62731172774d783c294c76de3afe/dbms/src/Interpreters/Join.cpp#L2654
however, for function `handleOtherCondition()`,  https://github.com/pingcap/tiflash/blob/ce42814e493e62731172774d783c294c76de3afe/dbms/src/Interpreters/Join.cpp#L850-L854
`right_table_columns` is a index based on previous block, of there is `REMOVE_COLUMN` action in `other_cond_expr`, the index will become invalid.
This pr disable generating `REMOVE_COLUMN` during `Join::finalize`. It is possible that refine the code in `handleOtherCondition` so it does not depends on the index based …

Fix hash join crash

---

dbms/src/Storages/Page/V3/BlobStore.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/8650
When all page data in a BlobFile gets removed in the GC thread, `removePosFromStats` will remove the BlobFile from disk. However, it holds a lock on `mtx_blob_files` when removing the file from disk. If `BlobStore::write` happens to write a page data to a new BlobFile, `BlobStore::getBlobFile` will be blocked by the GC thread.
According to local tests, removing a BlobFile takes tens of milliseconds. Thus introducing performance jitter.
https://github.com/pingcap/tiflash/blob/63eb295f0664ec4251907f00f335976225ddf337/dbms/src/Storages/Page/V3/BlobStore.cpp#L803-L814
https://github.com/pingcap/tiflash/blob/63eb295f0664ec4251907f00f335976225ddf337/dbms/src/Storages/Page/V3/BlobStore.cpp#L632-L636 …

PageStorage: Optimize the critical region when removing a BlobFile from disk

---

dbms/src/Common/TiFlashMetrics.h
dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
metrics/grafana/tiflash_summary.json

Issue Number: ref #8652
- Add CPU usage metrics of `SegmentReader`.
- Refine metrics of read thread and data sharing.
Tests 
Side effects
Documentation
```release-note
None
```

Storages: Refine metrics of read threads and data sharing

---

dbms/src/Interpreters/Join.cpp
dbms/src/Interpreters/Join.h
dbms/src/Interpreters/ProbeProcessInfo.cpp
dbms/src/Interpreters/ProbeProcessInfo.h

Issue Number: ref #8633
Refine `Join::handleOtherConditions` so it does not rely on index based `right_table_columns`
Tests 
Side effects
Documentation
```release-note
None
```

refine handleOtherConditions in join

---

dbms/src/Server/Server.cpp
dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.h
dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h

Issue Number: ref #8564
- In PR #8567, we disable data sharing when `dt_max_sharing_column_bytes_for_all <= 0`. 
- However, `SegmentReadTaskScheduler` will still try to merge `SegmentReadTask` when `dt_max_sharing_column_bytes_for_all <= 0`, although these SegmentReadTasks would not sharing data.
- Don't merge SegmentReadTasks when data sharing is disabled.
Tests 
Side effects
Documentation
```release-note
None
```

Storages: Don't merge SegmentReadTasks when data sharing is disabled

---

dbms/src/Storages/KVStore/FFI/ProxyFFI.cpp
dbms/src/Storages/KVStore/FFI/ProxyFFI.h
dbms/src/Storages/KVStore/MultiRaft/RegionData.cpp
dbms/src/Storages/KVStore/MultiRaft/RegionData.h
dbms/src/Storages/KVStore/Region.h
dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp

Issue Number: close #8697
Tests 
Side effects
Documentation
```release-note
None
```

Pick getLockByKey to master

---

dbms/src/Storages/KVStore/MultiRaft/RegionData.h
dbms/src/TiDB/Schema/SchemaBuilder.cpp
dbms/src/TiDB/Schema/SchemaBuilder.h

Issue Number: ref https://github.com/pingcap/tiflash/issues/8695
A storage instance may be created or dropped other than `CreateTable` and `DropTable` schema diff. Add the reason why storage instance is created or dropped to logging.
Tests 
Side effects
Documentation
```release-note
None
```

DDL: Add the reason why storage instance is created or dropped

---

dbms/src/Storages/Transaction/RowCodec.cpp
dbms/src/Storages/Transaction/tests/gtest_region_block_reader.cpp
tests/fullstack-test2/ddl/alter_column_nullable.test

cherry-pick of https://github.com/pingcap/tiflash/pull/8722
Issue Number: close https://github.com/pingcap/tiflash/issues/8419
Problem Summary: As the issue described. https://github.com/pingcap/tiflash/issues/8419#issuecomment-1898320057
When the column is defined with default value, the column id exists in non-nullable-column-ids:
https://github.com/pingcap/tidb/blob/90fc8148a29ee77708628b6c6984d51b7e9f8cc3/pkg/table/tables/tables.go#L525-L528
There is a function for fixing similar cases, but it only handle the case for "missing column". And those column defined with default value is not consider as "missing column"
https://github.com/pingcap/tiflash/blob/752a2800e7b61b6ad8570faa7e1dfd7c7269b424/dbms/src/TiDB/Decode/RowCodec.cpp#L387-L423
When tiflash meets such `NULL` datum value in …

ddl: Fix NULL value in non-nullable column (release-6.5)

---

dbms/src/Storages/KVStore/Decode/RegionBlockReader.cpp
dbms/src/Storages/KVStore/tests/gtest_region_block_reader.cpp
dbms/src/TiDB/Decode/RowCodec.cpp
tests/fullstack-test2/ddl/alter_column_nullable.test

Issue Number: close https://github.com/pingcap/tiflash/issues/8419
Problem Summary: As the issue described. https://github.com/pingcap/tiflash/issues/8419#issuecomment-1898320057
When the column is defined with default value, the column id exists in non-nullable-column-ids:
https://github.com/pingcap/tidb/blob/90fc8148a29ee77708628b6c6984d51b7e9f8cc3/pkg/table/tables/tables.go#L525-L528
There is a function for fixing similar cases, but it only handle the case for "missing column". And those column defined with default value is not consider as "missing column"
https://github.com/pingcap/tiflash/blob/752a2800e7b61b6ad8570faa7e1dfd7c7269b424/dbms/src/TiDB/Decode/RowCodec.cpp#L387-L423
When tiflash meets such `NULL` datum value in non-nullable column when force_decode==true, just fill with …

ddl: Fix NULL value in non-nullable column

---

dbms/src/Interpreters/Context.cpp
dbms/src/Interpreters/Context.h
dbms/src/Server/DTTool/DTTool.h
dbms/src/Server/Server.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
dbms/src/Storages/DeltaMerge/StoragePool/GlobalPageIdAllocator.cpp
dbms/src/Storages/DeltaMerge/StoragePool/GlobalPageIdAllocator.h
dbms/src/Storages/DeltaMerge/StoragePool/GlobalStoragePool.cpp
dbms/src/Storages/DeltaMerge/StoragePool/StoragePool.cpp
dbms/src/Storages/DeltaMerge/StoragePool/StoragePool.h
dbms/src/Storages/DeltaMerge/StoragePool/StoragePool_fwd.h
dbms/src/Storages/DeltaMerge/WriteBatchesImpl.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment_common_handle.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment_s3.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_storage_delta_merge.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_global_page_id_allocator.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
dbms/src/Storages/DeltaMerge/workload/DTWorkload.cpp
dbms/src/Storages/DeltaMerge/workload/MainEntry.cpp
dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
dbms/src/Storages/Page/V3/PageDirectoryFactory.h
dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
dbms/src/TestUtils/TiFlashTestEnv.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/8695
Problem Summary: As the issue describe: https://github.com/pingcap/tiflash/issues/8695#issuecomment-1895280095
Introduce a `GlobalPageIdAllocator` to avoid a page_id from being reused in one physical_table_id scope. Specifically,
* Introduced a `GlobalPageIdAllocator` to allocate page_id for segment_id, delta-layer and stable-layer for all IStorage instances instead of each `StoragePool` allocate the page_id for its own IStorage instance independently
* Each IStorage instance restored from disk, it will first try raise the lower bound of the `GlobalPageIdAllocator`. After that, a table won't be able to reuse the allocated id
* If an IStorage instance being physically removed (cause by setting tiflash replica to 0) and …

Storage: Fix max-id being mis-reused cause data corruption after changing tiflash replica number

---

dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp

Issue Number: ref #8736 
Verifing DeltaIndex will use new records to overwrite old records for records with the same key and commit_ts.
Tests 
Side effects
Documentation
```release-note
None
```

Storages: add unit-tests of duplicated handle and version.

---

dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.cpp
dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.h
dbms/src/Storages/DeltaMerge/Decode/SSTFilesToDTFilesOutputStream.cpp
dbms/src/Storages/DeltaMerge/DeltaMerge.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
dbms/src/Storages/DeltaMerge/PKSquashingBlockInputStream.h
dbms/src/Storages/DeltaMerge/RowKeyRange.h
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_key_range.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_randomized.cpp
dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeerCache.cpp

- Updating the comparsion code of RowKeyValueRef/RowKeyValue with operators that makes code more readable. 
- Rename comparator of `RowKeyValueRef` from `compare` to `operator<=>`, so that we can use operators >, <, >=, <= directly.
- Simply wrap `operator==` and `operator!=` with `operator<=>` because complier does not generate these functions when `operator<=>` if not default.
- Remove some unused overload operators.
- Refine comparator of `RowKeyValue`. Make it use the same comparator with `RowKeyValueRef`.
Tests 
Side effects
Documentation
```release-note
None
```

Storages: Refine comparator of row key to operator<=>

---

dbms/src/Functions/FunctionsTiDBConversion.h

Issue Number: ref #8285
https://github.com/pingcap/tiflash/blob/82a13c4da1a93ef872e553ff31ab140916c79a78/dbms/src/Functions/FunctionsTiDBConversion.h#L777C1-L778C44
The local variable field is a reference to temporary object col_from[i], and its scope is limited to that statement. It's suspicious here. 
Asan error:
https://github.com/pingcap/tiflash/issues/8285#issuecomment-1958520854
Tests 
Side effects
Documentation
```release-note
None
```

Fix decimal to real asan stack-use-after-scope error

---

dbms/src/Debug/DBGInvoker.cpp
dbms/src/Debug/MockTiDB.cpp
dbms/src/Debug/MockTiDB.h
dbms/src/Debug/dbgFuncSchema.cpp
dbms/src/Debug/dbgFuncSchema.h
dbms/src/TiDB/Schema/SchemaBuilder.cpp
dbms/src/TiDB/Schema/TiDBSchemaSyncer.cpp
dbms/src/TiDB/Schema/TiDBSchemaSyncer.h
tests/delta-merge-test/raft/schema/concurrent_ddl_conflict.test

Manually cherry-pick of https://github.com/pingcap/tiflash/pull/8785
* * *
Issue Number: close https://github.com/pingcap/tiflash/issues/8777
Normally, after users executed DDL statements, the TiDB server will generate some "SchemaDiff" to indicate what happens. And TiFlash will follow the "SchemaDiff" to figure out what DDL operations need to be executed.
But when there are special DDL `FLASHBACK CLUSTER TO` or `br restore point` (which generate `regenerate_schema_map == true`), TiFlash will try to list all existing databases and tables in the cluster and enter `syncAllSchema` to check all existing databases and tables one by one and execute proper DDL on them.
However, in the DDL framwork refactor since v7.2(https://github.com/pingcap/tiflash/pull/7437), there is a …

ddl: Fix database drop by accident when meet `regenerate_schema_map` flag (release-7.5)

---

dbms/src/Debug/DBGInvoker.cpp
dbms/src/Debug/MockTiDB.cpp
dbms/src/Debug/MockTiDB.h
dbms/src/Debug/dbgFuncSchema.cpp
dbms/src/Debug/dbgFuncSchema.h
dbms/src/TiDB/Schema/SchemaBuilder.cpp
dbms/src/TiDB/Schema/TiDBSchemaSyncer.cpp
dbms/src/TiDB/Schema/TiDBSchemaSyncer.h
tests/delta-merge-test/raft/schema/concurrent_ddl_conflict.test

Issue Number: close https://github.com/pingcap/tiflash/issues/8777
Normally, after users executed DDL statements, the TiDB server will generate some "SchemaDiff" to indicate what happens. And TiFlash will follow the "SchemaDiff" to figure out what DDL operations need to be executed.
But when there are special DDL `FLASHBACK CLUSTER TO` or `br restore point` (which generate `regenerate_schema_map == true`), TiFlash will try to list all existing databases and tables in the cluster and enter `syncAllSchema` to check all existing databases and tables one by one and execute proper DDL on them.
However, in the DDL framwork refactor since v7.2(https://github.com/pingcap/tiflash/pull/7437), there is a mistake in the implementation. In the following codes, only newly created …

ddl: Fix database drop by accident when meet `regenerate_schema_map` flag

---

.clang-format
dbms/src/DataStreams/NativeBlockInputStream.cpp
dbms/src/Encryption/tests/gtest_rate_limiter.cpp
dbms/src/Flash/Coprocessor/CHBlockChunkCodec.cpp
dbms/src/Flash/Coprocessor/CodecUtils.cpp
dbms/src/Flash/Coprocessor/CodecUtils.h
dbms/src/TiDB/Schema/SchemaBuilder.cpp
tests/_env.sh
tests/fullstack-test/issues/issue_8601.test

This is an manual fix of #8671 in release-7.1
Issue Number: close #8601
see https://github.com/pingcap/tiflash/issues/8601#issuecomment-1878393488. The different in release-7.1 and earlier branches is because the fsp change of `time` column type is ignored
Tests 
Side effects
Documentation
```release-note
Fix an issue where a query may throw an error during a remote read and the precision of a duration data type is changed.
```

ddl: Fix an issue where a query may throw an error during a remote read and the precision of a duration data type is changed (release-6.5)

---

contrib/jemalloc-cmake/include/jemalloc/internal/jemalloc_preamble.h
libs/libcommon/cmake/find_jemalloc.cmake

Issue Number: close #8824
See #8824.
It turns out to be a simple include order issue in the provided jemalloc header:
https://github.com/pingcap/tiflash/blob/ee0fc2270c9d5f60090f77dc9df75d58104d275d/contrib/jemalloc-cmake/include/jemalloc/internal/jemalloc_preamble.h#L4-L5
Switching the order passed the build.
Tests 
Side effects
Documentation
```release-note
None
```

Fix jemalloc build on Mac

---

dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
dbms/src/Flash/Statistics/TableScanImpl.cpp
dbms/src/Server/Server.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile.h
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.h
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.h
dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.h
dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
dbms/src/Storages/DeltaMerge/File/DMFileReader.h
dbms/src/Storages/DeltaMerge/ReadMode.h
dbms/src/Storages/DeltaMerge/ScanContext.cpp
dbms/src/Storages/DeltaMerge/ScanContext.h
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/Segment.h
dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
dbms/src/Storages/DeltaMerge/StableValueSpace.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_value_space.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_skippable_block_input_stream.cpp
dbms/src/Storages/StorageDisaggregated.cpp
dbms/src/Storages/StorageDisaggregated.h
dbms/src/Storages/StorageDisaggregatedRemote.cpp

Issue Number: ref #8675
- Add more statistical data of TableScanning in ScanContext.
- To distinguish between different stages of scanning files, set a `ReadTag` when creating `DMFileReader`.
- An example:
```
mysql> explain analyze select max(ol_o_id) from order_line where ol_dist_info < '0Fvf5TLWcqdvYC2IeTcQjgMs';
+--------------------------------+------------+---------+--------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```

Storages: Add statistical data of TableScanning in ScanContext

---

CMakeLists.txt
libs/libcommon/cmake/find_jemalloc.cmake
libs/libcommon/cmake/find_mimalloc.cmake

Issue Number: close #8859
Detect sanitizer for jemalloc and mimalloc, and disable themselves if any sanitizer is found.
Tests 
Side effects
Documentation
```release-note
None
```

Disable 3rd party allocators for sanitizer builds

---

.clang-format
dbms/src/DataStreams/NativeBlockInputStream.cpp
dbms/src/Encryption/tests/gtest_rate_limiter.cpp
dbms/src/Flash/Coprocessor/CHBlockChunkCodec.cpp
dbms/src/Flash/Coprocessor/CHBlockChunkCodecV1.cpp
dbms/src/Flash/Coprocessor/CodecUtils.cpp
dbms/src/Flash/Coprocessor/CodecUtils.h
dbms/src/TiDB/Schema/SchemaBuilder.cpp
tests/_env.sh
tests/fullstack-test/issues/issue_8601.test

This is an manual fix of #8671 in release-7.1
Issue Number: close #8601
see https://github.com/pingcap/tiflash/issues/8601#issuecomment-1878393488. The different in release-7.1 and earlier branches is because the fsp change of `time` column type is ignored
Tests 
Side effects
Documentation
```release-note
Fix an issue where a query may throw an error during a remote read and the precision of a duration data type is changed.
```

ddl: Fix an issue where a query may throw an error during a remote read and the precision of a duration data type is changed (release-7.1)

---

dbms/src/Common/TiFlashMetrics.h
dbms/src/Storages/KVStore/Read/LearnerReadWorker.cpp
metrics/grafana/tiflash_summary.json

Issue Number: ref #8864
Tests 
Side effects
Documentation
```release-note
None
```

Monitor learner read failures

---

dbms/src/Flash/Pipeline/Schedule/Reactor/WaitReactor.cpp
dbms/src/Flash/Pipeline/Schedule/Tasks/NotifyFuture.cpp
dbms/src/Flash/Pipeline/Schedule/Tasks/NotifyFuture.h
dbms/src/Flash/Pipeline/Schedule/Tasks/PipeConditionVariable.h
dbms/src/Flash/Pipeline/Schedule/Tasks/Task.cpp
dbms/src/Flash/Pipeline/Schedule/ThreadPool/TaskThreadPoolMetrics.cpp

Tests 
Side effects
Documentation
```release-note
None
```

fix the issue that building tiflash in mac fail introduced by #8872

---

dbms/src/Storages/DeltaMerge/ScanContext.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/8895
Tests 
Side effects
Documentation
```release-note
Fix the wrong number of `local_region_num` shown in logging
```

logging: Fix `local_region_num` in MPPTaskStatistics logging

---

dbms/src/Interpreters/AggSpillContext.cpp
dbms/src/Interpreters/Aggregator.cpp
dbms/src/Interpreters/HashJoinSpillContext.cpp
dbms/src/Interpreters/SortSpillContext.cpp
dbms/src/Interpreters/tests/gtest_operator_spill_context.cpp
dbms/src/Operators/AggregateContext.cpp

Issue Number: close #8905
Don't mark spill if there is not data to spill in auto spill mode
Tests 
Side effects
Documentation
```release-note
None
```

do not mark spill if there is no data to spill in auto spill mode

---

dbms/src/TiDB/Schema/SchemaSyncService.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/8911
In https://github.com/pingcap/tiflash/pull/8721, we introduce a rule that: "if the regions of a given table is not totally removed from TiFlash, skip physically dropping it". However, it does not set the succeeded = false, so after all it will update the last_gc_safepoint.
When the whole cluster has few write commands, the gc_safepoint may not change. It make that the physically dropping only run after the gc_safepoint is changed again. Which will slow down the data disk reclaim.
* If physically dropping a table is skipped by regions are not totally removed, set `succeeded = false`
* Then the `last_gc_safepoint` will not get updated
* And after `ddl_sync_interval_seconds` passed, `SchemaSyncService::gc` …

ddl: Do not succee the last_gc_safepoint when physically dropping table is skipped

---

dbms/src/Storages/S3/FileCache.cpp
dbms/src/Storages/S3/FileCache.h
dbms/src/Storages/S3/tests/gtest_filecache.cpp

Issue Number: close #8920
Tests 
- Run queries and make used size of file cache growth.
- Update config make size limitation of file cache smaller.
- Restart CNs.
- Before this PR, the used size of metrics is underflow:
- After this PR, the used size of metrics meet expectations:
Side effects
Documentation
```release-note
None
```

Disagg: fix used size metrics of FileCache

---

.gitignore
CMakePresets.json
README.md
release-centos7-llvm/gen_coverage.sh

Issue Number: ref https://github.com/pingcap/tiflash/issues/8889
Add a script for generating code coverage script.
The code coverage report could help find out the not-covered branches for refactoring. For example, prevent the bug of https://github.com/pingcap/tiflash/issues/8904 which was introduced during refactoring and non covered code path
Tests 
Side effects
Documentation
```release-note
None
```

tests: Add code coverage scripts

---

dbms/src/Columns/ColumnConst.h
dbms/src/Columns/ColumnVector.h
dbms/src/Columns/IColumn.h
dbms/src/Columns/tests/gtest_column_insertFrom.cpp
tests/tidb-ci/fullstack-test-dt/timestamp_with_timezone.test

Issue Number: ref #8904
I used `insertManyFrom` in https://github.com/pingcap/tiflash/pull/8854, where the source column is a const column while the target column is not and it causes #8904. To fix this, add `insertMany` interface to avoid convert const column to full column.
Tests 
Side effects
Documentation
```release-note
None
```

Add insertMany interface for IColumn

---

dbms/src/Flash/ResourceControl/MockLocalAdmissionController.h

Issue Number: close https://github.com/pingcap/tiflash/issues/8860
```
>  ninja gtests_dbms tiflash -j32                                                                                                                                                                               2024-04-12 18:03:07
[0/2] Re-checking globbed directories...
[41/44] Building CXX object dbms/src/Server/CMakeFiles/tiflash-server-lib.dir/Server.cpp.o
FAILED: dbms/src/Server/CMakeFiles/tiflash-server-lib.dir/Server.cpp.o 
/DATA/disk1/ra_common/tiflash-env-15/sysroot/bin/ccache /DATA/disk1/ra_common/tiflash-env-15/sysroot/bin/clang++ -DAWS_SDK_VERSION_MAJOR=1 -DAWS_SDK_VERSION_MINOR=11 -DAWS_SDK_VERSION_PATCH=186 -DBOOST_BIND_GLOBAL_PLACEHOLDERS -DBOOST_NO_CXX98_FUNCTION_BASE …
```

*: Fix compile error

---

dbms/src/TiDB/Schema/SchemaSyncService.cpp
dbms/src/TiDB/Schema/SchemaSyncService.h
dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/8911
After https://github.com/pingcap/tiflash/pull/8910, if some tables are not able to be dropped, `SchemaSyncService::gcImpl` will run again with the same gc_safepoint.
But in this path, `SchemaSyncService::gcImpl` always return true. So if there are some tables can not be dropped for some bugs, then this function will run again and again and print lots of loggings.
if `succeeded == false`, then let `SchemaSyncService::gcImpl` run again after `ddl_sync_interval_seconds`
Tests 
Side effects
Documentation
```release-note
None
```

ddl: Fix logging cause by non-dropped table

---

contrib/protobuf-cmake/CMakeLists.txt
dbms/CMakeLists.txt
dbms/src/IO/Compression/CompressionCodecDelta.cpp

Tests 
Side effects
Documentation
```release-note
None
```

*: fix release build when enable PCH

---

dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.h
dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.h
dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task_pool.cpp

- Avoid using the macro `DBMS_PUBLIC_GTEST` by declaring friend class and move some test functions in the TestFixture class.
Tests 
Side effects
Documentation
```release-note
None
```

Storages: Remove some `DBMS_PUBLIC_GTEST` hacks

---

dbms/src/TiDB/Schema/SchemaSyncService.cpp
dbms/src/TiDB/Schema/TiDBSchemaManager.h
dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/8968, close https://github.com/pingcap/tiflash/issues/8911
https://github.com/pingcap/tiflash/pull/8955 introduced a check on the cache gc_safepoint is not updated, but the background task of DDL sync make the ut unstable
* Disable the background task when `profiles.default.ddl_sync_interval_seconds == 0`
* Refine the code in `TiDBSchemaManager.h` with comments on locking `schema_syncers_mutex`
* Refine the code in `SchemaSyncTest` to use temporary instance instead of the instance in `global_context`
Tests 
Side effects
Documentation
```release-note
None
```

tests: Fix unstable schema test

---

dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetSnapshot.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetSnapshot.h
dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
dbms/src/Storages/DeltaMerge/DeltaIndex.h
dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/Segment.h
dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task.cpp
dbms/src/Storages/KVStore/Read/LearnerReadWorker.cpp
dbms/src/Storages/KVStore/Read/LearnerReadWorker.h

Issue Number: ref https://github.com/pingcap/tiflash/issues/8864
* Add the index to wait in learner read logging
* Add logging about place index result and snapshot rows/deletes
```
[2024/04/21 00:33:40.417 +08:00] [DEBUG] [Segment.cpp:2422] ["Begin segment getReadInfo <segment_id=1 epoch=1 range=[-9223372036854775808,9223372036854775807)>"] [thread_id=1]
[2024/04/21 00:33:40.418 +08:00] [DEBUG] [StableValueSpace.cpp:487] ["start_ts: 18446744073709551615, enable_handle_clean_read: false, is_fast_mode: false, enable_del_clean_read: false"] [source="segment_id=1 epoch=1"] [thread_id=1]
[2024/04/21 00:33:40.418 +08:00] [DEBUG] [DMFilePackFilter.cpp:118] ["RSFilter exclude rate: 0.00, after_pk: 2, after_read_packs: 2, after_filter: 2, handle_ranges: {[1,9223372036854775807)}, …
```

Storage: Refine logging about reading snap, place index, index to wait

---

dbms/src/Storages/KVStore/Read/LearnerReadWorker.cpp
dbms/src/Storages/KVStore/Read/ReadIndexDataNode.cpp
dbms/src/Storages/KVStore/Read/ReadIndexWorkerManager.cpp

Issue Number: ref #8845
Without this PR, we can't find correspondence between read index request and result.
Tests 
Side effects
Documentation
```release-note
None
```

KVStore: Add some log for Learner Read

---

dbms/src/Common/FailPoint.cpp
dbms/src/Flash/Pipeline/Schedule/Reactor/WaitReactor.cpp
dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeer.cpp
dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeerContext.cpp
dbms/src/Storages/KVStore/tests/gtest_kvstore_fast_add_peer.cpp

Issue Number: close #8988
Tests 
Side effects
Documentation
```release-note
None
```

KVStore: Fix exception in FAP worker

---

dbms/src/Storages/DeltaMerge/Filter/Equal.h
dbms/src/Storages/DeltaMerge/Filter/Greater.h
dbms/src/Storages/DeltaMerge/Filter/GreaterEqual.h
dbms/src/Storages/DeltaMerge/Filter/In.h
dbms/src/Storages/DeltaMerge/Filter/IsNull.h
dbms/src/Storages/DeltaMerge/Filter/Less.h
dbms/src/Storages/DeltaMerge/Filter/LessEqual.h
dbms/src/Storages/DeltaMerge/Filter/NotEqual.h
dbms/src/Storages/DeltaMerge/Filter/PushDownFilter.h
dbms/src/Storages/DeltaMerge/Filter/RSOperator.h

1. Use template function to replace macro `GET_RSINDEX_FROM_PARAM_NOT_FOUND_RETURN_DIRECTLY`.
2. Remove inherit from `enable_shared_from_this` in `RSOperator` and `PushDownFilter` since `shared_from_this` is not used.
Tests 
Side effects
Documentation
```release-note
None
```

Storages: Use template to replace macro in RSOperator

---

dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
dbms/src/Storages/DeltaMerge/DeltaIndex.h
dbms/src/Storages/DeltaMerge/DeltaPlace.h
dbms/src/Storages/DeltaMerge/DeltaTree.h
dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.h
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_value_space.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp

Issue Number: close #8845
1. Add a `max_dup_tuple_id` in `DeltaTree.h`.
2. Record the max duplucated tuple id in `DeltaPlace.h`.
3. Make sure the snapshot includes all duplicated tuples in the delta index when cloning the delta index in `DeltaIndex.h`.
Tests 
Side effects
Documentation
```release-note
Fix the potential issue that tiflash returns transient inconsistent results under high concurrent read
```

Storages: Fix cloning delta index when there are duplicated tuples

---

dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
dbms/src/Storages/DeltaMerge/DeltaIndex.h
dbms/src/Storages/DeltaMerge/DeltaPlace.h
dbms/src/Storages/DeltaMerge/DeltaTree.h
dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.h
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_value_space.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp

cherry-pick of https://github.com/pingcap/tiflash/pull/9000 to release-8.1
* * *
Issue Number: close #8845
1. Add a `max_dup_tuple_id` in `DeltaTree.h`.
2. Record the max duplucated tuple id in `DeltaPlace.h`.
3. Make sure the snapshot includes all duplicated tuples in the delta index when cloning the delta index in `DeltaIndex.h`.
Tests 
Side effects
Documentation
```release-note
Fix the potential issue that tiflash returns transient inconsistent results under high concurrent read
```

Storages: Fix cloning delta index when there are duplicated tuples (release-8.1) (#9000)

---

dbms/src/Common/FailPoint.cpp
dbms/src/Flash/Pipeline/Schedule/Events/AggregateFinalConvertEvent.cpp
dbms/src/Flash/Pipeline/Schedule/Events/AggregateFinalConvertEvent.h
dbms/src/Flash/Planner/Plans/PhysicalAggregationBuild.cpp
dbms/src/Flash/tests/gtest_spill_aggregation.cpp
dbms/src/Interpreters/AggSpillContext.cpp
dbms/src/Interpreters/Aggregator.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/9022
See https://github.com/pingcap/tiflash/issues/9022.
1. Add agg final spill event if have spill data
2. Parallelize converting when spill is triggered by inserting `AggregateFinalConvertEvent` first.
Add a unit test to test this bug. For the original code, the test will fail due to wrong result.
Tests 
Side effects
Documentation
```release-note
None
```

Add agg final spill event if have spill data

---

dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.h
dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task_pool.cpp

Issue Number: close #9024
- Add `pending_pools`: pools from computational layer will be added to `pending_pools` and can return immediately.
- `sched_thread` will reap `pending_pools` before calling `scheduleOneRound`.
Tests 
- Run queries without any exceptions. 
Side effects
Documentation
```release-note
None
```

Storages: Refine SegmentReadTaskScheduler::add to reduce lock contention

---

dbms/src/Storages/DeltaMerge/DeltaTree.h

Issue Number: ref #8845
- `DeltaTree::swap` need to swap `max_dup_tuple_id`. **Luckily, `DeltaTree::swap` is only used in tests**.
- Delete `DeltaTree::operator=` because it is not used.
Tests 
Side effects
Documentation
```release-note
None
```

Storages: Fix max_dup_tuple_id in DeltaTree::swap

---

dbms/src/Storages/KVStore/FFI/JointThreadAllocInfo.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/9043
As the issue describe
Shorten the thread name to be within const char[15]
Tests 
Side effects
Documentation
```release-note
None
```

*: Fix too long thread name make TSAN failed to run

---

dbms/src/Storages/DeltaMerge/StoragePool/StoragePool.cpp
dbms/src/Storages/Page/V3/tests/gtest_page_storage_mix_mode.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/9039
https://github.com/pingcap/tiflash/issues/9039#issuecomment-2108567189
The root cause is:
1. When the cluster upgrade from version lower than v6.5.0 to higher or equal to v6.5.0, TiFlash will try to migrate the data from PageStorage V2 to PageStorage V3.
2. When the table has no data in the delta layer, it will run under PageStorage V3 mode
3. But we get a wrong `max_id` for this situation, we must use `max_data_page_id = std::max(data_storage_v2->getMaxId(), data_storage_v3->getMaxId());` to avoid the page_id from being mis-reused. Otherwise it will cause data corruption and make tiflash fails to restart in the next restart
https://github.com/pingcap/tiflash/blob/eb6272c66624da39cde5e3b8605982a6db437de1/db …

Storage: Fix page_id being mis-reuse when upgrade from cluster < 6.5

---

dbms/src/Storages/DeltaMerge/StoragePool/StoragePool.cpp
dbms/src/Storages/Page/V3/tests/gtest_page_storage_mix_mode.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/9039
https://github.com/pingcap/tiflash/issues/9039#issuecomment-2108567189
The root cause is:
1. When the cluster upgrade from version lower than v6.5.0 to higher or equal to v6.5.0, TiFlash will try to migrate the data from PageStorage V2 to PageStorage V3.
2. When the table has no data in the delta layer, it will run under PageStorage V3 mode
3. But we get a wrong `max_id` for this situation, we must use `max_data_page_id = std::max(data_storage_v2->getMaxId(), data_storage_v3->getMaxId());` to avoid the page_id from being mis-reused. Otherwise it will cause data corruption and make tiflash fails to restart in the next restart
https://github.com/pingcap/tiflash/blob/eb6272c66624da39cde5e3b8605982a6db437de1/db …

Storage: Fix page_id being mis-reuse when upgrade from cluster < 6.5 (release-8.1)

---

dbms/src/Interpreters/Context.h
dbms/src/Storages/KVStore/FFI/JointThreadAllocInfo.cpp
dbms/src/Storages/KVStore/FFI/JointThreadAllocInfo.h
dbms/src/Storages/KVStore/FFI/ProxyFFI.cpp
dbms/src/Storages/KVStore/KVStore.cpp
dbms/src/Storages/KVStore/KVStore.h
dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp
dbms/src/Storages/KVStore/tests/region_kvstore_test.h

Issue Number: close #9038
Tests 
Side effects
Documentation
```release-note
None
```

*: Use static to avoid thread-wise memtrace lifetime problem

---

dbms/src/Common/FailPoint.cpp
dbms/src/Storages/StorageDeltaMerge.cpp
dbms/src/Storages/StorageDeltaMerge.h
dbms/src/TiDB/Schema/SchemaBuilder.cpp
dbms/src/TiDB/Schema/SchemaBuilder.h
dbms/src/TiDB/Schema/SchemaNameMapper.h
dbms/src/TiDB/Schema/TiDBSchemaSyncer.h
tests/fullstack-test2/ddl/alter_exchange_partition.test

Issue Number: close https://github.com/pingcap/tiflash/issues/7296
When `tryLoadSchemaDiffs` fails, we may run into `SchemaBuilder::syncAllSchem` -> `applyPartitionDiff` without `applyExchangeTablePartition`
The physical table maybe `EXCHANGE` to another database, we need to try to find the partition from all database rather than just using the database of the target partitioned table
try to find the partition from all database rather than just using the database of the target partitioned table
Tests 
Side effects
Documentation
```release-note
Fix the issue that TiFlash may fail to finish schema sync after executing `ALTER TABLE ... EXCHANGE PARTITION` across databases
```

ddl: Fix exchange partition across databases (release-7.1)

---

README.md

Issue Number: close #9074
```commit-message
Boring change to test commit message by bot
```
Tests 
Side effects
Documentation
```release-note
None
```

chore: Test commit message

---

dbms/src/Common/MemoryAllocTrace.cpp

Issue Number: close #8835
```commit-message
Fix USE_JEMALLOC macro
```
Tests 
Side effects
Documentation
```release-note
None
```

*: Fix USE_JEMALLOC macro

---

dbms/src/Storages/KVStore/FFI/JointThreadAllocInfo.cpp
dbms/src/Storages/KVStore/FFI/JointThreadAllocInfo.h
dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp
dbms/src/Storages/KVStore/tests/gtest_raftstore_v2.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/9090, ref https://github.com/pingcap/tiflash/issues/8835
Introduced by https://github.com/pingcap/tiflash/pull/9064, some tests that require jemalloc does not work well when tiflash is not compiled with jemalloc. For example, when compiled under `ASAN`/`TSAN`
https://github.com/pingcap/tiflash/blob/7cb240c9e86ff4cecdeb7cba40a373556f7f4738/libs/libcommon/cmake/find_jemalloc.cmake#L20-L23
* Disable `FFIJemallocTest.JemallocThread` and `RegionKVStoreTest.StorageBgPool` when jemalloc is not enabled
* Refine the method of `ThreadInfoJealloc`
```commit-message
Disable some tests when jemalloc is not enabled
```
Tests 
```
cmake .. -GNinja -DCMAKE_BUILD_TYPE=TSAN -DENABLE_TESTS=ON
ninja gtests_dbms tiflash -j32 …
```

tests: Disable some tests when jemalloc is not enabled

---

dbms/src/Flash/Mpp/MPPTaskManager.cpp
dbms/src/Flash/Mpp/MPPTaskManager.h
dbms/src/Storages/KVStore/TMTContext.cpp
tests/sanitize/tsan.suppression

Issue Number: close https://github.com/pingcap/tiflash/issues/9092, close https://github.com/pingcap/tiflash/issues/9097
For #9092
TMTContext will start a thread "MPPTask-Moniter" for running `checkLongLiveMPPTasks`.
https://github.com/pingcap/tiflash/blob/38ab3f912220b94962043bde7cc341017d569994/dbms/src/Storages/KVStore/TMTContext.cpp#L121-L126
When the TiFlash is shutting down, the thread is not explicitly stopped. And the thread may live longer than the TiFlashMetrics instance. If the TiFlashMetrics instance is released before `checkLongLiveMPPTasks` run, then `checkLongLiveMPPTasks` will access to a random address and cause use-after-free data race when shutting down.
For #9097
Seems the race is reported in `backtrace-rs`, there is nothing we can do in tiflash code, …

tests: Fix MPPTask-Moniter may live longer than TiFlashMetrics

---

dbms/src/Common/TiFlashMetrics.h
metrics/grafana/tiflash_summary.json

Issue Number: close #8835
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

*: Use prefix tiflash_ for thread-wise memory alloc info

---

dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/Segment.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_for_fast_scan.cpp

Issue Number: close #9118
```commit-message
Shrinking the read ranges of FastScan.
```
Tests 
Side effects
Documentation
```release-note
Fix the read ranges of FastScan to reduce duplicate data
```

Storages: Fix read ranges of FastScan

---

dbms/src/Storages/DeltaMerge/ReadThread/ColumnSharingCache.cpp
dbms/src/Storages/DeltaMerge/ReadThread/ColumnSharingCache.h

Issue Number: close #9125 
```commit-message
```
Tests 
- Run simple queries (`select max(k) from sbtest1`) concurrently.
- Time consumption unit: ms.
| Concurrency  |  Master | This PR  |
|-- | -- | -- |
|1 | 27 | 25|
|2 | 28 | 29|
|4 | 46 | 46|
|8 | 72 | 77|
|16 | 124 | 97|
|32 | 232 | 160|
|64 | 450 | 327|
</byte-sheet-html-origin>
Side effects
Documentation
```release-note
Improve the short queries performance under high concurrency by reducing the lock contention
```

Storages: Splitting DMFileReaderPool to reduce lock contention

---

dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
dbms/src/Storages/DeltaMerge/File/ColumnStream.cpp
dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.cpp
dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
dbms/src/Storages/DeltaMerge/Index/RSResult.h
dbms/src/Storages/DeltaMerge/ScanContext.cpp
dbms/src/Storages/DeltaMerge/ScanContext.h
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp

Issue Number: close #9103
```commit-message
1. Change `std::vector<UInt8> use_packs;` to `std::vector<RSResult> pack_res;`. 
2. Add statistical data of filtering results in `ScanContext`.
```
Tests 
Side effects
Documentation
```release-note
None
```

Storages: Change the element type of `use_pack` from `bool` to `RSResult` in `DMFilePackFilter`

---

.github/licenserc.yml
contrib/tiflash-proxy-cmake/CMakeLists.txt
libs/libprocess_metrics/CMakeLists.txt
libs/libsymbolization/CMakeLists.txt
rust-toolchain.toml

Issue Number: ref #4982, close https://github.com/pingcap/tiflash/issues/9147
update proxy to upgrade-near-8.2
Proxy PR: 
Including:\nSubmodule contrib/tiflash-proxy 7dc50b4eb0..0d76d66782:
> adapt to upgrade-near-8.2
> Merge remote-tracking branch 'tikv/master' into upgrade-near-8.2
> Add approvers (#373)
> Strengthen configuration change approval (#371)
> Add log for current ReadIndex mechanism (#370)
> Add some tests for replica read (#369)
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

update proxy of master to upgrade-near-8.2

---

dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp

Issue Number: ref #9103
```commit-message
```
- Before this PR, `checkIsNull` will never return `RSResult::All`.
- This PR makes `checkIsNull` return `RSResult::All` if a pack conatins null marks and no value (maybe some delete marks exists).
Tests 
Side effects
Documentation
```release-note
None
```

Storages: MinMaxIndex::checkIsNull returns RSResult::All if a pack only contains null marks and delete marks

---

dbms/src/Common/Checksum.h
dbms/src/Storages/DeltaMerge/Decode/SSTFilesToBlockInputStream.cpp
dbms/src/Storages/KVStore/KVStore.h
dbms/src/Storages/KVStore/Read/ReadIndex.cpp
dbms/src/Storages/KVStore/Region.cpp
dbms/src/Storages/KVStore/tests/gtest_kvstore.cpp

```commit-message
```
* Log the logging as warning level when `WaitCheckRegionReadyImpl ` take more than 60 seconds
* Add `keyspace` to `Region::getDebugString`
* Add some comments
* Fix the time unit is wrong in logging introduced by https://github.com/pingcap/tiflash/pull/9155
Tests 
Side effects
Documentation
```release-note
None
```

KVStore: Add comments and refine logging about WaitCheckRegionReady

---

dbms/src/Storages/DeltaMerge/Decode/SSTFilesToBlockInputStream.cpp
dbms/src/Storages/KVStore/FFI/SSTReader.cpp
dbms/src/Storages/KVStore/FFI/SSTReader.h
dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
dbms/src/Storages/KVStore/tests/region_kvstore_test.h

Issue Number: close https://github.com/pingcap/tiflash/issues/8081
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

KVStore: More log for Parallel Prehandle

---

CMakeLists.txt
README.md

Issue Number: close #8898, close #7193
cmake need to be upgrade to 3.23 at least for building under mac os with clang 14.0.0
```commit-message
update minimum cmake version to 3.23
```
Tests 
Side effects
Documentation
```release-note
None
```

*: update minimum cmake version to 3.23

---

.clang-tidy

Issue Number: close #9165
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

clang-tidy: ignore unknown pragmas warnings

---

dbms/src/Flash/Planner/PhysicalPlan.cpp

Issue Number: ref #9087
Last logged info is: https://github.com/pingcap/tiflash/blob/f6071b34ea1ab60f2484b2af50fd0eef82a5c233/dbms/src/Flash/Planner/PhysicalPlan.cpp#L302
Thus pipeline dag log is not logged. Add more debug info to locate the actual place. 
Tests 
Side effects
Documentation
```release-note
None
```

Add debug log info to locate random fmt exception

---

dbms/src/Debug/MockKVStore/MockRaftStoreProxy.h
dbms/src/Server/Server.cpp
dbms/src/Storages/KVStore/KVStore.cpp
dbms/src/Storages/KVStore/KVStore.h
dbms/src/Storages/KVStore/TMTContext.cpp
dbms/src/Storages/KVStore/TMTContext.h
dbms/src/Storages/KVStore/tests/gtest_raftstore_v2.cpp

Issue Number: close #8382
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

KVStore: Get addressed engine-addr from proxy

---

dbms/src/Storages/DeltaMerge/DeltaMergeDefines.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
tests/fullstack-test/expr/duration_filter_late_materialization2.test

Issue Number: close #9175
Problem Summary:  #9175
```commit-message
```
```
+------------------------+---------+--------------+---------------+--------------------------------------------------------------------+
| id                     | estRows | task         | access object | operator info                                                      |
+------------------------+---------+--------------+---------------+--------------------------------------------------------------------+
| TableReader_13         | 128.00  | root         |               | MppVersion: 2, data:ExchangeSender_12                              |
| └─ExchangeSender_12    | 128.00  | mpp[tiflash] |               | ExchangeType: PassThrough                                          |
|   └─Projection_5       | 128.00  | …
```

Storages: Fix returned column types may not match in late-materialization

---

release-centos7-llvm/dockerfiles/misc/prepare_basic.sh

CentOS 7 has reached EOL. and the mirror.centos.org and mirrorlist.centos.org is offline.
Issue Number: close #9179
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

build: fix docker image misc script

---

dbms/src/Storages/DeltaMerge/Decode/SSTFilesToBlockInputStream.cpp
dbms/src/Storages/DeltaMerge/Decode/SSTFilesToBlockInputStream.h
dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp

Issue Number: ref https://github.com/pingcap/tiflash/issues/8081
I'd like to introduce a new layer `SnapshotSSTReader` and move `getApproxBytes`/`findSplitKeys` into that layer. This could make the logic in parallel prehandle snapshots more clear.
This PR is a preceding PR that refactors the code to simplify the following logical change.
New `SnapshotSSTReader` interface in later PR:
```
struct SnapshotSSTReader
{
SnapshotSSTReader(
const SSTViewVec & snaps,
const TiFlashRaftProxyHelper * proxy_helper,
RegionID region_id,
UInt64 snapshot_index,
const ImutRegionRangePtr & region_range,
std::optional<SSTScanSoftLimit> && soft_limit,
const String & log_prefix);
// Currently it only takes effect if using tablet sst reader which is usually a raftstore v2 case.
// Otherwise …
```

KVStore: Refine parallel prehandle snapshot (part-1)

---

dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp

Issue Number: ref #9087
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

fix fmt error

---

dbms/src/Flash/tests/gtest_compute_server.cpp

Issue Number: ref #8285
```commit-message
In #9194, sleep time is changed to 8s in sanitizer mode. However, the case still failed occasionally. So change to a larger time span. 
```
Tests 
Side effects
Documentation
```release-note
None
```

Adjust sanitizer sleep time for cancelMPPGather

---

CMakePresets.json

Issue Number: close #8826
```commit-message
```
```shell
> ls cmake-build-coverage
ls: cannot access 'cmake-build-coverage': No such file or directory
> cmake --list-presets
Available configure presets:
"dev"          - Development: DEBUG build with tests enabled
"dev-coverage" - Development: DEBUG build with tests and code coverage enabled
"release"      - Release: RELWITHDEBINFO build without tests enabled
"asan"         - AddressSanitizer: ASAN build with tests enabled
"tsan"         - ThreadSanitizer: TSAN build with tests enabled
"benchmarks"   - Benchmarks: RELEASE build with benchmarks enabled
> cmake --preset=dev-coverage
Preset CMake variables:
CMAKE_BUILD_TYPE="DEBUG"
ENABLE_TESTS="ON"
TEST_LLVM_COVERAGE="ON"
...
> ls cmake-build-coverage
build.ninja …
```

*: Add binaryDir to CMakePresets.json

---

dbms/src/Storages/KVStore/tests/gtest_tikv_keyvalue.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/7563
Problem Summary: Add ut for parsing lock value
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

tests: Add ut for parsing lock value

---

dbms/src/Common/TiFlashSecurity.h
dbms/src/Common/tests/gtest_tiflash_security.cpp
dbms/src/Server/Server.cpp
dbms/src/Storages/DeltaMerge/DeltaTree.h

Issue Number: close https://github.com/pingcap/tiflash/issues/9235
TiFlash fails to start with following configs
```
[security]
ca_path = ""
cert_path = ""
key_path = ""
```
If any of the `security.ca_path`/`security.cert_path`/`security.key_path` is empty, treat it as missing.
And if all of the three config are not exist or empty strings, TLS is disabled in tiflash.
```commit-message
security: allow empty `security.ca_path`/`security.cert_path`/`security.key_path`
```
Tests 
Side effects
Documentation
```release-note
Fix a bug that empty SSL config strings will enable TLS for tiflash
```

security: Allow empty security config for disabling tls

---

dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
dbms/src/Storages/IManageableStorage.h
dbms/src/Storages/StorageDeltaMerge.cpp
dbms/src/Storages/TableNameMeta.h

Issue Number: ref https://github.com/pingcap/tiflash/issues/9233
A part of fixing #9233. In the previous code, updating `DeltaMergeStore::db_name` is not atomic.
```commit-message
Make renaming `DeltaMergeStore::db_name` to be atomic
```
Tests 
Side effects
Documentation
```release-note
None
```

ddl: Atomic rename `DeltaMergeStore::db_name` in memory

---

dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.cpp
dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/StableValueSpace.cpp

Issue Number: ref #9103
In table scanning, DMFilePackFilter of a DMFile may be created several times:
1. When building MVCC bitmap (ReadTag::MVCC).
2. When building LM filter stream (ReadTag::LM).
3. When building stream of other columns (ReadTag::Query).
Only need to count the filter result once.
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Storages: Fix statistical data of DMFilePackFilter

---

README.md
dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
tests/sanitize/tsan.suppression

Issue Number: close https://github.com/pingcap/tiflash/issues/9257
The TSAN will failed when one thread hold locks larger than 64. `StoreIngestTest.ConcurrentIngestAndWrite` will try to do "segmentMerge" on many segments (more than 500), causing this problem.
> The code in question is in lib/sanitizer_common/sanitizer_deadlock_detector.h
It limits the number of simultaneously held locks in a given thread to an arbitrary large number 64.
If you hold 65 locks in one thread at once, this will fail.
```commit-message
```
* Limit the segments to be merged under tsan
* Suppress a data race on xxh3
Tests 
Side effects
Documentation
```release-note
None
```

tests: Limit the segments to be merged under tsan to suppress deadlock

---

dbms/src/Common/TiFlashMetrics.h
dbms/src/Storages/DeltaMerge/ReadThread/WorkQueue.h
metrics/grafana/tiflash_summary.json

Issue Number: ref #6834
```commit-message
```
- Block pop-up latency when a query is heavy (sometime it means computing is the bottleneck):  
- Block pop-up latency when a query is light (sometime it means storage is the bottleneck):
Tests 
Side effects
Documentation
```release-note
None
```

Storages: Add Block pop-up latency metrics

---

dbms/src/DataStreams/RuntimeFilter.cpp
dbms/src/DataStreams/RuntimeFilter.h
dbms/src/Debug/MockStorage.cpp
dbms/src/Debug/MockStorage.h
dbms/src/Flash/Pipeline/Schedule/Tasks/RFWaitTask.h
dbms/src/Flash/Planner/Plans/PhysicalMockTableScan.cpp
dbms/src/Flash/Planner/Plans/PhysicalMockTableScan.h
dbms/src/Storages/DeltaMerge/ColumnDefine_fwd.h
dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp
dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.h
dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
dbms/src/Storages/StorageDeltaMerge.cpp
dbms/src/Storages/StorageDeltaMerge.h
dbms/src/Storages/StorageDisaggregatedRemote.cpp
dbms/src/Storages/tests/gtest_filter_parser.cpp
dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp
dbms/src/TiDB/Schema/TiDB.h
tests/fullstack-test/expr/generated_columns.test
tests/fullstack-test/expr/generated_columns2.test
tests/fullstack-test/expr/runtime_filter.test

This is an manual cherry-pick of #9189
Issue Number: close #9188
When parsing some column expressions, it may need  to use column index to obtain column information, but since virtual columns are filtered out before being sent to the storage layer, the original columns and the columns for storage to read are 
inconsistency.
```commit-message
1. Use the original columns  in `query_info.dag_query` instead of `columns_to_read` when building `RSOperator`.
2. For runtime filters, creating the `DM::Attr` object in `StorageDeltaMerge::read`, so it doesn't need to rely on `column_to_read`.
```
3. Currently, if a query contains virtual columns, hash join will not be pushed down to TiFlash. So in fact, runtime filters will not occur when a query contains virtual columns. But in …

Storages: Fix obtaining incorrect column information when there are virtual columns in the query (release-8.1)

---

dbms/src/Storages/KVStore/tests/gtest_async_tasks.cpp
dbms/src/Storages/Page/V3/Universal/UniversalWriteBatchImpl.h
dbms/src/Storages/Page/V3/Universal/tests/gtest_universal_page_storage.cpp

Issue Number: ref #9241 close #9250
```commit-message
Support generating adhoc heap profiling in svg format
```
Tests 
Side effects
Documentation
```release-note
Support generating adhoc heap profiling in svg format
支持生成即席的 heap profiling 的 svg 图
```

*: Support generating adhoc heap profiling in svg format

---

dbms/src/Debug/MockTiDB.cpp
dbms/src/TiDB/Schema/SchemaBuilder.cpp
dbms/src/TiDB/Schema/SchemaBuilder.h
dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp
tests/fullstack-test2/ddl/rename_table_across_databases.test

Issue Number: close https://github.com/pingcap/tiflash/issues/9266
In `InterpreterRenameQuery`, it use `context.getDatabase` which will throw an exception if the database instance is not exist in tiflash.
The database has been dropped in TiDB before TiFlash sync the schema diff of "create database". And the following rename table to that database (database_id=170) throw exception.
| TiDB | TiFlash |
| --- | --- |
| create table db_2.t_166; | |
| | sync create table db_2.t_166 and success |
| create database db_170; | |
| rename table db_2.t_166 to db_170.t_166; | |
| drop table db_170.t_166; | |
| drop database db_170; | |
|  | raft-log comes after database has been dropped, tiflash begin its schema sync |
|  | begin to sync create db_170 but failed sliently |
|  | begin …

ddl: Fix rename come after database has been dropped

---

dbms/src/Debug/MockTiDB.cpp
dbms/src/TiDB/Schema/SchemaBuilder.cpp
dbms/src/TiDB/Schema/SchemaBuilder.h
dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp
tests/fullstack-test2/ddl/rename_table_across_databases.test

cherry-pick of https://github.com/pingcap/tiflash/pull/9274
Issue Number: close https://github.com/pingcap/tiflash/issues/9266
In `InterpreterRenameQuery`, it use `context.getDatabase` which will throw an exception if the database instance is not exist in tiflash.
The database has been dropped in TiDB before TiFlash sync the schema diff of "create database". And the following rename table to that database (database_id=170) throw exception.
| TiDB | TiFlash |
| --- | --- |
| create table db_2.t_166; | |
| | sync create table db_2.t_166 and success |
| create database db_170; | |
| rename table db_2.t_166 to db_170.t_166; | |
| drop table db_170.t_166; | |
| drop database db_170; | |
|  | raft-log comes after database has been dropped, tiflash begin its schema sync |
|  | …

ddl: Fix rename come after database has been dropped (release-7.5)

---

dbms/src/Columns/ColumnArray.cpp
dbms/src/Columns/ColumnArray.h
dbms/src/Flash/Coprocessor/ArrowColCodec.cpp
dbms/src/Flash/Coprocessor/TiDBChunk.cpp
dbms/src/Flash/Coprocessor/TiDBColumn.cpp
dbms/src/Flash/Coprocessor/TiDBColumn.h
dbms/src/Flash/Coprocessor/tests/gtest_streaming_writer.cpp
dbms/src/TiDB/Schema/TiDB.h

`TiDBColumn::data` and `TiDBColumn::finishAppendVar` should not be exposed as public
```commit-message
```
* Add `TiDBColumn::appendVectorF32` and `ColumnArray::getElementRef` to replace the origin implementation
* Use `encodeLittleEndian` in `TiDBColumn::appendVectorF32` instead of exception checking
Tests 
Side effects
Documentation
```release-note
None
```

coprocessor: Refactor encoding `TiDBColumn`

---

dbms/src/Common/UniThreadPool.h
dbms/src/Storages/Page/V3/Blob/BlobStat.cpp
dbms/src/Storages/Page/V3/BlobStore.cpp
dbms/src/Storages/Page/V3/BlobStore.h
dbms/src/Storages/Page/V3/PageEntry.h
dbms/src/Storages/Page/V3/spacemap/SpaceMap.cpp
dbms/src/Storages/Page/V3/spacemap/SpaceMap.h
dbms/src/Storages/Page/V3/spacemap/SpaceMapSTDMap.h
dbms/src/Storages/Page/V3/tests/gtest_blob_stat.cpp
dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
dbms/src/Storages/Page/V3/tests/gtest_free_map.cpp
dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/9282
By dumping the entries from PageStorage WAL, we can locate that two entries cause this issue:
```
[PageDirectoryFactory.cpp:225] ["{type:VAR_ENT, page_id:0x020102000000009CA4430A08, ori_id:0x.0, version:108969363.0, entry:PageEntry{file: 551, offset: 0x15376, size: 0, checksum: 0x0, tag: 0, field_offsets: [], checkpoint_info: invalid}, being_ref_count:1}"] [thread_id=1]
[PageDirectoryFactory.cpp:225] ["{type:PUT    , page_id:0x020102000000018204A17C03, ori_id:0x.0, version:127726467.0, entry:PageEntry{file: 551, offset: 0x15373, size: 15, checksum: 0x12D46C1C0D5B51FE, tag: 0, field_offsets: [], checkpoint_info: invalid}, being_ref_count:1}"] [thread_id=1]
```
The first entry is a page with data.size == 0, …

PageStorage: Fix empty page cause TiFlash failed to start

---

dbms/src/Interpreters/Aggregator.h

Issue Number: close #9306
```
2024-08-09T16:38:58.501736078+08:00 /Users/pingcap/workspace/bp-tiflash-release-darwin-amd64-m7wlv-build-binaries/source/tiflash/dbms/src/Operators/AutoPassThroughHashAggContext.cpp:64:45: note: in instantiation of function template specialization 'std::make_shared<std::vector<unsigned long long>, std::vector<unsigned long>, void>' requested here
2024-08-09T16:38:58.501738228+08:00             new_block.info.selective = std::make_shared<std::vector<UInt64>>(std::move(pass_through_rows));
2024-08-09T16:38:58.501740465+08:00                                             ^
2024-08-09T16:38:58.501742711+08:00 /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__memory/construct_at.h:35:16: note: candidate template ignored: …
```

fix mac build

---

dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task.cpp

Issue Number: close #9309
Background tasks may flush `MemTableSet` of delta before snapshot is created. 
```commit-message
Disable `flushCache` in some unit-tests. 
```
Tests 
Side effects
Documentation
```release-note
None
```

tests: Fix unstable unit-tests

---

CMakePresets.json
README.md

```commit-message
*: add workflow in CMakePresets
```
```shell
$ cmake --list-presets        
Available configure presets:
"dev"          - Development: DEBUG build with tests enabled
"dev-coverage" - Development: DEBUG build with tests and code coverage enabled
"release"      - Release: RELWITHDEBINFO build without tests enabled
"asan"         - AddressSanitizer: ASAN build with tests enabled
"tsan"         - ThreadSanitizer: TSAN build with tests enabled
"benchmarks"   - Benchmarks: RELEASE build with benchmarks enabled
$ cmake --build --list-presets
Available build presets:
"dev"              - Build tiflash binary with debug info and tests enabled
"unit-tests"       - Build dbms unit tests
"unit-tests-all"   - Build all unit tests …
```

*: add workflow in CMakePresets

---

dbms/src/IO/Compression/CompressionCodecFactory.cpp
dbms/src/IO/Compression/tests/gtest_codec_factory.cpp

Issue Number: close #9322
```commit-message
Compression: fix zstd compression level could be a negative number
```
Tests 
Side effects
Documentation
```release-note
None
```

Compression: fix zstd compression level be negative number

---

dbms/src/Storages/Page/V3/PageDirectory.cpp
dbms/src/Storages/Page/V3/PageDirectory.h
dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
dbms/src/Storages/Page/V3/Universal/tests/gtest_remote_read.cpp
dbms/src/Storages/Page/V3/WAL/WALReader.cpp
dbms/src/Storages/Page/V3/WALStore.cpp
dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/9307
A RemotePage
1. Ingested into a Segment by FAP
2. The Segment get logical split, two RefPage to the RemotePage is created
3. The Ingested RemotePage is deleted
4. The split left and right segment get logical split again
5. A read to the segment is performed, and the original RemotePage get updated
The sequence that PageStorage see is
```
--- The page_id '0x78000001746C0000000000000060.3359'
---  created @ ver=676072, epoch=0
---  ref by .3439 @ ver=685132
---  ref by .3441 @ ver=685134
---  deleted @ ver=685265
---  ref by .3493 @ ver=693249
---  ref by .3495 @ ver=693251
---  ref by .3497 @ ver=693272
---  ref by .3499 @ ver=693274
--- Then '.3497' get read, UPDATE_DATA_FROM_REMOTE @ ver=729397
``` …

PageStorage: Fix TiFlash may fail to restart after FAP is enabled

---

CMakeLists.txt

Executing `cmake --install` failed in the new compile env. The error message is as follow
```
> cmake .. -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo
> ninja tiflash
...
> cmake --install . --component=tiflash-release --prefix=artifacts
Install the project...
-- Install configuration: "RELWITHDEBINFO"
-- Up-to-date: /tiflash/build/release/install_tiflash/tiflash/./tiflash
CMake Error at dbms/src/Server/cmake_install.cmake:66 (file):
file Could not resolve runtime dependencies:
libc++.so.1
libc++abi.so.1
Call Stack (most recent call first):
dbms/src/cmake_install.cmake:107 (include)
dbms/cmake_install.cmake:47 (include)
cmake_install.cmake:47 (include)
```
When executing `cmake --install`, cmake will try to find …

build: make `cmake --install` work well

---

dbms/src/IO/Compression/CompressionCodecFactory.cpp

Issue Number: close #9336
```commit-message
Compression: fix lz4/lz4hc/zstd map concurrent insert
```
Tests 
Side effects
Documentation
```release-note
None
```

Compression: fix lz4/lz4hc/zstd map concurrent insert

---

dbms/src/Storages/DeltaMerge/LateMaterializationBlockInputStream.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp

Issue Number: close #9348
If Min-Max index returns RSResult::All, we will create a **EMPTY**  filter column to make some checks on block structure happy. https://github.com/pingcap/tiflash/blob/f0a4087d599a19645820b0bc9c48d9b80906541f/dbms/src/DataStreams/FilterTransformAction.cpp#L77-L85
In LateMaterializationBlockInputStream, filter_column_stream does not execute projecting to remove filter column, and will execute filtering in https://github.com/pingcap/tiflash/blob/f0a4087d599a19645820b0bc9c48d9b80906541f/dbms/src/Storages/DeltaMerge/LateMaterializationBlockInputStream.cpp#L72-L75 
This result issue #9348.
Skip filtering for filter column as https://github.com/pingcap/tiflash/blob/f0a4087d599a19645820b0bc9c48d9b80906541f/dbms/src/Storages/DeltaMerge/LateMaterialization …

Storages: Skip filtering for filter column

---

dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
dbms/src/Flash/Planner/plans/PhysicalJoin.cpp
dbms/src/Interpreters/ExpressionActions.cpp
dbms/src/Interpreters/Join.cpp
dbms/src/Interpreters/Join.h

Issue Number: close #9190
Hold shared pointer of `Join` in `NonJoinedBlockInputStream`
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

avoid potential TiFlash crash in `NonJoinedBlockInputStream`

---

dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/8652
In https://github.com/pingcap/tiflash/pull/8653 (release-7.1 cherry-pick: https://github.com/pingcap/tiflash/pull/8661) we add CPU panel for segment read task scheduler. But the thread name is not set.
The thread name is originally set in https://github.com/pingcap/tiflash/pull/8557 which refactor the scheduler.
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Set thread name for seg task scheduler

---

dbms/src/Storages/System/StorageSystemDTSegments.cpp
dbms/src/Storages/System/StorageSystemDTTables.cpp

Add a `keyspace_id` field, so that TiDB could query TiFlash system tables over it.
`mapper.displayDatabaseName` is used in some other places so that it is unchanged.
```
TiFlash :) select * from dt_segments where keyspace_id=4
SELECT *
FROM dt_segments
WHERE keyspace_id = 4
Ok.
0 rows in set. Elapsed: 0.107 sec.
TiFlash :) select * from dt_segments where keyspace_id=1
SELECT *
FROM dt_segments
WHERE keyspace_id = 1
┌─database──┬─table─────┬─tidb_database─┬─tidb_table─┬─keyspace_id─┬─table_id─┬─is_tombstone─┬─segment_id─┬─range──────────────────────────────────────┬─epoch─┬──rows─┬──────size─┬─delta_rate─┬─delta_memtable_rows─┬─delta_memtable_size─┬─delta_memtable_column_files─┬─delta_memtable_delete_ranges─┬─delta_persisted_page_id─┬─delta_persisted …
```

storage: Add keyspace_id to DT system tables

---

dbms/src/Interpreters/InterpreterSelectQuery.cpp

Issue Number: ref #9032 
A.
```
❯ ~/Work/tiflash-cse/cmake-build-Debug/dbms/src/Server/tiflash client --port=9100 --host=127.0.0.1
ClickHouse client version 1.1.54381.
Connecting to 127.0.0.1:9100.
Connected to TiFlash server version 1.1.54381.
TiFlash :) show tables;
SHOW TABLES
Received exception from server (version 1.1.54381):
Code: 49. DB::Exception: Received from 127.0.0.1:9100. DB::Exception: pingcap::Exception code=UnknownError msg=unknown error : abort: "Error(InvalidKeyMode { cmd: get, storage_api_version: V2, key: \"6D536368656D6156FF65FF7273696F6E4BFF6579FF0000000000FF000000F700000000FF0000007300000000FB\" })".
0 rows in set. Elapsed: 0.641 sec.
```
B:
```
mysql> select * from information_schema.tiflash_tables;
ERROR 1105 (HY000): rpc error: code = Internal …
```

storage: Fix TiFlash system tables cannot query in Keyspace Mode

---

dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.cpp
dbms/src/Storages/DeltaMerge/Index/RoughCheck.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
tests/fullstack-test-dt/expr/compare_null.test

Issue Number: close #9374
The filter of `select * from test.t where not (a between NULL and '2024-08-25')` will be transformed in TiFlash as `not (a between NULL and '2024-08-25')` => `not (a >= NULL and a <= '2024-08-25')` => `a < NULL or a > '2024-08-25'`.
The problem is how `RSOperator` and `MinMaxIndex` handle `a < NULL`. 
As the code below, `Less` will be transformed into `not GreaterEqual`:
https://github.com/pingcap/tiflash/blob/81cd94782a912d3a61e38b7ebc5c2cfabe5694e9/dbms/src/Storages/DeltaMerge/Filter/Less.h#L32-L37
`MinMaxIndex` execute `GreaterEqual` and the result for comparing with `NULL` is `RSResult::None`.
https://github.com/pingcap/tiflash/blob/81cd94782a912d3a61e38b7ebc5c2cfabe5694e9/dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.cpp#L422-L426
`not …

Storages: Fix comparing null in MinMaxIndex

---

dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp
dbms/src/Storages/DeltaMerge/Index/IndexInfo.h
dbms/src/Storages/System/StorageSystemDTLocalIndexes.cpp
dbms/src/Storages/System/StorageSystemDTLocalIndexes.h
dbms/src/Storages/System/attachSystemTables.cpp

Pick https://github.com/tidbcloud/tiflash-cse/pull/211
```commit-message
storage: Add system.dt_local_indexes
```
Tests 
Side effects
Documentation
```release-note
None
```

storage: Add system.dt_local_indexes

---

dbms/src/IO/IOThreadPools.h
dbms/src/IO/tests/gtest_io_thread.cpp
dbms/src/Storages/StorageDisaggregatedRemote.cpp

Issue Number: ref #9378
If exception thrown in building read tasks, exception will propagate by the future object, and the request will abort immediately. 
https://github.com/pingcap/tiflash/blob/9afd0b2d83b19af8900576b7c9b11dc6555b1af5/dbms/src/Storages/StorageDisaggregatedRemote.cpp#L102-L106
However, there are many tasks running in the thread pool and these task has caught many local variables by reference. If the request aborted before these tasks finished, these reference will be dangling.
Wait the tasks in the thread pool finished before return like before https://github.com/pingcap/tiflash/blob/e6fc04addfedf88c77403760e9bea2049648c008/dbms/src/Storages/StorageDisaggregatedRemote.cpp#L223-L225
```commit-message
```
Tests 
Side effects
Documentation
```release-note …
```

Disagg: Wait tasks in thread pool finished before return

---

dbms/CMakeLists.txt
dbms/src/Common/NotNull.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_fast_add_peer.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.cpp
dbms/src/Storages/DeltaMerge/workload/DTWorkload.cpp
dbms/src/Storages/StorageDeltaMerge.cpp
dbms/src/Storages/StorageDeltaMerge.h
dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp

```commit-message
storage: refine DeltaMergeStore
```
Tests 
Side effects
Documentation
```release-note
None
```

storage: refine DeltaMergeStore

---

dbms/src/Storages/DeltaMerge/tests/gtest_skippable_block_input_stream.cpp

https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/tiflash-sanitizer-daily/runs/2109/nodes/86/log/?start=0
```
[2024-08-28T19:08:47.150Z] ==232506==ERROR: AddressSanitizer: stack-use-after-return on address 0x7f08686ea920 at pc 0x5651201f34d0 bp 0x7ffc3b905590 sp 0x7ffc3b905588
[2024-08-28T19:08:47.150Z] READ of size 1 at 0x7f08686ea920 thread T0
[2024-08-28T19:08:47.150Z]     #0 0x5651201f34cf in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__is_long[abi:ue170006]() const /usr/local/bin/../include/c++/v1/string:1734:33
[2024-08-28T19:08:47.150Z]     #1 0x5651201f34cf in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::size[abi:ue170006]() const …
```

unittest: Fix ASAN reports of SkippableBlockInputStreamTest

---

README.md
tests/README.md

```commit-message
tests: Refine the README of running integration tests
```
Tests 
Side effects
Documentation
```release-note
None
```

tests: Refine the README of running integration tests

---

dbms/src/Storages/S3/FileCache.cpp
dbms/src/Storages/S3/FileCache.h
dbms/src/Storages/S3/tests/gtest_filecache.cpp

Pick https://github.com/tidbcloud/tiflash-cse/pull/253 and https://github.com/tidbcloud/tiflash-cse/pull/257
```commit-message
storage: Force evict when downloading vector index files
```
Tests 
Side effects
Documentation
```release-note
None
```

storage: Force evict when downloading vector index files

---

dbms/src/Common/UniThreadPool.cpp
dbms/src/Common/UniThreadPool.h
dbms/src/IO/tests/gtest_io_thread.cpp
dbms/src/Storages/StorageDisaggregated.h
dbms/src/Storages/StorageDisaggregatedRemote.cpp

Issue Number: close #9392 
The default `wait_microseconds` is 0, which means never wait.
Set `wait_microseconds` to `disagg_build_task_timeout`.
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Disagg: Set the waiting time for thread pool.

---

dbms/src/TiDB/Schema/SchemaBuilder.cpp
dbms/src/TiDB/Schema/SchemaBuilder.h
dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/9227
Problem Summary: https://github.com/pingcap/tiflash/issues/9227#issuecomment-2225065052
In `SchemaBuilder::syncAllSchema`, each table that does not exists in tikv but still in the tiflash instance. TiFlash will execute `applyDropPhysicalTable` for each table, wich will update the "tombstone_ts" of the table in its ".sql" file.
Even if the table is already "tombstone", the function will update the "tombstone_ts" by a newer tso from PD. This make the IStorage instance still exist even after the gc_safepoint is exceed than the drop timepoint + gc_lifetime.
https://github.com/pingcap/tiflash/blob/28a2314dd36fc1e990b9d8a3a6aec89ba8a220b8/dbms/src/TiDB/Schema/SchemaBuilder.cpp#L1437-L1451 …

ddl: Skip updating the tombstone_ts if the table is already tombstone (release-7.1)

---

dbms/src/Common/FailPoint.cpp
dbms/src/Storages/KVStore/tests/gtest_kvstore_fast_add_peer.cpp
dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp
dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.cpp
dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.h
dbms/src/Storages/Page/V3/CheckpointFile/CPManifestFileWriter.cpp
dbms/src/Storages/Page/V3/CheckpointFile/CPManifestFileWriter.h
dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.h
dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.cpp
dbms/src/Storages/S3/S3RandomAccessFile.cpp

Issue Number: close #9406
1. Print error message and stack
2. Print error when GetObject timeout
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

UniPS: Catch exception when dumping incr snapshot

---

dbms/src/IO/Compression/CompressionCodecLightweight.h
dbms/src/Interpreters/Settings.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp

Issue Number: close #8982
```commit-message
Compression: enable lightweight temporarily 
```
Tests 
Side effects
Documentation
```release-note
None
```

Compression: enable lightweight temporarily

---

dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp

Add info level log when pipeline event is scheduled, this will be usefull for troubleshooting.
The log looks like this
```
[2024/09/11 14:45:35.865 +08:00] [INFO] [Event.cpp:84] ["Event is scheduled"] [source="MPP<gather_id:1, query_ts:1726037135481137861, local_query_id:5, server_id:2011, start_ts:452470278835142658,task_id:1> 0"] [thread_id=57]
```
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Add info log when pipeline even is scheduled

---

dbms/src/TiDB/Schema/SchemaBuilder.cpp
tests/fullstack-test2/ddl/alter_table_tiflash_replica.test

Issue Number: close https://github.com/pingcap/tiflash/issues/9438
In v8.1.0 and v8.1.1, if the tiflash replica num is set to 0, `applyDropTable(database_id, table_id, "SetTiFlashReplica-0")` will be executed and add a `tombstone_ts` to the IStorage instance.
https://github.com/pingcap/tiflash/blob/v8.1.1/dbms/src/TiDB/Schema/SchemaBuilder.cpp#L392-L407
If all the regions are removed from the tiflash instance, and the `tombstone_ts` exceeds the gc_safepoint, then we will generate a `InterpreterDropQuery` to physically drop the IStorage instance.
https://github.com/pingcap/tiflash/blob/v8.1.1/dbms/src/TiDB/Schema/SchemaSyncService.cpp#L304-L354
However, there could be a chance that data loss due to a concurrent issue:
1. In `SchemaSyncService::gcImpl`, a table is judge as …

ddl: Do not physical drop table after tiflash replica is set to 0

---

dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeer.cpp
dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeer.h
dbms/src/Storages/KVStore/MultiRaft/Disagg/ServerlessUtils.cpp
dbms/src/Storages/KVStore/MultiRaft/Disagg/ServerlessUtils.h
dbms/src/Storages/KVStore/TiKVHelpers/TiKVRecordFormat.h
dbms/src/Storages/KVStore/tests/gtest_kvstore_fast_add_peer.cpp
dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.cpp
dbms/src/Storages/Page/V3/Universal/UniversalPageIdFormatImpl.h

Issue Number: ref #8673
Ref https://github.com/tidbcloud/tiflash-cse/pull/287.
We have to add some dummy implementations in TiFlash master, to reduce the divergence between serverless interfaces and codes.
The PR includes:
1. In Proxy, we update ProxyFFI.h for some changes. We also introduce a serverless_extra.rs file that does nothing as a stub file.
2. In TiFlash, we add and change some functions in FastAddPeer.cpp to support newly added interfaces. The newly add functions will always return empty(string or int). So there is little side effect.
```commit-message
Compatibility for serverless FAP features including shard_ver, txn ref and enc key
```
Tests 
Side effects
Documentation
```release-note
None
```

Compat serverless FAP features including shard_ver, txn ref and enc key

---

dbms/src/Common/FailPoint.cpp
dbms/src/Debug/MockTiDB.cpp
dbms/src/Debug/MockTiDB.h
dbms/src/Debug/dbgFuncSchema.cpp
dbms/src/Debug/dbgFuncSchema.h
dbms/src/Storages/Transaction/RegionTable.cpp
dbms/src/Storages/Transaction/RegionTable.h
dbms/src/TiDB/Schema/SchemaSyncService.cpp
dbms/src/TiDB/Schema/SchemaSyncService.h
dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp
tests/fullstack-test2/ddl/alter_exchange_partition.test
tests/fullstack-test2/ddl/flashback_database.test

Issue Number: close https://github.com/pingcap/tiflash/issues/9437
When a table is dropped in tidb, and exceeds the gc_safepoint, tiflash will generate an `InterpreterDropQuery` to physically remove the data from the tiflash instance. The "DropQuery" will call `DeltaMergeStore::dropAllSegments` to remove the Segment at DeltaTree storage one by one. Because there are many segments for the table, running `DeltaMergeStore::dropAllSegments` is slow.
https://github.com/pingcap/tiflash/blob/v7.1.3/dbms/src/TiDB/Schema/SchemaSyncService.cpp#L216-L227
https://github.com/pingcap/tiflash/blob/v7.1.3/dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp#L342-L349
```
[2024/09/16 21:29:29.604 +00:00] [INFO] [SchemaSyncService.cpp:170] ["Performing GC using safe point 452597098965106688"] …
```

ddl: Fix the physically drop storage instance may block removing regions

---

dbms/src/Common/FailPoint.cpp
dbms/src/Storages/KVStore/FFI/ProxyFFIStatusService.cpp
dbms/src/Storages/KVStore/tests/gtest_sync_schema.cpp
dbms/src/Storages/KVStore/tests/region_kvstore_test.h

Pick https://github.com/tidbcloud/tiflash-cse/pull/281
```commit-message
storage: support the HTTP API of sync table schema
```
Tests 
Side effects
Documentation
```release-note
None
```

storage: support the HTTP API of sync table schema

---

dbms/src/DataStreams/AggregatingBlockInputStream.cpp
dbms/src/DataStreams/HashJoinProbeBlockInputStream.cpp
dbms/src/DataStreams/HashJoinProbeExec.h
dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
dbms/src/Flash/Mpp/MPPTask.cpp
dbms/src/Flash/Mpp/MPPTask.h
dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
dbms/src/Flash/Planner/Plans/PhysicalJoinBuild.cpp
dbms/src/Interpreters/Aggregator.h
dbms/src/Interpreters/CancellationHook.h
dbms/src/Interpreters/Context.h
dbms/src/Interpreters/Join.cpp
dbms/src/Interpreters/Join.h
dbms/src/Interpreters/NullAwareSemiJoinHelper.cpp
dbms/src/Interpreters/NullAwareSemiJoinHelper.h
dbms/src/Interpreters/SemiJoinHelper.cpp
dbms/src/Interpreters/SemiJoinHelper.h
dbms/src/Operators/AggregateContext.cpp
dbms/src/Operators/AggregateContext.h
dbms/src/Operators/AutoPassThroughHashAggContext.h

Issue Number: close #9430
Check cancel signal inside join
```commit-message
```
Tests 
Cancel a query with a cross join
```
mysql> select count(*) from t1;
+----------+
| count(*) |
+----------+
|  8000392 |
+----------+
mysql> explain select count(*) from t1 where id not in (select id from t1);
+------------------------------------------+------------+--------------+---------------+-----------------------------------------------------------------+
| id                                       | estRows    | task         | access object | operator info                                                   |
+------------------------------------------+------------+--------------+---------------+-----------------------------------------------------------------+
| HashAgg_35 …
```

join be aware of cancel signal

---

dbms/src/Flash/Coprocessor/DAGUtils.cpp

Issue Number: close #9444
Json comparision is not supported in TiFlash, this pr disable them.
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

disable some json functions pushdown

---

dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
dbms/src/Flash/Planner/Plans/PhysicalJoinBuild.cpp
dbms/src/Flash/Planner/Plans/PhysicalJoinProbe.cpp
dbms/src/Interpreters/Join.cpp

Issue Number: ref #9430
Set cancellation hook after dry run of `join->joinBlock` so the dry run will always get a meaningfull block
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

fix tiflash assert failure 

---

dbms/src/Debug/MockTiDB.cpp
dbms/src/Debug/MockTiDB.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp
dbms/src/Storages/DeltaMerge/File/DMFileIndexWriter.cpp
dbms/src/Storages/DeltaMerge/File/DMFileIndexWriter.h
dbms/src/Storages/DeltaMerge/Index/IndexInfo.cpp
dbms/src/Storages/DeltaMerge/Index/IndexInfo.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index_utils.h
dbms/src/Storages/DeltaMerge/tests/gtest_local_index_info.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
dbms/src/Storages/KVStore/Types.h
dbms/src/Storages/StorageDeltaMerge.cpp
dbms/src/Storages/StorageDeltaMerge.h
dbms/src/Storages/System/StorageSystemDTLocalIndexes.cpp
dbms/src/TiDB/Schema/SchemaGetter.h
dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp

- Support the vector index from tableInfo.IndexInfo.
- Support adding/dropping vector index when doing syncTableSchema.
```commit-message
*: support vector index and adding/dropping vector index when doing syncTableSchema
```
Tests 
Side effects
Documentation
```release-note
None
```

*: support vector index and adding/dropping vector index when doing syncTableSchema

---

dbms/src/TiDB/Schema/TiDB.cpp
dbms/src/TiDB/Schema/tests/gtest_table_info.cpp

The "kind" field is removed from the tidb vector index definition
https://github.com/zimulala/tidb/blob/bce9dabc8c7712b98ca4f9cd90beca89a1d62ca8/pkg/meta/model/index.go#L36-L41
```commit-message
ddl: Adapt with the latest vector index def
```
Removing the deadcode will make lots of test cases changes and introduce conflict when cherry-pick other PRs. This PR just do some small adaption to make things work as expected, the deadcode will be removed in later PRs
Tests 
Side effects
Documentation
```release-note
None
```

ddl: Adapt with the latest vector index definition

---

dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_fast_add_peer.cpp
dbms/src/Storages/KVStore/tests/gtest_raftstore_v2.cpp

Issue Number: close #9405
1. SimpleWriteReadAfterRestoreFromCheckPoint is an FAP [soft error](https://do.pingcap.net/jenkins/blue/rest/organizations/jenkins/pipelines/pingcap/pipelines/tiflash/pipelines/release-7.5/pipelines/pull_unit_test/runs/84/log/?start=0) that pending investigation.
2. KVStoreSingleSnap4 is a Parallel Prehandle bug that need to be picked into cse. The issue is #9405
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

tests: Disable some tests of inactivated features on 7.5

---

dbms/src/Interpreters/Settings.h
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
tests/tidb-ci/run.sh

Issue Number: close #8982
```commit-message
Compression: still using LZ4 by default
```
Tests 
Side effects
Documentation
```release-note
None
```

Compression: still using LZ4 by default

---

dbms/src/Common/FailPoint.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
dbms/src/Storages/DeltaMerge/File/DMFileIndexWriter.cpp
dbms/src/Storages/DeltaMerge/Index/IndexInfo.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_local_index_info.cpp
dbms/src/TiDB/Schema/TiDB.cpp

Pick https://github.com/tidbcloud/tiflash-cse/pull/283 and https://github.com/tidbcloud/tiflash-cse/pull/300
* Unify the logic of `generateLocalIndexInfos` and `initLocalIndexInfos`
* Print 1 logging for the vector index added/dropped/existing in one table instead. This can avoid the flood of logging when tiflash restart with lots of table with vector index defined
* Support drop the vector index defined on ColumnInfo after the Column has been dropped in TiDB
* Add more ut in the DeltaMergeStore read level
* vector search fallback when top_k = max uint32
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Storage: Support drop vector index defined on ColumnInfo when column is dropped

---

dbms/src/Common/FailPoint.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp
dbms/src/Storages/DeltaMerge/File/DMFileIndexWriter.cpp
dbms/src/Storages/DeltaMerge/File/DMFileIndexWriter.h
dbms/src/Storages/DeltaMerge/Index/LocalIndexInfo.cpp
dbms/src/Storages/DeltaMerge/Index/LocalIndexInfo.h
dbms/src/Storages/DeltaMerge/LocalIndexerScheduler.cpp
dbms/src/Storages/DeltaMerge/LocalIndexerScheduler.h
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/Segment.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index_utils.h
dbms/src/Storages/DeltaMerge/tests/gtest_local_index_info.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_local_indexer_scheduler.cpp
dbms/src/Storages/StorageDeltaMerge.cpp
dbms/src/Storages/StorageDeltaMerge.h
dbms/src/Storages/System/StorageSystemDTLocalIndexes.cpp

* Add 2 columns to `system.dt_local_indexes`
* `column_name` is removed from the `system.dt_local_indexes`, let the tidb fill the index_name
* `error_message` when it contains non-empty string, it means the index can not be built on tiflash
* An std::unordered_map<IndexID, String> fatal_error_when_building_local_index is added to each Segment:
* The error message will be set when:
* When the task can not be pushed to the LocalIndexScheduler, for example, need to large memory to be built
* When the task throws any exception in `DeltaMergeStore::segmentEnsureStableIndex`
* The error message will be clear when:
* New local tasks is pushed to the LocalIndexScheduler with the same index_id
* The index is dropped from tidb
* `generateLocalIndexInfos` now …

Storage: Add error message when fail to build local index

---

dbms/src/DataTypes/getLeastSupertype.cpp
dbms/src/DataTypes/getMostSubtype.cpp
dbms/src/DataTypes/tests/gtest_data_type_get_common_type.cpp
dbms/src/Flash/Mpp/MPPTaskScheduleEntry.cpp
dbms/src/Storages/DeltaMerge/File/ColumnStat.h
dbms/src/Storages/DeltaMerge/File/DMFileIndexWriter.cpp

```
CREATE TABLE `t413684e6` (
`col_1` time DEFAULT NULL,
`col_2` vector(2) NOT NULL DEFAULT '[0.476802, 0.584379]',
`col_3` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=gbk COLLATE=gbk_chinese_ci;
CREATE TABLE `t5bd2e4da` (
`col_46` datetime NOT NULL DEFAULT '1982-12-17 00:00:00',
`col_47` mediumint(8) unsigned DEFAULT '114607',
`col_48` timestamp DEFAULT '1982-08-02 00:00:00',
`col_49` json NOT NULL,
`col_50` json NOT NULL,
`col_51` time NOT NULL,
`col_52` json NOT NULL,
`col_53` vector(3) NOT NULL DEFAULT '[0.825384, 0.251245, 0.464911]',
`col_54` vector NOT NULL DEFAULT '[0.424734, 0.467973, 0.326344, 0.107600, 0.398175]',
`col_55` vector DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=gbk …
```

vector: Fix join by array meet error "no supertype for types Array(Float32), Nullable(Array(Float32))"

---

dbms/src/Core/Block.cpp
dbms/src/Core/Block.h
dbms/src/Storages/DeltaMerge/LateMaterializationBlockInputStream.cpp

Issue Number: ref #9472
Try to fix #9472, failed to reproduce the issue. But when the filter column is the first non-empty column in the block, block.rows() = filter_column->size(), but filter_column is not filtered, so the rows may not match.
**But filter_column is usually added to the back of the block, so it is kind of weird.**
```commit-message
storage: fix block rows not match when filter column is the first non-empty column in the block
```
Tests 
Side effects
Documentation
```release-note
None
```

storage: fix block rows not match when filter column is the first non-empty column in the block

---

dbms/CMakeLists.txt
dbms/src/VectorSearch/SimSIMD.h
dbms/src/VectorSearch/USearch.h
release-centos7-llvm/scripts/run-clang-tidy.py

clang-tidy is temporary disable to merge the feature branch
https://github.com/pingcap/tiflash/pull/9486#discussion_r1780614126
```commit-message
```
re-enable the clang-tidy checks
Tests 
Side effects
Documentation
```release-note
None
```

tests: fix build on m1 macbook && re-enable clang-tidy checks

---

dbms/src/Storages/DeltaMerge/Filter/RSOperator.cpp

```commit-message
Fix ANNIndexInfo is not utilized when TiDB specifies it
```
Tests 
Side effects
Documentation
```release-note
None
```

storage: Fix vector index not used

---

dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.cpp
dbms/src/Storages/DeltaMerge/File/DMFileV3IncrementWriter.cpp
dbms/src/Storages/DeltaMerge/ScanContext.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/9505, ref https://github.com/pingcap/tiflash/issues/9032
Encryption-at-rest is not compatible with building vector-index. We need more tests.
```commit-message
Storage: Abort adding vector index if encryption enabled
```
Encryption-at-rest is not compatible with building vector-index. We need more tests. Abort adding vector-index when encryption-at-rest is enabled in tiflash for now.
One of the reason is `DMFileV3IncrementWriter::writeAndIncludeMetaFile` call `WriteBufferFromWritableFileBuilder::buildPtr(..., /* create_new_encryption_info */ true, ...)` and it renew the encryption_info of the DMFile. It causes the encryption_info mismatch after generating the new DMFile meta v1.
There is still something wrong …

Storage: Abort adding vector index if encryption enabled

---

dbms/src/Functions/FunctionsString.cpp
dbms/src/Functions/tests/gtest_string_left.cpp
dbms/src/Functions/tests/gtest_strings_right.cpp
dbms/src/Functions/tests/gtest_substring.cpp
dbms/src/TestUtils/FunctionTestUtils.h
tests/fullstack-test/expr/substring_utf8.test

Issue Number: close https://github.com/pingcap/tiflash/issues/9473
```commit-message
Support other integer types for SubstringUTF8 & RightUTF8 functions
```
Tests 
Side effects
Documentation
```release-note
None
```

Support other integer types for SubstringUTF8 & RightUTF8 functions

---

dbms/src/Debug/MockStorage.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_storage_delta_merge.cpp
dbms/src/Storages/tests/gtest_filter_parser.cpp
dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp

https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/tiflash-sanitizer-daily/runs/2195/nodes/86/log/?start=0
The class `DAGQueryInfo` only keep reference to the query. So when writing unit test case, it is easy for us to pass a temporary variable and construct a `DAGQueryInfo` on the temporary variables. That cause stack-use-after-scope error.
https://github.com/pingcap/tiflash/blob/2f584c0949cd1a08811920cfa810390b694290ea/dbms/src/Flash/Coprocessor/DAGQueryInfo.h#L28-L58
```
[2024-10-10T19:09:42.918Z] ==53983==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7f98b52a4c88 at pc 0x559a56ea95db bp 0x7fff3e8cca50 sp 0x7fff3e8cca48
[2024-10-10T19:09:42.918Z] READ of size 4 at …
```

tests: Fix asan check failures

---

dbms/src/DataStreams/AsynchronousBlockInputStream.h
dbms/src/DataStreams/ParallelInputsProcessor.h
dbms/src/Flash/FlashService.cpp
dbms/src/Server/MetricsPrometheus.cpp
dbms/src/Storages/DeltaMerge/LocalIndexerScheduler.cpp
dbms/src/Storages/KVStore/Decode/PartitionStreams.cpp
dbms/src/Storages/KVStore/MultiRaft/RaftCommandsKVS.cpp
dbms/src/Storages/KVStore/Read/ReadIndexWorkerImpl.h
dbms/src/Storages/KVStore/Read/ReadIndexWorkerManager.cpp
metrics/grafana/tiflash_summary.json

```commit-message
```
* Set the thread name when the thread is executing task of building vector index
* Add thread CPU panel in the TiFlash-Summary Grafana
Tests 
Side effects
Documentation
```release-note
Add Grafana panel about CPU usage on building vector index
```

metrics: Add Thread CPU panel for building vector index

---

dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_for_fast_scan.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp

`STORAGE_FORMAT_CURRENT = STORAGE_FORMAT_V7` but many unit tests are still testing V1/V2/V3.
Test V3 which uses PageStorage V2 and the latest format version.
```commit-message
Storages: fix outdated unit tests
```
Tests 
Side effects
Documentation
```release-note
None
```

Storages: fix outdated unit tests

---

CMakePresets.json

The command added in https://github.com/pingcap/tiflash/pull/9304 is broken
```
> cmake --workflow --preset unit-tests-all
...
Executing workflow step 2 of 2: build preset "unit-tests-all"
[0/2] Re-checking globbed directories...
ninja: error: unknown target 'gtests_dbms, gtests_libdaemon, gtests_libcommon'
```
```commit-message
build: Fix cmake preset command
```
Tests 
Side effects
Documentation
```release-note
None
```

build: Fix cmake preset command

---

dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h

Issue Number: close #9537
If `check_range` of `SegmentTestBasic::ingestDTFileIntoDelta` is false, it may generate data out of the range of segment.
In https://github.com/pingcap/tiflash/pull/9531, we want to generate data out of the segment range, but in most other test cases, it doesn't.
Change the default of `check_range` to false. 
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

tests: fix unstable unittests

---

dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp
dbms/src/Storages/DeltaMerge/File/DMFileMeta.h
dbms/src/Storages/DeltaMerge/Remote/Proto/remote.proto
dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
dbms/src/Storages/DeltaMerge/SegmentReadTask.h
dbms/src/Storages/DeltaMerge/dtpb/CMakeLists.txt
dbms/src/Storages/DeltaMerge/dtpb/column_file.proto
dbms/src/Storages/DeltaMerge/dtpb/dmfile.proto
dbms/src/Storages/DeltaMerge/dtpb/vector_index.proto
dbms/src/Storages/DeltaMerge/tests/gtest_column_file_clone.cpp

This PR is part of https://github.com/tidbcloud/tiflash-cse/pull/293, which mainly adds index info in ColumnFileTiny meta.
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Storages: support building vector index for ColumnFileTiny (Part 1)

---

dbms/src/Flash/Mpp/MPPTunnelSetWriter.cpp

Issue Number: ref #9413
#9424 fix #9413 by "Make sure that each time an ExchangeSenderSinkOp is notified, the ExchangeSenderSinkOp should either write data to LooseBoundedMPMCQueue, or try to notify another ExchangeSenderSinkOp", and actually requires that when `ExchangeSenderSinkOp` write data to `MPPTunnelSetWriter`, it will write data to all tunnels in `MPPTunnelSetWriter`. But for fine grained write, current code may skip the write if some tunnel does not have data to write, this is unexpected, and may make query hang in some extrame cases.
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Fix potential hang issues when fine grained shuffle is enabled

---

dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h

```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

build: fix drawin build

---

dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyVectorIndexWriter.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyVectorIndexWriter.h
dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
dbms/src/Storages/DeltaMerge/File/DMFileIndexWriter.cpp
dbms/src/Storages/DeltaMerge/Index/VectorIndex.h
dbms/src/Storages/DeltaMerge/Index/VectorIndexHNSW/Index.cpp
dbms/src/Storages/DeltaMerge/Index/VectorIndexHNSW/Index.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index_utils.h
dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp

This PR is part of https://github.com/tidbcloud/tiflash-cse/pull/293, which introduce the write path.
Unit tests will be included in next PR.
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Storages: support building vector index for ColumnFileTiny (Part 2)

---

dbms/src/AggregateFunctions/AggregateFunctionCount.h

Issue Number: ref #9146
`AggregateFunctionCountNotNullUnary` does not overwrite `addBatchSinglePlace` and `addBatchSinglePlaceNotNull`, so the code path will be 
https://github.com/pingcap/tiflash/blob/08535236b8f3d6d41656f22ebb8c2334f3081d86/dbms/src/AggregateFunctions/IAggregateFunction.h#L267-L289
In fact, `AggregateFunctionCountNotNullUnary` can be optimized by count the element number in batch like `AggregateFunctionCount` by overwrite `addBatchSinglePlace` and `addBatchSinglePlaceNotNull` 
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

overwrite `addBatchSinglePlace` and `addBatchSinglePlaceNotNull` in `AggregateFunctionCountNotNullUnary`

---

dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilterView.h
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetInputStream.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetInputStream.h
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.h
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetWithVectorIndexInputStream.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetWithVectorIndexInputStream.h
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyVectorIndexReader.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyVectorIndexReader.h
dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp
dbms/src/Storages/DeltaMerge/Index/VectorIndex.cpp
dbms/src/Storages/DeltaMerge/Index/VectorIndex.h
dbms/src/Storages/DeltaMerge/Index/VectorIndexCache.h
dbms/src/Storages/DeltaMerge/Index/VectorIndexHNSW/Index.cpp
dbms/src/Storages/DeltaMerge/Index/VectorIndexHNSW/Index.h
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp
dbms/src/Storages/StorageDisaggregatedRemote.cpp

This PR is part of https://github.com/tidbcloud/tiflash-cse/pull/293, which introduces the read path and adds unit tests.
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Storages: support building vector index for ColumnFileTiny (Part 3)

---

dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetWithVectorIndexInputStream.cpp

```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

build: fix darwin build

---

dbms/src/DataStreams/HashJoinProbeBlockInputStream.cpp
dbms/src/DataStreams/ScanHashMapAfterProbeBlockInputStream.cpp
dbms/src/DataStreams/ScanHashMapAfterProbeBlockInputStream.h
dbms/src/Interpreters/Join.cpp
dbms/src/Interpreters/Join.h
dbms/src/Operators/HashJoinProbeTransformOp.cpp

Currently there is two way to get the output schema of `Join`
- use `Join::joinBlock` with `dry_run = true`
- use `Join::getOutputBlock`
This pr remove `dry_run` argument from `Join::joinBlock`. So the only way to get the output schema of `Join` is to use `Join::getOutputBlock`
Tests 
Side effects
Documentation
```release-note
None
```

Minor refine `Join`

---

dbms/src/Debug/MockKVStore/MockRaftStoreProxy.cpp
dbms/src/Storages/KVStore/MultiRaft/ApplySnapshot.cpp
dbms/src/Storages/KVStore/MultiRaft/RegionRangeKeys.h
dbms/src/Storages/KVStore/tests/gtest_kvstore.cpp
dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp

Issue Number: close #9329
Cherry-pick of #9330
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

KVStore: Fix spurious region overlap when two region are both applying snapshots

---

README.md
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetWithVectorIndexInputStream.cpp
dbms/src/Storages/DeltaMerge/File/DMFileWithVectorIndexBlockInputStream.cpp
dbms/src/Storages/DeltaMerge/Index/VectorIndexHNSW/Index.cpp
release-darwin/build/build-release.sh
release-darwin/prepare-environments/prepare-llvm.sh

https://github.com/orgs/pingcap/discussions/57069
```commit-message
build: use llvm@17 in darwin
```
Tests 
Side effects
Documentation
```release-note
None
```

build: use llvm@17 in darwin

---

dbms/src/Columns/IColumn.h
dbms/src/Columns/tests/gtest_column_misc.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/9605
See https://github.com/pingcap/tiflash/issues/9605。
The newly-added unit test will fail for the original codebase.
```commit-message
Fix the bug that `cloneFullColumn` does not clone the subcolumns at the second and higher levels 
```
Tests 
Side effects
Documentation
```release-note
None
```

Fix the bug that `cloneFullColumn` does not clone the subcolumns at the second and higher levels 

---

dbms/src/DataStreams/PushingToViewsBlockOutputStream.cpp
dbms/src/DataStreams/SquashingBlockInputStream.cpp
dbms/src/DataStreams/SquashingBlockInputStream.h
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetWithVectorIndexInputStream.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetWithVectorIndexInputStream.h
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyVectorIndexReader.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyVectorIndexReader.h
dbms/src/Storages/DeltaMerge/ConcatSkippableBlockInputStream.cpp
dbms/src/Storages/DeltaMerge/ConcatSkippableBlockInputStream.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp
dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
dbms/src/Storages/DeltaMerge/File/DMFileVectorIndexReader.cpp
dbms/src/Storages/DeltaMerge/File/DMFileVectorIndexReader.h
dbms/src/Storages/DeltaMerge/File/DMFileWithVectorIndexBlockInputStream.cpp
dbms/src/Storages/DeltaMerge/File/DMFileWithVectorIndexBlockInputStream.h
dbms/src/Storages/DeltaMerge/Filter/RSOperator.cpp
dbms/src/Storages/DeltaMerge/Filter/RSOperator.h
dbms/src/Storages/DeltaMerge/Filter/WithANNQueryInfo.h
dbms/src/Storages/DeltaMerge/Index/VectorIndex.h
dbms/src/Storages/DeltaMerge/Index/VectorIndexHNSW/Index.cpp
dbms/src/Storages/DeltaMerge/Index/VectorIndexHNSW/Index.h
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
dbms/src/Storages/DeltaMerge/SegmentReadTask.h
dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h
dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
dbms/src/Storages/DeltaMerge/VectorIndexBlockInputStream.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp

Issue Number: ref #9600 , close #9599
Before, the read path of vector search is:
1. load stable vector index.
2. read all packs that contain TopK results.
3. load all ColumnFileTiny vector index.
4. read all ColumnFileTiny that contain TopK results.
5. read Memtable.
A simple example:
We have cf_0 (indexed, offset: 100-110), cf_1 (indexed, offset: 110-120), cf_3 (indexed, offset: 120-130), cf_4 (memtable, offset: 130-140), dmfile_0 (indexed, offset: 0-100, each 10 rows as a pack), to find top5:
1.  load stable vector index: top5 is [0, 10, 13, 25, 99]
2. read all packs that contain TopK results: read pack_0, pack_1, pack_2, pack_9
3. load all ColumnFileTiny vector index: top5 is [100, 101, 115, 116, 119]
4. read all ColumnFileTiny that contain TopK results: read cf_0, …

Storages: Optimize vector search in scenarios with updates

---

dbms/src/Functions/FunctionsString.cpp
tests/fullstack-test/expr/substring_utf8.test

Issue Number: close #9604
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

fix substring wrong result bug

---

dbms/src/DataStreams/RuntimeFilter.h
dbms/src/Flash/Mpp/tests/gtest_mpp_exchange_writer.cpp
dbms/src/Operators/DMSegmentThreadSourceOp.h
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetSnapshot.h
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetWithVectorIndexInputStream.h
dbms/src/Storages/DeltaMerge/ConcatSkippableBlockInputStream.cpp
dbms/src/Storages/DeltaMerge/DMSegmentThreadInputStream.h
dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
dbms/src/Storages/DeltaMerge/Delta/MemTableSet.cpp
dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
dbms/src/Storages/DeltaMerge/File/DMFileReader.h
dbms/src/Storages/DeltaMerge/Filter/RSOperator.h
dbms/src/Storages/DeltaMerge/Filter/RSOperator_fwd.h
dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.h
dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/Segment.h
dbms/src/Storages/DeltaMerge/StableValueSpace.h
dbms/src/Storages/DeltaMerge/tests/DMTestEnv.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment_common_handle.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task.cpp
dbms/src/Storages/StorageDisaggregated.h
dbms/src/TestUtils/ColumnGenerator.h

In the previous code, `DeltaValueSnapshot` and `ColumnFileSetSnapshot` instances will be created then set belonging members. This is not a good code practice may lead to some fields missing to be assign when implementing "clone" and "deserialize". It led to unexpected bug likes https://github.com/pingcap/tiflash/pull/9530
```commit-message
```
* Make the members of `DeltaValueSnapshot` and `ColumnFileSetSnapshot` "const" as possible
* Refine the include header of `RSOperator`
Tests 
Side effects
Documentation
```release-note
None
```

Storage: Refine the snapshot creation on DeltaValueSpace

---

dbms/src/Common/getNumberOfCPUCores.cpp
dbms/src/Common/tests/gtest_miscellaneous.cpp

Issue Number: close #9212
```commit-message
```
Tests 
Side effects
Documentation
```release-note
Fix the that fail to start tiflash because of the zero division when getting cpu number
```

Fix the fail start of tiflash because of the zero division when getting cpu number

---

dbms/src/Interpreters/InterpreterCreateQuery.cpp
dbms/src/Interpreters/InterpreterCreateQuery.h
dbms/src/TiDB/Schema/SchemaBuilder.cpp

Issue Number: close #9613
Checkout the details logging in https://github.com/pingcap/tiflash/issues/9613#issuecomment-2478382674 
According to the log, it took about 4 seconds to create an empty table when the CI environment is busy.
```commit-message
```
* Increate the max wait time for concurrent create table to 5 seconds.
* Refine the logging when concurrent create table happen
Tests 
Side effects
Documentation
```release-note
None
```

ddl: Fix unstable test "fullstack-test/mpp/rollup_tpcds.test"

---

dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment_s3.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_replace_stable_data.cpp
dbms/src/Storages/KVStore/TMTContext.cpp
dbms/src/Storages/KVStore/tests/gtest_kvstore_fast_add_peer.cpp
dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.cpp

Issue Number: close #9394
there is a time gap after TMTContext is created but before `TMTContext::initS3GCManager` finished
Do not init S3LocalLockManager, if the client is not set.
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Abort uploading checkpoint if s3 lock client is not initialized

---

README.md
dbms/src/Storages/DeltaMerge/tests/gtest_segment_bitmap.cpp

```commit-message
Fix README instruction for MacOS
Fix build unit test failure in LLVM17 + MacOS
```
This doesn't work, so removed: "use CMAKE_C_COMPILER and CMAKE_CXX_COMPILER to specify the compiler"
Tests 
Side effects
Documentation
```release-note
None
```

*: Fix build and readme in llvm17

---

dbms/src/DataStreams/WindowBlockInputStream.cpp
dbms/src/DataStreams/WindowBlockInputStream.h
dbms/src/Operators/WindowTransformOp.cpp
dbms/src/TestUtils/WindowTestUtils.h
dbms/src/WindowFunctions/tests/gtest_lead_lag.cpp

Issue Number: ref #9433
Before this pr, `WindowTransformAction::tryCalculate()` will try to calculate as many as possible results at a time. This makes the calling time of `WindowTransformAction::tryCalculate()` unpredictable.
This pr let `WindowTransformAction::tryCalculate()` to calculate at most 1 block result at a time, so the calling time of `WindowTransformAction::tryCalculate()` won't be too long, and be more friendly for pipeline model.
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

`WindowTransformAction::tryCalculate()` calculate at most 1 block result at a time

---

dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.h
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyReader.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyReader.h
dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.h
dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
dbms/src/Storages/DeltaMerge/Delta/MinorCompaction.h
dbms/src/Storages/DeltaMerge/PKSquashingBlockInputStream.h

```commit-message
remove the code of ColumnFileTiny cache which is useless.
```
Tests 
Side effects
Documentation
```release-note
None
```

Storages: remove ColumnFileTiny cache

---

dbms/src/Interpreters/Join.cpp
dbms/src/Interpreters/Join.h
dbms/src/Interpreters/NullAwareSemiJoinHelper.cpp
dbms/src/Interpreters/NullAwareSemiJoinHelper.h
dbms/src/Interpreters/SemiJoinHelper.cpp
dbms/src/Interpreters/SemiJoinHelper.h

Issue Number: ref #9433
The same as #9672, this pr refine na semi join so each `NASemiJoinHelper::doJoin()` call only handle at most `max_block_size`'s data.
And this pr also remove cancellation check inside `NASemiJoinHelper` and `SemiJoinHelper` since now all the method in `NASemiJoinHelper/SemiJoinHelper` will handle at most `max_block_size`'s data, so there is no need to check cancellation inside them.
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Refine na semi join

---

dbms/src/Common/FailPoint.cpp
dbms/src/Flash/Pipeline/Schedule/Tasks/Task.h
dbms/src/Flash/Pipeline/Schedule/Tasks/TaskHelper.h
dbms/src/Flash/Pipeline/Schedule/Tasks/TaskTimer.cpp
dbms/src/Flash/Pipeline/Schedule/Tasks/TaskTimer.h
dbms/src/Flash/Pipeline/Schedule/ThreadPool/TaskThreadPool.cpp
dbms/src/Flash/tests/gtest_join_executor.cpp
dbms/src/Interpreters/Join.cpp

Issue Number: close #9433
Limit the max execution time for nasemi/semi join probe.
Testing result:
Testing data set
```
mysql> desc t1;
+-------+------+------+------+---------+-------+
| Field | Type | Null | Key  | Default | Extra |
+-------+------+------+------+---------+-------+
| id    | int  | NO   |      | NULL    |       |
| value | int  | YES  |      | NULL    |       |
+-------+------+------+------+---------+-------+
2 rows in set (0.00 sec)
mysql> desc t2;
+-------+------+------+------+---------+-------+
| Field | Type | Null | Key  | Default | Extra |
+-------+------+------+------+---------+-------+
| id    | int  | NO   |      | NULL    |       |
| value | int  | YES  |      | NULL    |       |
+-------+------+------+------+---------+-------+
2 rows in set …
```

limit the max exec time for nasemi/semi join probe

---

dbms/src/Interpreters/Context.cpp
dbms/src/Interpreters/executeQuery.cpp
dbms/src/Storages/DeltaMerge/LocalIndexerScheduler.cpp
dbms/src/Storages/DeltaMerge/LocalIndexerScheduler.h
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV3.cpp

pre-cherry-pick of https://github.com/pingcap/tiflash/pull/9712 on release-8.5 to fix the issue
Issue Number: close https://github.com/pingcap/tiflash/issues/9714
Checkout the logging in issue.
From "Invalid page id, entry not exist [page_id=451.26] [resolve_id=451.26]" and the StackTrace     `DB::DM::Segment::restoreSegment(std::__1::shared_ptr<DB::Logger> const&, DB::DM::DMContext&, unsigned long)  dbms/src/Storages/DeltaMerge/Segment.cpp:427` we can know that something is wrong when restoring the StableValueSpace of Segment. After adding some debugging message, we know that the error comes from restoring table_id=451, segment_id=8822.
Then dump the BlobData from PageStorage "meta". We found that the last two records persisted on disk is invalid as a SegmentMetaInfo. …

Storages: Shutdown the LocalIndexScheduler before shutting down PageStorage/DeltaMergeStore (release-8.5)

---

dbms/src/Storages/Page/V3/PageEntry.h
dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV3.cpp
release-centos7-llvm/env/.gitignore

Issue Number: close https://github.com/pingcap/tiflash/issues/9716
```commit-message
PageCtl: Support getting blob data from PageStorage instance
And output the "PageEntryV3.offset" in decimal instead of hexadecimal
```
```
>  ./dbms/src/Server/tiflash pagectl -V 3 --mode 7 --blob_id 1060 --blob_offset 30413 --blob_size 47 -P /data1/1210_down/meta
Running with mode=DISPLAY_BLOB_DATA
...
checksum: 0xE1CB85684ED5E5B6
hex:030000000500000000000000220A18080010011A08800000000003D05C2208800000000007A11510F04418F744201A
```
Tests 
Side effects
Documentation
```release-note
None
```

PageCtl: Support getting blob data from PageStorage instance (release-8.1)

---

dbms/src/Storages/Page/V3/PageEntry.h
dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV3.cpp
release-centos7-llvm/env/.gitignore

Issue Number: close https://github.com/pingcap/tiflash/issues/9716
```commit-message
PageCtl: Support getting blob data from PageStorage instance
And output the "PageEntryV3.offset" in decimal instead of hexadecimal
```
```
>  ./dbms/src/Server/tiflash pagectl -V 3 --mode 7 --blob_id 1060 --blob_offset 30413 --blob_size 47 -P /data1/1210_down/meta
Running with mode=DISPLAY_BLOB_DATA
...
checksum: 0xE1CB85684ED5E5B6
hex:030000000500000000000000220A18080010011A08800000000003D05C2208800000000007A11510F04418F744201A
```
Tests 
Side effects
Documentation
```release-note
None
```

PageCtl: Support getting blob data from PageStorage instance (release-7.5)

---

dbms/src/Interpreters/Context.cpp
dbms/src/Interpreters/executeQuery.cpp
dbms/src/Storages/DeltaMerge/LocalIndexerScheduler.cpp
dbms/src/Storages/DeltaMerge/LocalIndexerScheduler.h
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/Segment.h
dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV3.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/9714
Checkout the logging in issue.
From "Invalid page id, entry not exist [page_id=451.26] [resolve_id=451.26]" and the StackTrace     `DB::DM::Segment::restoreSegment(std::__1::shared_ptr<DB::Logger> const&, DB::DM::DMContext&, unsigned long)  dbms/src/Storages/DeltaMerge/Segment.cpp:427` we can know that something is wrong when restoring the StableValueSpace of Segment. After adding some debugging message, we know that the error comes from restoring table_id=451, segment_id=8822.
Then dump the BlobData from PageStorage "meta". We found that the last two records persisted on disk is invalid as a SegmentMetaInfo.
Before the error happen, we saw that the table_id=451, segment_id=8822 had applied a …

Storages: Shutdown the LocalIndexScheduler before shutting down PageStorage/DeltaMergeStore

---

dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
dbms/src/Storages/DeltaMerge/File/ColumnStream.cpp
dbms/src/Storages/DeltaMerge/File/DMFile.cpp
dbms/src/Storages/DeltaMerge/File/DMFile.h
dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.h
dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.cpp
dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
dbms/src/Storages/DeltaMerge/File/DMFilePackFilterResult.cpp
dbms/src/Storages/DeltaMerge/File/DMFilePackFilterResult.h
dbms/src/Storages/DeltaMerge/File/DMFilePackFilter_fwd.h
dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
dbms/src/Storages/DeltaMerge/File/DMFileReader.h
dbms/src/Storages/DeltaMerge/File/DMFileWithVectorIndexBlockInputStream.cpp
dbms/src/Storages/DeltaMerge/Index/RSResult.h
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/Segment.h
dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
dbms/src/Storages/DeltaMerge/StableValueSpace.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_bitmap.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_skippable_block_input_stream.cpp

```commit-message
Before, TiFlash will load the `RSResult` three times for one query (MVCC/Build Bitmap/Query).
This PR introduces `DMFilePackFilterResult` which load `RSResult` only once, and only passes the `RSResult` to `DMFileReader`.
```
Tests 
Side effects
Documentation
```release-note
None
```

Storages: load RSResult only once

---

dbms/src/Flash/Coprocessor/CodecUtils.cpp
dbms/src/Flash/Mpp/ExchangeReceiver.cpp
dbms/src/Flash/Mpp/ExchangeReceiver.h
dbms/src/Server/Server.cpp
dbms/src/Server/StorageConfigParser.cpp
dbms/src/Storages/DeltaMerge/RestoreDMFile.cpp
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/FormatVersion.cpp

Issue Number: ref https://github.com/pingcap/tiflash/issues/9673
```commit-message
```
Changes:
* Refine the error message when storage.format_version is invalid
* Refine the error message with keyspace_id, table_id, page_id, meta_version when restoring segment from disk
* Refine the error message with exectuor name when exchange receiver meet unexpected data type
After this PR:
If we set a illegal storage.format_version
```
[2024/12/26 18:35:35.117 +08:00] [ERROR] [<unknown>] ["DB::Exception: Illegal format_version value: 9"] [source=Application] [thread_id=1]
```
If we meet unexpected data type when restarting tiflash
```
[2024/12/26 23:27:43.778 +08:00] [ERROR] [Exception.cpp:91] ["Storage inited fail, keyspace=4294967295 table_id=127: Code: 50, e.displayText() = …
```

*: Refine the error message when schema mismatch in ExchangeReceiver

---

dbms/src/Storages/FormatVersion.h

Issue Number: close #9673
Enable serdes format of DataTypeString that introducing by https://github.com/pingcap/tiflash/pull/9608.
```commit-message
```
Tests 
Side effects
Documentation
```release-note
Enable new serialization method of string by default to improve the table scan performance
```

*: enable new serdes format of DataTypeString

---

dbms/src/Flash/Coprocessor/CoprocessorReader.h
dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
dbms/src/Flash/Coprocessor/ExecutionSummary.cpp
dbms/src/Flash/Coprocessor/ExecutionSummary.h
dbms/src/Flash/Mpp/ExchangeReceiver.cpp
dbms/src/Flash/Mpp/ExchangeReceiver.h
dbms/src/Flash/Mpp/GRPCReceiverContext.cpp
dbms/src/Flash/Mpp/GRPCReceiverContext.h
dbms/src/Flash/Mpp/MPPTask.cpp
dbms/src/Flash/Mpp/MPPTunnel.cpp
dbms/src/Flash/Mpp/MPPTunnel.h
dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
dbms/src/Flash/Statistics/BaseRuntimeStatistics.cpp
dbms/src/Flash/Statistics/BaseRuntimeStatistics.h
dbms/src/Flash/Statistics/ConnectionProfileInfo.h
dbms/src/Flash/Statistics/ExchangeReceiverImpl.cpp
dbms/src/Flash/Statistics/ExchangeReceiverImpl.h
dbms/src/Flash/Statistics/ExchangeSenderImpl.cpp
dbms/src/Flash/Statistics/ExchangeSenderImpl.h
dbms/src/Flash/Statistics/ExecutionSummaryHelper.cpp
dbms/src/Flash/Statistics/TableScanImpl.cpp
dbms/src/Flash/Statistics/TableScanImpl.h
dbms/src/Operators/CoprocessorReaderSourceOp.cpp
dbms/src/Operators/ExchangeReceiverSourceOp.h
dbms/src/Operators/IOProfileInfo.h

Issue Number: close #9748
Inner/inter zone network traffic is priced differently in cloud, thus trace each mpp query's such info will help users to locate the most network-expensive query. 
This PR stats thress kinds of network traffic:
1. Exchange sender
2. Exchange receiver
3. Remote table reader using coprocessor request
```commit-message
```
Tests 
Currently, set same and different zone labels for tiflash proxy config, and hack DAGStorageInterpreter to always use remote coprocessor read. Then check the MPPTaskStatistics.cpp output to see if local/inner/inter zone label is set correctly.
When tidb side change is merged, will check slow log and statements summary.
Side effects
Documentation
```release-note
None
```

Stats inner/inter zone network traffic for mpp tasks

---

dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.h
dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.h
dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp

Make changes for DMFileBlockInputStreamBuilder:
- public build → private buildNoLocalIndex
- public tryBuildWithLocalIndex → public build
Local index aware is by default now, so that we don't need to care about "local index" or not.
Tests 
Side effects
Documentation
```release-note
None
```

storage: Remove tryBuildWithVectorIndex

---

dbms/src/Server/Server.cpp
metrics/grafana/tiflash_summary.json

Issue Number: close #9745 ref #4982
```commit-message
```
After this, the memory_usage_limit on proxy's side will be:
If memory_usage_limit is set on proxy's side, use it
Otherwise:
If max_memory_usage_for_all_queries is not zero, use its size or ratio and compute on proxy's side.
Use default value MEMORY_USAGE_LIMIT_RATE
update proxy to raftstore-proxy-8.5
Proxy PR: 
Including:\nSubmodule contrib/tiflash-proxy b877a97699..fdb7f17746:
> Limit proxy's memory from TiFlash's side (#408) (#409)
> Cherry-pick #403 and #404 to release-8.5 (#405)
Tests 
Side effects
Documentation
```release-note
Fix an issue that TiFlash may unexpectedly reject raft message when memory usage is not high
```

Set proxy's memory limit by TiFlash (#9753) and update tiflash proxy

---

dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
dbms/src/Interpreters/Set.cpp
dbms/src/Interpreters/Set.h
tests/fullstack-test/expr/in_expression.test

Issue Number: close #9778
- `DAGExpressionAnalyzer` hasn't deal with timezone when handling set for `IN()` express.
```commit-message
```
Tests 
Side effects
Documentation
```release-note
Fix the bug of incorrect result when handling IN(Timestamp | Time * ) expressions with timezone
```

Fix the incompatible behavior when handling `IN(Timestamp | MysqlTime * )` expressions with timezone

---

dbms/src/Flash/Coprocessor/DecodeDetail.h
dbms/src/Flash/Coprocessor/ExecutionSummary.cpp
dbms/src/Flash/Mpp/ExchangeReceiver.cpp
dbms/src/Flash/Mpp/MPPTunnel.h
dbms/src/Flash/Mpp/ReceivedMessage.h
dbms/src/Flash/Statistics/BaseRuntimeStatistics.cpp

Issue Number: ref #9748 
Fix several issues for network traffic stats:
1. Two typo-like issues for mixing variable names. Previously, no tidb side changes, so only checks the remote coprocessor read code path manually, This time tests with tidb side changes, found these issues. RT.
2. Currently, in exchange sender side, we stats very small packets which don't look like data packets, with size <= 2 bytes; while in receiver side, these packets are not found. Maybe they include eof or other kinds of packets. Since they are so small that we can just ignore them now.
3. For fine grained shuffle exchange receiver, the network traffic is counted duplicatedly. 
```commit-message
```
Tests 
Manually test with https://github.com/pingcap/tidb/pull/58683, check execution summary …

Fix several network stats issues

---

dbms/src/AggregateFunctions/AggregateFunctionNull.h

Issue Number: close #9794
`align_size` is unused in release mode.
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Fix compilation errors with unused variables

---

dbms/src/Debug/MockStorage.cpp
dbms/src/Debug/MockStorage.h
dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
dbms/src/Flash/Coprocessor/GenSchemaAndColumn.cpp
dbms/src/Flash/Planner/Plans/PhysicalMockTableScan.cpp
dbms/src/Storages/IManageableStorage.h
dbms/src/Storages/StorageDeltaMerge.cpp
dbms/src/Storages/StorageDeltaMerge.h
dbms/src/TiDB/Decode/TypeMapping.cpp
dbms/src/TiDB/Decode/TypeMapping.h

1. refine `compareColumns` in `DAGStorageInterpreter`
2. remove useless virtual function `getStoreColumnDefines` in `IManageableStorage`
3. remove `getDataTypeByColumnInfoForDisaggregatedStorageLayer` which is the same as `getDataTypeByColumnInfo`
4. adjust member position of `StorageDeltaMerge`, `sizeof(StorageDeltaMerge)` from `720` to `704`
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

*: some minor refine

---

dbms/src/Server/Setup.cpp

Issue Number: close #9812 ref #9722 
See issue 9812
```commit-message
Re-enable jemalloc's background thread by default
```
Tests 
Side effects
Documentation
```release-note
Fix an issue that the memory may stay in high level after large amount of data ingested
```

Re-enable jemalloc's background thread by default

---

dbms/src/Flash/Mpp/HashPartitionWriter.cpp

Issue Number: close #9824
The root cause is in HashPartitionWriter, it need update `mem_size_in_blocks` if using `partitionAndWriteBlocksV1`, and if data_codec_version is MPPDataPacketV2, it use `partitionAndWriteBlocksV1` but not update `mem_size_in_blocks`  
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

fix false assert in tiflash debug binary after enable new string serde

---

dbms/src/Columns/ColumnDecimal.cpp
dbms/src/Columns/ColumnDecimal.h

Issue Number: close #9838
move methods implementation from `ColumnDecimal.h` to `ColumnDecimal.cpp`
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

fix compilation error on arm64

---

dbms/src/Storages/StorageDisaggregatedRemote.cpp

Issue Number: close #9847
We will wrap ANN query info in `DM::RSOperator::build()`, but `filter_conditions.hasValue() = false` makes early return.
Introduce by https://github.com/pingcap/tiflash/pull/9547, fixed by https://github.com/pingcap/tiflash/pull/9741 in master branch.
```commit-message
vector: fix ANN query info not wrapped
```
Tests 
Side effects
Documentation
```release-note
Fix a bug that vector index is not used when executing vector search queries under disaggregated compute and storage arch
```

vector: fix ANN query info not wrapped in disaggregated mode

---

dbms/src/Storages/DeltaMerge/Filter/RSOperator.cpp
dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp
dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
dbms/src/Storages/tests/gtest_filter_parser.cpp
dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp

using `std::unordered_map` instead of lambda
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Storages: refine FilterParser

---

dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp
dbms/src/Storages/DeltaMerge/Index/LocalIndexInfo.cpp
dbms/src/Storages/DeltaMerge/Index/LocalIndexInfo.h
dbms/src/Storages/DeltaMerge/Index/LocalIndexInfo_fwd.h
dbms/src/Storages/DeltaMerge/tests/gtest_local_index_info.cpp
dbms/src/Storages/KVStore/FFI/ProxyFFIStatusService.cpp
dbms/src/Storages/StorageDeltaMerge.h
dbms/src/Storages/System/StorageSystemDTLocalIndexes.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/9854
When we try to add a vector index on a relative large table, there are much useless logging under debug level
* After DDL owner try to add a vector index, the tidb ddl owner will get the add index progress by fetching `system.dt_local_indexes` from all tiflash instances
* `StorageSystemDTLocalIndexes::read` call `getLocalIndexesStatsFromStorage`. For non-inited `DeltaMergeStore`, the function calls `genLocalIndexStatsByTableInfo` -> `initLocalIndexInfos` -> `generateLocalIndexInfos` and generate useless logging like `"Local index info does not changed, ..."` for each `StorageDeltaMerge`. This will cause much debug logging when there are lots of tables in the cluster
```commit-message
* Move the logging …
```

vector: Reduce logging under debug level

---

dbms/src/Storages/KVStore/ProxyStateMachine.h

Issue Number: close https://github.com/pingcap/tiflash/issues/9750
When creating a placement policy through tidb, tidb will create a placement-rule with `"engine" notIn "tiflash"` https://github.com/pingcap/tidb/pull/22065
However, under tiflash disaggregated compute and storage arch, the compute node will register store with label `{"engine": "tiflash_compute"}`.
The logic in PD of choosing store for rule: [pkg/schedule/placement/label_constraint.go @ pd](https://github.com/tikv/pd/blob/7d33065019f78d9150a8c89ddb4593f81e6ff9b3/pkg/schedule/placement/label_constraint.go#L81-L95)
1. If the store's label.key is equal to "engine" (or "exclusive," or starts with '$'), and the rule's constraint does not contain a rule with the same label.key, then do not schedule the peer to …

disagg: Add exclusive label for tiflash compute node

---

dbms/src/Debug/dbgQueryCompiler.h
dbms/src/Flash/Coprocessor/DAGContext.cpp
dbms/src/Flash/Coprocessor/DAGContext.h
dbms/src/Flash/Coprocessor/tests/gtest_dag_context.cpp
dbms/src/Functions/FunctionsTiDBConversion.h
dbms/src/Functions/tests/bench_function_cast.cpp
dbms/src/Functions/tests/gtest_tidb_conversion.cpp
dbms/src/TestUtils/mockExecutor.cpp

Issue Number: close #9752
Problem Summary: check description in issue. tidb removed `OverflowAsWarning` flag, because its semantics is same with `TruncateAsWarning`
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

remove OVERFLOW_AS_WARNING flag

---

dbms/src/Storages/DeltaMerge/tests/gtest_segment_bitmap.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_replace_stable_data.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_util.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_util.h

Issue Number: ref #9866
This PR mainly refine `sequenceEqual` to accept two vector-like sequence, instead of two pointer.
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

tests: refine some test utils

---

dbms/src/Storages/KVStore/KVStore.cpp
dbms/src/Storages/KVStore/KVStore.h
dbms/src/Storages/KVStore/KVStoreConfig.cpp
dbms/src/Storages/KVStore/KVStoreConfig.h
dbms/src/Storages/KVStore/MultiRaft/Persistence.cpp
dbms/src/Storages/KVStore/ProxyStateMachine.h
dbms/src/Storages/KVStore/Read/LearnerRead.cpp
dbms/src/Storages/KVStore/Read/ReadIndex.cpp
dbms/src/Storages/KVStore/TMTContext.cpp
dbms/src/Storages/KVStore/TMTContext.h
dbms/src/Storages/KVStore/tests/gtest_kvstore.cpp
dbms/src/Storages/KVStore/tests/gtest_kvstore_fast_add_peer.cpp
dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp
dbms/src/Storages/KVStore/tests/gtest_proactive_flush.cpp

```commit-message
KVStore: Move the configs of Raft Read and Region Flush to KVStoreConfig
```
Tests 
Side effects
Documentation
```release-note
None
```

KVStore: Move the configs of Raft Read to KVStoreConfig

---

dbms/src/Server/Server.cpp

Issue Number: close #9745 ref #4982
```commit-message
```
Tests 
Side effects
Documentation
```release-note
Fix an issue that TiFlash may unexpectedly reject raft message when memory usage is not high
```

Set proxy's memory limit by TiFlash (#9753) and update tiflash proxy 

---

dbms/src/Common/FailPoint.cpp
dbms/src/Common/getNumberOfCPUCores.cpp
dbms/src/Common/getNumberOfCPUCores.h
dbms/src/Interpreters/SettingsCommon.h
dbms/src/Server/Server.cpp
dbms/src/Storages/KVStore/ProxyStateMachine.h
dbms/src/Storages/KVStore/tests/gtest_proxy_state_machine.cpp

Issue Number: close #9880
See the issue. We make `setAuto` not static as a workaround. However, we have to handle the coupling of Proxy and Settings.h.
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Fix the incorrect value of the max thread size

---

dbms/src/Core/TiFlashDisaggregatedMode.cpp
dbms/src/Core/TiFlashDisaggregatedMode.h
dbms/src/DataTypes/DataTypeAggregateFunction.cpp
dbms/src/Flash/Mpp/tests/gtest_mpp_task_manager.cpp
dbms/src/Interpreters/Context.cpp
dbms/src/Interpreters/Context.h
dbms/src/Server/CLIService.h
dbms/src/Server/Client.cpp
dbms/src/Server/DTTool/DTTool.h
dbms/src/Server/Server.cpp
dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV3.cpp
dbms/src/TestUtils/TiFlashTestEnv.cpp

Issue Number: ref https://github.com/pingcap/tiflash/issues/9857
Problem Summary: After https://github.com/pingcap/tiflash/pull/9753, the code that set "application_type" and "disagg" params is far away from `Context::createGlobal()`. This could lead to unexpected behavior in later code changes.
`Context::checkIsConfigLoaded` rely on `context->application_type` being set correctly
The application type should be set when GlobalContext created. 
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

*: Set ApplicationType and disagg param when GlobalContext created

---

dbms/src/Common/FailPoint.cpp
dbms/src/Server/StorageConfigParser.h
dbms/src/Storages/S3/S3Common.cpp
dbms/src/Storages/S3/S3Common.h
dbms/src/Storages/S3/tests/gtest_s3client.cpp
dbms/src/TestUtils/gtests_dbms_main.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/9889
We encounter some error logging as follow after the lifecycle is correctly added.
```
[2025/02/18 15:47:25.784 +00:00] [WARN] [S3Common.cpp:847] ["Create lifecycle rule with tag filter \"tiflash_deleted=true\" failed, please check the bucket lifecycle configuration or create the lifecycle rule manually, bucket=tiflash  s3error=UNKNOWN s3exception_name=InvalidArgument s3msg=Unable to parse ExceptionName: InvalidArgument Message: Rule ID must be unique. Found same ID for more than one rule request_id=WH14MR0TVK0DTGN5"] [source="bucket=tiflash root=tiflash_dev/"] [thread_id=371]
[2025/02/18 15:47:25.784 +00:00] [WARN] [S3Common.cpp:145] ["tag=AWSErrorMarshaller message=Encountered Unknown AWSError …
```

disagg: Adapt with the GetLifecycleConfig response on AWS S3

---

dbms/src/Storages/KVStore/ProxyStateMachine.h

cherry-pick of https://github.com/pingcap/tiflash/pull/9849
Issue Number: close https://github.com/pingcap/tiflash/issues/9750
When creating a placement policy through tidb, tidb will create a placement-rule with `"engine" notIn "tiflash"` https://github.com/pingcap/tidb/pull/22065
However, under tiflash disaggregated compute and storage arch, the compute node will register store with label `{"engine": "tiflash_compute"}`.
The logic in PD of choosing store for rule: [pkg/schedule/placement/label_constraint.go @ pd](https://github.com/tikv/pd/blob/7d33065019f78d9150a8c89ddb4593f81e6ff9b3/pkg/schedule/placement/label_constraint.go#L81-L95)
1. If the store's label.key is equal to "engine" (or "exclusive," or starts with '$'), and the rule's constraint does not contain a rule …

disagg: Add exclusive label for tiflash compute node (release-8.5)

---

dbms/src/Server/Server.cpp

cherry-pick of https://github.com/pingcap/tiflash/pull/9849
Issue Number: close https://github.com/pingcap/tiflash/issues/9750
When creating a placement policy through tidb, tidb will create a placement-rule with `"engine" notIn "tiflash"` https://github.com/pingcap/tidb/pull/22065
However, under tiflash disaggregated compute and storage arch, the compute node will register store with label `{"engine": "tiflash_compute"}`.
The logic in PD of choosing store for rule: [pkg/schedule/placement/label_constraint.go @ pd](https://github.com/tikv/pd/blob/7d33065019f78d9150a8c89ddb4593f81e6ff9b3/pkg/schedule/placement/label_constraint.go#L81-L95)
1. If the store's label.key is equal to "engine" (or "exclusive," or starts with '$'), and the rule's constraint does not contain a rule …

disagg: Add exclusive label for tiflash compute node (release-7.5)

---

dbms/src/Server/Server.cpp

cherry-pick of https://github.com/pingcap/tiflash/pull/9849
Issue Number: close https://github.com/pingcap/tiflash/issues/9750
When creating a placement policy through tidb, tidb will create a placement-rule with `"engine" notIn "tiflash"` https://github.com/pingcap/tidb/pull/22065
However, under tiflash disaggregated compute and storage arch, the compute node will register store with label `{"engine": "tiflash_compute"}`.
The logic in PD of choosing store for rule: [pkg/schedule/placement/label_constraint.go @ pd](https://github.com/tikv/pd/blob/7d33065019f78d9150a8c89ddb4593f81e6ff9b3/pkg/schedule/placement/label_constraint.go#L81-L95)
1. If the store's label.key is equal to "engine" (or "exclusive," or starts with '$'), and the rule's constraint does not contain a rule …

disagg: Add exclusive label for tiflash compute node (release-8.1)

---

dbms/src/AggregateFunctions/ReservoirSampler.h
dbms/src/AggregateFunctions/ReservoirSamplerDeterministic.h
dbms/src/AggregateFunctions/UniquesHashSet.h
dbms/src/Common/CombinedCardinalityEstimator.h
dbms/src/Common/CounterInFile.h
dbms/src/Common/HyperLogLogCounter.h
dbms/src/Common/OptimizedRegularExpression.inl.h
dbms/src/Databases/DatabaseTiFlash.cpp
dbms/src/IO/ReadHelpers.h
dbms/src/Server/Server.cpp
dbms/src/Server/Setup.cpp
dbms/src/Storages/DeltaMerge/StoragePool/StoragePool.cpp
dbms/src/Storages/KVStore/KVStore.cpp
dbms/src/Storages/KVStore/MultiRaft/RegionPersister.cpp
dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp
dbms/src/Storages/KVStore/Utils/SerializationHelper.h
dbms/src/Storages/Page/Page.h
dbms/src/Storages/Page/PageStorage.cpp
dbms/src/Storages/Page/PageStorage.h
dbms/src/Storages/Page/V2/PageStorage.cpp
dbms/src/Storages/Page/V2/PageStorage.h
dbms/src/Storages/Page/V2/tests/gtest_page_storage.cpp
dbms/src/Storages/Page/V3/PageStorageImpl.cpp
dbms/src/Storages/Page/V3/PageStorageImpl.h
dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
dbms/src/Storages/Page/workload/PSWorkload.cpp
libs/libcommon/include/common/ErrorHandlers.h

Issue Number: close https://github.com/pingcap/tiflash/issues/9902
Under some cases, we meet exception with no stacktrace
```
[2025/01/17 18:11:13.564 +08:00] [ERROR] [<unknown>] ["DB::Exception: Too large string size."] [source=Application] [thread_id=1]
```
```commit-message
* Add progress logging in `RegionPersister::restore` so that we can get more info how many region is restoring
* Add stacktrace logging when exceptions are thrown in `Server::main`
* Use DB::Exception instead of Poco::Exception to get more stacktrace info
```
Tests 
Mock the `KVStore::restore` throw an exception in `Server::main`, and the logging can print the stacktrace info
```
[2025/02/24 13:01:46.197 +08:00] [INFO] [DeltaMergeStore.cpp:375] ["Release DeltaMerge Store start"] …
```

*: Add stacktrace logging when exceptions are thrown in `Server::main`

---

dbms/src/Interpreters/loadMetadata.cpp
dbms/src/Server/BgStorageInit.cpp
dbms/src/Server/BgStorageInit.h
dbms/src/Server/Server.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/9906
If `profiles.default.init_thread_count_scale` to 0, tiflash stuck at loading metadata because we try to add task into a thread pool with num_thread == 0.
```commit-message
* If `profiles.default.init_thread_count_scale == 0`, run `loadMetadata` and `BgStorageInit` in serial order.
* Respect `terminate_signals_counter` in `BGStorageInit`
```
Tests 
deploy a cluster and add this config line to tiflash by tiup edit-config
```
profiles.default.init_thread_count_scale: 0
```
```
[2025/02/24 16:14:18.240 +08:00] [INFO] [BgStorageInit.cpp:181] ["Lazily init store"] [thread_id=1]
[2025/02/24 16:14:18.361 +08:00] [INFO] [BgStorageInit.cpp:138] ["Init stores without thread pool"] [thread_id=77]
[2025/02/24 …
```

Storage: Fix init_thread_count_scale == 0, tiflash can not start normally

---

dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
dbms/src/Storages/DeltaMerge/LocalIndexerScheduler.cpp
dbms/src/Storages/DeltaMerge/StoragePool/StoragePool.cpp
dbms/src/Storages/KVStore/FFI/ProxyFFI.cpp
dbms/src/Storages/KVStore/FFI/ProxyFFI.h
dbms/src/Storages/KVStore/FFI/ProxyFFICommon.h
dbms/src/Storages/KVStore/KVStore.h
dbms/src/Storages/KVStore/MultiRaft/ApplySnapshot.cpp
dbms/src/Storages/KVStore/MultiRaft/Disagg/ServerlessUtils.cpp
dbms/src/Storages/KVStore/tests/gtest_kvstore.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/9915
There could be a chance that GetLockByKey is called when region is not exist
And returning `BaseBuffView` to rust is not memory safe
Pending on https://github.com/pingcap/tidb-engine-ext/pull/426
```commit-message
FFI: Fix NPE when GetLockByKey is called when region is not exist
FFI: Use CppStrWithView as the return type of fn_get_lock_by_key
```
Tests 
Side effects
Documentation
```release-note
None
```

FFI: Fix NPE when GetLockByKey is called when region is not exist

---

dbms/src/Debug/MockStorage.cpp
dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
dbms/src/Storages/DeltaMerge/Filter/PushDownExecutor.cpp

Issue Number: ref https://github.com/pingcap/tiflash/issues/9146
Enable `two_value_and` in late materialization, more details in #9560. `PhysicalFilter::build` and `executePushedDownFilter` both have enable `two_value_and`.
Ref https://github.com/pingcap/tiflash/pull/9741
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

*: enable `null_as_false` when build push down filter in late materialization

---

dbms/src/Common/FailPoint.cpp
dbms/src/Flash/Coprocessor/RemoteRequest.cpp
dbms/src/Flash/Coprocessor/TablesRegionsInfo.cpp
tests/fullstack-test/mpp/remote_read_virtual_column.test

Issue Number: close #9561
```
select col, gen_col from t;
```
gen_col is a virtual generated column. The current approach is that TiFlash generates an empty column and places it in the block. Then, it passes the block to TiDB, allowing TiDB to calculate and populate the column.
I’ve named this column generated_xxx.
The information about this column is marked in tipb_table_scan.columns with a flag. When TiFlash sees this flag, it automatically adds a generated_xxx column.
However, this situation has an issue when a remote read occurs: the block returned from the remote read, when parsed, assigns names to each column based on RemoteRequest.schema. For example, if TiFlash-1 receives a block from TiFlash-2, it will parse it as <col, gen_col>.
But TiFlash-1, in the table …

fix virtual column not found when remote read happens

---

dbms/src/Interpreters/Context.cpp
dbms/src/Interpreters/Context.h
dbms/src/Server/Server.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetWithVectorIndexInputStream.h
dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp

```commit-message
Split local index cache into light/heavy, which distinct by memory usage. It aims to improve cache hit ratio when the table is quite large.
```
Tests 
Side effects
Documentation
```release-note
None
```

Storages: split LocalIndexCache

---

release-linux-llvm/Makefile
release-linux-llvm/dockerfiles/Dockerfile-tiflash-llvm-base

Issue Number: ref https://github.com/pingcap/tiflash/pull/9587
The env in built image of tiflash-llvm-base is not correct
```
> SUFFIX=-llvm-17.0.6 make image_tiflash_llvm_base
> SUFFIX=-llvm-17.0.6
>  docker run -it --rm -v /DATA/disk1/jaysonhuang/tiflash/:/build/tics hub.pingcap.net/tiflash/tiflash-llvm-base:rocky8${SUFFIX} /bin/bash
[root@cdf467e9694f root]# 
[root@cdf467e9694f root]# echo $LIBRARY_PATH 
/usr/local/lib/$(uname -m)-unknown-linux-gnu/:
[root@cdf467e9694f root]# echo $LD_LIBRARY_PATH 
/usr/local/lib/$(uname -m)-unknown-linux-gnu/:
[root@cdf467e9694f root]# echo $CPLUS_INCLUDE_PATH 
/usr/local/include/$(uname -m)-unknown-linux-gnu/c++/v1/:
```
```commit-message
```
Tests 
```
> SUFFIX=-llvm-17.0.6
>  docker run -it --rm -v …
```

build: Fix ENV setting in tiflash-llvm-base image

---

dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileDeleteRange.h
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.h
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.h
dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
dbms/src/Storages/DeltaMerge/Delta/MinorCompaction.cpp
dbms/src/Storages/DeltaMerge/Delta/tests/gtest_dm_delta_value_space.cpp
dbms/src/Storages/DeltaMerge/Index/VectorIndex/Writer.cpp
dbms/src/Storages/DeltaMerge/tests/CMakeLists.txt
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h

Issue Number: close https://github.com/pingcap/tiflash/issues/9946
Some pages for local index in the ColumnFileTiny is not removed when doing MinorCompaction
https://github.com/pingcap/tiflash/blob/6fec03d61355a52ae623f0770de0b66f2feefc46/dbms/src/Storages/DeltaMerge/Delta/MinorCompaction.cpp#L53-L54
In `MinorCompaction::prepare` we use `wbs.removed_log.delPage(t_file->getDataPageId());` to remove the ColumnFileTiny. But this will not remove the related LocalIndex page_id with the ColumnFileTiny. We must use `t_file->removeData(wbs);` to remove the ColumnFileTiny along with its LocalIndex page_ids.
BTW, `SegmentSplit`, `SegmentMerge` and `SegmentDeltaMerge` (MajorCompaction) calls `DeltaValueSpace::recordRemoveColumnFilesPages` and can correctly remove the LocalIndex …

vector: Fix the bug that the local index in CFTiny is not removed during MinorCompaction

---

contrib/aws-cmake/0003-Suppress-enum-overflow.patch
contrib/aws-cmake/CMakeLists.txt

Issue Number: close https://github.com/pingcap/tiflash/issues/9955
Apply a patch to suppress enum overflow warning on S3 SDK. And we may upgrade the S3 SDK in later PRs
```commit-message
disagg: Suppress enum overflow warning on S3 SDK
```
Tests 
Side effects
Documentation
```release-note
Suppress a logging that report unknown enum from S3
```

disagg: Suppress enum overflow warning on S3 SDK

---

dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyLocalIndexWriter.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyVectorIndexReader.cpp
dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
dbms/src/Storages/DeltaMerge/File/DMFileLocalIndexWriter.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp

Issue Number: close #9971, close #9972
```commit-message
1. Fix the existing index infoes in ColumnFileTiny are missed after add new indexes.
2. Do not add task into `LocalIndexerScheduler` if the DMFile is empty.
3. Fix delta data do not build the new added local indexes.
```
Tests 
Side effects
Documentation
```release-note
None
```

Storages: fix adding delta vector index does not work with existing indexes 

---

dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp
dbms/src/Storages/S3/FileCache.h
tests/sanitize/tsan.suppression

Issue Number: close #9961
```commit-message
1. We should not reuse anything which is not thread-safe between different queries, so do not reuse `ann_query_info` in unit tests.
2. Fix `FileCache::bgDownload` may still be running after `FileCache::shutdown`.
3. Suppress false positive alarm in `~shared_ptr`  and `re2::RE2::NumberOfCapturingGroups`.
4. Suppress alarm in `TiFlashStorageTestBasic::reload` which is only used in unit tests.
5. Fix data race between `DeltaMergeStore::segmentWaitDeltaLocalIndexReady` and `ColumnFilePersistedSet::updatePersistedColumnFilesAfterAddingIndex`
```
Tests 
Run the unit test cases with TSAN built binary
Side effects
Documentation
```release-note
Fix a data race issue by waiting for all background task done when shutting down under disagg …
```

Storages: fix a series of data race issues

---

dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp

Issue Number: close #9983
```commit-message
- Converting string type to default parameter in DeltaMergeStore
```
Tests 
- Compacting tiflash replica make string data from `String` to `StringV2`. 
Side effects
Documentation
```release-note
Fix a bug that the string serialize method of existing data does not follow `storage.format_version` after upgraded
```

Storages: use default string type in DeltaMergeStore

---

contrib/aws-cmake/CMakeLists.txt

Issue Number: close https://github.com/pingcap/tiflash/issues/9955
Ref https://github.com/pingcap/tiflash/pull/9957
```
cmake /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DENABLE_TESTS=ON -DCMAKE_BUILD_TYPE=ASan -DUSE_CCACHE=ON -DRUN_HAVE_STD_REGEX=0 -DCMAKE_PREFIX_PATH=/usr/local -DUSE_GM_SSL=0 -GNinja
...
[2025-03-09T18:47:24.402Z] -- aws patch not apply: 1, patching...
[2025-03-09T18:47:24.402Z] 'git' 'apply' '-v' '/home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/aws-cmake/0001-More-reliable-way-to-check-if-there-is-anything-in-r.patch'
[2025-03-09T18:47:24.402Z] Checking patch src/aws-cpp-sdk-core/source/client/AWSJsonClient.cpp...
[2025-03-09T18:47:24.402Z] Checking patch …
```

disagg: Fix build under ASAN; Check each aws patch separately

---

dbms/src/DataStreams/FilterTransformAction.cpp
dbms/src/DataStreams/MergeSortingBlockInputStream.cpp
dbms/src/Flash/tests/gtest_spill_sort.cpp
dbms/src/Operators/MergeSortTransformOp.cpp

Issue Number: close #9999
The root cause is described in #9999, this pr fix the error and add some check in sort operator to avoid potential undefined fail when the input block of sort is not well generated.
```commit-message
Fix sort spill crash in some corner cases.
```
Tests 
Side effects
Documentation
```release-note
Fix sort spill crash in some corner cases
```

Fix spill crash

---

dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilter.cpp
dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilter.h
dbms/src/Storages/DeltaMerge/Filter/And.h
dbms/src/Storages/DeltaMerge/Filter/ColumnRange.cpp
dbms/src/Storages/DeltaMerge/Filter/ColumnRange.h
dbms/src/Storages/DeltaMerge/Filter/Equal.h
dbms/src/Storages/DeltaMerge/Filter/Greater.h
dbms/src/Storages/DeltaMerge/Filter/GreaterEqual.h
dbms/src/Storages/DeltaMerge/Filter/In.h
dbms/src/Storages/DeltaMerge/Filter/IntegerSet.cpp
dbms/src/Storages/DeltaMerge/Filter/IntegerSet.h
dbms/src/Storages/DeltaMerge/Filter/IsNull.h
dbms/src/Storages/DeltaMerge/Filter/Less.h
dbms/src/Storages/DeltaMerge/Filter/LessEqual.h
dbms/src/Storages/DeltaMerge/Filter/Like.h
dbms/src/Storages/DeltaMerge/Filter/Not.h
dbms/src/Storages/DeltaMerge/Filter/NotEqual.h
dbms/src/Storages/DeltaMerge/Filter/Or.h
dbms/src/Storages/DeltaMerge/Filter/RSOperator.h
dbms/src/Storages/DeltaMerge/Filter/Unsupported.h
dbms/src/Storages/DeltaMerge/tests/gtest_inverted_index.cpp
dbms/src/Storages/tests/gtest_filter_parser.cpp

Issue Number: ref #9843
```commit-message
Part 2 of inverted index, introduce `IntegerSet` and `ColumnRange`:
`IntegerSet` is a collection of discrete integer values, like `{0, 1, 8}`, `[10, 11)` and `{0, 1, 8} U [10, 11)`.
`ColumnRange` represents the range of values for columns, the range of values of a column is represented by `ColumnID` and `IntegerSet`. It supports all types of algebra of sets.
And we support convert `RSOperator` to `ColumnRange`.
For example, `RSOperator` a > 0 and a < 10 and b < 10 or c > 0` will be converted to `col_id_a: [1, 9] && col_id_b: [-inf, 9] || col_id_c: [0, inf]`
```
Tests 
Side effects
Documentation
```release-note
None
```

Storages: support build inverted index query info from RSOperator

---

dbms/src/IO/ReadHelpers.h
dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.cpp
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/KVStore/TiKVHelpers/TiKVKeyValue.h
dbms/src/Storages/KVStore/Utils/SerializationHelper.h
dbms/src/Storages/KVStore/tests/gtest_region_persister.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/10052
```
[performance]
txn-entry-size-limit = 125829120
```
```
[raftstore]
raft-entry-max-size = '120MiB'
```
```
set global max_allowed_packet = 1073741824;
CREATE TABLE `t` (
`id` bigint(21) unsigned NOT NULL,
`text` longtext DEFAULT NULL
);
```
TiDB could allow a raft-log with 120MiB at max, while TiFlash `Region::deserialize` use `readBinary2<std::string>` only allow 16MiB at max. So if there are some raftlog larger than 16MiB and flushed to `RegionData`, then TiFlash could fail to restart when restoring Region data from disk.
If the raftlog is committed, the rows are decoded into `Block` and write down to `IStorage`. Reading/writing rows larger than `16MiB` in the `IStorage` layer does not cause any …

KVStore: Fix fail to restore tikv value larger than 16MiB

---

dbms/src/Interpreters/OWNERS

https://github.com/pingcap/tiflash/pull/9191 which adds `dbms/src/Interpreters/JoinV2/HashJoinSettings.h` accidentally blocked by the `OWNERS` file 
```commit-message
Only check the `Interpreters/Settings.h` file
```
Tests 
Side effects
Documentation
```release-note
None
```

CI: fix regex in interpreters OWNERS file

---

dbms/src/Debug/dbgNaturalDag.h
dbms/src/IO/Buffer/WriteBufferFromString.h
dbms/src/IO/Buffer/WriteBufferFromVector.h
dbms/src/IO/ReadHelpers.h
dbms/src/Storages/KVStore/Decode/DecodedTiKVKeyValue.h
dbms/src/Storages/KVStore/MultiRaft/RegionRangeKeys.h
dbms/src/Storages/KVStore/TiKVHelpers/TiKVRecordFormat.h
dbms/src/Storages/KVStore/tests/gtest_region_persister.cpp
dbms/src/TiDB/Decode/DatumCodec.h
dbms/src/TiDB/Decode/RowCodec.h

```commit-message
tests: Avoid disk IO in `RegionSeriTest`
Use `WriteBufferFromOwnString`/`ReadBufferFromString` instead of `WriteBufferFromFile`/`ReadBufferFromFile` to make the time of running tests more stable
```
Tests 
Side effects
Documentation
```release-note
None
```

tests: Avoid disk IO in `RegionSeriTest`

---

dbms/src/Storages/DeltaMerge/Index/InvertedIndex/Reader/ReaderFromColumnFileTiny.cpp
dbms/src/Storages/DeltaMerge/Index/InvertedIndex/Reader/ReaderFromColumnFileTiny.h
dbms/src/Storages/DeltaMerge/Index/InvertedIndex/Reader/ReaderFromDMFile.cpp
dbms/src/Storages/DeltaMerge/Index/InvertedIndex/Reader/ReaderFromDMFile.h
dbms/src/Storages/DeltaMerge/Index/InvertedIndex/Reader/ReaderFromSegment.cpp
dbms/src/Storages/DeltaMerge/Index/InvertedIndex/Reader/ReaderFromSegment.h
dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/InputStream.cpp
dbms/src/Storages/DeltaMerge/Index/VectorIndex/tests/gtest_dm_vector_index.cpp
dbms/src/Storages/DeltaMerge/ScanContext.cpp
dbms/src/Storages/DeltaMerge/ScanContext.h

Issue Number: ref #9843 
```commit-message
Part 5 of inverted index, add inverted index statistics to `ScanContext` to improve observability.
Other changes：
- rename `total_vector_idx_xxx` to `vector_idx_xxx`.
```
Tests 
Side effects
Documentation
```release-note
None
```

Storages: add inverted index statistics to ScanContext

---

dbms/src/Interpreters/JoinV2/HashJoin.cpp
dbms/src/Interpreters/JoinV2/HashJoinPointerTable.cpp
dbms/src/Interpreters/JoinV2/HashJoinPointerTable.h
dbms/src/Interpreters/tests/JoinV2/gtest_hash_join_pointer_table.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/10100
See https://github.com/pingcap/tiflash/issues/10100.
```commit-message
Do not allocate memory for unit test in `HashJoinPointerTable::init`
```
Tests 
Side effects
Documentation
```release-note
None
```

Do not allocate memory for unit test in `HashJoinPointerTable::init`

---

.github/licenserc.yml

Issue Number: ref #9032 
```commit-message
Fix license checker for CI. These directories are generated in CI build so that they should not be checked anyway.
```
Failed at: https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftiflash%2Fmerged_build/detail/merged_build/217/pipeline
Tests 
Side effects
Documentation
```release-note
None
```

*: Fix license checker

---

libs/libclara-cmake/CMakeLists.txt
libs/libclara/Cargo.toml

Issue Number: ref #10080 
```commit-message
- Fix build error when ThinLTO is enabled.
- Reduce libclara library size.
```
Tests 
```shell
cmake .. -GNinja --fresh \
-DCMAKE_BUILD_TYPE=RELWITHDEBINFO \
-DCMAKE_C_COMPILER=clang \
-DCMAKE_CXX_COMPILER=clang++ \
-DENABLE_TESTING=OFF \
-DENABLE_TESTS=OFF \
-DENABLE_FAILPOINTS=OFF \
-DENABLE_THINLTO=ON \
-DTHINLTO_JOBS=70 && ninja tiflash
```
Side effects
Documentation
```release-note
None
```

*: Fix build issue when ThinLTO is enabled

---

dbms/src/Common/TiFlashMetrics.h
dbms/src/Interpreters/AsynchronousMetrics.cpp
dbms/src/Interpreters/SharedContexts/Disagg.cpp
dbms/src/Interpreters/SharedContexts/Disagg.h
dbms/src/Server/Server.cpp
dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
dbms/src/Storages/DeltaMerge/DeltaIndex/DeltaIndex.h
dbms/src/Storages/DeltaMerge/Index/VectorIndex/tests/gtest_dm_vector_index.cpp
dbms/src/Storages/DeltaMerge/Remote/RNDeltaIndexCache.cpp
dbms/src/Storages/DeltaMerge/Remote/RNDeltaIndexCache.h
dbms/src/Storages/DeltaMerge/Remote/RNMVCCIndexCache.cpp
dbms/src/Storages/DeltaMerge/Remote/RNMVCCIndexCache.h
dbms/src/Storages/DeltaMerge/Remote/RNMVCCIndexCache_fwd.h
dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
dbms/src/Storages/DeltaMerge/Remote/Serializer.h
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/Segment.h
dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
dbms/src/Storages/DeltaMerge/SegmentReadTask.h
dbms/src/Storages/DeltaMerge/VersionChain/NewHandleIndex.h
dbms/src/Storages/DeltaMerge/VersionChain/VersionChain.cpp
dbms/src/Storages/DeltaMerge/VersionChain/VersionChain.h
dbms/src/Storages/DeltaMerge/VersionChain/VersionChain_fwd.h
dbms/src/Storages/DeltaMerge/VersionChain/tests/gtest_mvcc_bitmap.cpp
dbms/src/Storages/DeltaMerge/VersionChain/tests/gtest_version_chain.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_bitmap.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_segment_replace_stable_data.cpp
metrics/grafana/tiflash_summary.json

Issue Number: ref #9963
Support VersionChain in StorageDisaggregated.
```commit-message
1. Rename all DeltaIndexCache-related names to MVCCIndexCache.
2. Store DeltaIndex and VersionChain in MVCCIndexCache with different keys.
3. Lazily get DeltaIndex or VersionChain from MVCCIndexCache only before reading the segment.
```
Tests 
- Run chbenchmark with version chain enabled.
- Run chbenchmark with version chain disabled.
Side effects
Documentation
```release-note
None
```

Disagg: Support VersionChain in StorageDisaggregated

---

dbms/src/Common/FailPoint.cpp
dbms/src/Common/getNumberOfCPUCores.cpp
dbms/src/Common/getNumberOfCPUCores.h
dbms/src/Interpreters/SettingsCommon.h
dbms/src/Server/Server.cpp
dbms/src/Storages/KVStore/ProxyStateMachine.h
dbms/src/Storages/KVStore/tests/gtest_proxy_state_machine.cpp

Note:
* This change to the FFI interface for proxy adaptation. And the related issue is currently suspected to potentially cause fluctuations in LearnerRead latency in some cases. https://github.com/pingcap/tiflash/pull/9841, https://github.com/pingcap/tiflash/pull/9882
* This change to the FFI interface for proxy adaptation  https://github.com/pingcap/tiflash/pull/9893
* Fix stale read can not eliminate the learner read https://github.com/pingcap/tiflash/pull/10132
Issue Number: ref #4982, close https://github.com/pingcap/tiflash/issues/10046
update proxy to raftstore-proxy-8.1
Proxy PR: 
Including:\nSubmodule contrib/tiflash-proxy caa7a0c1dd..96545a2632:
> Fix safe ts not updated (#429) (#434)
The leader_safe_ts, self_safe_ts are always 0 in the TiFlash side, making …

[hotfix] Fix stale read can not eliminate the learner read on TiFlash

---

dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp

```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Storages: fix UT ParsePushDownExecutorTest.TimestampColumn when local timezone is UTC

---

dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp

#10136 try to fix the test, but failed.
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Fix TimestampColumn fail in ASan/TSan

---

dbms/src/Common/getNumberOfCPUCores.cpp
dbms/src/Server/Server.cpp

Currently, TiFlash use `std::thread::hardware_concurrency()` as the default pool size of grpc async client pool, it does not work well when TiFlash is in virtual environment, this pr use `CPUCores::number_of_logical_cpu_cores` as its default value.
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

use logical cpu cores as the default pool size of grpc async client pool

---

tests/fullstack-test2/ddl/expression_index.test

Issue Number: ref https://github.com/pingcap/tiflash/issues/9891, ref https://github.com/pingcap/tidb/issues/61133
TiDB disable the invalid expression index `((null))` from being created by https://github.com/pingcap/tidb/pull/61135. Update the integration test cases
```commit-message
ddl: Fix integration test of expr index
TiDB disable the invalid expression index `((null))` from being created by https://github.com/pingcap/tidb/pull/61135. Update the integration test cases
```
Tests 
Side effects
Documentation
```release-note
None
```

ddl: Update integration test of expr index

---

dbms/src/Common/tests/gtest_arena.cpp
dbms/src/Interpreters/JoinPartition.cpp

Issue Number: close #10163
Ref to #10163
Use `alignAlloc` instead `alloc` to alloc memory for `CachedColumnInfo`
```commit-message
Fix TiFlash crash due to invalid address alignment
```
Tests 
Side effects
Documentation
```release-note
None
```

Fix address alignment error

---

dbms/src/Interpreters/Settings.h

Issue Number: close #9963
```commit-message
Storages: Enable VersionChain
Set profiles.default.enable_version_chain to 1 by default
```
Performance768D1M
Deploy on a single machine 16c 64GB
  | DeltaIndex | VersionChain | VersionChain/DeltaIndex
-- | -- | -- | --
QPS | 54.0482 | 117.2117 | 2.168651315
Deploy on a single machine 16c 128GB
* For stable-only workload, the total query cost using VersionChain is almost the same as DeltaIndex
* For read-only with delta workload, non-clustered index, using VersionChain gain 30%~100% performance boost
* For read-only with delta workload, clustered index, using VersionChain gain 90% performance boost
* For read-write workload, non-clustered index, using VersionChain gain 13% performance boost
* For read-write workload, clustered …

Storages: Enable VersionChain

---

dbms/src/Flash/Mpp/MPPTask.cpp

Since reportStatus error doesn't affect query results, change to info level log instead.
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Downgrade reportStatus log level from error to info

---

dbms/src/Common/TiFlashMetrics.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
dbms/src/Storages/DeltaMerge/Remote/RNMVCCIndexCache.h
dbms/src/Storages/DeltaMerge/VersionChain/MVCCBitmapFilter.cpp
dbms/src/Storages/KVStore/FFI/ProxyFFI.h
dbms/src/Storages/KVStore/MultiRaft/Disagg/CheckpointIngestInfo.cpp
dbms/src/Storages/KVStore/MultiRaft/Disagg/CheckpointIngestInfo.h
dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeer.cpp
dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeerContext.cpp
dbms/src/Storages/KVStore/tests/gtest_kvstore_fast_add_peer.cpp
dbms/src/Storages/StorageDeltaMerge.cpp
dbms/src/Storages/StorageDeltaMerge.h

backport of https://github.com/tidbcloud/tiflash-cse/pull/379
Issue Number: close https://github.com/pingcap/tiflash/issues/8673
```
2025-03-04 16:30:59 
[2025/03/04 08:30:59.004 +00:00] [FATAL] [Exception.cpp:106] ["Failed query fap snapshot state region_id=333200905 peer_id=338728629: Code: 0, e.displayText() = DB::Exception: fail to get normal id [page_id=0x78019D3374640000000000000074.211393] [seq=1070914] [resolve_id=0x78019D3374640000000000000074.211393] [resolve_ver=1070914.0], e.what() = DB::Exception, Stack trace:
0xaaaac71808cc    StackTrace::StackTrace() [tiflash+34736332]
dbms/src/Common/StackTrace.cpp:23
0xaaaac717de20    DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int) …
```

Delay removing FAP snapshot for restoring applying snapshot

---

contrib/tici-search-lib/CMakeLists.txt

make tici-search-lib compile compatible with mac

make tici-search-lib compile compatible with mac

---

dbms/src/Common/ColumnsHashing.h
dbms/src/Flash/tests/gtest_aggregation_executor.cpp

Issue Number: close #10079
before: `TestZeroBlock` will fail, check https://github.com/pingcap/tiflash/issues/10079#issuecomment-2948917192
after: success
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

fix wrong check for agg when block.rows() is zero

---

dbms/src/DataStreams/WindowTransformAction.cpp
dbms/src/WindowFunctions/tests/gtest_agg.cpp

Issue Number: close #10236
```commit-message
Remove a wrong judgement
```
Tests 
Side effects
Documentation
```release-note
Fix the issue that window function returns incorrect result when range type frame end is preceding
```

Fix the issue that window function returns incorrect result when range type frame end is preceding

---

dbms/src/Flash/Coprocessor/CHBlockChunkCodecV1.cpp

Issue Number: close #10254
In CHBlockChunkCodecV1.cpp, DecoderHeader's improper use of DataTypeFactory::get() for type name resolution caused performance degradation:
https://github.com/pingcap/tiflash/blob/f518f4662dbf348cc891fab69acc21ca384cd7d8/dbms/src/Flash/Coprocessor/CHBlockChunkCodecV1.cpp#L89
It should use DataTypeFactory::getOrSet() like CHBlockChunkCodec.cpp:
https://github.com/pingcap/tiflash/blob/f518f4662dbf348cc891fab69acc21ca384cd7d8/dbms/src/Flash/Coprocessor/CHBlockChunkCodec.cpp#L235
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

*: Fix the performance degradation caused by using DataTypeFactory::get

---

dbms/src/Core/Block.cpp
dbms/src/Core/Block.h
dbms/src/DataStreams/ExpandTransformAction.cpp
dbms/src/Interpreters/ExpressionActions.cpp
dbms/src/Storages/DeltaMerge/DeltaMergeHelpers.h
dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
dbms/src/Storages/DeltaMerge/File/DMFileReader.h
tests/fullstack-test/expr/duration_filter_late_materialization.test

Issue Number: close #10264
https://github.com/pingcap/tiflash/pull/9956 swap `start_offset` in `Block::swap`.
```
void Block::swap(Block & other) noexcept
{
std::swap(info, other.info);
data.swap(other.data);
index_by_name.swap(other.index_by_name);
+    std::swap(start_offset, other.start_offset);
std::swap(segment_row_id_col, other.segment_row_id_col);
std::swap(rs_result, other.rs_result);
}
```
`new_block.startOffset()` has default value 0, after swap, `block.startOffset()` will be change to 0. Therefore, the block returned by `ExpressionBlockInputStream` if there is a `Project` action will always have `block.startOffset() == 0`.
Note: Only changes in dbms/src/Interpreters/ExpressionActions.cpp can fix this bug. Other changes are refactor.
```commit-message
```
Tests …

Fix ExpressionAction Project miss block start offset

---

dbms/src/Interpreters/InterpreterCreateQuery.h

Issue Number: close https://github.com/pingcap/tiflash/issues/10291
```commit-message
Use string instead of string_view in InterpreterCreateQuery
```
Tests 
Side effects
Documentation
```release-note
None
```

ddl: Fix invalid memory access in InterpreterCreateQuery

---

dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp

cherry-pick of https://github.com/pingcap/tiflash/pull/10301
Issue Number: close https://github.com/pingcap/tiflash/issues/10300
In `DAGStorageInterpreter::buildLocalStreamsForPhysicalTable` we need to confirm the regions' keyranges not changed and regions are not removed before the storage snapshot is built. Otherwise the query result is incorrect.
https://github.com/pingcap/tiflash/blob/bec1390d8be06e97612404a61867f0b38b3627b2/dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp#L1069-L1072
Building storage snapshot usually takes about a hundreds ms to few seconds. But the max retry time is only 1. If retry reach the max time, then all the Regions will be fetch though "RemoteRead". When querying a hot write large table, it could fail more than 1. And because the table …

Raft: Increase max retry times to avoid too large remote requests

---

dbms/src/Flash/Coprocessor/DAGDriver.cpp
dbms/src/Flash/Mpp/MPPTaskManager.cpp
dbms/src/Flash/Mpp/MPPTaskManager.h
dbms/src/Server/FlashGrpcServerHolder.cpp
dbms/src/Server/Server.cpp
dbms/src/Storages/KVStore/ProxyStateMachine.h

This reverts commit bec1390d8be06e97612404a61867f0b38b3627b2.
Issue Number: ref https://github.com/pingcap/tiflash/issues/10266
https://github.com/pingcap/tiflash/pull/10267 does not support a real graceful shutdown because the read index request will be canceled if setting `stopping` to store status, which is not expected and can cause MPP tasks to fail.
To make the upcoming cherry-pick easier, this PR reverts https://github.com/pingcap/tiflash/pull/10267 first. 
Then I will file a new PR to fix this issue.
```commit-message
Revert "Support graceful shutdown in TiFlash"
```
Tests 
Side effects
Documentation
```release-note
None
```

Revert "Support graceful shutdown in TiFlash"

---

dbms/src/Storages/DeltaMerge/Remote/RNMVCCIndexCache.h
dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
dbms/src/Storages/DeltaMerge/VersionChain/VersionChain.cpp
dbms/src/Storages/DeltaMerge/VersionChain/VersionChain.h

Issue Number: ref #10323 
- `VersionChain<HandleType>::getBytes()` requires locking.
- Logging if the size of VersionChain is larger than 1MB.
```commit-message
```
Tests 
Side effects
Documentation
```release-note
None
```

Storages: Fix VersionChain::getBytes

---

dbms/src/Operators/tests/gtest_cte.cpp

Issue Number: close #10373
```commit-message
We introduce a new variable to record how many threads have exited so that we can ensure that all blocks have been pushed into queue before `notifyEOF` is called.
```
Tests 
Side effects
Documentation
```release-note
Fix flaky cte concurrent unit test
```

Fix cte concurrent unit test

---

dbms/src/Common/TiFlashMetrics.cpp
dbms/src/Common/TiFlashMetrics.h
dbms/src/Flash/Coprocessor/DAGContext.cpp
dbms/src/Storages/DeltaMerge/ConcatSkippableBlockInputStream.cpp
dbms/src/Storages/DeltaMerge/ConcatSkippableBlockInputStream.h
dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
dbms/src/Storages/DeltaMerge/Index/VectorIndex/tests/gtest_dm_vector_index.cpp
dbms/src/Storages/DeltaMerge/Index/VectorIndex/tests/gtest_dm_vector_index_utils.h
dbms/src/Storages/DeltaMerge/ReadMode.h
dbms/src/Storages/DeltaMerge/ScanContext.cpp
dbms/src/Storages/DeltaMerge/ScanContext.h
dbms/src/Storages/DeltaMerge/Segment.cpp
dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
dbms/src/Storages/DeltaMerge/VersionChain/Common.cpp
dbms/src/Storages/DeltaMerge/VersionChain/Common.h
dbms/src/Storages/DeltaMerge/VersionChain/DMFileHandleIndex.h
dbms/src/Storages/DeltaMerge/VersionChain/DeleteMarkFilter.cpp
dbms/src/Storages/DeltaMerge/VersionChain/RowKeyFilter.cpp
dbms/src/Storages/DeltaMerge/VersionChain/VersionChain.cpp
dbms/src/Storages/DeltaMerge/VersionChain/VersionFilter.cpp
dbms/src/Storages/DeltaMerge/VersionChain/tests/mvcc_test_utils.h
dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
metrics/grafana/tiflash_summary.json

Issue Number: ref #10380
- `ConcatSkippableBlockInputStream`
- When generating MVCC bitmaps using DeltaIndex, row_id is generated in `DeltaMergeBlockInputStream`. The `getPlacedStream` method sets the `need_row_id` parameter to **false** when obtaining the stable stream. Therefore, in **ConcatSkippableBlockInputStream**, `need_row_id` **cannot** be used to determine whether MVCC is involved.
- This can be resolved by switching to a check based on read_tag.
- `DeltaValueReader`
- When we use `getInputStreamNormal` to read data, delta data is read through `DeltaValueReader`. Thus, `DeltaValueReader` needs to add statistics for `user_read_bytes`.
- VersionChain
- Track the read bytes consumed during the construction of MVCC bitmaps.
- ScanContext
- Encapsulate the reporting of primary …

Storages: Fix the statistics of user_read_bytes and add metrics

---

dbms/src/Storages/Page/V3/LogFile/LogFilename.h
dbms/src/Storages/Page/V3/PageDirectory.cpp
dbms/src/Storages/Page/V3/PageDirectory.h
dbms/src/Storages/Page/V3/WAL/WALReader.cpp
dbms/src/Storages/Page/V3/WAL/WALReader.h
dbms/src/Storages/Page/V3/WALStore.cpp
dbms/src/Storages/Page/V3/WALStore.h
dbms/src/Storages/Page/V3/tests/gtest_wal_store.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/10401
In the previous code, if the last WriteBatch contains no changes is persisted in the LogFile, then it may lead to exception in `getMaxSequenceForRecord` as the issue describe.
```commit-message
PageStorage: Fix an exception in gc when meet an empty WriteBatch
* If the last edit stored in Logfile is empty, then we won't collect that LogFile for compacting WAL in the current GC round
* These remain log_files will be compacted in the following rounds once we found a log_file has larger log_num and its max_seq <= snap_sequence.
```
Tests 
Side effects
Documentation
```release-note
Fix an exception that may block data from being GCed
```

PageStorage: Fix an exception in gc when meet an empty WriteBatch

---

dbms/src/Flash/Coprocessor/DAGDriver.cpp
dbms/src/Flash/Coprocessor/DAGResponseWriter.h
dbms/src/Flash/Coprocessor/DAGUtils.cpp
dbms/src/Flash/Coprocessor/DAGUtils.h
dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.cpp
dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.h
dbms/src/Flash/Coprocessor/tests/gtest_streaming_writer.cpp
dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.cpp
dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.h
dbms/src/Flash/Mpp/FineGrainedShuffleWriter.cpp
dbms/src/Flash/Mpp/FineGrainedShuffleWriter.h
dbms/src/Flash/Mpp/HashPartitionWriter.cpp
dbms/src/Flash/Mpp/HashPartitionWriter.h
dbms/src/Flash/Mpp/newMPPExchangeWriter.cpp
dbms/src/Flash/Mpp/newMPPExchangeWriter.h
dbms/src/Flash/Mpp/tests/gtest_mpp_exchange_writer.cpp
dbms/src/Flash/Planner/Plans/PhysicalExchangeSender.cpp
dbms/src/Storages/KVStore/tests/gtest_kvstore_fast_add_peer.cpp

Issue Number: close #10337
The root cause is in current implementation, the buffered block number in ExchangeSender can be upto max_threads * max_threads * fine_grain_stream_count, so if max_threads is large, and the size of each row is big, the buffered block can consume very large memory.
This pr limit the memory usage of ExchangeSender by `max(MAX_BATCH_SEND_MIN_LIMIT_MEM_SIZE * max_threads, max_buffered_bytes_in_executor)`
```commit-message
```
Tests 
test in 2-tiflash's cluster, with max_threads = 32 and sort memory limit set to 5G
```
explain analyze select * from (select *, row_number() over(partition by ps_partkey order by ps_suppkey) as rn from test) d where rn = 10;
```
Where `test` has `40000000` rows, each row has ~1200 bytes.
Before this pr
peak memory of …

Limit memory usage of exchange sender

---

dbms/src/Functions/CollationStringSearchOptimized.h
dbms/src/Functions/FunctionsStringSearch.cpp
dbms/src/TiDB/Collation/Collator.cpp
dbms/src/TiDB/Collation/Collator.h
dbms/src/TiDB/tests/gtest_tidb_collator.cpp

Issue Number: close #10399 
When performing a LIKE operation on strings in SQL, the underlying code logic varies depending on the collation used, leading to significant performance differences.
Currently, the LIKE operation performs well with BIN-type collations, but its performance with CI-type collations is poor—with a substantial gap compared to BIN-type collations.
Check if the LIKE pattern consists of only ASCII characters first. If so, prioritize case-insensitive (CI) comparison using the small (128-entry) ASCII character table (avoiding expensive UTF-8 decoding initially). Fall back to UTF-8 decoding only when non-ASCII characters are detected during matching.  
When a pattern starts with `%`, restart backtracking directly from the characters *after* `%` (instead …

Improve like perf for utf8 ci collations

---

dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
dbms/src/Storages/DeltaMerge/tests/gtest_key_range.cpp

Issue Number: close https://github.com/pingcap/tiflash/issues/10455
```commit-message
Storage: Fix data race in `DeltaMergeStore::checkSegmentUpdate`
```
And add more debug log for flaky test `RowKey.ToNextKeyIntHandle`
https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftiflash%2Frelease-8.5%2Fpull_unit_test/detail/pull_unit_test/259/pipeline
```
[0;33mNote: Google Test filter = RowKey.ToNextKeyIntHandle
[m[0;32m[==========] [mRunning 1 test from 1 test case.
[0;32m[----------] [mGlobal test environment set-up.
[0;32m[----------] [m1 test from RowKey
[0;32m[ RUN      ] [mRowKey.ToNextKeyIntHandle
[2025/09/26 00:05:24.222 +08:00] [WARN] [RowKeyRangeFromRegion.cpp:110] ["Meet rowkey which has extra suffix, keyspace=4294967295 table_id=1 …
```

Storage: Fix data race in `DeltaMergeStore::checkSegmentUpdate`

---

dbms/src/Flash/Statistics/TableScanImpl.cpp
dbms/src/TiDB/Schema/SchemaBuilder.cpp
dbms/src/TiDB/Schema/SchemaGetter.cpp
dbms/src/TiDB/Schema/SchemaSyncService.cpp

cherry-pick of https://github.com/pingcap/tiflash/pull/10466
Issue Number: close https://github.com/pingcap/tiflash/issues/10467
Problem Summary: Reduce the logging with `command.rs:169`, which is about 33.5% of the total number of logging
```commit-message
```
Tests 
Side effects
Documentation
```release-note
Reduce unnecessary logging of handling raft commands
```

*: Downgrade unnecessary log(release-8.5)
